### ISSUE TITLE
Generate nav menu programmatically

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#1]
Rather than reinventing, it's probably best to start from the example implementation in https://github.com/springload/wagtailsites:
- https://github.com/springload/wagtailsites/blob/4262f1e4a094e8fb7d9efed2cff260de0a1cb572/core/snippets.py
- https://github.com/springload/wagtailsites/blob/master/core/templatetags/core_tags.py

More explanation at http://jordijoan.me/simple-orderable-menus-wagtail/

**Comment by noahmanger** [comment]
+1 to doing this programmatically. The tricky / annoying part will be figuring out how to get it in sync across the data site as well.
