### ISSUE TITLE
Bug: Links to content pages on beta.fec.gov are broken

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#100]
The links in the checklist section on [this page](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/) all result in an "Internal server error".

This is not critical for launch because we're not yet launching these pages, but wanted to log it.

**Comment by jmcarp** [comment]
Looks to be some quirk of copying over the database from dev. Re-publishing the affected pages seems to fix, so I did--@noahmanger please confirm when time allows. Not urgent.

**Comment by noahmanger** [comment]
LGTM.
