### ISSUE TITLE
Finalize copy on site search page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1003]
I originally wrote these as a draft, but we need to actually finalize language before releasing this feature. We need to do the sidebar:
![image](https://cloud.githubusercontent.com/assets/1696495/25203493/71691bd4-2527-11e7-99a6-905024227550.png)

And also the no results error message.

The idea for the sidebar is we should give _very brief_ sense of what is included in the additional search options.

cc @emileighoutlaw @jenniferthibault

**Comment by emileighoutlaw** [comment]
How's this for length? 

> **Individual contributions**
> Find out who’s donating to candidates and committees

> **Disbursements**
> Find purchases and payments made by committees

> **Legal resources**
> Including advisory opinions and enforcement cases
_(Note: I like the "including" pattern we have in other spots on the website, so I went with that here. I didn't put "laws" in, but maybe that's a mistake. Curious what you think)_

> **Latest updates**
> Including press releases other FEC publications

**Comment by jenniferthibault** [comment]
This is so hard. Ideally we could do this in one line each—WHICH MIGHT BE IMPOSSIBLE—just enough of a hint to get people going, and know we won't be able to be comprehensive.

But that means culling out the actions, and cutting straight to the examples, which might look (something) like this:

> **Individual contributions**
> Who’s donating to campaigns

> **Disbursements**
> Committee purchases and payments

> **Legal resources**
> Guidance, rulings, laws, and more

> **Latest updates**
> Press releases and other postings

I know I just massacred your consistency, framing, and sentence structure, but what you said about important helper copy being ignored feels especially relevant here too. How can we surface recognizable terms for each section without making the whole block so long that people skip over it? That's where my goal for one-liners comes from.

**Comment by emileighoutlaw** [comment]
It's dang hard to get it to one line, but I'm down for eliminating verbs :) We could even argue the "search" in the header gives us all the verb we need for these bits.

Two questions-ish:
1. Do we think that enforcement is an important bit of legal to call out? Or nah?
1. I do think we should be consistent in the first two about using either _campaigns_ or _committees_. On the one hand, _campaigns_ is the more human-readable word. On the other, _committees_ is more technically correct and inclusive.

**Comment by jenniferthibault** [comment]
Yeah, I don't think one line is going to happen, all of these are likely going to wrap to two.
Two answers-ish:
1. I was wondering if Guidance + Rulings = Enforcement? Tough to balance jargon and word count here. I'm honestly not sure if it's the thing to call out or not, BUT, since this is the search that does go through MURs, and later ADRs, AFs, it might be the thing to say here. Maybe "Enforcement, laws, and more" ?
2. Iiiiiiiiiii don't know how to make the choice between the two, but I agree with you that using the same word makes sense!

**Comment by emileighoutlaw** [comment]
I took a quick tour through our code, and it seems that for the most part we've been pretty consistent about using "committees" except when we're talking specifically about campaigns. So maybe:

> **Individual contributions**
> Who’s donating to committees

> **Disbursements**
> Purchases and payments made by committees

> **Legal resources**
> Guidance, rulings, laws, and more

> **Latest updates**
> Press releases and other postings

The more I think about enforcement the more I think guidance + rulings can encompass enforcement. So 👍

**Comment by jenniferthibault** [comment]
👍

**Comment by noahmanger** [comment]
Works for me. Paging @AmyKort .

**Comment by AmyKort** [comment]
Individual contributions: Who's contributing to committees? or Who's making contributions?

"Contribution" is a FECA term of art that means something different from "donation." I'd like to get away from using "donation" on the Advanced Data page as well.

Otherwise, these look fine to me. Thanks!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1010
