### ISSUE TITLE
Missing number in fax number

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1008]
The fax number on the AO process page is [missing a digit](https://beta.fec.gov/legal-resources/advisory-opinions-process/):
![image](https://cloud.githubusercontent.com/assets/1696495/25318627/9680e10e-2847-11e7-8f27-55c0b4fbda00.png)

Easy fix in Wagtail, but I can't for the life of me figure out what it's supposed to be.

**Comment by AmyKort** [comment]
(202) 219-3923

**Comment by noahmanger** [comment]
Thanks! Fixed.
