### ISSUE TITLE
Correct "upcoming deadline" on home page for candidates

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1011]
So that people aren't confused by the "upcoming deadline" on the home page for candidate committees, only display certain dates that make more sense.

![image](https://cloud.githubusercontent.com/assets/1696495/25361254/0d729eb4-2902-11e7-97b9-727726c37ecc.png)

Ping @AmyKort and @llienfec for help to figure out what these should be.

**Comment by AmyKort** [comment]
@llienfec do you want to take a crack at this? I think the way this works is that we'd have a different, appropriate deadline show up in the Upcoming Deadline box depending on whether the user had toggled to candidate materials, corporate/labor, etc. So, is this a situation where we want quarterly filing deadlines only to show up in the candidate view? Monthly and semi-annual in the others? Do we need to account for special elections?

**Comment by llienfec** [comment]
Thanks @AmyKort. I agree that we had a potential problem and this feature is too cool not to rework a little.   Is this pre or post flip?

**Comment by AmyKort** [comment]
We've had this as a pre-flip priority.

**Comment by llienfec** [comment]
For the House and Senate section, show quarterly filing schedule and special election schedules in the non-election year.  In the election year, show quarterlies, specials, runoffs, pre-primary/convention, pre-general, post-general, and year-end.

For PACs and parties, show monthlies and semi-annuals in the non-election year.  In the election year, show monthlies, quarterlies, pre-general, post-general, and year-end.

Designers will be best suited to figuring out how to show this in a non-confusing way, whether below each committee type, or like @AmyKort suggested above - have one set of boxes that changes depending on the committee you're looking at (which means they'd have to be sticky somehow, so you could see them when you're looking at each committee section).  Or something even better that we haven't thought of yet!

**Comment by llienfec** [comment]
So sorry - I was on the wrong page. I see now that this is for home page.  Agree that the upcoming report box should change depending on the committee type.  

@AmyKort mentioned that we could use the same filters as the calendar.  This will work in its current state for candidates.  Filters: quarterly, pre/post election.

For PACs and parties, we're missing information.  We'd need the monthly schedule and the quarterly schedule.  However, quarterly filing schedule is different for PACs and parties than it is for candidates in the non-election year.  In the non-election year, quarterly becomes semi-annual.  Also, the pre/post election information would be needed, but only for the general election.  They wouldn't need the pre primary/special/convention info included.

We can try to find a simpler way to lay out the filing schedules, but the filters for the calendar probably also need to be updated.

**Comment by AmyKort** [comment]
Super! Thank you @llienfec . 

I think the issue you raised with the calendar filters is something we need to focus on.

**Comment by noahmanger** [comment]
I'm not sure that this level of granularity is possible with the current calendar data. Is there a simpler solution we can implement for pre-flip? We could simply link to the calendar from this card rather than show the upcoming date? Or link to the [Dates and Deadlines](https://beta.fec.gov/help-candidates-and-committees/dates-and-deadlines/) page?

**Comment by AmyKort** [comment]
I think that's a fine solution for the homepage--either option. Let's focus instead on @llienfec 's great catch (that doesn't belong in this issue) where we're not showing the mid-year report in the quarterly filing filter on the calendar.

**Comment by llienfec** [comment]
Agree w/ @AmyKort.  Let's go simple and add MY report to the filter in the calendar.  

Is there any way that we can have a filter for Quarterly (authorized) and Quarterly (PACs & Parties)?

**Comment by noahmanger** [comment]
I'll make another issue for figuring out MY reports on the calendar. Does this work for the home page? The link goes to the Dates and Deadlines page:

![image](https://cloud.githubusercontent.com/assets/1696495/25592696/a3f3aa42-2e6e-11e7-9284-c10d90589c8a.png)

Or we could link straight to https://transition.fec.gov/info/report_dates_2017.shtml#quarterly

**Comment by AmyKort** [comment]
I think the the option to go to the calendar is great! I prefer that to sending folks to the transition page. What do you think, @llienfec ?

**Comment by llienfec** [comment]
Yeah, I think that's a great option.

**Comment by noahmanger** [comment]
Just to be clear, my suggestion was to link to https://beta.fec.gov/help-candidates-and-committees/dates-and-deadlines/ , not the calendar. Should it be the calendar instead?

**Comment by AmyKort** [comment]
I can go either way. The good thing about the calendar is that once you are there you can find other dates and deadlines that might apply to you, so maybe you'd see a meeting date that interested you or a deadline to register for a training. Also, you can filter how you'd like if you want to look at reporting dates. Maybe you'd like to download dates to your phone. BUT, I am going to defer to @llienfec  because this is her area, not mine. I wanted to stay off of the transition pages.

**Comment by llienfec** [comment]
Maybe we do whatever's easiest for now and push a better solution off to post flip?

**Comment by noahmanger** [comment]
Same difference. We can go to the calendar. Should it be filtered to all deadlines or no filters?

**Comment by llienfec** [comment]
Calendar - all deadlines is my vote.

**Comment by AmyKort** [comment]
Sounds great!

**Comment by noahmanger** [comment]
Implemented in https://github.com/18F/fec-cms/pull/1032
