### ISSUE TITLE
Review efiling content and update links

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#1016]
Tasks to completion

- [x] Share efiling edits with filing office
- [x] Implement changes
- [ ] Final review by Amy and possibly OGC?

**Comment by emileighoutlaw** [comment]
@llienfec and I are pairing on this :)

**Comment by llienfec** [comment]
Quick update: the edits are w/ Ken and Eliza in EFO. They'll be sending edits next week.

**Comment by emileighoutlaw** [comment]
We weren't quite able to get this over the finish line this week. @amykort is working on review and approvals for this content right now. 

@llienfec holds all the knowledge about where these new draft Wagtail pages live and can help see this through to publication. 

When the efiling pages are all approved and ready to take the place of the old `Filing candidate reports` pages, perhaps @noahmanger can assist @jameshupp in:
- Deleting the old Wagtail pages
- Publishing the new pages
- Making sure no links break in the process

**Comment by noahmanger** [comment]
This is now live. Thanks @llienfec .
