### ISSUE TITLE
Make edits to FOIA page

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#1018]
We need minor copyedits to the FOIA page in order to publish the new page.

**Comment by emileighoutlaw** [comment]
@AmyKort, [edits to the page are live](https://fec-prod-proxy.app.cloud.gov/freedom-information-act/) 🔒 

I think we're just waiting on:
- [ ] Additional language on new materials coming soon
- [ ] Legal citations on the bottom of the page are all 2 U.S.C. — do we need updated cites for there?

**Comment by AmyKort** [comment]
On it!

**Comment by emileighoutlaw** [comment]
Closing!
