### ISSUE TITLE
Remove misc. components for flip

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1034]
I think we discussed wanting to remove the reaction boxes:
![image](https://cloud.githubusercontent.com/assets/1696495/25596954/d48a1af8-2e80-11e7-878f-8574cb59fce7.png)

And disabled features, like the "search" buttons:
![image](https://cloud.githubusercontent.com/assets/1696495/25596949/caf14a16-2e80-11e7-90b9-325482e3f495.png)

Is that right? I think it makes sense to.

**Comment by AmyKort** [comment]
That was my understanding too. Thanks!
