### ISSUE TITLE
beta.fec.gov domain redirect to www.fec.gov

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1067]
We need to account for a redirect for beta.fec.gov to www.fec.gov. I believe the beta.fec.gov is not a route within fec-proxy and therefore needs to be taken care of a different way. Any ideas?

This really needs to be addressed pre-flip.

**Comment by LindsayYoung** [comment]
Wanted to confirm this was up and running

**Comment by patphongs** [comment]
I have not implemented a separate server block for this redirect yet. But if we are keeping the beta domain around, I don't think this is as urgent anymore pre flip

**Comment by patphongs** [comment]
Pull request is in for this redirect: https://github.com/18F/fec-proxy/pull/46

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-proxy/pull/46
