### ISSUE TITLE
Press office pages that need to be transition pages

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1068]
As promised to @patphongs, here are two recent pages I've found that are on www.fec.gov but not on transition.fec.gov that we linked to in various press releases and record articles. So users will see broken link if we don't get them on transition. Since these deal with the 2016 presidential election, and are linked on 2016 articles and releases, definitely would want to move these two pages over.

http://www.fec.gov/press/bkgnd/fund.shtml

http://www.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml

Thanks - please reach out if any questions.

**Comment by patphongs** [comment]
@dorothyyeager The Presidential Election Campaign Fund page https://transition.fec.gov/press/bkgnd/fund.shtml has been added to transition. As discussed, the content under the /finance/ directory will all go to classic.fec.gov since it will be moved to data eventually anyways.
