### ISSUE TITLE
So that users register a visual change in message content, change "Start tour" link to button in site banner

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1081]
The last tiny detail from the banner design issue—after the site flip, the "start tour" should have moved to a button target to complete the design on both new fec.gov and transition.fec.gov as part of the final change from beta language https://github.com/18F/fec-cms/pull/1075#event-1094212668.

Here's the [original google doc](https://docs.google.com/document/d/1I-fCJB3Cl5qXjN7o268JKfOUvjwauZW9HMU3TdR_sTU/edit#heading=h.aamn2b9ibczi) 🔏  with copy & designs, and a screenshot pulled out:
<img width="821" alt="screen shot 2017-05-24 at 8 39 10 am" src="https://cloud.githubusercontent.com/assets/11636908/26403594/cdb5cdc4-405c-11e7-95b4-b7b3fc160a5c.png">

cc @xtine

**Comment by noahmanger** [comment]
Oops! Sorry for forgetting this part.
