### ISSUE TITLE
So that there is consistency in formatting between FEC publications, enable custom title formatting on FEC Record page CMS templates

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1087]
A funny scenario I just ran into:

On Press release page templates, we have a custom `Formatted title` field that allows content publishers to italicize court case titles.

 - ![screen shot 2017-05-26 at 5 59 49 pm](https://cloud.githubusercontent.com/assets/11636908/26514151/09946322-423e-11e7-8c0a-268f0d083b6a.png)

On FEC Record page templates, we do not have that field.

 - ![screen shot 2017-05-26 at 5 59 27 pm](https://cloud.githubusercontent.com/assets/11636908/26514155/0ecd48cc-423e-11e7-95d7-a146e9b4f611.png)

Often, press releases and FEC Record articles cover the same topic, which means that it's possible to have a Press release and a Record article side by side with mis-matched formatting. (For transparency, I had to try intentionally to make this happen with sorting and filtering, but it is possible to happen through regular search behavior as well.)

 - ![screen shot 2017-05-26 at 6 00 52 pm](https://cloud.githubusercontent.com/assets/11636908/26514150/007c9e12-423e-11e7-810d-fa735ec78b04.png)

For consistency in formatting, we should enable the custom formatted title on Record templates. To make it one step more user-friendly for content managers, I also think we should move the `Formatted title` field to be immediately below the page title field, instead of below the body block. This would group fields by the same function.

**Comment by dorothyyeager** [comment]
Just wanted to say thanks to @jenniferthibault for tipping me off to this github issue. This will definitely be good for the Record and also for any future litigation pages to be designed.
