### ISSUE TITLE
Create contributions limit Wagtail snippet

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1093]
So that content managers only need to edit the contributions chart in one place and have those changes propagate everywhere, implement a Wagtail "snippet" for the chart.

**Comment by jenniferthibault** [comment]
Complication: Content managers have wanted to embed the table in a variety of _Help for candidate and committees_ pages, spanning the Custom Page template and the Resource Page template. The table as-is doesn't work well in templates that have both a side nav and a side resources bar

<img width="1110" alt="screen shot 2017-06-02 at 10 12 38 am" src="https://cloud.githubusercontent.com/assets/11636908/26729581/0c0a0c04-477c-11e7-806e-928bf9a8751f.png">

**Comment by AmyKort** [comment]
pinging @dorothyyeager for visibility

**Comment by AmyKort** [comment]
We'll need to have this functionality when we launch the citizens pages as well.

**Comment by johnnyporkchops** [comment]
I have a solution ready to submit, I just need to have a quick pair with @jenniferthibault

**Comment by johnnyporkchops** [comment]
- [ ] Allow users to embed the current contribution limits table  in pages
- [ ] Maintain the table in one location so that changes are reflected globally

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1193
