### ISSUE TITLE
Confusion around meeting pages being published from the future in latest updates

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1094]
In the latest updates feed, it's been causing confusion that it looks like the meetings are being published from the future.

The meeting pages currently use the meeting date in the position that other publications use as Publication date: 

(today is June 2)
<img width="1177" alt="screen shot 2017-06-02 at 11 50 44 am" src="https://cloud.githubusercontent.com/assets/11636908/26733732/be8c8aca-4789-11e7-920d-a40f4620d4c0.png">

@AmyKort & @dorothyyeager outlined the logic of where things appear and how they are dated:

> We seem to rely on the posting date for other documents, so the June 6 scheduled maintenance for Efiling is dated June 2--the day we posted the notice. The June 7 webinar sign up announcement is dated May 24, because that's the day it was posted. I thought the function putting of the meeting agenda's in the Latest Updates feed was primarily to provide the meeting documents, not announce the day of the meeting--which is a calendar function.

> I think of What's Happening as the news feed where people can access information and Upcoming Events as the calendar feed where people can see a date? So like you, I thought of the agendas in updates as the place to get the meeting documents.

> For something like a webinar - there's the calendar which should have the actual date of the event, and the what's happening feed, which will have the tip announcing it (dated the day the tip is posted) and the Record article with more information (dated the day the article is posted). Both tip and Record article will work the date of the event into the headline though.

> Since the meeting notice is already headlined June 8 Open Meeting, I think we should date it for the purposes of Latest Updates with the posting date. Does that make sense?

_________________

The result of that discussion was that it would make more sense to date the meeting page with the date it's posted, since the date of the meeting will be in the page title. 

*Criteria for completion*
- [ ] Change meeting page template post date to be date of publication instead of date of meeting

**Comment by AmyKort** [comment]
@rhoughfec

**Comment by jenniferthibault** [comment]
This will likely be resolved by #2158, which recommends separating meetings from latest updates into their own feed/page.

**Comment by noahmanger** [comment]
I'm just gonna close this since the new meeting page concept obviates it.
