### ISSUE TITLE
Take next steps on website governance process

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1100]
This issue is for creating an actionable content/website/publishing governance process that we can start to use in order to test it and see how it works.

@jameshupp any details to add?

**Comment by noahmanger** [comment]
Tagging in @acolter who is also looking into this, as I understand it.

**Comment by jameshupp** [comment]
A lot of this work is happening over in #1174 and we probably just need to specify what goes where.

**Comment by AmyKort** [comment]
@jameshupp  Do you think we should close out this issue in favor of #1174  ? Or are there steps we should add to this issue and keep it open?

**Comment by jameshupp** [comment]
Let's close this. #1174 handles part of this, and the work of #1283 will give us more specificity on the rest.

**Comment by AmyKort** [comment]
Thanks!
