### ISSUE TITLE
Page content, model, design out of sync

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1103]
Each filer group has sub-categories of guidance. For example, political party committees (parent) has seven child pages:
- Registering as a political party
- Taking in receipts as a party
- Making disbursements as a party
- Handling party loans, debts and advances
- Keeping party records
- Filing political party reports
- Terminating a committee

When you're on one of these child pages, users should be able to navigate between their siblings without needing to link back out to the parent category, which is currently housed on the _Help for candidates and committees_ home page.

To enable this, we have a resource-like sidebar housing these links on each child page.
This works well when the introductory content is multiple sentences, and fills the space (which is what we predicted for this design module). 

Like _[Registering as a political party](https://www.fec.gov/help-candidates-and-committees/registering-political-party/)_ or[ _Making disbursements as a party_](https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/)

![screen shot 2017-06-12 at 6 05 34 pm](https://user-images.githubusercontent.com/11636908/27057339-c70dd308-4f99-11e7-8713-9b79cbbcce13.png)

![screen shot 2017-06-12 at 6 06 12 pm](https://user-images.githubusercontent.com/11636908/27057365-e5def38e-4f99-11e7-9588-340a01d71a07.png)

Where it's not working well for us, however, is sections that have either no introductory content, or very little. Like [_Filing political party reports_](https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/) or [_Handling party loans, debts and advances_](https://www.fec.gov/help-candidates-and-committees/handling-political-party-loans-debts-and-advances/), where we've omitted it because it would be the only thing there

![screen shot 2017-06-12 at 6 08 22 pm](https://user-images.githubusercontent.com/11636908/27057422-2922ed80-4f9a-11e7-9567-6f75a2eace7f.png)

![screen shot 2017-06-12 at 6 07 57 pm](https://user-images.githubusercontent.com/11636908/27057427-2cd4492e-4f9a-11e7-9477-3e6e99ed2539.png)

cc @jameshupp

**Comment by jameshupp** [comment]
To my view, the way it renders on narrow screens is also a little awkward even with full text. It looks almost like a footer, like this page content is over and you should go to one of these other pages, unless you scroll down past it. Do we have any research or general concern about that (including that says I'm wrong, which would be delightful)? I can file this as something to research later, too, but if we're dealing with the sidebar in the first place, I think it might be easier to handle this question at the same time.

![img_0028](https://user-images.githubusercontent.com/6314097/27058102-3df16f54-4f9d-11e7-93d7-5c2fb788ed64.PNG)

**Comment by jenniferthibault** [comment]
Thanks for adding that on @jameshupp! To my knowledge we haven't tested or researched the structure of these pages or this section (and for sure not on small screens), but it's looking more and more like it's needed. 

This also makes me think of the existing issue for content strategy & design around the Resource page templates and Custom page templates in wagtail: https://github.com/18F/fec-cms/issues/1036

Though that issue seems to get at it from a strategy perspective, this one is cataloging awkward/confusing interface experiences.

**Comment by noahmanger** [comment]
Going through old issues. What's the status with this?

**Comment by dorothyyeager** [comment]
This issue should be largely resolved by the new language added in #1696
