### ISSUE TITLE
Make PDFs view open in browser instead of force-download

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/fec-cms#1107]
So that users can view PDFs in the browser instead of downloading. 
A similar issue with audio files was fixed by this PR: https://github.com/18F/fec-cms/pull/1086

Possibly, a similar solution as https://github.com/18F/fec-cms/pull/1086 could be used, but ideally we would want the default to be for PDFs to open in browser window, and only set it to force download where we might want that for some  particular content strategy.

Background: It seems that Django's default is to serve documents as "attachments". So clicking on links to PDFs forces download instead of using the built in PDF viewer available in most modern browsers.

Documents added to the CMS either by pasting a URL into a text type fields (URLField, TextField, etc) or documents uploaded to the documents tab of the CMS via the document option in a RichTextBlock interface are force-downloaded instead of viewed in browser.

Documents added via a DocumentChooserBlock can be configured at the template-level to view in browser, instead of download by adding "file" before the URL in the template block, like this example:
Change block.value.item_audio.url to block.value.item_audio.file.url

But the above solution does not work for text type fields and any similar per-template solution like this would be tedious to implement and likely cumbersome to maintain.

So the solution in this PR (https://github.com/18F/fec-cms/pull/1112 )is to override Wagtail's default document view and redirect to the real file URL by adding a view to views.py and a URL pattern to urls.py.

Tested this locally and it seems to work for all types of fields.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1112 . Thanks @johnnyporkchops !
