### ISSUE TITLE
Change templates to upload rather than URL field

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1110]
Now that we have the capability to upload documents into Wagtail. We need to update our templates to allow document chooser/upload funcitonality rather than provide a link when applicable. 

Will provide some more screenshots and examples of necessary areas later.

**Comment by johnnyporkchops** [comment]
Is there a new functionality that we did not previously have? We already have document upload options in the page editor for some pages, Has something been added in wagtail as it relates to s3?

**Comment by johnnyporkchops** [comment]
The ability to upload larger documents that @pat has added will solve issues I have experienced a few times, thanks@pat

**Comment by jenniferthibault** [comment]
@johnnyporkchops I see that you added the uploader to at least one field in https://github.com/18F/fec-cms/pull/1228

Does that close this issue, or do you want to make a list of other fields? 
And if it's the latter, can you make that list and move this issue out of "Done" and into the backlog?

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by AmyKort** [comment]
We'll continue this work at https://github.com/18F/fec-cms/issues/1517 as necessary
