### ISSUE TITLE
Determine which content is able to launch

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#112]
- [x] Emileigh to work with Amy & Amy to determine what to launch
- [x] Submit to OGC for re-review

Story map card: [Candidate committees can find out how to register](https://18f.storiesonboard.com/m/fec/!card/qv-XXBL-Je7ikjnTowJqCg)

**Comment by emileighoutlaw** [comment]
Next steps:
- [ ] Final review of content
- [ ] Beta warning?

**Comment by jenniferthibault** [comment]
If it's an option to go without the beta warning, I'd advocate for that. The site screams beta at you everywhere :)

**Comment by emileighoutlaw** [comment]
Yeah, I'm totally with you on that. Let's talk about it at the meeting today. A few weeks ago it seemed like OGC felt this was non-negotiable, but maybe we could try to coax again.

**Comment by noahmanger** [comment]
Done!
