### ISSUE TITLE
Explore govdelivery for relationship between existing lists and pages on the new site

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1121]
To help users receive effective and targeted alerts of new content, we need to re-map the govdelivery list from classic to the new website. 

related to https://github.com/18F/fec-cms/issues/1090

**Comment by AmyKort** [comment]
Pinging @dorothyyeager as well.

**Comment by jameshupp** [comment]
Spreadsheet where I went through a bunch of lists to figure out design needs: 
🔒  https://docs.google.com/spreadsheets/d/182VvW_PAbl9Gfg6kDElXC1vKGsQTofJNg4uaBbaqEMI/edit#gid=1706517435

**Comment by dorothyyeager** [comment]
Hi @jameshupp - looked at your spreadsheet and have a note to add regarding the Educational outreach list. Right now it's being used for info that goes with https://transition.fec.gov/info/outreach.shtml. That page is one of the pages to be factored into the next quarterly planning for a redesign, so I would guess that whatever emerges from that will be the page to match up with that particular list.

**Comment by jameshupp** [comment]
I need to take a closer look at this against #1090. I'm not 100% sure how to order the work here vs the work there, they kind of seem to need to go simultaneously.

**Comment by jameshupp** [comment]
Closing in favor of #1090. They're too similar to keep separate.
