### ISSUE TITLE
Implement CMS single-sign on plan

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1127]
To improve our authentication process in Wagtail, implement single sign-on plan. 

Identify all of the steps we need to take to understand and implement this enhancement, including potential cross-agency solutions.

**Comment by AmyKort** [comment]
@PaulClark2

**Comment by PaulClark2** [comment]
Update: met with cloud.gov and FEC's infrastructure team. FEC's infrastructure team will review some documentation. The plan is to have a more technical meeting between cloud.gov and FEC next week.

**Comment by PaulClark2** [comment]
FEC IT and cloud.gov folks will review and troubleshoot setup of FEC's SSO integration to cloud.gov's staging environment Friday, 8/18, morning.

**Comment by PaulClark2** [comment]
Met with cloud.gov this morning. We hit a blocker with a certificate. Cloud.gov will ping us when the issue is resolved. We can test on stage as soon as we hear from them.

**Comment by PaulClark2** [comment]
New blocker: I was unable to login to cloud.gov's stage environment. I will need to wait for cloud.gov to get back to me. 

![image.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/9066c535-7eb5-45d6-b02a-86be67f999b0)
