### ISSUE TITLE
Audit content around SSF registration

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#113]
Story: So that SSFs know how and when to file a report, create content explaining when and how to file a report.
- [x] Do inventory of what needs to be included

Story map card: [SSFs can learn how to file a report](https://18f.storiesonboard.com/m/fec/!card/gCSRHfjPWegOKjnT8EgiIg)

**Comment by emileighoutlaw** [comment]
Inventory captured here: https://docs.google.com/document/d/1W0npV-cUju7qj3zgEkgVtrj_Hq0Ft4RFFJrcR9th-vQ/edit#heading=h.7nq6m5fpkzwz

**Comment by emileighoutlaw** [comment]
Complete
