### ISSUE TITLE
Select examples of content to fit into long-form model

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1131]
So that users can easily find and digest the specific information they're looking for, we need to present complex guidance in a way that allows users to find what they specifically need, hold onto the larger context surrounding that information, and move back and forth between related content/concepts. With the goal of developing a rubric for how to approach long form content, we'll start with an inventory of known examples.
- [x] Completion criteria: create list of examples of long-form content
- [x] Resolve outstanding issues around citizens content

**Comment by AmyKort** [comment]
Met with @llienfec this morning. We think the work we're currently doing to resolve long-form content issues related to the citizens content and the reporting examples will get us where we need to go to developing our rubric for approaching long-form content. 
https://github.com/18F/fec-cms/issues/1123
https://github.com/18F/fec-cms/issues/1132

Does it make sense to close this issue in favor of the other two?

cc @dorothyyeager and @gsmaragdis

**Comment by gsmaragdis** [comment]
I think so

**Comment by AmyKort** [comment]
Great! Got together with @dorothyyeager today as well, and I think we have a consensus that the reporting examples and the citizens content are our two best examples of types of long form content that we need to figure out how to tackle.
