### ISSUE TITLE
Prioritize and identify outreach transition.fec.gov pages for being brought into new fec.gov 

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1133]
FEC Information Division staff need to identify which of our pages/sections on transition.fec.gov will eventually move into fec.gov, and then prioritize those pages/sections in terms of need/desirability to have them on the main site by election year 2018.

- [x] Create a list of 1 or 2 transition pages to migrate

**Comment by dorothyyeager** [comment]
Just had a good conversation with @AmyKort. Right now the Info division is primed to move quickest on these two sections:

1) Educational outreach, currently at https://transition.fec.gov/info/outreach.shtml. Most of this involves conferences and webinars. The Resource page template should work provided images can be used.

2) Filing and reporting, currently at https://transition.fec.gov/info/filing.shtml - but there are current pages on fec.gov (Forms, Electronic Filing and Deadlines) that serve as the new home for these pages. So the pages to be brought over (mostly deadline pages) would be child pages of these already-created pages. Forms and instructions just need to be uploaded.

**Comment by AmyKort** [comment]
Looks great!
