### ISSUE TITLE
Create documentation for links to fec.gov domains

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1136]
We have many different domains that has caused issues with linking to our different sites: www.fec.gov and transition.fec.gov. We need to create documentation on the correct links to use when generating links in either Wagtail or Contribute.

**Comment by patphongs** [comment]
One page cheatsheet has been created: https://docs.google.com/document/d/1R2iv7HJlAPZKY0w8NbdspCL9GmTYD_t_kM67mgcrYnU/edit#heading=h.ho1pj7ec498c

**Comment by AmyKort** [comment]
Perfect! Thanks!
