### ISSUE TITLE
Add versioning to prod content s3 bucket

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1141]
Here are the instructions:
http://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-versioning.html

This will make it so we can restore things if there are accidental deletions. :)

**Comment by patphongs** [comment]
Versioning has been turned on for all buckets: transition-prod, legal-downloads-dev, legal-downloads-stage, legal-downloads-prod

**Comment by LindsayYoung** [comment]
I don't think we want versioning for downloads or in the non-prod environments, because that would cause some bloat, but happy to reconsider if you disagree. 

I do think we want it in content-s3  Did that happen?

**Comment by patphongs** [comment]
@LindsayYoung I agree, we should just turn on in Prod S3. The 2 buckets that will need it is the content-s3 bucket and the hybrid transition site bucket. I don't believe I have turned it on for the content-S3 yet. Will have to double check

**Comment by AmyKort** [comment]
Can we close this?
