### ISSUE TITLE
Show multiple amended Sunshine Act notices as amended with number

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/fec-cms#1144]
When there is  more than one amended Sunshine Act Notice, the current template logic only shows the last on as being amended. Dayna Brown, Commission Secretary asked if we could show each amended notice as being amended. Below are screenshots of current view and how it looks on the PR: https://github.com/18F/fec-cms/pull/1145
**Request from Dayna:**
Dayna Brown
Wed 6/28, 3:23 PM
_Thanks, John.  One change.  Can we please refer to the middle notice as an “Amended Notice” as well, since it was amended from the first/original notice?_
Thanks!

## **Currently:**
![multiple_sunshines](https://user-images.githubusercontent.com/5572856/28443941-69ddadfa-6d87-11e7-8ae9-e89b19893d0d.gif)

## **New:**
![new_multiple_sunshines](https://user-images.githubusercontent.com/5572856/28443952-81616cf0-6d87-11e7-912e-601910b7086c.gif)
## **On Updates Feed:**
![new_multiple_sunshines_upates](https://user-images.githubusercontent.com/5572856/28443953-87f6a3a0-6d87-11e7-8dfd-6e850a934f4d.gif)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1145
