### ISSUE TITLE
Enhance Wagtail Search/Filter Capabilities

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1149]
It's hard to find specific pages in Wagtail. We'll investigate options to:

- [ ] Make updates easier to find
- [ ] Disambiguate pages in Candidates and committees section
- [ ] Provide names to recurring content that distinguish year from year
- [ ] Move content that's in the wrong place and test for/repair broken links

---
Now that https://github.com/18F/fec-cms/pull/1172 is merged in, we can start organizing pages under folders. To do this:

- [ ] Create new "folder" pages and add a URL where the page should redirect to
- [ ] Using the command line, bulk move all latest updates under parent folders
- [ ] Using the command line, get all of the URLs for each page type and then set up redirect rules

**Comment by noahmanger** [comment]
I have an idea for how we can introduce folders that I wrote up in a PR here: https://github.com/18F/fec-cms/pull/1172

**Comment by llienfec** [comment]
@noahmanger: Met with @dorothyyeager and we think this idea would be a big help for those huge collections.  We may still need @patphongs to weigh in.

Also, we need your brain.  We were wondering if we could use the same folder/redirect idea to help us organize the content pages.  Under Explorer>Help for candidates and committees, we need some help distinguishing between which pages are committee specific (and specific to which committees) and which apply to all committees.  The major concern here is that in the future, someone would update a page with committee-specific information, not realizing that page is used for all committee types.  

We thought that a "folder" per committee type (candidate, SSF, nonconnected, party) would really help, and then possibly one that is for all of the info that applies to everyone.

**Comment by noahmanger** [comment]
Yes! Those would work the same way. You'd just need a link to redirect to, which you could point to, say, `/help-candidates-and-committees#ssf` or whatever. Since this sounds like it'll work, I'll try to get that PR reviewed.

**Comment by llienfec** [comment]
Update to issue.  

- Make updates easier to find
- Provide names for recurring content that distinguish from year to year

Came up with 2 approaches.  
1. Add years to file names.  @dorothyyeager is currently working on this.
2.  Add a column to the browse/search pages in Wagtail for the date that the page was originally published.  This would be a huge help for getting to info faster.  We have a column for when pages were updated, but if you make a change, that date changes and is no longer helpful in figuring out what year to put in the title.  @noahmanger would this be a possible addition to Wagtail?

- Move content that's in the wrong place and test for/repair broken links

We identified content that needs to move.  We'll set up a meeting time to move this content and then testing links and fixing anything that breaks because the page links changed.  We also identified pages that can be deleted.  Will add an issue for this since we are not able to delete these pages.

**Comment by noahmanger** [comment]
I'm not positive if #2 is possible but I think it is. Can you make a separate issue for that?

**Comment by dorothyyeager** [comment]
I can take care of making the issue for the browse/search pages @llienfec @noahmanger

**Comment by dorothyyeager** [comment]
One more thought - for the future in terms of naming things for the updates folder, we may want to develop and provide guidelines to the Information Division and the Press Office.

**Comment by AmyKort** [comment]
What would you think about addressing naming conventions in the style guide?

**Comment by dorothyyeager** [comment]
@AmyKort Think that's a great idea, especially as more people get onboard and are doing things in Wagtail. Even when we were doing the party pages, found that some of our folks understood naming and SEO and being careful with that more than others.

**Comment by llienfec** [comment]
@AmyKort @dorothyyeager Maybe even finding a good SEO article to link to would help too.  It's such a specific data architecture idea that extra education/and easy reference couldn't hurt.

**Comment by AmyKort** [comment]
I'll update https://github.com/18F/fec-cms/issues/1174 to add this to completion criteria. Thanks!

**Comment by noahmanger** [comment]
I just updated this issue with some more steps now that we have the new Folder page types merged in.

**Comment by PaulClark2** [comment]
From Slack #content 8/15/17

Noah Manger [3:01 PM] 

Great news! I found a _much_ better way to solve the long-standing problem of organizing the latest updates, and it’s even better than the folder option I made earlier this sprint: https://github.com/18F/fec-cms/pull/1200

[3:01] 
Over the course of this work, I also discovered that it’s possible to display custom formatting of all page titles in the admin view. I’m wondering if maybe this would be a better solution for keeping the Help pages organized?

[3:02] 
For instance you could have a format like `[page title] - PAC - [original date]` or something

[3:02] 
to help disambiguate

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1200
