### ISSUE TITLE
Clarify who the SSF guide applies to

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#115]
Story: So that SSFs can learn more details how to conduct campaign activity, make it clear who an SSF is and which campaign guide they should read. 

- [x] Clarify who the SSF guide applies to

Story map card: [SSF's can find campaign guide relevant to them](https://18f.storiesonboard.com/m/fec/!card/gmRJlccKVUYMfjnT8EgiIg)

**Comment by emileighoutlaw** [comment]
`Registration options` content should address both these issues.

Draft text here: 1s4L4ajnuY0rJwYSGrlAqgI3RzRqZhruVsnuLxFnqAVY
