### ISSUE TITLE
Move reporting date transition pages into CMS

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1150]
While general information on reporting deadlines is included in the cms, specific reporting date information from 2017 is on transition. https://transition.fec.gov/info/report_dates_2017.shtml#frequency# (for example)

We want to bring that information into the cms while:

- [ ] creating a way to highlight current-year reporting requirements and archiving past year requirements
- [ ] making sure user can easily find the reporting dates that apply to each type of filer
- [ ] making sure users can find and understand special election reporting requirements
- [ ] accounting for 2018 Congressional Pre-election reports

**Comment by dorothyyeager** [comment]
When we are planning this in PI planning next month, we will need to include finding a way to make sure this information is printable, in order to avoid having to create and upload a ton of PDF files.

**Comment by dorothyyeager** [comment]
Just wanted to note for PI planning purposes that #1146 is something that will relate to this issue. The ability to customize tables will be really important for the reporting tables pages. @PaulClark2 @AmyKort
