### ISSUE TITLE
Find new home for information about FEC's data holdings

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1154]
The FEC provides guidance on how to search public records of campaign finance data and information, including an explanation of the types of data that have been collected over time as campaign finance disclosure regulations have changed. In order to help users find and understand historical campaign finance data, we'll need to provide this information in a way that is findable, understandable, and consistent with the way data is displayed on the site.

- [x] Is the information current and consistent with our current practices?
- [x] Does it makes sense in context of work we've done to make data more accessible to public users?
- [x] Can this be rolled into other work to improve explanations in the data section?
- [x] Information lives one place 
- [x] How to address information that is not strictly campaign finance data clarification
- [x]  Does some of this fit into our About section?
- [x] Meet users at their level

**Comment by AmyKort** [comment]
Content owners met to discuss these issues and determined the current site doesn't have good contextual information do go with our data--for example, when do you itemize receipts and what information is included when a transaction is itemized. We'd like to take some of the great explainers that our Public Records office has developed and build out space in the data section to give people context for the information they're looking at. This could take the form of a data library, for example. 

So, we have two streams of work: 1) build out contextual information on the data that is disclosed, the filing schedule, etc. to help users understand the data they're seeing. 2) Take this contextual information out of the citizens section, where it is too far away from the data it describes.

**Comment by AmyKort** [comment]
For other content that is not strictly related to describing campaign finance data, our next step is to determine whether all of the other resources are currently captured on the new site and whether links to these resources from the citizens section makes sense--is this where public users would go, for example, to fund an audit report?

**Comment by AmyKort** [comment]
Met with @dorothyyeager @PaulClark2 and @gsmaragis today to review information about data holdings in the context of explanations provided here: https://www.fec.gov/data/advanced/ and https://www.fec.gov/data/advanced/?tab=other . Our consensus was that the information currently in "Researching Public Records" isn't redundant with what's already in the data section, but that maybe it should be because there's a lot of great information in the Researching Public Records section that we could expand upon and include in the data section. This is probably going to be a longer-term project to implement.

We've also confirmed that links to other FEC resources currently collected in what we've been considering the "Citizens Section" already exist on the new site.

cc @jameshupp

**Comment by noahmanger** [comment]
Just my $.02 for the future of this work: it could even be good to think about pulling in explanations when relevant to the data table pages or candidate and committee profiles. Just something to noodle on.

**Comment by AmyKort** [comment]
speaking for @PaulClark2 and me, we'd love to go big on this. It's so important to give context to folks who are looking at our data. It would be great to look into ways to make those connections.

**Comment by gsmaragdis** [comment]
Totally agree about going big.  
Very high value project. 
Is that a haiku?

**Comment by AmyKort** [comment]
Next steps: create content within data section and find design solution for presenting information both all together and related to specific data sets.
