### ISSUE TITLE
Find new home for general information about elections, including contact information for other agencies

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1155]
To help direct users who need election and voting information, and state campaign finance information, the FEC provides quick explanations, links and directories to other federal and state agencies. We need to make this information easily accessible on the new website.

- [x]  Determine universe of outside contact information we have to share and the audience
- [ ]  Find a good home for this information

**Comment by dorothyyeager** [comment]
Just an update. The first task is done and I've created a google spreadsheet listing everything. Some things already are on the website but spread out in various places. The next step will be to figure out my recommendation for the new homes and bring it to the content team.

**Comment by dorothyyeager** [comment]
Closing this issue as we have decided to set up a page for this information that will be part of the citizens section referenced in #1182.
