### ISSUE TITLE
Update glossary with additional terms

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1157]
Various FEC information division specialists have given informal feedback that they think it would be helpful to have additional FEC and FECA terms added to the glossary. In posting and reviewing the pages in the help for candidates section, there does seem to be a need for this, to help make the information easier to understand, especially on pages that by necessity are filled with legal terminology.

Doing this would involve:

- [x] Determining which terms to include
- [x] Developing the definition for each new term (note: FEC campaign guides will have this in most if not all cases)
- [x] Updating the code for the new terms to be added
- [ ] Updating the pages to add links to new terms

**Comment by dorothyyeager** [comment]
Just an update - have sent a draft document to the content team containing suggested terms to include and a draft definition for each.

**Comment by dorothyyeager** [comment]
Had a good pairing with @noahmanger and many of the terms have been coded. See https://github.com/18F/fec-style/pull/756. There's a few that are undergoing OGC or content team review.

**Comment by AmyKort** [comment]
@dorothyyeager is there still work we need to do to link the terms in the text to our new glossary items?

**Comment by dorothyyeager** [comment]
@AmyKort  Yes. Code to add the terms to the glossary overall needs review (Pull request is at https://github.com/18F/fec-style/pull/756) and then I'll need to go into the pages and add the html code where each term appears.

**Comment by AmyKort** [comment]
Awesome! Thank you @dorothyyeager !

**Comment by AmyKort** [comment]
Closing this issue. We'll pick up the remaining terms under https://github.com/18F/fec-cms/issues/1199
