### ISSUE TITLE
Find home for FECConnect One on One (public appearances) information

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1159]
Connect One on One is an educational outreach program that offers Commission speakers to groups, as well as an opportunity to get one-on-one training on the law (either via webinar or in-person). It is used for student and international groups, as well as enforcement case settlements (usually ADR cases). It is currently described with a short blurb at https://transition.fec.gov/info/outreach.shtml#appearances and has a dedicated email (speaker@fec.gov) which is answered by the Information Division (which makes all the arrangements for the appearances).

We need to:
- [x]  Add the speaker@fec.gov information to the "Contact us" section
- [x] Evaluate whether this information should appear elsewhere on the site (and where?)
- [x]  Make sure that we have the right introductory text to explain what this is

**Comment by dorothyyeager** [comment]
In regard to #1, there's two possibilities:

Option 1: Make it into its own section on Contact us (following the format used by other entries):

Public appearances

To invite a Commissioner or FEC staff member to speak to your organization about campaign finance issues, please contact the Information Division:

1-800-424-9530 (menu option 6)
202-694-1100
speaker@fec.gov

Option 2: Fold it into the Information Division part as currently posted, by updating the information for our emails:

Help with campaign finance law questions: info@fec.gov
Public appearance and FEC speaker requests: speaker@fec.gov
Educational outreach and training inquiries: conferences@fec.gov

We will need to figure out which approach to take. This brings into play the issue @patphongs raised in https://github.com/18F/fec-testing/issues/75 as we need to find the best way to let users know the contact information for our programs.

**Comment by dorothyyeager** [comment]
Happy to say a decision on the initial wording of the "contact us" entry has been made. We are going to start with option 2 and see what happens when tested. I will work with @patphongs and @johnnyporkchops to get the page updated.

**Comment by johnnyporkchops** [comment]
@dorothy: For updating the contact info:
Here is what is there now, would the three email addresses go below that:
```
Information Division

Including help with educational materials, registering a committee, ordering a reporting form or campaign finance law 1-800-424-9530, menu option 6 202-694-1100 info@fec.gov```

**Comment by johnnyporkchops** [comment]
removing first info@fec.gov`

**Comment by johnnyporkchops** [comment]
PR https://github.com/18F/fec-cms/issues/1178 only adds contact info to contact page. I believe these issues from above are still awaiting resolution:
2. Evaluate whether this information should appear elsewhere on the site (and where?)
3.  Make sure that we have the right introductory text to explain what this is

**Comment by dorothyyeager** [comment]
@johnnyporkchops  Yes, basically where most of the entries have the one address is where we'd want the three. The second and third items will depend on user testing results (and in the case of the second, probably figuring what we want to say on the educational outreach page that will be designed in Q1 of FY19).

**Comment by AmyKort** [comment]
When we decided to go with this option, I think we took a first pass at answering those last two completion criteria. We'll confirm our assumptions with usability testing.
