### ISSUE TITLE
Create reporting example and scenario modules

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1160]
Carried designs over from https://github.com/18F/fec-cms/issues/1123

In order to publish reporting examples and scenarios, we need to create these components in wagtail.

- [x] Discuss implementation approaches for possible changes to "continue learning" with @jenniferthibault & @noahmanger 
- [x] Determine if we want to make new page templates or adjust an existing template
- [x] Add components to wagtail templates

Successful completion ends with the components available for use in a template(s) in Wagtail and ready for content.

**Comment by jenniferthibault** [comment]
Here's a wuick cheat-sheet of components. The one I'd like to particularly discuss with @noahmanger is the Video/PDF resources grid, which would be an adjustment to "Continue learning" examples

![screen shot 2017-07-27 at 4 20 07 pm](https://user-images.githubusercontent.com/11636908/28690579-aefa5fe0-72e7-11e7-8799-ede9e9fec35c.png)
![screen shot 2017-07-27 at 4 20 24 pm](https://user-images.githubusercontent.com/11636908/28690580-aefc3414-72e7-11e7-9b2b-e5bf7c28417f.png)

**Comment by jameshupp** [comment]
Adding the guidelines for content managers here. As I said on #1123 it's too belabored probably, but I think it might be relevant information, and at very least we might gain relevant information from this story to add into it. 🔒 https://docs.google.com/document/d/1Y4qshPcm6eelxqYY_FaxLVE6rLUeZUIsd0N2VlMxzBc/edit#heading=h.x1yhokkt7auz

**Comment by jameshupp** [comment]
Would like to sit in on early discussions about what Wagtail has to do. I want to keep the guidelines up to date and more relevant to the CMS where that's useful.

**Comment by jenniferthibault** [comment]
We touched on this briefly in design pairing today, and decided on a few things:

## A new page template makes sense
that since the reporting example and scenario page will need significantly less widgets & thingamabobs than the existing Custom page template, it does make sense for them to have a new template


## Continue learning module change
We also agreed that it makes sense to adjust the "Continue learning about this topic" module that exists on Custom page templates and will be re-used here. We're experiencing some resource link creep on those pages, and the irregular formats are creating some irregular layouts. The [Types of contributions](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-types/) page illustrates this well. The adjustment we'd make is to make the icons uniform size and shape, and to use more universal icons than custom images that would fall in three categories: 
1. video
2. PDFs
3. Brochures (also PDFs, but a resource that's differentiated as particularly useful in the FEC's world)

I'm torn between two options for the brochure icon, but leaning toward the first. Thoughts @jameshupp @noahmanger ? :
_(PDF icon credit: [CFPB,](https://thenounproject.com/cfpb_minicons/uploads/?i=89525) who we use icons from frequently)_

![screen shot 2017-08-04 at 6 55 24 pm](https://user-images.githubusercontent.com/11636908/28989907-879d4d62-7946-11e7-8140-84dd268ede66.png)

**Comment by jenniferthibault** [comment]
Trying my hand at summarizing the above + finished designs from https://github.com/18F/fec-cms/issues/1164#issuecomment-320364241 into a list of changes by template. @noahmanger take a peek!

## Changes to the `Collection` page template

- Add a new section for "Reporting examples" with lists and section headers. This should be available in the sticky nav
  - @jenniferthibault will export the icon

![screen shot 2017-08-09 at 1 40 09 pm](https://user-images.githubusercontent.com/11636908/29135472-3ddc8484-7d08-11e7-9f5d-c6bf32319b93.png)

## Changes to the `Custom` page template

- Add Reporting example card modules that can be inserted between paragraph blocks. They should display in grids of two-across
![screen shot 2017-08-09 at 1 42 26 pm](https://user-images.githubusercontent.com/11636908/29135603-ac69e3ec-7d08-11e7-8aa9-07183f9ed256.png)

- *Change* the style of embedded brochures and videos in the `Continue learning about this section` module so that the thumbnails are uniform dimensions with default images. Change the headline structure to begin with what type of media it is, then the title. (This module will also be reused in future templates in this comment)
- Since this always occurs as a full-container-width module, it could hold 4 elements wide before breaking onto a new line
  - @jenniferthibault will export the images
![screen shot 2017-08-09 at 1 46 32 pm](https://user-images.githubusercontent.com/11636908/29135736-22101f76-7d09-11e7-8bb9-eb069380f9af.png)


## Create a new template
This template will be used for both Reporting examples and Reporting scenario pages. I'm not sure what we should title it.

- Include these heading/page title components:
![screen shot 2017-08-09 at 1 50 01 pm](https://user-images.githubusercontent.com/11636908/29135902-9dd5bddc-7d09-11e7-81bc-fcada7ffc298.png)

- Include example modules (built off of the existing embedded example module) with an image caption on the side. Should be able to include one or more images and captions per example

![screen shot 2017-08-09 at 1 52 29 pm](https://user-images.githubusercontent.com/11636908/29136082-226febee-7d0a-11e7-950e-b3a159d85dcb.png)

- Include card module for example scenarios that link to example scenario pages
![screen shot 2017-08-09 at 1 55 02 pm](https://user-images.githubusercontent.com/11636908/29136158-616f9e48-7d0a-11e7-81f6-3a27ca947faf.png)

- Include media/resources module
This should be the same as the changes "Continue learning about this topic" module mentioned above
![screen shot 2017-08-09 at 1 59 54 pm](https://user-images.githubusercontent.com/11636908/29136373-0f71eb2c-7d0b-11e7-89c7-3ee419c4b544.png)

**Comment by noahmanger** [comment]
This is all making sense. Can you just upload the red icon images for the media/resources module?

**Comment by jenniferthibault** [comment]
[images-icons.zip](https://github.com/18F/fec-cms/files/1215133/images-icons.zip)

Yup! Here are those three plus the financial document for the cards

**Comment by noahmanger** [comment]
This is all done and ready to demo at design pairing tomorrow.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1187
