### ISSUE TITLE
Preparing BCRA pages on transition.fec.gov for retirement to classic.fec.gov

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1161]
The BCRA (Bipartisan Campaign Reform Act) pages were created in 2002 and 2003 in response to legislation that changed federal campaign finance law in significant ways. While it was necessary to have them back then to assist committees in adapting to significant changes in the ways campaigns and parties were funded, 14 years later, there is no longer a need to have them as a separate, dedicated page or section. Moreover, the law has evolved post-BCRA and up to date information summarizing the law post-BCRA is available for each type of committee in the Help for Candidates section. Information on BCRA itself is in the Legal Resources section, where one can find statutes, regulations, advisory opinions, litigation and a link to the full text of the BCRA legislation.

As a result, the BCRA pages will live on for historic purposes (with a banner noting they are no longer updated) at http://classic.fec.gov/pages/bcra/bcra_update.shtml, but should be removed from the transition site (as they have not been kept current and users can actually find more current listings on the FEC's current website). 

Pages that should be removed (with suggested redirect noted):

- [x] https://transition.fec.gov/pages/bcra/bcra_update.shtml - redirect to https://www.fec.gov/legal-resources/legislation/
- [x] https://transition.fec.gov/pages/bcra/major_resources_bcra.shtml - suggest redirect to https://www.fec.gov/legal-resources/ as this page was primarily a list of where to find statutes, rules and AOs.
- [x] https://transition.fec.gov/pages/bcra/litigation.shtml - suggest redirect to https://www.fec.gov/legal-resources/court-cases/ as major BCRA litigation is included in our "selected court cases" list
- [x] https://transition.fec.gov/pages/bcra/aos_bcra.shtml - suggest redirect to https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&search=BCRA&q=BCRA&ao_category=F (which brings up AOs tagged BCRA and is more current than the old BCRA page)
- [x] https://transition.fec.gov/pages/bcra/rulemakings/rulemakings_bcra.shtml - suggest redirect to https://www.fec.gov/legal-resources/regulations/ where rulemakings, regulations and E&Js can be searched

**Comment by johnnyporkchops** [comment]
These pages have been redirected to www, via PR: https://github.com/18F/fec-proxy/pull/55.
As soon as the redirects are deployed, I will remove them from transition.fec.gov

**Comment by dorothyyeager** [comment]
Excellent - thank you!

**Comment by AmyKort** [comment]
Are we ready to close this one out?

**Comment by dorothyyeager** [comment]
Not sure   the BCRA pages are still up. It may need to wait for the release to verify that the redirects @johnnyporkchops are working.

**Comment by johnnyporkchops** [comment]
These are not redirected yet, as soon as they are deployed, I will comment here.

**Comment by dorothyyeager** [comment]
Confirming that the BCRA page redirects are working and those pages are no longer on the transition site. Thank you @patphongs @johnnyporkchops
