### ISSUE TITLE
Creating collections to house documents and files currently living on transition site

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1162]
We have several important types of documents and files in PDF or XML formats that are linked on many pages on fec.gov. These documents need to be in PDF and XML format and need to have a permanent home as opposed to the transition site. 

This issue is to create collections to house these documents on the website and make available for easy access in Wagtail.

Collections to consider creating with suggested names:

-  "Guides and publications" - This would be a collection for the four PDF files for Campaign Guides, as well as any other brochure or publication in PDF format.
- [ ] Create collection - name it "**Guides, manuals and publications**" to incorporate FECfile manuals as well as other "manuals" or guide-type publications by other divisions, as well as those produced by the Information Division
- [ ] Upload initial files
- [ ] Create needed redirects
 
- "Forms and instructions" - This would be a collection to house the PDF files for the paper FEC forms and instructions. Update: 
- [x] Create collection; named "**FEC reporting forms and instructions**"
- [x] Files uploaded
- [ ] Create needed redirects

- "Information notices" - While Federal Register notices related to rulemakings live in SERS, the Commission sometimes publishes other types of Federal Register notices. Most of these notices regard special election notices, inflation adjustments to various limits in the law and policy initiatives, such as "interpretive rules" and "policy statements" that are not actual rulemakings. In general, the Information Division has been the one to upload these documents, so a dedicated collection in which to upload them would be desirable. (Keeping in mind, however, that no determinations have been made yet regarding the policy page or files related to that, so this collection and issue are focused now on the other types of notices mentioned, which are generally authored by the Information Division.)
- [x] Create collection - Info has decided to name it "**Information FR notices**"
- [x]  Upload files
- [ ] Create needed redirects

- [ ] "XML files" - There are several XML files updated by various divisions for users who subscribe to RSS feeds. Examples include the tips for treasurers XML file edited by the Information Division and the Weekly Digest feed edited by the Press Office. Currently, these XML files are being uploaded to the classic.fec.gov site to house them. It is worth considering how to best organize and upload them into Wagtail. @johnnyporkchops provided additional details below: They each have a dedicated document in Wagtail.

Possible steps:

- [ ] Create collections for the documents and files mentioned
- [x] Upload the files - will do as noted above for each collection
- [ ] Create any needed redirects for transition site links  - will do as noted above for each collection
- [x] Consider whether any other files should be included or collections created
- [x] Think about including publications from other offices

**Comment by johnnyporkchops** [comment]
Regarding the XML files, the thought was to have a link to the current document in Wagtail, like:https://fec-prod-proxy.app.cloud.gov/admin/documents/edit/69/
And possible have this link inside certain templates, like Tips for Treasurers and Weekly Digest that gives the editor a direct link to change this document to the new one.

**Comment by dorothyyeager** [comment]
This looks good @johnnyporkchops. Thanks!

**Comment by llienfec** [comment]
Can we also add a collection for e-filing documents?  We need a place on the current website to house the Getting Started Manuals.  We'll be linking to these a bunch in the reporting examples and it would be nice to do it on www instead of transition if possible.  Thanks!

**Comment by dorothyyeager** [comment]
Totally agree this is needed @llienfec - I guess a follow-up question for all to consider is do we want to fold these into the "Guides and publications" - maybe with a new title of "Manuals and publications" (since the Guides are publications)? Or is it better to separate them into their own categories?

**Comment by dorothyyeager** [comment]
Updating the top portion so that we can best track what's been done for each collection and what remains.

**Comment by dorothyyeager** [comment]
We've discovered that the newly uploaded documents show up with their Amazon cloud URLs rather than with the fec.gov ones. It may have something to do with the default view for them (download rather than view). Will hold off on creating 3rd collection until this gets figured out. @patphongs and @johnnyporkchops have the spreadsheet showing recommended redirects for the other two collections.

**Comment by dorothyyeager** [comment]
Adding to yesterday, as I compile the list of things to put in the Guides, Manuals, etc. collection, I'm seeing that it's a bigger collection that may need more thinking through by the content team compared to the other collections. I'm thinking I may make it into a new issue so that we can close this one sooner.

**Comment by dorothyyeager** [comment]
Updating post-content grooming. In doing an inventory of our publications, there are some issues with the Guides, publications and manuals collection that need to be tackled first before we are ready to put some of them on the new site. 

In the meantime, will ask @patphongs and @johnnyporkchops today to create that collection, so that that part is done. Organizing that collection, uploading a few initial documents to it and redirects for the other two collections will be put into a successor issue I'll create, and then we can close this one out.
