### ISSUE TITLE
18F + FEC Pair on Cloudwatch

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1168]
New logging system Cloudwatch will be implemented. FEC will not have access yet, however, we can pair with 18F to get an early look at it.

RDS logging dependency

**Comment by PaulClark2** [comment]
- [ ] Rohan
- [ ] Jun

**Comment by patphongs** [comment]
Issue moved to [18F/openFEC #2607](https://github.com/18F/openFEC/issues/2607) via [**ZenHub**](https://www.zenhub.com/)
