### ISSUE TITLE
Training and accounts for New Relic

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1169]
Video session
Paul make list of people who need access

Completion Criteria:
- [x] Need to add relevant users to New Relic for error alerts
- [ ] Update fec-accounts repo with policies to add users to New Relic
- [ ]  Training needed for those who have New Relic access and how to find logs

**Comment by PaulClark2** [comment]
- [ ] Priya
- [ ] Rohan
- [ ] Helen
- [ ] Jun

**Comment by PaulClark2** [comment]
Training tracked in issue: https://github.com/18F/fec-transition/issues/119
