### ISSUE TITLE
Update and expand content style guide

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1174]
To ensure that content is consistent, easy to use and written in plain language across the website, we'll need to develop a style guide. 

- [x] Reflect design changes made this PI
- [x] Guidelines for proposing additions to the Guide
- [x] Design approval process for Guide
- [x] Design process for sharing the Guide as we onboard new content managers
- [x] Include guidance to different templates and modules
- [x] Detail responsibility for accuracy and timeliness of different content (ownership)

**Comment by jameshupp** [comment]
The primary issue I'm seeing with 🔒  [the draft guide as it exists so far](https://docs.google.com/document/d/1cIWTO4X9kNvjL-Lpq8A6t9NrA3ZtWvSZ5mKS1ic0-Js/) 🔒  is that it doesn't deal with specific content types or templates. It's broad, which is useful as a baseline for decisions about new things, but less helpful for managing within frameworks we've already established. The guide to reporting examples we put together, conversely, is probably _too_ specific for this. But I'm putting together a couple pieces for this based on that, slimmed down, to see how they read. If it works, we could try to expand the guide further along those lines.

**Comment by rhoughfec** [comment]
@jameshupp I completely agree. I think when we started we didn't realize how far reaching we would need it to go. Also agree that the reporting examples would be too specific for all the different content on the site.
