### ISSUE TITLE
Continue drafting candidate reporting examples

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1177]
To help users understand how to report campaign finance transactions, we need to draft the content portion of the reporting examples (language + images) that will go with the candidate section within Help for Candidates and Committees.

This is a continuation of the work started in #1170.  After we finish the initial drafts of the candidate reporting examples and have them reviewed, we will need to draft the remainder of the candidate examples that are identified in #1123.

Tasks to completion:
- [x] identify a set of examples that need to be drafted
- [x] create the images needed for each example (Jim Jones)
- [x] draft the text needed for each example ( @llienfec @rhoughfec )
- [x] RAD review
- [x] content team notification
- [x] publish examples

**Comment by llienfec** [comment]
We identified candidate reporting examples, focusing on receipts examples for this sprint.

**Comment by patphongs** [comment]
@llienfec linking to the filtering mechanisms reporting example testing ticket that was created to track the work: https://github.com/18F/fec-testing/issues/80

**Comment by llienfec** [comment]
We are currently working on getting the initial set of receipts reporting examples through RAD review before posting.

**Comment by llienfec** [comment]
We received RAD comments back on the initial set of receipts-related reporting examples.  I plan to review comments and make changes.

Work left on this ticket:
- [ ] Review text edits & make a final  (me)
- [ ] Review images for edits (me & @rhoughfec)
- [ ] Edit images (@jjones0618)
- [ ] Begin creating wagtail pages 
- [ ] Report out in content channel
- [ ] Finish creating wagtail pages

Once I coordinate with the team, I'll split this issue into sprint-sized tasks.  In the future, we will split these tickets into much smaller component parts so that the deliverables match our sprint cadence better.

**Comment by llienfec** [comment]
Entered 17 reporting examples into Wagtail.  @jjones0618 and @rhoughfec are going to help me fill in a few more images.  After that we should be ready to publish, then work on creating links to the pages.

**Comment by llienfec** [comment]
Finished the first round of reporting examples and published them.  Will be meeting with @jjones0618 and @rhoughfec to discuss next steps and open new github issues.
