### ISSUE TITLE
Identify all types of non-reporting-deadlines data that need to be included on calendar

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#118]
**[Story](https://18f.storiesonboard.com/m/fec/!card/5X1JTYVxlgg6XznT3Laojg):** So that the public can follow the commission's decision-making activity, show dates for meetings, AOs, and other activities on a calendar.

**Goal:** Identify which types of events (meetings, AOs, rulings, etc.) need to be included on the calendar and what kind of meta-data is associated with each one.

**Comment by noahmanger** [comment]
Here's my initial assessment of everything the calendar needs to include (both reporting and non-reporting type events):

## Event types

**Commission meetings**
- Administrative review hearing
- Open meeting
- Executive session

**Deadlines**
- Quarterly
- Monthly
- Pre- and post-election
- EC period begins / date range
- IE period begins / date range

**Education and outreach**
- Webinars
- Conferences
- Round tables
- State outreach workshops

**Elections**
- Special elections
- Primary elections
- General elections

**AOs and Rules**
- Draft AO comments due
- *anything else???*

**Other**
- Litigation
- FEA periods (*what are these?*)

## Event meta-data
All events have the need for this information:
- Event title
- Type and sub-type (from above)
- Start date
- Location
- Event description

Some events need:
- Start time 
- End time
- End date (in the case of a range, like electioneering communication windows)
- Relevant state (in the case of elections and election periods related to them)
- Links to other pages and supporting materials (e.g. meeting agenda page, other educational pages, webinar links, special election report notice, full reporting schedules, draft of AO)

## Feedback
@amykort anything to add or expand on? Specifically, I had a hard time finding what other "AO and Rules" type events there may be and what information they may need associated with them.

**Comment by amypike** [comment]
@noahmanger, this is excellent, you captured the activities that go on the Calendar. Anything added at this point is just fine-tuning. For your purposes, at this stage, is it necessary to have an exhaustive list of Calendar items?  If so, I suggest: 
Under "Deadlines:" 
*add 48 hour report period for contributions received by candidates period/date range
*clarify that we are talking about 24/48 hour notice periods for IE reports begins / date range
*add FEA periods/date range (Federal Election Activities (FEA) are certain activities conducted by state, district and local political party committees during a set time period before any election and is calculated based on the ballot access period under state law.)

Under "AOs and Rules:"
*add a broad category, like "Any Federal Register Notice issued by the Commission.”  That covers all rulemaking activities (notice, comment, final rules, etc) plus things like annual notices for inflationary adjustment to contribution limits, notice of coordinated party expenditure limits for elections, all of which are currently posted to the Calendar with a link to the Federal Register Notice.   I can break out all the possibilities, if that would be more helpful - let me know if you need that level of detail.

Under "Commission Meetings,"  you could add "Audit hearings" and "public forums," though those events are posted and linked in the same way as an Administrative review hearing or an Open Meeting. @amykort, can you think of anything else?

**Comment by noahmanger** [comment]
Great, thank you. I added those in an edit to the comment above.

For FEA periods, are there multiple types of them? Or just general? Like, would a user ever need to filter down?

And for the federal register notice, are these actually tied to a date? Or are they just published to the calendar because it's easy? 

Also do the rule making activity things make sense as ranges (e.g. "accepting comments on this AO for these two weeks" or whatever)?

**Comment by amypike** [comment]
There are two FEA time periods in each state (one for Type 1 FEA, the other for Type 2 FEA).  For the general election, the FEA period is the same in each state (because election day is the same everywhere); however, for primary/special/runoff, the two FEA periods are different in each state. So maybe users would need to filter?  I'm sorry, I think maybe I don't know enough about filtering.  We can Slack this, if that would help.

Federal Register notices are tied to a date.  For example, our regulations take effect 30 days after their publication in the Federal Register so knowing the date of publication is important.  You've been looking at the calendar and may know this better than I do but I *think* we list the date of publication in the FR on the Calendar, but 30 days later, we don't post something like "Hey, those regulations we mentioned?  Yeah, those take effect today" on the Calendar.  It would be nice if we could do that, too. 

Rulemaking activity things absolutely make sense as ranges!

**Comment by noahmanger** [comment]
Awesome! Thank you for explaining. This all makes a lot of sense. Here's an updated list, new items in **bold**:

## Event types

**Commission meetings**
- Administrative review hearing
- Open meeting
- Executive session
- **Audit hearings**
- **Public forums**

**Deadlines**
- Quarterly
- Monthly
- Pre- and post-election
- EC period begins / date range (general + for each state)
- **48 hour report period for contributions received by candidates period/date range**
- **24/48 hour IE reporting period begins / date range (general + for each state)**
- **Type 1 FEA date range (general + for each state)**
- **Type 2 FEA date range (general + for each state)**

**Education and outreach**
- Webinars
- Conferences
- Round tables
- State outreach workshops

**Elections**
- Special elections
- Primary elections
- General elections

**AOs and Rules**
- **Federal Register notices**
- **Regulation effectiveness dates (30 days after Register notice)**
- **Rule-making (AO and other) comment period ranges**

**Other**
- Litigation

## Event meta-data
All events have the need for this information:
- Event title
- Type and sub-type (from above)
- Start date
- Location
- Event description

Some events need:
- Start time 
- End time
- End date (in the case of a range, like electioneering communication windows)
- Relevant state (in the case of elections and election periods related to them)
- Links to other pages and supporting materials (e.g. meeting agenda page, other educational pages, webinar links, special election report notice, full reporting schedules, draft of AO)

**Comment by noahmanger** [comment]
Sorry, one more question: what are all of the options for "rule making comment ranges"? AOs? Rules? Any others? And are those always the same?

**Comment by AmyKort** [comment]
AOs, rulemakings, policy statements:  these all have comment periods that have opening dates and closing dates. So, I had imagined the date range would cover that--you can comment during these dates. Is that what you had in mind?

**Comment by noahmanger** [comment]
Excellent. Thank you.

**Comment by noahmanger** [comment]
Ok, I'd say this issue is completed. Now moving over to identifying how this is all filtered: https://github.com/18F/fec-cms/issues/125
