### ISSUE TITLE
Document S3 buckets: management, usage, etc.

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1180]
Bucket names
Environments each bucket lives in
Configurations on bucket
Bucket policies
CORs
etc.

**Comment by patphongs** [comment]
This has been completed and documentation can be found [here](https://docs.google.com/document/d/1iF_DZGe-SlDRLbJXlc89ePtLaHINX4iLgzdKcabuL-U/edit#)  🔒
