### ISSUE TITLE
Add "date originally published" to Wagtail browse/search function

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1184]
As mentioned in #1149  we are investigating ways to find articles in the updates folder, especially as many of the press releases and Record articles have similar names. While an easy fix is to add the year to the names, as we do that, the page is updated and thus the date updated field becomes less useful for identifying when an article was published (and what year it should have on it).

It would be desirable to have the ability in Wagtail to sort the pages in the updates folder by the date of their original publications (or have another way to search using this date), so we'd like to investigate adding this search function. 

<img width="960" alt="8-9-2017 1-00-41 pm" src="https://user-images.githubusercontent.com/24437369/29133906-f6d4e89c-7d02-11e7-81fa-041fa60c1587.png">

**Comment by noahmanger** [comment]
Ok, I think I have a couple options on this. First, we can customize the display title for any page in the admin area to include the original date (or any other meta data we want), like:

![image](https://user-images.githubusercontent.com/1696495/29330551-629d4560-81ae-11e7-8e66-52a8415eccf3.png)

Second, we can create custom admin panels for the different update types and set one of the columns as the original date, like:
![image](https://user-images.githubusercontent.com/1696495/29330575-7af21fd2-81ae-11e7-8d4d-65884661305b.png)

Doing so would give us an admin panel like:
![image](https://user-images.githubusercontent.com/1696495/29330590-88e59858-81ae-11e7-954b-d3196029e595.png)

I think this may actually be a better solution than the folder concept I proposed earlier.

**Comment by dorothyyeager** [comment]
I love both of these ideas. The original date will help with the duplicative titles (e.g., "July reporting reminder" articles over the years) and I'm guessing the custom admin panel will help us not do redirects since the URLs wouldn't change?

**Comment by dorothyyeager** [comment]
Follow up thought - would this work well in the "Help for Committees" folder (I'm thinking yes?) #1149

**Comment by noahmanger** [comment]
Also, I think with the custom views for each update type having a column for "date" we don't need to include the date in the title. Or would that still be useful @dorothyyeager ?

**Comment by dorothyyeager** [comment]
I think in some cases it's still useful, but that could be a case-by-case call by the person posting the page. It definitely would reduce the need to do this, which would be great.

**Comment by noahmanger** [comment]
Cool. So yeah, you could still do it by editing the page title, but it won't be default displayed.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1200
