### ISSUE TITLE
move to circle CI

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1186]
This should be done by Sept 12

**Comment by hollyallen** [comment]
FYI: This repository has been using Travis CI, however access to Travis CI is now turning off.

**Comment by ccostino** [comment]
Thanks, @hollyallen!  We've been actively working through getting this migrated over and will have it done  with our next release of this (PR #1253).

**Comment by ccostino** [comment]
We've finished getting the config setup for deployment and are all set!
