### ISSUE TITLE
Delete out of date pages in Wagtail

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1188]
Before we move the electronic filing pages out of the candidate committee section to disambiguate the links (#1149), we need to delete the following pages from the CMS, which are out-of-date.  This will keep us from accidentally updating the wrong pages.  Content managers can't delete these pages, so we may need some help from 18F partners.

### Pages to delete
These pages are housed under:  Explorer > Home > Help for Candidates and committees
- [x] Electronic filing
- [x] Filing software
- [x] Paper filing
- [x] Filing candidate reports [2]

**Comment by patphongs** [comment]
@llienfec Redirects have been created for these old pages. The delete functionality is currently broken in wagtail, I just logged a ticket for the bug. https://github.com/18F/fec-cms/issues/1189

**Comment by jenniferthibault** [comment]
Lauren and I paired and deleted those pages through my account. This tells us that there is a permissions problem (since I can delete them and she can't) but this issue's tasks are complete.
