### ISSUE TITLE
Find new home and approach for adding the yearly coordinated party expenditure limits

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1197]
Every year the FEC is responsible for calculating and publishing the annual coordinated party expenditure limits. While published in the Federal Register, the FEC has also had a web page for each year of these limits. (The 2017 page is at https://transition.fec.gov/info/charts_cpe_2017.shtml.)

We need to determine the best place to house the limits on the new fec.gov, whether that is the page that explains the laws applying to coordinated party expenditures (https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/) or a separate page that both the Record news article and the help for parties page could link to. 

We also want to consider using whether the new embedded snippet table tool (see #1193) could be useful for displaying the updated limits.

Editing to add these thoughts and completion criteria:

Finally we will need to think through how to archive past years' coordinated party expenditure limits. Right now, they can be accessed via searching old Record articles (https://www.fec.gov/updates/?update_type=fec-record&category=outreach&search=coordinated+party+expenditure+limit), but the result is not ideal. Would we want to set up a separate page for each past year, or link old transition sites that still live but aren't live links right now, or link old Record articles? Also, how far back do we need to archive this?

This issue relates to the larger issue of archiving historic information for enforcement, adademic and legal research purposes. See #1216.

Completion criteria:
- [x] Determine new home and format for displaying coordinated party expenditure limits 
- [x] If a new page is needed for 2018 as a starting point, create that page and link it off appropriate party pages.
- [x] Think through the issues of how to archive the limits of past years.

**Comment by johnnyporkchops** [comment]
I think Snippets in Wagtail could be used effectively for this. @dorothyyeager, Let me know if you want to sync on this

**Comment by dorothyyeager** [comment]
Sounds good @johnnyporkchops

**Comment by llienfec** [comment]
FYI @dorothyyeager I received questions from Audit Division about past coordinated party expenditure pages, so it looks like we may have a user case for figuring this out.  Thanks!

**Comment by dorothyyeager** [comment]
As @llienfec noted above, there is a user need for archived party coordinated expenditure limit pages (which currently are best researched by searching old Record articles). While the immediate task in this issue is to prepare the limits for 2018 and the new website, we will want to think through how to tie this into other archival needs (e.g., contribution limits)

**Comment by PaulClark2** [comment]
I have all contribution limits (1976 to 2018), https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits-candidates/, in a database table on FECP.  Let me know if we need to copy this table to our Postgres database.

**Comment by dorothyyeager** [comment]
Hi @PaulClark2 that sounds like it would be useful for this issue and @llienfec's issue at #1216 - thanks!

**Comment by dorothyyeager** [comment]
For this year (2018), we will prepare a separate page in Wagtail (housed in the H4CC Party disbursement bucket) that contains the 2018 limits. Will need to touch base with @PaulClark2 and @johnnyporkchops about the best template or page set up to use and the snippets they mention in this issue above. We will try to set up the page so that it can be used as an archive of past limits. (For now that might mean linking to transition pages with them.)

**Comment by dorothyyeager** [comment]
We've actually figured out a way to archive the limits without using snippets. We'll be ready to implement this after a little more discussion with the content team and once the Federal Register notice with the limits is posted (expected this week).

**Comment by dorothyyeager** [comment]
Since quick answers on the transition site are being phased out, we’ve identified a new home in the Help for Candidates and Committees section of the FEC website for a revised coordinated party expenditure limits page that is a child page of https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/. 

We intend to have the yearly limit information on a new page that we’re calling the “Coordinated party expenditure limits” page. That page will also serve as an archive page for limits of the past.

We ended up changing the wording slightly, as well as the organization from our current format and are running through OGC for approval. We've also asked members of the content team to review and weigh in.

We also set up a second page where we’ve moved the information about how we calculate the limits. 
The second page, “Calculating the coordinated party expenditure limits” is intended to be a static page with just the formulas so we won’t have to update it unless the law changes. The annual COLA will be on the limits page and in the annual Record article. Both pages will link to each other and to the basic H4CC pages that explain what a coordinated party expenditure is, as well as to the annual Record article (which will have the COLA).

We intend for both new pages to go live when the corresponding Federal Register notice goes live. Will leave the issue in Ready status for now until OGC or the content team returns any comments.

**Comment by dorothyyeager** [comment]
The 2018 limits will be published in the Federal Register on Monday 2/12. I've sent OGC a reminder as it's in their hands now. We hope to make these pages live on the 12th.

**Comment by AmyKort** [comment]
Can I close this ticket and make a new one to deploy these pages in Sprint 1?

**Comment by dorothyyeager** [comment]
Hi Amy - sure if that works better. We are still waiting to hear back from OGC so I guess completion criteria would be to implement any of their edits and publish the pages. I'll need to edit transition quick answer to point to the new page.

**Comment by AmyKort** [comment]
Implementation discussion at https://github.com/18F/fec-cms/issues/1749
