### ISSUE TITLE
Investigate pre-built solutions for calendaring

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#120]
**[Story](https://18f.storiesonboard.com/m/fec/!card/MMqQA-Nti_w8TDnUFKPJ-Q)**: So that the public has access to latest and most relevant dates around decision-making processes, make it easy for FEC employees to add events to the calendar.

**Goal:** We don't want to reinvent the wheel if we don't need to, so look into what pre-built calendaring tools may meet the technical needs as well as organizational needs discovered via #119 .

**Comment by noahmanger** [comment]
Might be useful to have some thoughts on this for Tuesday's calendar data meeting.

**Comment by LindsayYoung** [comment]
After the calendar meeting, it looks like we want to focus on the user-facing aspects of the tool. Josh found [Full Calendar](http://fullcalendar.io/). It looks promising to have minimal work to add the features we need. Love to hear what the team thinks.

**Comment by LindsayYoung** [comment]
Timekit sounds pretty interesting. They say if you sign up now it will be free forever, that doesn't mean they won't go out of business or something. 

http://timekit.io/features#feature-calendars
http://booking.timekit.io/
http://timekit.io/pricing

**Comment by jmcarp** [comment]
@LindsayYoung: timekit looks like a nice calendar backend, but it looks they leave the frontend up to their customers. Seems like it would be worthwhile to research them further if we decide to rebuild the calendar backend.

**Comment by jenniferthibault** [comment]
Do you all have any leads on the one you're most interested in? I can start looking at styling, but want to design within the constraints of the one you pick.

**Comment by noahmanger** [comment]
Can we close this?
