### ISSUE TITLE
[Bug] New pages in Wagtail 404 in Dev and Stage

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1203]
When creating a new page in Wagtail Dev and Stage, the page is published ok but when trying to view it live, you get a 404.

**Comment by patphongs** [comment]
Here's an example of what happens on staging when trying to click the "view live" button to see the published page on stage.

![error-view-live](https://user-images.githubusercontent.com/12799132/29592710-c58451b2-8773-11e7-8373-dc209f592b71.gif)

**Comment by johnnyporkchops** [comment]
What is the url of dev and stage please. I never used them

**Comment by johnnyporkchops** [comment]
Oh disregard last comment, I have the URS:
https://fec-stage-proxy.app.cloud.gov/admin/
https://fec-dev-proxy.app.cloud.gov/admin/
