### ISSUE TITLE
Organize and upload collection of documents for FEC publications currently on transition site, and finish redirects for other new document collections already created

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1215]
This issue picks up from #1162. It also may have a dependency on #1204.

We are creating a collection for Campaign Guides, FECFile manuals and other guides, manuals and publications. In taking inventory of what publications have, it turns out that we need to make some initial decisions about what should live on, what is already covered well in existing pages, and where things we need to add or upload should be added (and for brochures, what format - PDF or html?). After we make decisions about how to proceed with these publications in flux, then we can upload them and create any needed redirects from the classic and/or transition sites.

We also need to finish and verify the redirects for the other two collections created for forms and for Information Division Federal Register notices.

Completion criteria:
- [x] Implement and verify the redirects for the Forms and instructions, and for the Information Division FR notices.
- [x] Upload Campaign Guides and FECFile manuals
- [x] Create redirects for the Guides and manuals
- [x] Review remaining inventory of publications on transition site (in a google doc I've shared with content team) and make decisions regarding which ones will come over to new site and which ones are already there in a different format.

**Comment by dorothyyeager** [comment]
Status update - Have touched base with @johnnyporkchops regarding the first checkbox and also regarding creating the collection for the Guides, manuals and publications. Have updated a google doc with an inventory of the publications FEC content team staff need to think through adding, particularly in regard to those that are out of date or covered adequately elsewhere. This doc has been shared with the team for review and comment.

**Comment by dorothyyeager** [comment]
Update: The collection has been created. Guides have been uploaded (with the exception of the very outdated Corporate/Labor Guide). FECFile manuals will be uploaded shortly, as well as high value brochures (e.g., Contributions, Special Notices). 

Content team has reviewed the list of publications. In some cases, we are going to redirect to a Record article that updates the current publication. Other publications that are not as high value will remain in their homes on transition while their fate is decided or a Record article is written to update them. In some cases, decisions will need to be made and so we will put these lesser-value and/or outdated publications into another Github issue for another day.

**Comment by dorothyyeager** [comment]
Update: After some wrangling, we've identified a few publications listed below that do not require an update because there are more current materials in Wagtail. We have updated the transition site to link to them and put in redirect requests for these brochures:

- Advisory opinions
- Best practices for committee management
- Coordinated communications and independent expenditures (in this case, the brochure was badly outdated, so we've replaced it with links to updated and current material for candidates, parties and PACs. We will need to come up with something for Form 5 filers)
- Committee treasurers
- Delegate activity
- Embezzlement: Prevention and response
- Joint fundraising
- Local party activity
- Separate segregated funds and nonconnected PACs
- Testing the waters

Once the redirects for everything are implemented, we can close this issue. Will make a new one in the future for the publications that will require some re-imagining/rethinking for placing them into Wagtail and redirecting old pages to them.

**Comment by johnnyporkchops** [comment]
@dorothyyeagerrewrite https://transition.fec.gov/pages/brochures/ao.shtml 
is already redirected to https://www.fec.gov/data/legal/advisory-opinions/ 
but you now have it redirected to  https://www.fec.gov/legal-resources/advisory-opinions-process/ 
which I am sure is correct, but just checking that this is what yo want

**Comment by dorothyyeager** [comment]
@johnnyporkchops Yes, confirming that's what we want. That page does what the brochure used to do - describe how to ask for an AO. So we want to retire the brochure and redirect people to the page that explains the process. Thanks!

**Comment by dorothyyeager** [comment]
Just talked to @lbeaufort and saw @johnnyporkchops' post on Slack. The redirects for all of the publications addressed in this issue are now in place and working, so we have completed our work on this issue. Closing it now.
