### ISSUE TITLE
Revisit Commission Meeting Language

### ISSUE THREAD

**Issue by rhoughfec** [18F/fec-cms#1219]
Users have commented that the language on the homepage for closed commission meetings seems "way too long and jargony, especially compared to the description of public meetings." Can we slim down the language without losing the intent?

**Comment by jenniferthibault** [comment]
Hi @rhoughfec , it looks like you mean this blurb?

![screen shot 2017-08-28 at 3 04 30 pm](https://user-images.githubusercontent.com/11636908/29788913-49d63524-8c02-11e7-9a7e-9afd25317a15.png)

And when you say "users" — is this from internal users? or is there any additional context from external testing/calls with it to share?

**Comment by rhoughfec** [comment]
Yes, it's from several internal users. Sorry, meant to copy in that blurb, got ahead of myself!

**Comment by jenniferthibault** [comment]
No problem! Ok, these blurbs gets pulled from the calendar, and you can see them all here: https://www.fec.gov/calendar/?category=Executive+Sessions&category=Open+Meetings&category=Public+Hearings

So editing should be coordinated through the process data is entered there — cc @fechoosier

**Comment by rhoughfec** [comment]
@AmyKort I think we can close this. We can clean up language as needed while we work on the other calendar issues. Thanks!
