### ISSUE TITLE
Merge openFEC-web-app into fec-cms

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#1223]
Merge openFEC-web-app into fec-cms as a new app, and make sure all dependencies for openFEC-web-app are covered.

- [x] New `data` app on fec-cms
- [x] New `legal` app on fec-cms
- [x] Make sure changes since August 14 (when webapp+cms repo was started) have been updated as well
- [x] Migrate `fec-style` into static assets
- [x] Update front-end build process
- [x] Move and verify Python and JS tests
- [x] Feedback tool for Github issues (making sure it's processing within the CMS now, not the web app form)
- [ ] Double check config vars, bound services are correct
- [ ] Cloud.gov app deploy set
- [x] Set extra front end minification build step for deployment
- [ ] .gitignore/.cfignore setup

**Comment by patphongs** [comment]
Linking this issue to make sure this proxy PR gets deployed with the release of the merged web-app and cms. https://github.com/18F/fec-proxy/pull/60
