### ISSUE TITLE
Create new page for non-FEC election information

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1233]
In #1155 it was decided that the new home for the general non-FEC election information would take the shape of a separate page that would be part of the larger citizens section we are creating ( #1182 ). The purpose of this issue is to create the page.

Completion criteria
- [x] complete design components
- [x] Using the inventory created for #1155, create the new page (making sure to have the most updated information for the other agencies)
- [x] Incorporate it into the overall citizens section

**Comment by AmyKort** [comment]
Our first iteration of this work is implemented with https://github.com/18F/fec-cms/issues/1237 We'll make a new issue to address "how to research data" pages and to continue to refine and improve navigation.
