### ISSUE TITLE
Implement changes to Introduction to campaign finance and elections panel on homepage

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1237]
- [x] ⭐️ **Needed to complete issue grooming:** Copy review and edits (cc @jameshupp @dorothyyeager @gsmaragdis ) ⭐️ 

___
History and discussion in https://github.com/18F/fec-cms/issues/1182
___
### Designs

![screen shot 2017-09-06 at 5 37 16 pm](https://user-images.githubusercontent.com/11636908/30135715-01bf5e30-932a-11e7-9a2b-fd0e1804e1fe.png)

____

### Notes:

**Links:**
 - Start learning: https://fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
 - Compare candidates: (anchor link needed on data landing page, see checkbox 1 below) https://www.fec.gov/data/#compare-candidates-in-an-election (or a smarter URL, but you get the idea of the anchor)
- 2017–2018 contribution limits: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits-candidates/ 

**Images**
📁 [Getting-started-images.zip](https://github.com/18F/fec-cms/files/1282774/Getting-started-images.zip)
These images will get us started, and I can make tweaks later if needed. The FEC owns the first image, the second is a photo from the [US Navy](https://www.flickr.com/photos/56594044@N06/8053995099/) that we can use because it's govt works, and the third is one I made quickly to keep things moving with images we have rights for.
I wasn't sure what's best to name them

**Steps to completion**
- [ ]  Create anchor links to the sections of the [data landing page](https://www.fec.gov/data/) so that we can link to it from the middle tile's button (this seems useful to the future as well)
- [ ]  Rename images to something that makes sense
- [ ]  Rebuild `Introduction to campaign finance` home page section (this may need more grooming and fleshing out from @xtine's help )

⚠️ **Dependencies for release**
- [x] The page [Understanding ways to support federal candidates](https://fec-prod-proxy.app.cloud.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/) need to be published without a password

**Comment by dorothyyeager** [comment]
One more thought/issue to cross-reference - some of the brochures linked on that Understanding Ways page are undergoing revision or discussions about retirement. See https://github.com/18F/fec-cms/issues/1215 and discussion in google document (linked in Slack content channel).

**Comment by jenniferthibault** [comment]
In design pairing today we reviewed the copy and made some tweaks to make the structure of each more consistent. Here's what we landed on for v1 under each image:

__

**Find out how individuals can support federal candidates**
Including making contributions, volunteering, internet activities and filing complaints
 [Start learning] >
__

**Explore financial data for current and past elections and the candidates in those races**
[Compare candidates] >
__

**Learn about how much contributors can give to different types of committees**
[Get the contribution limits] >

**Comment by dorothyyeager** [comment]
Sounds good. I will go into the supporting candidates section we are linking to and update any needed links (mentioned above in my last comment) since we closed out #1215  and some of those links may need modification.

**Comment by patphongs** [comment]
Implementation of this within https://github.com/18F/fec-cms/pull/1290 is complete. Closing this ticket as design for this will also be reviewed within that PR.

**Comment by jenniferthibault** [comment]
@patphongs to keep the work visible (and to keep the pressure on for reviewing PRs) our practice has been to keep an issue open, labeled as "Done" until the PR with the changes in it is reviewed and merged. Going to reopen this issue to keep with that practice

**Comment by AmyKort** [comment]
Where are we on this issue?

**Comment by patphongs** [comment]
@AmyKort That will be in my court to review the PRs that John has submitted, which includes this new design for the homepage. I will be doing that this sprint (4.3) and hopefully we can get them merged in.

**Comment by AmyKort** [comment]
Thanks!

**Comment by jenniferthibault** [comment]
Released on 11/21
