### ISSUE TITLE
Redirects for classic.fec.gov and ftp.fec.gov

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1244]
We need to work with networking to add classic.fec.gov and ftp.fec.gov redirect rules. These redirect rules should be set on the same web server as the fec.gov redirects. 

Completion Criteria:
- [ ] ftp.fec.gov should redirect to https://www.fec.gov/files/bulk-downloads/index.html
- [ ] classic.fec.gov should redirect to https://www.fec.gov

**Comment by PaulClark2** [comment]
closed in favor of https://github.com/18F/openFEC-web-app/issues/2325
