### ISSUE TITLE
Plan for retirement of new site orientation

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1251]
@AmyKort commented on [Thu Sep 14 2017](https://github.com/18F/openFEC-web-app/issues/2310)

When we launched the site orientation for the new website, we set a 90 day post-transition window for re-evaluating our communications strategy, including the site orientation. With 90 days behind us, it's time to take down the site orientation and prominent link to classic.

**Comment by xtine** [comment]
Site orientation is now removed from the dev and will make it into the next release.
