### ISSUE TITLE
Add MS-H "Disavowal Notices" to RFAI search

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1252]
- [ ] Add Disavowal notices to RFAI search https://www.fec.gov/data/filings/?data_type=processed&candidate_id=H2MD06054&form_type=RFAI 

form_type: "F99"
document_type_full: "Disavowal Notice"

User contacted me looking for a letter the FEC sent regarding a Form 2 and could not find it on the candidate page with the rest of the candidate's information.  It appears that the candidate data pages may be missing a type of letter that gets sent to committees regarding their Statement of Candidacy.  These letters were included in the Candidate/Committee Viewer on the classic site and do appear with the committee's filings in the All Filings filter page.

In researching this, I found two potential points of confusion:
1. Candidate page "About" sections show Form 2s filed by the committee, as well as disavowal notices that are sent to the committee.  Another type of letter that the committees receive - RQ-5s labeled "RFAI: Document [year]" are not showing up in the "Other documents filed" section of the candidate page.  I looked at the filings portion of the committee pages just in case, and the "RFAI: Document [year]" is not there either.  (See Morago, Walters, and Baake examples below.)

1. On the All Filings filter page, the document type filter did not work as the user expected.  When they put in the candidate's ID number and filtered for RFAIs, the "RFAI: Document [year]" did show up.  However, the committee's disavowal notice (another type of RQ-5 sent by the FEC) did not show up.  The user expected to be able to select "Disavowal letter" as a document type or have it show up when "RFAI" was selected.  (See Bartlett example below).

For more info, here are some committees that demonstrate the incomplete candidate page and the RFAI filter issues:

Candidate | ID | Type of RQ-5 | On candidate page? | In All Filings RFAI filter? | On classic.fec?
------------  | ------------- | ------------- | ------------- | ------------- | -------------
Bartlett | H2MD06054 | Disavowal | [Yes ](https://www.fec.gov/data/candidate/H2MD06054/?cycle=2008&tab=about-candidate)| [No ](https://www.fec.gov/data/filings/?data_type=processed&candidate_id=H2MD06054&form_type=RFAI)| Yes
Morago | P00004879| Form 2 needs more info | [No ](https://www.fec.gov/data/candidate/P00004879/?cycle=2020&election_full=True&tab=about-candidate)| [Yes ](https://www.fec.gov/data/filings/?data_type=processed&candidate_id=P00004879)| Yes
Walters | S8WI00208 | Form 2 needs more info | [No ](https://www.fec.gov/data/candidate/S8WI00208/?tab=about-candidate)| [Yes ](https://www.fec.gov/data/filings/?data_type=processed&candidate_id=S8WI00208&office=P&office=S&office=H)| Yes
Baake | H8NM02131 | Form 2 needs more info | [No ](https://www.fec.gov/data/candidate/H8NM02131/?cycle=2018&election_full=False&tab=about-candidate)| [Yes ](https://www.fec.gov/data/filings/?data_type=processed&candidate_id=H8NM02131&office=P&office=S&office=H)| Yes

*Please note that we figured out how to get to both of these document types.  So while this should probably be addressed, it's not an immediate need since we have a work-around.*

A big thanks goes out to @rhoughfec for helping me think through testing this and to @lbeaufort in advance for wading through all of this info!

**Comment by lbeaufort** [comment]
Note: Adding form_type: "F99" and document_type: "H" just shows disavowals because FRQ document_type is null. We don't want to add all F99's, either.
https://github.com/18F/openFEC/blob/develop/webservices/resources/filings.py#L65

Can we filter out just MS- type filings associated with a candidate and not a committee? Is it just MS-H's? What about MS-I (Disavowal responses?)
