### ISSUE TITLE
Commissioner edit to RAD Form page

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1259]
@johnnyporkchops I need your help making the following edits to the RAD Form page that came from Commissioner Goodman's office: 
https://www.fec.gov/help-candidates-and-committees/question-rad/

Submit this form and your committee's RAD analyst will email you, usually within 3 business days. Or, for immediate assistance, use `your designated analyst's` provided contact information to call `the analyst` by phone during business hours.

**Comment by johnnyporkchops** [comment]
@llien,  We are in the middle of a migration right now , merging the WebApp with CMS, so we need to temporarily refrain from hotfixes.  We can do this in a few days, once we deploy the merge.

**Comment by PaulClark2** [comment]
Can we close this?

**Comment by jenniferthibault** [comment]
Yup, looks like this was resolved and merged via https://github.com/18F/fec-cms/pull/1325. Now live on production.
