### ISSUE TITLE
Home page banner not going live or expiring at the times it's set to do so

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1261]
The new home page banner is working, but it is not turning on at the times or days it was set to be active, and it's not turning off at the time it is set to expire. @patphongs reports that the same thing is happening on staging when tested. We are instead manually publishing and unpublishing the banner.

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/fec-cms/issues/1267
