### ISSUE TITLE
Home page banner - Need to standardize language used

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1262]
The content team needs to settle upon the language to be used for the home page banners on open meeting days (next one is October 26) and on days reports are due (the next one is October 15; banner will be needed on October 13 since FEC will have late hours then). We also need to decide when banners come down for these occasions.

On meeting days, the language we'd originally agreed upon works, but is confusing if the banner is left up after the meeting ends, as the livestream is only live during the meeting and not available the rest of the day. However, the public may need access to meeting documents and may wish to have easy access that day to the meeting page (which the banner links).

On due date/extra hours days, often these occur on Friday when a due date is on the weekend. At what point should they come down? Also, the wording for these needs to be hammered out for the new format.

Completion criteria:
- [x] Decide upon wording for meeting days
- [x] Decide upon wording for due date/extra hours announcements
- [ ] Determine when banners in each case should come down.

**Comment by dorothyyeager** [comment]
Just wanted to note this pull request because it helps us resolve when banners announcing meetings should come down. 

https://github.com/18F/fec-cms/pull/1323

**Comment by dorothyyeager** [comment]
Now that we know when meeting streams will be pulled, we can go ahead and plan to close the banners at the end of the day that pertains to them.

**Comment by llienfec** [comment]
Today, content team discussed several options regarding what language to use in the homepage banner for when the Commission offers extended hours around filing deadlines and reached consensus.

### Finalized banner language:

**Title:** Need help filing the > report?  
**Description:** Call 800-424-9530.  
**Link 1:** RAD (option 5) and E-Filing (option 4) are available today until 8 pm (ET).  
**URL 1:** link to Tip for Treasurers covering that report

![image](https://user-images.githubusercontent.com/22914750/35352167-15b63954-0111-11e8-9050-a6101911b672.png)

Updated shared doc with the consensus banner language for extended hours as well as with approved rulemaking comment period language from October 2017.
