### ISSUE TITLE
Engineering transition items to discuss

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1268]
During the transition, there will be many engineering items to discuss from front-end to back-end to database. Going to set up a meeting every Wednesday to make sure we have time to discuss all of these things. 

* Feel free to tack on to discussion items for our Wednesday engineering meetings

**Possible agenda items:**

- [ ] - Analyze performance of js - Noah left a plugin
- [ ] - moment.js - make dates easier to work in javascript. File is huge because it includes all languages. 
- [ ] - Front end performance tuning
- [ ] - Tweaking on JS and CSS to see if we are using all of our classes efficiently
- [ ] - Look at mark-up for maintenance (nested code)
- [ ] - Look at all of our assets (images, icon scripts)
- [ ] - Loading of styles into pattern library (after post merge)
- [ ] - Eregs depends on fec-style, think about how to maintain the styles for this
- [ ] - How to load new eRegs 
- [ ] - discuss api_caller.py and views.py

**Comment by johnnyporkchops** [comment]
There are some items here I have been wanting to discuss, but not sure which meeting, so this is a good idea!

John

________________________________

**Comment by AmyKort** [comment]
Is this issue still relevant?

**Comment by patphongs** [comment]
These items have been discussed to some degree during pairings and trainings so I think we can close this.
