### ISSUE TITLE
Calendar Details Pop-up

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1271]
Regardless of the event, the calendar details pop-up that appears when you click on an event (in calendar view), the pop-up appears cut-off on the left-hand side. 

![calendardetailspop-up](https://user-images.githubusercontent.com/31663028/30826545-fb113696-a204-11e7-96cc-3d13009aa370.jpg)

**Comment by JonellaCulmer** [comment]
This issue was also logged yesterday in FEC repo #4557

**Comment by jenniferthibault** [comment]
Thanks for filing this @JonellaCulmer — since you moved the issue filed by Jim Jones over into this repo in https://github.com/18F/fec-cms/issues/1274 , we can also close this so that there's only one issue to track the bug.
