### ISSUE TITLE
Better understand capabilities of data analytic tools

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1278]
We want to improve and refine the information we get from our site analytics, so that we have the information to make really good decisions. A first (and really important) step is to develop an overview of the tools we have and what they can do, including:

API analytics
DAP analytics
Digital gov search analytics
Google analytics
Goolge webmaster tools

Complete when content team has training or a briefing on each of these tools.
@Cptechiegal

**Comment by patphongs** [comment]
1) 18F/FEC google analytics UA-48605964-22 (ask @jenniferthibault to contact 18F for access)

2) Digital analytics program (DAP). You can compare analytics government-wide. (need to sign-up to get access to the program for new users, sign up here: https://docs.google.com/forms/d/e/1FAIpQLSc002Xp2hMjH0KxzilzfKG-ei8TzHLK-uady-qQbbAZms7jNQ/viewform)

3) Still need to add the new site to google webmaster tools. It was only on beta which no longer exists.

4) https://analytics.usa.gov/ shows users that are currently on government websites

5) Digitalgov analytics (can see what users are searching for from our website’s global search tool) Ping me for access

**Comment by jenniferthibault** [comment]
Here's some quick backgroud on the 18F analytics view vs the DAP view, excerpted from https://github.com/18F/analytics-standards/blob/master/faq.md:

> ### What is the difference between 18F Google Analytics and the Digital Analytics Program (DAP)?
>
> The [Digital Analytics Program](http://www.digitalgov.gov/services/dap/) and 18F Google Analytics are different services with two distinct code snippets. 18F projects should participate in both services.
>
> ##### Digital Analytics Program
> The [Digital Analytics Program](http://www.digitalgov.gov/services/dap/) is a shared service available to all federal agencies to provides website analytics. DAP both offers a fully functional analytics service to agencies but also integrates with a cross-government combined analytics dashboard.  Staff at participating agencies are able to access the full, government-wide data.
>
> Furthermore, the Digital Analytics Program offers government agencies services such as guidance, training, and web analytics tools.  Government sites including 18F sites can be added to the DAP Google Analytics account via a code snippet.
>
> ##### 18F Google Analytics
> 18F Google Analytics is an account only for 18F websites. Since 18F is the owner of the account it allows us to make special modifications not avaiable through the DAP. To add a new 18F site to our Google Anaytics account follow the [18F Snippet Standards for Website Analytics directions](https://github.com/18F/analytics-standards#18f-snippet-standards-for-website-analytics).

**Comment by AmyKort** [comment]
Thanks, @jenniferthibault ! This is great!

**Comment by llienfec** [comment]
Here's the DigitalGov University [YouTube training series on DAP](https://www.youtube.com/playlist?list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P) that @LindsayYoung mentioned in PI planning, and a few of the courses:

- [DAP 101](https://www.youtube.com/watch?v=YxNQNL8-kLo&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P&index=3)
- [Visualizing analytics data](https://www.youtube.com/watch?v=HSJq7OTaF0Q&index=2&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P)  (Part 2 is live on Oct 12 from 2-3.  [Register here](https://www.digitalgov.gov/event/online-dap-learning-series-visualizing-analytics-data-part-2/).)
- [Using data for action](https://www.youtube.com/watch?v=run6cI_A2P4&index=4&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P)
- [Knowing your reporting pitfalls](https://www.youtube.com/watch?v=uud16gaZDT4&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P&index=1)

**Comment by dorothyyeager** [comment]
Part 2 of the Visualizing data training mentioned above is now posted at https://www.youtube.com/watch?v=TQ2CXlEY3qw.

**Comment by AmyKort** [comment]
This is great, but it's a lot. 

The main purpose of this issue is to help content team members better understand the analytic side of our work so that we can better explain this information to stakeholders and can incorporate this great information into our decision making in a more useful way.

Since @dorothyyeager and @llienfec  seem to be the content team folks taking the deepest dive on this one (thank you!), do you think the two of you could put together an informal cheat sheet for the rest of the team that will either explain the story that each tool can tell us or just point us laggards toward a good training on the tool?

**Comment by llienfec** [comment]
Yep! @dorothyyeager and I can definitely do that.

**Comment by dorothyyeager** [comment]
Sure, I'm happy to work on that. I found the two-hour video (DAP 101) the most helpful of the things and can try to grab the notes that went with it and pull out the most helpful tidbits.

**Comment by JonellaCulmer** [comment]
@llienfec @dorothyyeager A helpful starting point for that could be in the synthesis document on page 2. 
https://docs.google.com/document/d/1B0Er_qZ4o6fQzQiI51u8p5XRN9M4uQLVt4pJdw-Bi2w/edit#heading=h.5i25ceobg1ad

**Comment by patphongs** [comment]
Content team will be meeting to train others on the analytic tool capabilities this week. Since a meeting still has to take place, moving this to 4.2

**Comment by dorothyyeager** [comment]
My cliff's notes on the 2 1/2 hour long but very worthwhile DAP video 101 are here: https://docs.google.com/document/d/1WmAaWtr7R08vDimeq58RVtk5lFy7tM1UUdO6d59KMNg/edit?usp=sharing

**Comment by AmyKort** [comment]
Looks great! Thanks!
