### ISSUE TITLE
Prep for value proposition excercise

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1279]
We'll be holding exercises to develop a value proposition for the site and gain consensus on our statement. We need to plan how we're going to do that.

**Comment by llienfec** [comment]
Initial planning - talked to our wonderful design team for ideas about facilitating this type of meeting.  @jenniferthibault had some great ideas for us:

- [ ] Look at 18F research methods cards, esp. the KJ method
- [ ] Headline writing exercise
- [ ] Split session into two - one that is idea-generative and one that reduces/distills them

**Comment by AmyKort** [comment]
Sounds great! for next steps, let's set an agenda for the content teal to get together and draft a few value proposition statements. To do this, we'll need to:
- [ ] 	Figure out what goal of meetings are: get a few (4?) value proposition drafts
- [ ] 	Figure out who needs to be there; schedule the meeting
- [ ] 	Figure out how it will run: Right now, looks like 2 meetings – one meeting to generate ideas, and another to narrow them down and draft a few different propositions
- [ ] 	Figure out what good value propositions sound like 
- [ ] 	Make sure that the participants have the information regarding “who are we trying to serve?” so they can make informed decisions.
- [ ] 	Schedule internal stakeholder meetings to allow us to workshop our drafts

**Comment by AmyKort** [comment]
Coming out of Thursday's prep meeting, the only outstanding work is to schedule the internal stakeholder meetings. I'm going to open a separate ticket for that, since we're not looking to have those meetings this week or next, and close this issue.
