### ISSUE TITLE
Redirects for classic site and FTP

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1305]
Redirects for
- [ ] classic site
- [ ] FTP

@Gmengistu

Original web-app issue: https://github.com/18F/openFEC-web-app/issues/2325

**Comment by dorothyyeager** [comment]
Was looking at this issue (https://github.com/18F/fec-cms/issues/1310#issuecomment-334276597) and there's a few classic pages in the press section in the comment I'm linking that will need some sort of redirect (but there's not really a great page to redirect to so the pages might need to be moved into transition) - just wanted to note it here and then maybe we can close #1310 .

**Comment by dorothyyeager** [comment]
While I'm at it, two more classic links in a different issue: https://github.com/18F/FEC/issues/4538 - Again, two older documents that will need to be moved into transition and have a redirect applied.

**Comment by AmyKort** [comment]
Closing in favor of https://github.com/18F/fec-cms/issues/1472
