### ISSUE TITLE
Ensure links to classic.fec.gov searches are updated to the new place to search 

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1310]
In some parts of the new fec.gov, the pages contain links to the old AO search or the old MUR search. Sometimes the pages point to the classic site. These pages need to be updated to link to the new search pages. 

Some examples:
This page for journalists links https://www.fec.gov/press/resources-journalists/fecs-response-possible-violations/ contains a link to an admin fine case search on classic (http://classic.fec.gov/data/AdminFine.do?format=html) (The more recent targeted admin fine search is linked on https://www.fec.gov/legal-resources/enforcement/administrative-fines/).

This page for journalists lists the legacy enforcement query search but not the updated MUR search under "related topics": https://www.fec.gov/press/resources-journalists/fec-enforcement-programs/

It is possible that older Record articles, weekly digests and press releases also contain links to outdated search pages, so those should be updated as well (perhaps through redirects).

**Comment by AmyKort** [comment]
Thanks @dorothyyeager . This is a really important find. As a quick fix on this page https://www.fec.gov/press/resources-journalists/fecs-response-possible-violations/ maybe we can change the link for closed Admin fines cases to http://eqs.fec.gov/eqs/searcheqs , as Dorothy suggests. 

Let's change the EQS related topics link at https://www.fec.gov/press/resources-journalists/fec-enforcement-programs/ to "Enforcing federal campaign finance law" and link it to https://www.fec.gov/legal-resources/enforcement/

I don't know what to do with the Record articles, etc. Thoughts?

I noticed that inside the press pages if you hover over the link it gives you a "beta" address. Is this something we should address?

Also, @patphongs . Can look through the site again for classic links? I keep thinking we've caught them all.

**Comment by dorothyyeager** [comment]
I can take care of the two minor link changes. The beta thing seems like something to change (especially if it's an internal link). 

I've been regularly going through Record articles for style updates, updating from PDF to html, etc., so I can add this to things I go through on them. I'm also thinking I can easily search out articles that would have these links. (If you want to assign this to me in part, go for it.)

**Comment by AmyKort** [comment]
Thanks, Dorothy. If you have time to take on some record articles too, that's great. From a priorities standpoint, I think we can live with broken links in older articles and releases if we need to focus on other things. But if there are quick wins you have in mind, that would be awesome!

**Comment by dorothyyeager** [comment]
Have updated the two Press Office pages to update the links mentioned above, as well as add a search description, correct a page reference in the text on one, and correct some other erroneous links/update beta links on those two pages.

Went through the other "for journalists" child pages and found a lot that needed updating. I updated outdated or external-should be-internal links where I could. Links to the brochures that the Information Division has recently retired were removed and replaced with more current link where we have them. 

I found these classic pages linked on those pages and left the links as they are now (the pages may need to be moved to the transition site):

http://classic.fec.gov/press/bkgnd/AllPublicFunds.xls

http://classic.fec.gov/press/press2011/ieoc_alpha.shtml

http://classic.fec.gov/press/press2011/2012PoliticalCommitteeswithNonContributionAccounts.shtml

**Comment by dorothyyeager** [comment]
Just adding completion criteria for me and @patphongs :
- [ ] Remove classic links from journalist pages and Record articles
- [ ] Move the pages noted above to transition site and create redirect 
- [ ] Doublecheck site for other classic site links and correct as needed.

**Comment by AmyKort** [comment]
Thanks @dorothyyeager  for flagging outstanding issues in https://github.com/18F/fec-cms/issues/1305#issuecomment-337241245
