### ISSUE TITLE
Upgrade Prod CMS PostgreSQL service 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1318]
Upgrade production to `medium-psql` https://cloud.gov/docs/services/relational-database/

This shouldn't be too bad we would just want to make sure no one is using the cms while we do the switch.

**Comment by jwchumley** [comment]
Pair with Rohan and/or Jean

**Comment by ccostino** [comment]
This would be a good activity to do on Monday when we're in the office @LindsayYoung, but I'm not going to be in on 10/30.  Maybe shift this back a week (and therefore next sprint) unless you're able to tackle it with @rjayasekera and/or @fecjjeng?

**Comment by ccostino** [comment]
Also want to flag that we should probably take one more backup right before doing this, too. :-)

**Comment by fecjjeng** [comment]
The Monday after next week (11/6) sounds good to me.  Please include me in.  Thanks.

**Comment by ccostino** [comment]
👍 shifting this to 4.3!

**Comment by ccostino** [comment]
We completed this work today!
