### ISSUE TITLE
Create homepage information section for public comment

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1321]
Chairman requested a place on the homepage where users can to get all of the information that they need for reading about/commenting on internet communication disclaimers.

We have two ways to highlight special events on the homepage: a banner or a "pinned" event/article. After talking with @PaulClark2 @rhoughfec and @wluoFEC, the banner seemed most appropriate for the Chairman's request due to time sensitvity.

We created a draft of the banner in the FEC staging environment to get a screenshot of what the banner would look like.  This was sent to Policy and will be decided on by Commission.

## Work still outstanding
- [x] Approval by Commission (blocker for the rest of the steps)
- [x] Create banner in Wagtail production environment
- [x] Make sure comment link goes to correct place when comments are live
- [x] Change 2016 FR link to the link that is published on Tues, 10/10
- [x] Post banner

**Comment by PaulClark2** [comment]
I spoke with Policy. We will want to link to the FR that will be published Tuesday (10/10), not the 2016 FR notice.

**Comment by llienfec** [comment]
Thanks, Paul, I'm updating that task line to remind us to change it.

**Comment by dorothyyeager** [comment]
If we want to link to all the documents, the forthcoming Record article that OGC has reviewed can be used for a gateway link since it will link to all of them. One note - we can't pin Record articles anymore (or tips), so banner is the way to go.

**Comment by llienfec** [comment]
Entered the banner in production. Updated the links this morning to include the live comment page and the new Federal Register page (Policy wanted direct link instead of Record link).  Got go-ahead from policy and approval to publish.  Published this morning.
