### ISSUE TITLE
Candidate pages are not loading datatables

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#1329]
There is a JS bug which prevents loading of datatables on candidate pages. Looks to be possibly a Webpack error, but more investigation is needed to figure out the actual source of the problem. This is a bug produced after webapp+cms merge.

For reference, datatables on similarly styled pages like /data/elections/* to not seem be affected by this so it might be helpful to compare any differences in implementation and compilation of JS.

Might be helpful to look at: `https://github.com/webpack/webpack/issues/959`

<img width="1392" alt="screen shot 2017-10-11 at 9 19 50 am" src="https://user-images.githubusercontent.com/24054/31453071-9fb99532-ae65-11e7-973a-9107d50577a3.png">

**Comment by patphongs** [comment]
This might be a clue. The code is breaking at line 54. When adding a breakpoint there, I stepped through all the modules that are loaded. One particular `moduleId: 111` is undefined. How can we traceback what module is being called here?
 
<img width="1090" alt="screen shot 2017-10-12 at 11 51 42 pm" src="https://user-images.githubusercontent.com/12799132/31529632-64c50abc-afa8-11e7-8e02-78c1a151897a.png">

**Comment by johnnyporkchops** [comment]
Does this mean anything: Line 11 of /static/js/candidate-single-46ba4a7c0619f64dc25e.js
![oct-15-2017 23-54-41](https://user-images.githubusercontent.com/5572856/31594671-6c873b2c-b204-11e7-9e48-b84d8f03e7bf.gif)

**Comment by patphongs** [comment]
@johnnyporkchops Looks like there is a problem finding that particular module `var maps = require('../modules/maps');`. The pages in which this module is required is on the /fec/fec/static/js/pages/candidate-single.js, /fec/fec/static/js/pages/committee-single.js, and /fec/fec/static/js/pages/elections.js

**Comment by johnnyporkchops** [comment]
Do you think it is a path variable issue somewhere?

**Comment by patphongs** [comment]
This should be resolved in the most recent PR here https://github.com/18F/fec-cms/pull/1351

**Comment by patphongs** [comment]
resolved in https://github.com/18F/fec-cms/pull/1351
