### ISSUE TITLE
Check broken links from dev proxy after merge

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1336]
Here's the [spreadsheet](https://docs.google.com/spreadsheets/d/1BIoaZsi0NQGDUm7PsJXGupRsGhTiD6jOA68IC7L4Tmo/edit#gid=15140960) :lock: for broken links from crawl of fec-dev-proxy post merge of webapp and cms.

**Comment by AmyKort** [comment]
Great! What is our next step with this? Is this issue resolved, with next steps in a new ticket?
