### ISSUE TITLE
Contributions appear to be missing from Individual Search

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1339]
User contacted and let us know that receipts filed on the M9 report (8/1/17 - 8/31/17) do not appear in the receipt filters for the RNC (C00003418).  The M9 appears to be Pass 3 coded and disbursements for that report are showing up.

Interestingly, the "raising" section states that total receipts goes through 8/31, and the filter for individual contributions also goes through 8/31, but when you click on the filters, receipts for August don't show up.

![image](https://user-images.githubusercontent.com/22914750/31468762-3034b7f8-aead-11e7-8cba-211f49134e31.png)

**Comment by llienfec** [comment]
This issue may be related to #1329.

**Comment by AmyKort** [comment]
@patphongs  Does this seem like an issue that will be resolved with https://github.com/18F/fec-cms/pull/1351 ? Or a separate issue?

**Comment by patphongs** [comment]
@AmyKort @llienfec Unfortunately that PR does not resolve this. I see 2 bugs here:

1) 2016 data should not be showing up on the RNC profile page when the 2017-2018 cycle is selected (https://www.fec.gov/data/committee/C00003418/?tab=raising). Might be a bug in the front-end code for when we call that endpoint.

2) August data is missing from the IC reports (need to investigate the database to see if these reports have been loaded)

**Comment by llienfec** [comment]
Researched 5 additional PAC and Party committees to see if they were affected.  Each of the 5 committees displayed results as we'd expect - 4 committees showed contributions during the M9 timeframe (8/1-8/31).  1 committee files semi-annually and will not show these contributions until the Year-End reporting is filed on 1/31/18.

Quick note:  For the original committee - RNC (C00003418) - Disbursements for the M9 **are** showing up on the committee "spending" page.  Contributions **are not** showing up on the "raising" page.

**Comment by PaulClark2** [comment]
This seems to be resolved. 

https://www.fec.gov/data/receipts/?two_year_transaction_period=2018&data_type=processed&committee_id=C00003418&min_date=08%2F01%2F2017&max_date=08%2F31%2F2017

https://www.fec.gov/data/individual-contributions/?+two_year_transaction_period=2018&two_year_transaction_period=2018&committee_id=C00003418&min_date=08%2F01%2F2017&max_date=08%2F31%2F2017
