### ISSUE TITLE
Fix "Draft minutes" link on open meeting page

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#1342]
Draft minutes links are broken: 
<img width="409" alt="screen shot 2017-10-12 at 10 41 25 am" src="https://user-images.githubusercontent.com/24054/31510648-f2fd02ea-af39-11e7-92b0-7bab24037f12.png">

Link needs to be updated on `meeting_page.html`: `<a class="pdf-link" href="self.draft_minutes_links">Draft minutes</a>`

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
yes this was resolved in the latest release in this PR https://github.com/18F/fec-cms/pull/1343. Closing now.
