### ISSUE TITLE
Test staging site before release

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#1345]
This is a general issue to collect any feedback about any broken links or features not working on staging, as it will be the first general release of the merged webapp+cms code.

**Comment by dorothyyeager** [comment]
Home page banner scheduled to go live at 7 AM this morning was not live and had to be manually published. (https://fec-prod-proxy.app.cloud.gov/campaigns-can-call-800-424-9530-tonight-help-their-q3-report-due-1015/ - link will stay up until I take it down tonight). Next one to be scheduled is scheduled for 10/26 for a Commission meeting. I

**Comment by JonellaCulmer** [comment]
Campaign Guide images are missing from H4CC landing page.

**Comment by dorothyyeager** [comment]
The links to many of the forms linked on https://fec-stage-proxy.app.cloud.gov/help-candidates-and-committees/forms/ are not working:
Specifically, seems to be the links to forms with /cms-content/documents/ (unfortunately, that's all the paper forms, so pretty much every form but the web forms).

**Comment by dorothyyeager** [comment]
Commissioner headshots are missing. https://fec-stage-proxy.app.cloud.gov/about/leadership-and-structure/

**Comment by dorothyyeager** [comment]
Images that go with videos, brochures etc in the continue learning section of the campaign guidance/help pages are not working. For an example, see https://fec-stage-proxy.app.cloud.gov/help-candidates-and-committees/candidate-taking-receipts/travel/ (screenshot from this page below):
<img width="753" alt="continue learning" src="https://user-images.githubusercontent.com/24437369/31546348-e8a59bec-aff0-11e7-9fb4-ca072170512b.PNG">

**Comment by amypike** [comment]
I'm getting a 404 error when I click on the FEC Directives.  https://fec-stage-proxy.app.cloud.gov/cms-content/documents/directive_32.pdf   

![image](https://user-images.githubusercontent.com/13456282/31547024-c2f57bbc-aff3-11e7-9207-e4075caff0fa.png)

**Comment by dorothyyeager** [comment]
Images in the updates files (mostly used in Record news articles) are not working. Like the other images not showing, these all have addresses with cms-content/images/ in the URL.

Here's a screenshot from one article but it seems to be all images affected.

<img width="763" alt="images-updates" src="https://user-images.githubusercontent.com/24437369/31547341-f379b68a-aff4-11e7-9964-533b286c493b.PNG">

**Comment by patphongs** [comment]
@dorothyyeager Re: homepage banner, John will be testing this in staging. In production the fix that John put in to fix the homepage banners won't be live until after the release.

**Comment by patphongs** [comment]
@JonellaCulmer @dorothyyeager The images and document related bugs are here because the static assets (images and documents) have not been uploaded to staging like we do in production. They should be fine in production after the release since all the static assets are there in production.

**Comment by dorothyyeager** [comment]
Sorry about the home page banner mention; posted that before I saw his response in Slack about the release. Glad to know we're resolving it with the release!  (And yay, glad to know the images/documents/forms will be live!) As always, thanks!

**Comment by JonellaCulmer** [comment]
Great! Thanks, Pat.

**Comment by johnnyporkchops** [comment]
@dorothyyeager  @patphongs **Homepage banner announcement:** This did not make it into the release branch because Christine requested I merge migrations, which I did and now it is ready to merge if it is something we really want to make in the release.

**Comment by dorothyyeager** [comment]
Thanks @johnnyporkchops I don't think the banner is worth holding up the release for - seems much more important to get that out. If there's a way to include it without too much work or delay, that's good, but if not, no worries on my end, it can go into the next one. (The next thing needing a banner is 10/26 but that's a meeting and we can manually do the banner on the day of the meeting.) @patphongs

**Comment by johnnyporkchops** [comment]
The banner announcement expiry control has been added to this release and works on staging. @dorothyyeager -You can test this on https://fec-stage-proxy.app.cloud.gov/admin, just set it to expire in a minute or so and you will see it dissapear

**Comment by llienfec** [comment]
Dorothy said above: form PDF links aren't working on H4CC Forms page - just adding that instructions are 404ing as well.  
https://fec-stage-proxy.app.cloud.gov/help-candidates-and-committees/forms/

**Comment by AmyKort** [comment]
Thanks, everybody!

**Comment by AmyKort** [comment]
If no one objects, I'll close this issue.
