### ISSUE TITLE
Retire the forms page on the transition site

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1352]
We no longer need the page that is up at https://transition.fec.gov/info/forms.shtml. The current page is https://www.fec.gov/help-candidates-and-committees/forms/. The older page contains duplicated information and in some case, links to forms that are outdated, so it is best to take it down.

- [x] Take down https://transition.fec.gov/info/forms.shtml
- [x]  Redirect links to that page to point to https://www.fec.gov/help-candidates-and-committees/forms/

**Comment by patphongs** [comment]
Will run the redirect deploy tonight for this.

**Comment by AmyKort** [comment]
Thanks @patphongs !

**Comment by patphongs** [comment]
Forms page has been deleted and redirects will be deployed tonight
