### ISSUE TITLE
Content: Legal Resources Sidebar

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#136]
Jen and I had a great discussion of the "Legal resources" sidebar on our registration and reporting pages today. I think we have a good first draft, with room for improvement. Questions about this section:

1. How often do we expect (or should) readers access these laws and read them? Is this something supplemental, which only edge case readers will use? Or do we expect that most folks will need to reference the original law?

1. Would we be better served making these footnotes within the text? Making these resources footnotes might be a more clear indicator of what part of the text each legal resource points to. *Or* would it be an equally good idea to not make them footnotes but add a title to each legal resource. For example, *11 CFR 102.2 (a)- Statement of organization: Forms and committee identification number.*  I think @jenniferthibault's perfect analogy was that clicking the legal resources without any indication what they talk about is like playing legal bingo. :)

1. Related: 70 Fed. Reg. 3, “Statement of Policy Regarding Treasurers Subject to Enforcement Proceedings” doesn't currently link to anything. If I remember correctly there wasn't a good online source for this. Is that the case?

@amykort @amypike, would love to know your thoughts on this. And let me know if you have any questions about what I wrote above. Trying to get all our thoughts out quickly and clearly!

**Comment by amypike** [comment]
Hello @emileighoutlaw and @jenniferthibault! @amykort and I talked about this a bit this afternoon and came up with the following:
1) Good question!  Is there a way to user test this?  We really have no idea how often folks will want to turn to the original legal resource.  Lawyers who use these pages may frequently click on the legal resource whereas non-lawyers probably will rarely click on the legal resource. If we are designing these pages to on-board new, non-lawyer filers, the legal resources are there more for background and maybe won't be clicked on as often as in other parts of the site?
2. Hmmm.  The tricky part about titles is for lengthier regulations, the source will be deep within the reg e.g., 11 CFR 102.2(b)(i)(ii)(A) - so the title may not be helpful, in those cases. Let's talk about footnotes.  However we wind up doing this, we will have to stay pretty close to how citations are already used in the campaign guides to avoid characterizing a regulation (or explanatory text) in a new way. 
3.  There's the Federal Register notice but I think the better resource is the RECORD summary: http://www.fec.gov/law/policy/2004/notice2004-20.pdf
http://www.fec.gov/pdf/record/2005/feb05.pdf#page=4
FYI, @amykort is battling a ferocious cold so we are making her stay home tomorrow. STAY HOME, AMY!

**Comment by emileighoutlaw** [comment]
User testing: This might be a good conversation to bring @onezerojeremy in on, if he feels up to thinking about this. Much like @amykort, he also needs to rest!!

Footnotes: Since we've re-written the text pretty substantially, I'm thinking putting footnotes back in might be tricky. But we can certainly try it out with a few pieces of text and go from there. *If* footnotes are the way we want to go with this.

Right now, I think the idea I like best is @jenniferthibault one: Put footnotes in the text, and those footnotes go to a well-designed Legal Resources box like we have now. That box can either be on the side (as it is now) or on the bottom of the page. If we can't do reg titles (and I totally get why this is tricky), maybe we could include a quick line at the top of box that says something along the lines of:

> **Legal Resources**
> *Full-text campaign finance law*     OR
> *Read the laws that apply to this page*

**Comment by AmyKort** [comment]
I like this idea:
Legal Resources
Full-text campaign finance regulations OR
Read the regulations that apply to this page

**Comment by onezerojeremy** [comment]
Can I see a sample? I think the footnotes box probably makes the most sense to me, especially if it preserves the linkage to the referring text, and makes it clear which you are linking to. I don't know many patterns on this, but wikipedia's isn't a bad place to start* (though I suspect there might be better ones). 

At first blush, I think there are a couple testing questions here. 
1. how common is the behavior? - in this case, clicking to see the relevant laws. This question is almost always be easier to tease out in metrics than in usability testing, though likely both have a role to play. 
2. what linkages between the content need to exist to promote understandability, and how granular should they be? - in this case, how granular do the links need to be to the legal resources, and how do you name those links so that the uninitiated have half a shot at getting what they need. This is indeed something for usability testing. So we could, in theory, test how successful people were at finding something referenced in the text by just listing things under "legal resources".  

* for example, if you click on the [8] on [this wikipedia page](https://en.wikipedia.org/wiki/Turritopsis_dohrnii), it takes you to and highlights the relevant reference. We can probably clean this up considerably since all the places we're linking to are known to us.

**Comment by jenniferthibault** [comment]
Here's a light mockup of what this could look like with the text citations linking to the Legal resources sidebar. Hard to illustrate here, but I'd intend the interaction be similar to that of Wikipedia: if you click the citation number in the text, it would jump you to that item on the list and highlight it.

<img width="871" alt="screen shot 2015-12-01 at 12 18 42 pm" src="https://cloud.githubusercontent.com/assets/11636908/11508263/caa66124-9825-11e5-8e97-bab27908f957.png">

<img width="870" alt="screen shot 2015-12-01 at 12 23 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/11508370/6fa203d6-9826-11e5-8c77-83b4641dbe09.png">

**Comment by jenniferthibault** [comment]
(side note, I completely invented those citations, not real!)

**Comment by emileighoutlaw** [comment]
This looks awesome. Looking at the mock ups, I prefer `Full-text campaign finance regulations` to `Read the regulations...`

**Comment by onezerojeremy** [comment]
I like the direction! Especially the syntax highlighting, I like that a lot! 

There might be a limitation to this pattern which I'm not sure if we'll encounter or not. If there is either a lot of text or a lot of references, clicking on one will either a. jump* you somewhat down the page, or b. highlight a reference that happens to be off the page. Neither seems ideal, but again, this will depend a lot on how many references and how long the text will be and maybe I'm overestimating the amount of jump. 

I'm speculating, but possibly this jumping variable amounts is what drove a bottom footnotes box used by wikipedia. Another, more radical option might be to consider thinking about a way to incorporate these links into the dictionary, but that will undoubtedly come with it's own special bundle of hurdles.  

* by jumping i mean auto-scrolling.

**Comment by jenniferthibault** [comment]
OH! HA! @emileighoutlaw I thought you wanted both pieces of text as the whole. Didn't realize it just one to be included :)

**Comment by emileighoutlaw** [comment]
It actually gave me excellent clarity as to which I preferred, though! :wink: :grin:

**Comment by amypike** [comment]
I am really glad you flagged the auto-scroll issue @onezerojeremy.  I am hopeful that the registration and reporting content will (fingers crossed) continue to have limited text and reg citations (because that's not generally a reg-heavy area) but eventually, we will wade into deeper content waters that are citation and text heavy so it is good to have that issue in mind.

**Comment by noahmanger** [comment]
Just noting this here so that I don't forget: in order to get the new styles for the sidebar I had to make a change to the way that the we create sidebar content in the CMS. I can explain later, but once it's time to update content we can do it the new way.

**Comment by emileighoutlaw** [comment]
I've been doing a research dive on footnotes on web pages. Every opinion I can find says footnotes are distracting and pull readers out of the text— which makes for a :(, disjointed experience. 

Essentially, every time a reader encounters a footnotes, they have to make a decision about whether they're going to look at the footnote and, if so, whether they want to click the link in the footnote before they can continue reading the sentence.

What I'm leaning toward now is

>**Legal resources**
Read the regulations that apply to this page


Then we include a very light description below each CFR. Similar to Jen's fabulous mock-up:

>11 CFR 102.2(a)
Statement of Organization


I'd love to get a pulse-check from @AmyKort or @amypike on this.

**Comment by amypike** [comment]
Thanks for doing the research, @emileighoutlaw and I agree we should try to avoid footnotes if we can ("I really enjoy a footnote" said no one, ever). I like the idea of a light description below each CFR citation and @jenniferthibault  mock-up is spot-on.  The light description we write will get reviewed by OGC and they can help us avoid characterizing a regulation, if that comes up.

**Comment by emileighoutlaw** [comment]
Great! I'll come up with a list or resources and light descriptions for each page, and we can review/submit to OGC

**Comment by emileighoutlaw** [comment]
Submitting doc to FEC today. [Link to Google Doc](https://docs.google.com/document/d/1WN-_rHa1Stj6sP4CbZrLvAbYKHcrbfT3g1XgBelznGw/edit?pli=1#heading=h.him0jxvc1cxq) (for 18F folks)

**Comment by emileighoutlaw** [comment]
After discussion with FEC, I added the intro note and the official CFR title of the regulation to all the legal sidebars. Using the official title avoids the issue of us "summing up" the law. 

Closing this issue for now with the note that we can consider other techniques once we have e-regs up and running.
