### ISSUE TITLE
Mis-labelled AOs

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1361]
It has been reported that some AOs are mislabeled in both the PDF and the tab name. See screenshot below of AO 2015-09, which labels it as AO 2009-18 in the grey bar at the top of the PDF as well as in the <title> tags `<title>ADVISORY OPINION 2009-18</title>`. 

- [ ] investigate how title tags are populated
- [ ] fix title tags

![image003](https://user-images.githubusercontent.com/12799132/31895994-a2df491c-b7e0-11e7-8ac5-c89d94e1440a.jpeg)

**Comment by vrajmohan** [comment]
Are the AOs mislabeled **anywhere except the gray bar** at the top of the PDF in Google Chrome? Do we have additional examples?

**Comment by AmyKort** [comment]
https://www.fec.gov/files/legal/aos/63615.pdf 2007-05 is labeled on the gray bar as 2007-03. 2007-03 is also labeled (correctly) as 2007-03).

I will keep looking. I'm only seeing this error on the gray bar.

**Comment by AmyKort** [comment]
2007-02 reads 2004-34 on the bar https://www.fec.gov/files/legal/aos/68692.pdf

2007-04 reads 2004-34 on the bar https://www.fec.gov/files/legal/aos/63644.pdf

2011-04 reads 72764 on the bar https://www.fec.gov/files/legal/aos/72764.pdf

**Comment by vrajmohan** [comment]
It looks like the defect is _in the metadata inside the actual PDFs themselves_. It looks like Google Chrome's PDF viewer uses this metadata to display the title of the PDF. The only way to fix this would be to fix the metadata in the original source PDFs and reload them.

This metadata is not used by Firefox or Safari.

**Comment by AmyKort** [comment]
What would be involved in fixing the metadata in the original pdfs?  cc @jwchumley

**Comment by vrajmohan** [comment]
FYI, this can be demonstrated on the classic site, e.g.,  http://saos.fec.gov/aodocs/2007-02.pdf.

**Comment by AmyKort** [comment]
Thanks, @vrajmohan . I think we should close out this ticket since it is not something we can fix on your end. I will open a new ticket for future work to look into the metadata in our pdfs. Thank you so much for getting to the bottom of this so quickly!

**Comment by vrajmohan** [comment]
Agreed. Assigning it to @AmyKort to close after new upstream ticket is opened.

**Comment by AmyKort** [comment]
We'll take the next steps on this at https://github.com/18F/openFEC-web-app/issues/2342
