### ISSUE TITLE
Change link format in feedback bot

### ISSUE THREAD

**Issue by lbeaufort** [18F/fec-cms#1369]
Per @jwchumley:

The website feedback repository in Github has an issue with links where "&" is being stored as "&amp;" So that the correct link is stored, save the exact URL in the GitHub issue.

https://github.com/18F/FEC/issues/4474

In this example, this is the stored URL:
 https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2016&amp;min_date=01%2F01%2F2015&amp;max_date=12%2F31%2F2016&amp;contributor_name=Maria+Cino

and this is the cleaned up url:
https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2016&contributor_name=Maria+Cino&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016

**Comment by lbeaufort** [comment]
Resolved by latest refactoring of feedback tool

**Comment by jenniferthibault** [comment]
@lbeaufort for documentation, could you point to the PR that resolves this? Thanks!

**Comment by lbeaufort** [comment]
@jenniferthibault thanks - resolved by "The Great Merge of CMS + webapp" https://github.com/18F/fec-cms/pull/1230
