### ISSUE TITLE
Add coverage end date to candidate pages

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1373]
Add coverage end date to candidate pages

- [ ] Research usability considerations of showing this data - does it need to be a column? Could other columns such as party be shortened?
- [ ] Design the display for coverage end dates

https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true
https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true
https://www.fec.gov/data/candidates/house/

**Comment by JonellaCulmer** [comment]
Related issue: #1372

**Comment by JonellaCulmer** [comment]
Researching this issue, I spoke with Christian in the Press Office. We discussed the issue facing press contacts when trying to use this information (links above) and have some key takeaways:
- Press contacts often want to know whether the numbers reflected in the election tables included the latest figures
- To verify data was up-to-date, users were encouraged to total the figures shown for previous reports to see if the totals matched up
- Wanted to know if the data included the 30th or before.

Coverage dates were again discussed as an option to resolve this work-around, as is noted in the initial comment on this issue. 

While coverage dates are important, the same information can be gleaned simply by knowing which reports have been filed.

**Recommendation**
Incorporate the `Most recent filing` (October Quarterly, Post-General 2016, etc) into the existing structure on the site. This proposed solution would avoid a time-consuming redesign involving adding additional columns. 

Presently, users can open the candidate panel on the right side of the page. This window provides valuable information on the candidate. 
![candidatetablemostrecentfiling](https://user-images.githubusercontent.com/31663028/32464135-09c1d24e-c30d-11e7-9638-427d904ea34b.jpg)

**Alternative solutions also considered but not pursued:**
Include columns or another mechanism to display the coverage dates. That did not seem like a viable solution as the columns currently take up a significant amount of space. 

Include a column to the source reports, similar to the way information is displayed on the candidate election tables ([example](https://www.fec.gov/data/elections/house/IL/01/2018/)) However, I was not convinced that a user wanting to learn more about the candidates would know to look under the list of all Presidential, Senate or House candidate lists would start a data search. They would likely conduct a more targeted search. Such as by election or by searching for a specific candidate.

**Next steps:**
@PaulClark2 Flagging for your review. This proposed solution as well as the solution for #1372 (forthcoming) can be discussed

**Comment by jenniferthibault** [comment]
@JonellaCulmer I just left a [comment](https://github.com/18F/fec-cms/issues/1372#issuecomment-342639792) on #1372 — if folks like that approach we'd probably want to make the same slight tweak here for consistency. Wanted to mention it now, but can hold pending feedback on that issue.

**Comment by PaulClark2** [comment]
Thanks. Let's go with this approach.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/18F/fec-cms/issues/1468

**Comment by jenniferthibault** [comment]
@JonellaCulmer I want to pump the brakes on this one to dig a little deeper into my last comment. 

You rightly pointed out that the approaches in this issue and https://github.com/18F/fec-cms/issues/1372 should relate. Given the tweaks that ended in the [final design](https://github.com/18F/fec-cms/issues/1372#issuecomment-342653161) focusing on coverage end date, I think we should integrate that here as well for consistency. 

To also be consistent within this feature's context (the rest of the panel)  it would also make sense to link to the filing referenced, as the others above do.

What do you think of the following?

![screen shot 2017-11-08 at 12 17 13 pm](https://user-images.githubusercontent.com/11636908/32563454-4e714fe6-c47f-11e7-9d13-658854f0cd79.png)
