### ISSUE TITLE
Make 24-hour and 48-hour IE reports the default

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1375]
Make 24-hour and 48-hour IE reports the default instead of regularly scheduled reports.
Christian, Judy, Eileen, and Jason in Press and Info Divisions have said that users are having trouble finding Independent Expenditure information.

Regularly scheduled reports are the quarterly/monthly reports that duplicate the data that is shown on the more time-sensitive 24/48 hour reports.

So that users can access IE data easily, we should make 24-hour and 48-hour IE reports the default.
- [x] Research to make sure this is the best course of action - talk to Christian, Judy, Eileen, and Jason in Press and Info Divisions

https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=false&max_date=10%2F24%2F2017

**Comment by JonellaCulmer** [comment]
After speaking with individuals in the Press, Public Records and Information divisions, it appears to be a valuable service to provide the latest independent expenditures - those included under the category `24-and 48-Hour Reports` as the default. While the same information is later reported a second time on `Regularly scheduled reports`, the information included in that section is quickly out of date when another IE is made after a reporting period ends. 

Also, while the greatest use of this section will occur before regular elections, there are still upcoming Special elections where the default of the latest IEs would still be more valuable to data users that what is included in an older report. 

This appears to be a relatively simple fix and I do not believe this issue rises to the level of requiring additional external testing before implementation. 

**Recommendation:** This default change should include moving the `24- and 48-Hour Reports` button above `Regularly scheduled reports` as well as ensuring this information is the first users see when viewing IEs.

**Comment by jenniferthibault** [comment]
That makes sense to me! Especially moving the option that's selected by default to the first position out of the two options. 👍

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue #1434
