### ISSUE TITLE
Candidate details pane not showing up on house page

### ISSUE THREAD

**Issue by ccostino** [18F/fec-cms#1377]
The details pane for any given candidate on the [house specific candidates page](https://www.fec.gov/data/candidates/house/) does not currently open due to a JS `toString` error on production:

<img width="1250" alt="screen shot 2017-10-24 at 2 19 57 pm" src="https://user-images.githubusercontent.com/121565/31960762-c0c457a6-b8c6-11e7-96ca-dab9f190b9cd.png">

The details pane does work for the presidential and senate candidate pages.

**Comment by patphongs** [comment]
This bug is fixed, the problem with the panel yesterday was due to production API issues, so I am closing this ticket.
