### ISSUE TITLE
Broken AO pagination

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1382]
When reaching the end of a result set, paginating to previous breaks.  

https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_requestor_type=11&ao_category=F

**Comment by AmyKort** [comment]
Thanks, everybody!

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
Yes, this was resolved in https://github.com/18F/fec-cms/pull/1383. Closing now.
