### ISSUE TITLE
Integrate classic's "recent developments in the law" section into H4CC

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1388]
User was looking for the analogous section for "recent developments in the law" on the new site to get to the "Independent Expenditure Committees - aka Super PACs (SpeechNow)" section.  It has information compiled that is not anywhere else on our site - new or classic.  It's not a page we are planning to keep up because the historical information is not updated and other parts of the new site do this better.

However, there is a lot of great information/citations on these pages that we don't want to lose.  Content team will look at these pages and move these over into the H4CC section where possible.

### To do:
- [x] Take an inventory of the content in "recent developments" on classic and match the sections to relevant H4CC pages, if necessary
- [x] Add citations, articles, etc., to the H4CC pages and publish, if necessary
- [x] Make sure all the AOs are covered in H4CC
- [x] Make sure all of the Record articles came over to the new site and are in H4CC

**Comment by dorothyyeager** [comment]
Hi @llienfec and @AmyKort  That page should redirect to legal resources where they can access the relevant court cases and regs. This was tackled in this issue: https://github.com/18F/openFEC-web-app/issues/2254

Got your email on the one case's Record 2010 summary not being scraped properly and will fix that today.

**Comment by dorothyyeager** [comment]
Started a google document to organize our references and thoughts about this task. It can be found at https://docs.google.com/document/d/170HXm70q8MVZ7zbuDNLWtR670DRF3QPprwJs3pIw_3Y/edit?usp=sharing

**Comment by dorothyyeager** [comment]
For the Record articles (some from 2010) - will need this bug resolved - https://github.com/18F/fec-cms/issues/1415 since to bring them over from PDF works best when using Wagtail's HTML editor.

**Comment by AmyKort** [comment]
This one is separate from but related to https://github.com/18F/fec-cms/issues/1472

**Comment by AmyKort** [comment]
moving this to the next sprint

**Comment by llienfec** [comment]
Since search page redirects, but we need to see the old resources to do the inventory, here is a cached version of the Recent Developments page for researching this issue: http://classic.fec.gov/law/recentdevelopments.shtml

I am working with the RAD analyst that flagged this issue to make sure the resources that the team uses are in the H4CC pages, and we'll also use the resources Dorothy added above.

**Comment by llienfec** [comment]
Hey @dorothyyeager - I want to get your thoughts on a couple of additions to resources on the H4CC page: https://www.fec.gov/help-candidates-and-committees/registering-pac/types-nonconnected-pacs/

Looks like 4 AOs are missing from the citations for SuperPACs.  I know this was a "selected AOs" list.  I was thinking about whether we should add some or all of the following just to be safe:
- AO 2012-34 An authorized committee contributing excess campaign funds to an independent expenditure-only committee.
- AO 2011-24 Web application for users to post ads online and finance the airing of ads on television, radio, and in other media.
- AO 2011-12 Candidate solicitations for independent expenditure-only committees.
- AO 2011-11 Application of media exemption.

**Comment by dorothyyeager** [comment]
Of those four, AO 2011-12 is the important AO IMO that would end up on a "selected" list. AO 2011-24 could be added if desired. I wouldn't cite it to a Super PAC as anything helpful to them. It really doesn't say much more than the group can have a Super PAC; most of it is about how it really wanted to do a commercial venture (which the Commission split and didn't respond to), so I'd point people to the AOs we already have on the types of nonconnected PACs page since those are the core two that get cited in every Super PAC AO.

AO 2011-12 and two more recent AOs are linked on this page: https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/fundraising-super-pacs-federal-candidates-nonconnected-pac/ which seems correct.

AO 2011-11 is on this page https://www.fec.gov/help-candidates-and-committees/taking-receipts-pac/contributions-to-super-pacs-and-hybrid-pacs/. That seems like a better fit for AO 2012-34 too.

**Comment by llienfec** [comment]
This is great.   I felt the same way about 2011-12.  I'll add it to the page and then also add 2012-34 for the receipts page mentioned above.  

We also discussed the HTML problem for the press release cited at the bottom of the page.  I'll clean that up as well.  When the work is finished, I'll close this issue.  We can always continue to work on it if I hear that RAD requests other resources linked for these committee types.  I think we've hit the major ones.

**Comment by llienfec** [comment]
- AOs have been added per discussion above
- Remade linked press release and edited HTML: https://www.fec.gov/updates/fec-statement-on-carey-fec/ thanks to @dorothyyeager for the HTML review
- Closing issue.
