### ISSUE TITLE
FEC Glossary updates for the next release (Glossary round 3, beginning after 10-26-17)

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1394]
The glossary updates, corrections and additions are something that is part of a release, so the purpose of this issue is to organize for upcoming glossary work for the next round. Background information on the process for updating the glossary is at https://github.com/18F/FEC/issues/4498#issuecomment-329518919.

**Past issues to be closed and addressed/consolidated in this issue:**
https://github.com/18F/fec-style/issues/436
https://github.com/18F/FEC/issues/4498
https://github.com/18F/FEC/issues/3976 (the Commission approved a revised definition of the word suggested by a feedback-giver today so we'll work that in.)

My google doc of things to revise for this round:
https://docs.google.com/document/d/1G7fwx3wmcmTB2cOHzKXtVvmVgtqvL0hJeSUf-i2hWGM/edit?usp=sharing

**To do list:**

- [x] Update the html code on the website for the various terms added in round 2 (the 10/26/2017 release). (See #1199 )
- [x] Find official language or get OGC review/approval for the terms to be added
- [x] Add the new "round 3" terms and other tweaks to the glossary JSON code.

**Comment by dorothyyeager** [comment]
This issue needs the bug in https://github.com/18F/fec-cms/issues/1415 to be resolved in order to do the first task.

**Comment by dorothyyeager** [comment]
Have pulled together the definitions for the next round of terms. Some will need OGC review. This document contains them. https://docs.google.com/document/d/1_-dD5xgUw8X9M_ajpW9vcizfa04-2-8H_IQuRLEHq4o/edit?usp=sharing

**Comment by dorothyyeager** [comment]
OGC has approved the terms that needed review with some minor edits we'll incorporate.

**Comment by dorothyyeager** [comment]
New terms and corrections have been updated in the JSON code; pull request filed and review requested before the next release.

**Comment by dorothyyeager** [comment]
All of the terms from round 2 (included in the 10/26 release) have been coded on the html pages. We are able to close this topic as the new terms will be part of the next release. Will pick up with a new issue to code the new terms from this round after they are part of a release.

**Comment by dorothyyeager** [comment]
Had to update the pull request so have re-opened the issue.

**Comment by AmyKort** [comment]
@xtine  Can you review this? Thanks!

**Comment by dorothyyeager** [comment]
@lbeaufort is my new hero and this issue can be closed, as the revisions will be in the next release!
