### ISSUE TITLE
Make and publish pages for bulk data metadata in Wagtail 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1399]
Bulk data tab created in https://github.com/18F/fec-cms/issues/1396

_______________________________
## Design template from https://github.com/18F/openFEC-web-app/issues/2318

![screen shot 2017-10-26 at 6 51 38 pm](https://user-images.githubusercontent.com/11636908/32080620-bec0dfc4-ba7e-11e7-8d9b-2e3f7940adcb.png)

## Content
📝  [Google Doc of metadata content](https://docs.google.com/a/gsa.gov/document/d/15ELHgzOIdS-x3oD3pByuhhzhSTgf6xo_boNECsvo_zI/edit?usp=sharing)

**Completion criteria**
- [x] Decide on a place where these pages should live in the Wagtail folder structure (should be the same place as in #1401, depending on which issue gets picked up first)
- Use the Custom page wagtail template with paragraph and table block modules to create metadata pages for:
  - [x]  All candidates file metadata
  - [x]  Candidate master file metadata
  - [x]  Candidate-committee linkages file metadata
  - [x]  Current campaigns for House and Senate file metadata
  - [x]  Committee master file metadata
  - [x]  PAC and party summary file metadata
  - [x]  Contributions by individuals file metadata
  - [x]  Contributions from committees to candidates file metadata
  - [x]  Any transaction from one committee to another file metadata
  - [x]  Operating expenditures file metadata

**Comment by PaulClark2** [comment]
There are drafts of all of these pages in Wagtail.

**Comment by llienfec** [comment]
@PaulClark2 created all of these pages.  I went through and edited the pages for language and added/populated an `example data` column to the tables for each of the pages.  The pages are now back to Paul for revising/posting.  Thanks!

**Comment by AmyKort** [comment]
These are ready to go as soon as Paul gives us the thumbs up. I've created an issue for deploying the pages at https://github.com/18F/fec-cms/issues/1755

**Comment by AmyKort** [comment]
Wait! Spoke too soon. We'll pick up this work with another level of review at https://github.com/18F/fec-cms/issues/1774
