### ISSUE TITLE
Content: Get a bank account

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#140]
Users in testing on 12/3 asked for additional text on this page. Questions included "Can I get another personal account, or do I need to get a special kind of bank account? What kind of bank can I go to? Any bank?"

Can we add 1–2 sentences to flesh this page out, @amykort @amypike? 
![screen shot 2015-12-03 at 5 16 57 pm](https://cloud.githubusercontent.com/assets/10552702/11575953/b1fd40d0-99e1-11e5-9b14-782dff60742d.png)

**Comment by amypike** [comment]
The campaign guide says that it must be "a checking account or a transaction account" and "the following institutions may be designated: state banks, national banks and depositories insured by the FDIC, Federal Savings and Loan Insurance Corporation or the National Credit Union Administration." 11 CFR 103.2.

**Comment by emileighoutlaw** [comment]
Awesome! How about we add something to the end like:

>This account can be a checking or a transaction account. You can open it at any of the following institutions:
- State bank
- National bank and depository insured by the FDIC
- Federal Savings and Loan Insurance Corporation
- National Credit Union Administration

I'm trying to make all the institutions singular (so they match grammatically), but I wasn't sure how to deal with the second one (national bank and depository? national bank or depository?)
