### ISSUE TITLE
Implement data download links and metadata page in Wagtail for Administrative fine

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1405]
Embeds the download for Administrative fine cases onto the Admin fine page and adds a link to a page for its metadata using an existing Wagtail template

**Resources**
  - 📝 [Google Doc of accordion content](https://docs.google.com/a/gsa.gov/document/d/1UldBI9T_Bhz8j-CPoCr7LViBOEYLZNtbZnH8BgMd7mk/edit?usp=sharing)
  - 📝 [Google Doc of metadata content](https://docs.google.com/a/gsa.gov/document/d/15ELHgzOIdS-x3oD3pByuhhzhSTgf6xo_boNECsvo_zI/edit?usp=sharing)

- [x] On the [Administrative fines](https://www.fec.gov/legal-resources/enforcement/administrative-fines/) page, add links to download administrative fine data as .CSV by two-year period via Wagtail. Use the following styling and content:
  - ![screen shot 2017-10-26 at 10 08 22 pm](https://user-images.githubusercontent.com/11636908/32084975-6bbe1564-ba9a-11e7-880e-2074d89eaacb.png)
- [x] Create a child page "Administrative fines" in wagtail using the Custom page wagtail template
- [x] Use paragraph and table block modules to create metadata pages for: "Administrative fines file metadata"
- [x] Publish the new metadata page 
- [x] Link to the new page from the Administrative fine page (shown in the design above)

**Comment by jenniferthibault** [comment]
@PaulClark2 one question to get us started on this issue (and the other download issues) — Where do we get the links for each two-year period as a CSV to download?

**Comment by PaulClark2** [comment]
@jenniferthibault  the bulk download URL is https://www.fec.gov/files/bulk-downloads/index.html

There are two-year folders. These folders contain the files we need.  I need to confirm that all the files are there.

![image](https://user-images.githubusercontent.com/11817734/32245889-ad2c4752-be53-11e7-94bb-28b21db1dab4.png)


https://www.fec.gov/files/bulk-downloads/index.html?prefix=bulk-downloads/2016/
![image](https://user-images.githubusercontent.com/11817734/32245952-e1f2cdda-be53-11e7-8e41-53b9a4b4db15.png)

**Comment by jenniferthibault** [comment]
Thanks @PaulClark2 that accounts for 1/2, but what about the data catalog downloads? Using this as an example, we're looking for the Administrative Fine data that will download as .CVS files (Also relevant to https://github.com/18F/fec-cms/issues/1400 )

**Comment by jenniferthibault** [comment]
Following up from a quick check with Paul on slack, the data catalog data lives here:
https://docs.google.com/a/gsa.gov/document/d/1UldBI9T_Bhz8j-CPoCr7LViBOEYLZNtbZnH8BgMd7mk/edit?usp=sharing

I'll try to work links into the content documents, which will help for all of these implementation issues

**Comment by jenniferthibault** [comment]
@rhoughfec andI just paired through implementing this (and it was awesome).

Now live and available for download:

- [Administrative fine case search and download](https://www.fec.gov/legal-resources/enforcement/administrative-fines/)

- [Administrative fines file metadata](https://www.fec.gov/legal-resources/enforcement/administrative-fines/administrative-fines-file-metadata/) page

Closing 🎉
