### ISSUE TITLE
Content: Secretary of Senate text

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#141]
@amypike @amykort, moving this conversation to GitHub so we can hopefully make a decision!

https://fec-dev-cms.18f.gov/registration-and-reporting/48-hour-notices/:
![screen shot 2015-12-03 at 5 37 49 pm](https://cloud.githubusercontent.com/assets/10552702/11576448/abb0b5c4-99e4-11e5-938d-23df70de9503.png)

We had a question from OGC in the Word document about making sure readers didn't think they _had_ to file by fax. So I re-ordered the sentences and just added in text that said "as an option" before the fax number. 

Will this work and solve our issue?

**Comment by amypike** [comment]
I like it and thinks it solves that particular problem. @amykort

**Comment by noahmanger** [comment]
Is this resolved?

**Comment by AmyKort** [comment]
Yes. Thanks!
