### ISSUE TITLE
check load times on committee and candidate profiles

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1417]
Want to make sure there was not a regression where whole page might me loading instead of just the tab.

- [ ] Check on all Candidate and Committee profile pages that  right api calls are made.
- [ ] Also check if there are any additional api calls being made when we you click on the following 
       tabs: 
- [ ]     Financial Summary
- [ ]     About the Committee
- [ ]     Raising
- [ ]     Spending
- [ ]     Filing

**Comment by jwchumley** [comment]
Front end task. On demand and not on page load. Benchmarking.

**Comment by jenniferthibault** [comment]
@LindsayYoung in standup just now you added a lot of detail and color to what this issue was about, and why it's important. Could you add that background here?

**Comment by pkfec** [comment]
Tested all of the *Committee Profiles* links. Each left had menu appears to make a right api. They all seem correct.

<img width="632" alt="screen shot 2017-11-30 at 2 30 46 pm" src="https://user-images.githubusercontent.com/11650355/33450860-27076f36-d5db-11e7-99f0-64045d23dfc9.png">

**Comment by pkfec** [comment]
This is more of a research task. No code changes. Closing the issue.
