### ISSUE TITLE
Explore AO button broken

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1420]
Need to fix `Explore all advisory opinions` button within /fec/legal/templates/legal-advisory-opinions-landing.jinja. There is an additional bracket in the button URL that is breaking the link. 

![pasted image at 2017_10_30 03_14 pm](https://user-images.githubusercontent.com/12799132/32191409-63f4f858-bd87-11e7-87d7-79ae13b948a7.png)

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
Yes, this was just deployed this morning in this PR https://github.com/18F/fec-cms/pull/1422. Closing now.
