### ISSUE TITLE
User feedback: AO legal citations missing

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1425]
From feedback repo:  https://github.com/18F/FEC/issues/4613. 

**JonellaCulmer**
Received feedback regarding AO 2016-24 from user via email:

I was just looking at the above referenced AO and noticed that in the Legal Citations box, it says that the AO does not cite statutes and regulations. It does. It picked up the other AOs cited, but not the statutes and regulations.

**AmyKort** 
@vrajmohan Is this related to the way citations appear in our documents--the spacing, the section symbols, etc.? I feel like we've run into this before.

**vrajmohan**
It is indeed due to the inconsistent way the citations appear in the documents. In this case, it is due to "C.F.R." instead of "CFR" in "11 C.F.R. § 100.15", and the § symbol is followed by an unexpected space in "52 U.S.C. § 30101". These 2 cases are relatively easy fixes. My estimate is 1 to fix them. We would have to then reload the AOs and back them up again, which would make it a 2.

- [X] Make API changes, automated tests
- [X] Test API
- [x] Test on front-end
- [ ] Reload the AOs and back them up again

**Comment by lbeaufort** [comment]
@vrajmohan - it looks like this is now working. We just need to back up and reload AO's. I can give [these backup instructions](https://github.com/18F/openFEC/wiki/Elasticsearch-backup-instructions) a shot and reload AO's if that's not going to add to the production issues we've been having. I'll ping the dev channel in slack.

**Comment by lbeaufort** [comment]
REGEX issues resolved by https://github.com/18F/openFEC/pull/2740

**Comment by vrajmohan** [comment]
Reloaded AOs on `prod` and backed up to snapshot named `es_backup_20171120_with_better_ao_citations`.
