### ISSUE TITLE
Evaluate and refine draft value prop statements

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1426]
We've created a great list of value prop examples. Our next step is refining our statements and creating a shared understanding of what the real-world impact of each draft statement would be, so we understand the differences among our options. After that, we can limit those options to 3 or 4 that we'll propose to internal stakeholders.

**Comment by rhoughfec** [comment]
tagging in @jameshupp to work on this as well

**Comment by AmyKort** [comment]
Can I help too? I love this stuff!

**Comment by rhoughfec** [comment]
of course! James offered at the end of sprint planning yesterday...the more the merrier!

**Comment by AmyKort** [comment]
We've got four great examples. Thanks everyone!
