### ISSUE TITLE
Identify base filter patterns to add to the pattern library

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1428]
Ensure that the base components of filter interactions are recorded in the pattern library for consistent use and construction in interfaces.

**Completion criteria**
- [ ] Identify modules for filter patten components (including the new dependent dropdown category/subcategory pattern from the audit search filters) with design mockups
- [ ] Transfer designs to implementation in https://github.com/18F/fec-cms/issues/1368

**Comment by jenniferthibault** [comment]
@JonellaCulmer I'm working on a collection of the base patterns in [this Mural](https://app.mural.ly/t/gsa6/m/gsa6/1510067679674/11e44c652bbf873b6aef425a4b5507434b3cd390) so that we can both work on it simultaneously

At this point I _think_ I've identified the basic filter components, so would appreciate you taking a look to see if I've missed any.

Then, we should organize and label the components into how we'd like them arranged in the pattern library. We can even write the UX documentation for when & how to use them in here

**Comment by JonellaCulmer** [comment]
@jenniferthibault I went through all the data search options and I do believe you got all of the basic filter components. I added a few notes on the board as well. I started to go overboard and included other design patterns that need to be added, but that's for another day. :grimacing:

**Comment by jenniferthibault** [comment]
Here's our complete list of base filter patterns, which I'll break out into separate implementation issues.  

**Filters**
- Checkboxes
- Checkbox: standalone
- Dropdown: single-select
- Dropdown: multiple select
- Dropdown: multiple select with suggestions
- Dropdown: subcategory
- Toggle button: horizontal
- Toggle button: vertical
- Search: type-ahead only
- Search: type-ahead and free text
- Search: free text only
- Range
- Range: time

____
Noting for documentation: the Boolean search interaction (which allows complex search logic operators, like "and, or, not" seems like more of a complete interaction pattern, made of of the components above. So for that reason it doesn't make sense to include in the filter list, but probably does make sense to include as a search pattern of its own.

**Comment by jenniferthibault** [comment]
Broken down into the following implementation issues:

- Checkboxes: https://github.com/18F/fec-pattern-library/issues/22
- Radio buttons: https://github.com/18F/fec-pattern-library/issues/25
- Dropdown: https://github.com/18F/fec-pattern-library/issues/23
- Toggle button: https://github.com/18F/fec-pattern-library/issues/24
- Search fields: https://github.com/18F/fec-pattern-library/issues/26
  - Boolean search fields (separate because it's a little more complex): https://github.com/18F/fec-pattern-library/issues/27
- Ranges: https://github.com/18F/fec-pattern-library/issues/28

Closing in favor of implementation of those issues
