### ISSUE TITLE
Breadcrumbs for the MUR cannonical pages

### ISSUE THREAD

**Issue by pkfec** [18F/fec-cms#1429]
`Legal resources` and `Enforcement` links in the breadcrumbs are broken
they should not have the `/data` in the path for those breadcrumbs.

Here is the broken link:
https://www.fec.gov/data/legal-resources/

**Comment by pkfec** [comment]
Updated the breadcrumb_links for archived murs.
Added missing breadcrumb_links for current murs.
tested the changes in my local. Links on the header  for current and archived murs works fine.
submitted a PR : https://github.com/18F/fec-cms/pull/1433.
"xtine" approved the PR. This PR ready to merge to develop.

**Comment by PaulClark2** [comment]
Fixed by  https://github.com/18F/fec-cms/pull/1433
