### ISSUE TITLE
Content: New registration and reporting page

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#143]
[New page](https://fec-dev-cms.18f.gov/registration-and-reporting/).

@jenniferthibault and @noahmanger. I think these new designs look awesome! So awesome they've got me re-re-re-thinking a couple content things.

## Question 1: Headers
![screen shot 2015-12-03 at 6 01 50 pm](https://cloud.githubusercontent.com/assets/10552702/11577038/e02c6114-99e8-11e5-8ad8-01f67e35a661.png)

I think 
#### Register your candidacy or committee and get started reporting
is too similar to 
#### Learn how to register as a candidate or committee and get started reporting
which appears farther down on the page. Do we need the second one at all? 

## Question 2: Hero
I'm suddenly having a concern that "Start by finding the group you identify with below" might deter people who want to find information about a group but don't identify as that group. Curious if anyone else feels the same way? 

Thanks for your brains on this!

**Comment by noahmanger** [comment]
## Question 1:
I think a heading is useful here, but agree that maybe it could be more descriptive. What about something along the lines of:
> Options for registering with the FEC

## Question 2:
I think a call to action type thing is good, but maybe a slight tweek:
> View the different ways to register 

Or something? The "identify with" language feels a little obtuse.

**Comment by jenniferthibault** [comment]
**Question 1:** 
If we're no longer using `Learn how to register as a candidate or committee and get started reporting` below, could we use `Register as a candidate or committee and get started reporting` above instead of `Register your candidacy` ? I find it slightly more natural.

I defer you you @emileighoutlaw on whether you think an intro headline about the group types here is necessary or not, and what it should be.

**Question 2:** 
Same, defer to you on what text is needed, but I think a call to take action is helpful here.

**Comment by emileighoutlaw** [comment]
Ooooh! I love where this is heading.

## Question 1:
Absolutely, Jen. Let's change the top header to 
> Register as a candidate or committee and get started reporting

Then, below, I want to make sure we capture that there's content on registration _and_ reporting. What if we mirror the header above ("What does it mean to register and report?") with:
> Who can register and report?


## Question 2:
I think we have a couple options where we could go with this. I don't know if we ever considered something in the friendly first-person? Like: 
> I want to learn more
> Show me my options
> Show me registration options

Tone-wise, that might not be exactly right. The more formal options I think could be 
> Start by finding the group you want to learn about
> View the different ways to register

Any preference on these things? Also, thanks for letting me run these ideas by you two.

**Comment by jenniferthibault** [comment]
Weee! Teamwork!

Q1 sounds resolved.

Q2: I agree the slightly more formal tone feels like a better fit. My preference is for the first:
> Start by finding the group you want to learn about

**Comment by emileighoutlaw** [comment]
I like that too. @noahmanger does that option sound good to you? If so, I'll get a PR going with those content edits!

**Comment by noahmanger** [comment]
Hmm. "Start by finding the group you want to learn about" feels too vague to me, and makes me think it's about learning about a _particular type_ of group, not the general options for registering. I think I prefer "View the different ways to register." But we should just pick something and try it.

**Comment by emileighoutlaw** [comment]
Maybe we can convince @onezerojeremy to weigh in? We're trying to decide between either

> Start by finding the group you want to learn about

or

> View the different ways to register

for the top of the page

**Comment by onezerojeremy** [comment]
i think i like number 2. It feels more slightly more active. Plus when i read "start by finding the group you want to learn about" I think of a particular group (like say, Bob's SuperPAC).

**Comment by emileighoutlaw** [comment]
Helpful to know! I'm bringing this page to content critique today, so I'll report back what our content cohort says. ;)

**Comment by emileighoutlaw** [comment]
Thoughts from our content critique:

1. Clicking the arrow allows users to skip the section "What does it mean to register and report?" 
Do we want to let folks do that? If not, we should rethink whether we want any button or copy there.

2. "Ways to register" sounds like "by paper or electronically" more than it does registrant groups. 
How about something like "View registration categories" or "See registration categories"
