### ISSUE TITLE
[hotfix] Correct Senate classes in constants.py

### ISSUE THREAD

**Issue by lbeaufort** [18F/fec-cms#1430]
Per @PaulClark2:
"I did find a mistake in the Senate classes but not with Texas. Texas was correctly in Class 1. Here's the correct class information. I've corrected this in FECP. We'll need to correct it `constants.py`."

`'1': ['AZ', 'CA', 'CT', 'DE', 'FL', 'HI', 'IN', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NJ', 'NM', 'NY', 'ND', 'OH', 'PA', 'RI', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], `

`'2': ['AL', 'AK', 'AR', 'CO', 'DE', 'GA', 'ID', 'IL', 'IA', 'KS', 'KY', 'LA', 'ME', 'MA', 'MI', 'MN', 'MS', 'MT', 'NE', 'NH', 'NJ', 'NM', 'NC', 'OK', 'OR', 'RI', 'SC', 'SD', 'TN', 'TX', 'VA', 'WV', 'WY'],`  

`'3': ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'MD', 'MO', 'NV', 'NH', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'SC', 'SD', 'UT', 'VT', 'WA', 'WI']`

**Comment by PaulClark2** [comment]
I'd like to make this a hotfix instead of waiting for our next release. A number of states in Classes 2 and 3 where wrong in FECP. I've corrected the data in FECP.
