### ISSUE TITLE
Implement New 24- and 48-Hour Report Toggle Default

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1434]
**What we're after:** For interested groups, the latest independent expenditures (IEs) are often more valuable than IEs listed in regularly scheduled reports. In order to get users to the most recent IEs made, we need to make the default search view of IEs submitted through `24- and 48-Hour Reports`.

**Design:**
![modifiedietoggle](https://user-images.githubusercontent.com/31663028/32291571-d44f5278-bf13-11e7-8b36-3fae211c18ad.jpg)

**Completion Criteria:**
- [x] Swap the `24- and 48-Hour Reports` toggle with the `Regularly scheduled reports` toggle in the filters panel so that `24- and 48-Hour Reports` is the top option
- [x] Set the `24- and 48-Hour Reports` as the default option, so data in that view is populated automatically on the page

History in #1375

**Comment by jenniferthibault** [comment]
I got this started in the branch `feature/fix-ie-report-toggle`

A midstream question, and a good opportunity for someone from the FEC to train a novice...
on https://github.com/18F/fec-cms/blob/feature/fix-ie-report-toggle/fec/data/templates/macros/filters/ie-reports.jinja#L14 the value set for the 24- and 48- Hour Reports toggle is  already set to `value="true"` , which makes me think it's the toggle option that's applied by default, but that doesn't seem to be the case looking at the existing interface, which applies the "Regularly scheduled reports" option by default, even though it's set to `value="false"`

Is there another property or file that determines which option is applied by default that I'm overlooking?

**Comment by jenniferthibault** [comment]
I got some help from a colleague at 18F, and finished up the work in https://github.com/18F/fec-cms/pull/1496 which is now ready for review

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by jenniferthibault** [comment]
Yes, closed via implementation #1496
