### ISSUE TITLE
Searching for "C9....." committee ID's resulting in server errors

### ISSUE THREAD

**Issue by hcaofec** [18F/fec-cms#1445]
per Jason Bucelato, slack-data channel, 
a user called about getting server errors on these pages:
https://www.fec.gov/data/committee/C90011677/ 

https://www.fec.gov/data/committee/C90011230/

**Comment by lbeaufort** [comment]
@xtine  - when you get a chance, it looks like `url_for()` isn't working [here](https://github.com/18F/fec-cms/blob/e9ef001cc9aedc6ce6e5897d57f5457e3c1c338a/fec/data/views.py#L327) I took a crack at it and can't figure out how to fix this issue

**Comment by lbeaufort** [comment]
This might be helpful but I'm a little out of my depth: https://docs.djangoproject.com/en/1.11/ref/urlresolvers/

**Comment by PaulClark2** [comment]
FYI: the API returns financial data
https://api.open.fec.gov/v1/committee/C90011677/totals/?sort=-cycle&per_page=20&page=1&api_key=DEMO_KEY

**Comment by LindsayYoung** [comment]
url_for exists in flask but not Django. 

I gave it a shot this evening and I can't seem to pass the committee_id and cycle to the committee function. 

What we can do is remove the redirect for now- that will get rid of the feature where it will default to the most recent cycle with data, but it will get you to the current page and then you can manually change cycles.

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by lbeaufort** [comment]
@AmyKort  - yes, I'll close it. We have a workaround and a new ticket to address this issue for the long-term.
