### ISSUE TITLE
candidate profile page gets not found error when 2017-2018 filter is selected

### ISSUE THREAD

**Issue by cptechiegal** [18F/fec-cms#1467]
When filter for Time Period: 2017-2018 selected,
https://www.fec.gov/data/candidate/P80001571/?cycle=2018&election_full=false
the filter page is getting a not found: 404 page

- [ ] Step 1 is to determine whether this is a front end problem or an API problem

May be related to 18F/fec-cms#1511

Check that this fix resolves this issue too: 
found this 404 error: https://www.fec.gov/data/candidate/S8AL00308/?cycle=2017&election_full=true

Steps to reproduce: Click on candidate page https://www.fec.gov/data/candidate/S0AL00156/ and choose "2017." Not sure if this is addressed by @patphongs's redirect fix, but 2017 and 2018 probably shouldn't both be in the dropdown.

**Comment by lbeaufort** [comment]
To reproduce:
![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/20e72bc5-46f0-42cd-ad8d-1578dd251dd8)[image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/550c47c9-006d-41fa-9251-ee236462536e)

**Comment by lbeaufort** [comment]
@AmyKort 

This was fixed by another hotfix: https://github.com/18F/fec-cms/pull/1637

I entered a separate bug for AL senate: https://github.com/18F/fec-cms/issues/1642
