### ISSUE TITLE
Find home for FEC brochures, et al

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#147]
FEC has a variety of publications that apply to registration and reporting. Eventually they'll need a home on our registration and reporting section

To do:
- [x] Inventory of what exists by registrant type (Emileigh)
- [x] FEC review and approval
- [ ] Design discussion
- [ ] Implementation

[Stories on board card](https://18f.storiesonboard.com/m/fec/!card/Q5QE2mGqKNa2lDnUgJwigQ)

**Comment by noahmanger** [comment]
Is there already a white card on our story map that this falls under? If not, can you make one with a user story to help us prioritize?

**Comment by emileighoutlaw** [comment]
This was under a different card, but I pulled it out so it doesn't look like a blocker on a different task when it's, in fact, a related but non-priority item. I'll add a card!

**Comment by emileighoutlaw** [comment]
[Audit located here](https://docs.google.com/document/d/1X_snIcsZdoZIK89X-ve4LSPwa9Pttz7t-KWZe5a03BI/edit?pli=1#). I believe this captures all of FEC's published guidance to users.

@amypike @amykort, two thoughts:
1. Can you view this doc (or let me know if you can't view this doc) and let me know what you think?
2. I think we're ready to start thinking about how and if we want to incorporate all of this into the site.

**Comment by noahmanger** [comment]
Is this issue still relevant? Should we close or icebox it?

**Comment by emileighoutlaw** [comment]
We got great feedback from FEC on these publications. That said, let's icebox it for now— I'm thinking we'll want to wrap this into our work when we design a new publications home for betaFEC.

**Comment by emileighoutlaw** [comment]
(I could have/should have just moved it to icebox myself (duh). sorry and thanks)

**Comment by noahmanger** [comment]
More robust issue over at #387
