### ISSUE TITLE
Test staging site before release 11/09 release

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1473]
This is a general issue to collect any feedback about any broken links or features not working on staging before the 11/09 release.

**Comment by jenniferthibault** [comment]
Withdrawn advisory opinions are displaying `1900` dates instead of `Withdrawn` as expected from the fix in https://github.com/18F/fec-cms/issues/1390.

All withdrawn AOs: 
https://fec-stage-proxy.app.cloud.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=W

2009-05, which was the test case in the fix: 
https://fec-stage-proxy.app.cloud.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=W&ao_no=2009-05

cc @vrajmohan & @lbeaufort who had their hands in the code for this fix

**Comment by AmyKort** [comment]
Are we ready to close this?

**Comment by jenniferthibault** [comment]
Yes! This was resolved and released on 11/9. Thanks, closing.
