### ISSUE TITLE
Improve design of essentials template

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#148]
**[Story](https://18f.storiesonboard.com/m/fec/!card/4sHk8_8fF-AnQTnTwqtsBA)**: House and senate candidates and committees can register.

**Goal:** Based on our discussion in the meeting today and the feedback from usability testing, we need to do more in both the visual and content design of the candidate committees essentials page to clearly communicate the order in which steps need to be completed.

**Tasks:**
- [x] @jenniferthibault mockup
- [x] @emileighoutlaw discuss content changes with Amys (e.g. consolidating tax ID and bank account articles)
- [x] I'll implement

**Comment by jenniferthibault** [comment]
Notes from usability testing:
> None of the tested users had much difficulty finding the essentials page. However, on the essentials page, the metaphor of steps to complete is clearly not as strong: some users still understood that this was the list of all things necessary, some did not. 

> Users wanted more content in the concise version about bank accounts. For instance, one user wondered if it could be a personal bank account?

Notes from sprint planning to try:
> try: bullet styles or making a single-column list, OR content shuffling to create a more clear direction

**Comment by emileighoutlaw** [comment]
One thing I'm going to do is for sure is combine "Get a tax ID" with "Get a bank account." So the new section will be "Get a tax ID and bank account."

**Comment by jenniferthibault** [comment]
I have a bunch o' options for discussion:

#### 1. Return to single-column layout. 
- Options: use checkmarks as bullets (I don't think this really helps order anything, but...) , or keep traditional bullets

<img width="767" alt="screen shot 2015-12-08 at 3 07 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/11667137/f5c6e200-9dbd-11e5-945a-5329a80bfc5a.png">

#### 2. Single column, increase item independence w/ white space & rule lines

<img width="771" alt="screen shot 2015-12-08 at 3 07 33 pm" src="https://cloud.githubusercontent.com/assets/11636908/11667176/30018434-9dbe-11e5-93c3-ec82a72b1fa7.png">

##### 2a. with imagery
<img width="769" alt="screen shot 2015-12-08 at 3 07 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/11667236/8784f2d6-9dbe-11e5-9995-1ed1513d7458.png">


#### 3. Two column, increase item independence w/ white space & rule lines

<img width="773" alt="screen shot 2015-12-08 at 3 06 46 pm" src="https://cloud.githubusercontent.com/assets/11636908/11667201/5bfdf6e4-9dbe-11e5-8301-1edbaacb4b9c.png">

@onezerojeremy / @emileighoutlaw , thoughts? What do you think would help, and what are your outstanding concerns?

**Comment by emileighoutlaw** [comment]
First pass reaction:

I definitely prefer the single column. 
I'm initially drawn to the checkmarks, but I also _really love_ 2a. with imagery.

I'm going to keep thinking and add more notes.

**Comment by onezerojeremy** [comment]
I like option 1 the best. The single column plus checkmark bullets makes it feel very much like a list again! 

My second choice would be either 2 or 2a, probably leaning ever so slightly toward 2: like Emileigh, I really like the imagery, but I have the slight concern that it'll distract, and it moves us slightly away from the checklist metaphor. (though i suppose people do often doodle on checklists. :grin: )

Only thought on 1: will the checklist checkmarks feel too overbearing if they are all visible. 

These are testable!

**Comment by jenniferthibault** [comment]
@onezerojeremy as I understood, we had decided to move away from the checklist metaphor, the criteria was instead making sure users could tell the order they needed to complete steps in, rather than make it seem like they need to complete ALL of them. (Example: users would not register as **both** a candidate *and* a committee.)  Is this still true?  

If it is true, I think **2** or **2a** would be better to pursue. 

If it's not true, and you want to checklist metaphor, here's a list using the checkmarks but with more space. I think the possibility of overbearingness is a product of clutter. 

<img width="692" alt="screen shot 2015-12-08 at 4 22 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/11669111/ed147446-9dc8-11e5-9bf8-89a6715e8373.png">

**Comment by onezerojeremy** [comment]
So my recollection is, as always, imperfect. But imperfect as it is, I thought we wanted to move away from the specific implementation of the checklist metaphor that used check-box like markers, as people were confused about whether or not they were clickable. IIRC, was the main hang-up. If there were discussions to completely abandon it, I don't recall them.

For what it's worth, (specific implementation aside) I am still very much pro-the checklist metaphor, as it gets people to understand that the list of items on the page are by and large all things that they'll need to do. They actually do need to register both as a candidate, and as a candidate committee. The more these feel like a list of things that might be of interest and might not, the more users will just look for the "register now" link, not realizing they first need a tax id and bank account.

**Comment by jenniferthibault** [comment]
My memory is also fuzzing around this, feels like we've been talking about or around it for a long time, so things are getting mixed up. Thanks for the helpful clarification! (and your patience). In that case, are you ok with trying out the adjustment to the checkmark mockup in my last comment?

(if we want to get really fancy, we can make all the checkmarks federal blue by default, then turn them orange on the pages a user has read already using cacheing. Is this a possible thing? I think it is, but don't want to speak for implementation)

**Comment by onezerojeremy** [comment]
oh sorry. Yes! The edit you made looks positively lovely and not overbearing in the least. Nice work. 

I also like the idea of turning them federal blue, but i'd make it an easter egg/discoverable feature; you gotta click on them to make 'em blue (and then cookie that). Could be confusing. (my assumption is that folks will return to this page multiple times before they finish everything on it)

**Comment by noahmanger** [comment]
Nice! I agree, I like the checkmark option the most too. While I think that changing the color based for items they've visited is possible and neat, I'm imagining it's more work than it's worth right now. I also think it may be a little confusing.

**Comment by jenniferthibault** [comment]
Works for me! Transferring ownership over to @noahmanger for implementation while @emileighoutlaw 's content changes are ongoing.
