### ISSUE TITLE
Populate the Help for Corporations and Labor Organizations section with content from the newly approved Campaign Guide

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1482]
The Commission recently approved the revised campaign guide for corporations and labor organizations and approved text that reflects the current state of the law is now available to fill up the buckets in that section, including the new bucket for fundraising for an SSF.

The high-level (and secondary-level too) buckets were identified in #1392. It is now time to fill those buckets with the text from the new guide.

Completion criteria:
- [x] Create new bucket for SSF fundraising (update the landing page)
- [x] Create google doc with the Guide text to use for each page (as noted on this spreadsheet: https://docs.google.com/spreadsheets/d/1Jnkagj1Dnf_cu0IViNcR8WKXTyDzmaJstOLxdfg3qT4/edit?usp=sharing) and circulate to content team
- [x] As needed, get approval from OGC for content that varies from approved language.
- [x]  Begin creating pages and populating them with content. (This is something that @gsmaragdis can assign various Information Division staff to help with.)
    - [x] SSF registration - These pages are ready for review.  Some pages will need links to pages in other sections; but otherwise this is done and ready for review by content team.
    - [x] SSF receipts - Myles has entered these; I've doublechecked and added glossary and read next links.This is done and ready for review by content team. 
    - [x] SSF fundraising - Kathy has entered these. I've doublechecked and added glossary and read next links. This is done and ready for review by content team. 
    - [x] SSF disbursements - This is done and ready for review by content team. One page on electioneering communications is awaiting input from RAD. Updated: @llienfec just gave go-ahead on the EC page.
    - [x] SSF filing -No updates for this are needed at this time.
    - [x] SSF recordkeeping - Paul S. has entered these; I've doublechecked and added glossary and read next links. This is ready for review by content team.
    - [x] SSF loans and debts - Myles has entered these; I've doublechecked and added glossary and read next links. This is done and ready for review by content team.
- [ ] Review by content team
- [x] Double check work against [new Guide pages](https://fec-stage-proxy.app.cloud.gov/help-candidates-and-committees/)

**Comment by dorothyyeager** [comment]
Will update this comment with links to the various working documents for each bucket. They are works-in-progress now (will note when they are finalized and ready for page creation).

**Working document for "Registering as an SSF":**
https://docs.google.com/document/d/1Grlv5KiWCvarOkGexaukgBsQ3kXUohKACpwX5faR6Ds/edit?usp=sharing

**Working document for "Taking in receipts as an SSF"**: https://docs.google.com/document/d/1G4iL6Y_oWvi3hMvrD-mk3acLy5j5D8BT8JxekqCRZDc/edit?usp=sharing

**Working document for "Keeping Records as an SSF"**
https://docs.google.com/document/d/1AXgRbZ9TzMmC6-lqRJFKIPG3iwYiQ_2v6JssyK3WU-Y/edit?usp=sharing

**Comment by dorothyyeager** [comment]
This task will definitely continue into sprint 4.5.

**Comment by dorothyyeager** [comment]
The disbursement bucket is finally ready for comment! See link above. The remaining buckets should go more quickly as there's not as much content for them.

**Comment by dorothyyeager** [comment]
And the recordkeeping and the debts/loans bucket are also ready. See link above.

Once the team has reviewed, we can flag issues for OGC review and begin creating the web pages for the rest.

**Comment by rhoughfec** [comment]
Big kudos to @dorothyyeager for all her hard work on this!

**Comment by dorothyyeager** [comment]
We've sent off a document to OGC with some minor proposed changes to the text for their review. By and large, most of the pages will use approved text from the Guide throughout. @gsmaragdis is going to assign several specialists to begin creating the pages and I'll get them going.

**Comment by dorothyyeager** [comment]
We've created the landing pages (in draft of course) following the format used for the new Guide pages. Several Info Division specialists have been recruited to begin entering in content and creating the new pages; I'm finalizing the google docs above to resolve comments and give some instructions to the specialists. I'll keep tabs on where we are with these in the completion criteria above.

**Comment by dorothyyeager** [comment]
Just realized as we are inputting material, we may need to change the wording of the Guide page. I'll file a separate issue for this.

**Comment by dorothyyeager** [comment]
We received OGC's minor edits today. I'll update the google docs with them and ensure they make it into the final versions of the SSF pages.

**Comment by dorothyyeager** [comment]
This task is coming along but will need to continue into RBS4

**Comment by dorothyyeager** [comment]
The pages have all been entered. I'm doublechecking one section for adding links/glossary terms, but otherwise they are ready for the content team to review. I've added that to the completion criteria. @AmyKort @rhoughfec @llienfec @gsmaragdis

**Comment by gsmaragdis** [comment]
Thanks @dorothyyeager !  I will complete my review by cob on Tuesday.

**Comment by dorothyyeager** [comment]
We've got a few Info Division people putting some fresh eyes on the new pages before we unveil them, but they are just about ready! I'm going to close this issue, as the work is done. Further work on making the pages live will be done under #1704
