### ISSUE TITLE
Calendar entries for November 13-15 not in chronological order

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1485]
Via Greg Scott:

I just noticed that November 13-15 don’t appear in chronological order on the Commission Calendar.  There are lots of issues with the calendar that I understand cannot be addressed right now, but I wondered if this one might rise to the level of a “hot fix”?  Thanks! – Greg 

![calendar-cap](https://user-images.githubusercontent.com/24437369/32731375-a6d2b5c2-c857-11e7-9fdb-ff6ac017b609.jpg)

**Comment by dorothyyeager** [comment]
Immediate issue was resolved by removing the time of 11:59 PM from the entry for November 13. 

However, there are times we need to put the time on a calendar entry, so it would be good to investigate why having the time on this entry caused the dates to appear out of order.

**Comment by AmyKort** [comment]
Let's keep an eye on this. Closing for this instance. Thanks!
