### ISSUE TITLE
Create rotation list for team members to participate in releases

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1489]
Action item from Sprint 4.3's retro:

So that more team members get experience in creating a release, create a rotation list that assigns team members to upcoming releases regularly.

Consider whether one person to paired on a release one sprint should be responsible for training the next team member for the next sprint's release.

**Comment by jenniferthibault** [comment]
Turns out we've had this idea before. It should not be a big lift to make.

Here's the rotation list we had of 18F team members formerly: 🔏 [FEC Release Rotation](https://docs.google.com/a/gsa.gov/document/d/1cjoV-VBvQjWHlbfu2DZ6I2ji9NjJ4CgddruMU8luODA/edit?usp=sharing)

**Comment by AmyKort** [comment]
For the interim, we're going to plan to ping the pool of FEC team members immediately following each release to determine who will participate in the next release, and memorialize this information in our sprint planning documents.
