### ISSUE TITLE
Test staging site before 11/21 release

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1502]
This is a general issue to collect any broken links or features not working as expected on staging before the 11/21 release.

**Comment by jenniferthibault** [comment]
- [ ] Breadcrumbs missing parent section on ["Guides" page](https://fec-stage-proxy.app.cloud.gov/help-candidates-and-committees/guides/?tab=political-party-committees). More inconvenient to navigate backwards without this
  - **Current:** `Home` > `Guides`
  - **Expected:** `Home` > `Help for candidates and committees ` > `Guides`
  - ![screen shot 2017-11-16 at 3 06 40 pm](https://user-images.githubusercontent.com/11636908/32913259-cc18265c-cadf-11e7-9982-b4f601988a00.png)

**Comment by jenniferthibault** [comment]
- [ ] Focus state cut off on "Guides"  page side menu, making the experience look broken and interrupted
  - **Current:**  Top edge cut off
  - ![screen shot 2017-11-16 at 3 12 32 pm](https://user-images.githubusercontent.com/11636908/32913557-b1de0f76-cae0-11e7-9c78-59b487908730.png)
  - **Expected:** Top edge visible
  - ![screen shot 2017-11-16 at 3 13 18 pm](https://user-images.githubusercontent.com/11636908/32913596-c6a784c8-cae0-11e7-8adf-b94e0083ae5c.png)

**Comment by jenniferthibault** [comment]
- [ ] Fix order of content bucket items on all Guide pages.
  - **Current order transposed from previous layout:**
  - ![screen shot 2017-11-16 at 3 42 13 pm](https://user-images.githubusercontent.com/11636908/32914808-d9e276d4-cae4-11e7-8809-9a1e44483d95.png)
  - **Correct/expected order transposed from previous layout:**
  - ![screen shot 2017-11-16 at 3 42 09 pm](https://user-images.githubusercontent.com/11636908/32914799-d246cf60-cae4-11e7-95f1-73ba7a671f70.png)


@patphongs I know we talked about this one, but looks like we ended up talking past each other. I confirmed this order in slack in the #content channel

**Comment by jenniferthibault** [comment]
- [ ] Individual guidance pages and sections now need missing parent "Guide" category in breadcrumbs
  - **Current:**
  - ![screen shot 2017-11-16 at 5 14 41 pm](https://user-images.githubusercontent.com/11636908/32918903-f30cd4da-caf1-11e7-91a8-f43ed9e0f158.png)
  - ![screen shot 2017-11-16 at 5 16 59 pm](https://user-images.githubusercontent.com/11636908/32918904-f33796a2-caf1-11e7-9c24-7ad42a38beae.png)
  - **Expected:**
  - `Home` > `Help for candidates and committees ` > **`Guides`** > `Taking in receipts`
  - `Home` > `Help for candidates and committees ` > **`Guides`** > `Taking in receipts` > `Types of contributions`

**Comment by xtine** [comment]
Commissioner headshots missing for on Leadership and Structure page: https://fec-stage-proxy.app.cloud.gov/about/leadership-and-structure/

**Comment by jenniferthibault** [comment]
Through design and front end pairing, we realized that the breadcrumb issue in my last comment above is probably a bigger fix, but shouldn't hold the feature from being released. I'm going to move that into a separate issue for us to pick up later. The other issues flagged above have been addressed though @patphongs work in #1504

**Comment by patphongs** [comment]
Through testing we found out that the dates and deadlines link was incorrect on the new H4CC landing page. I have corrected the link also in #1504 and just logging that here so we know that work is done.

**Comment by AmyKort** [comment]
Thanks, everybody!
