### ISSUE TITLE
F1s from 1999 not appearing on site

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1523]
Form 1s from 1999 don't seem to appear on the website. Here are some examples:

## Details
* URL: https://www.fec.gov/data/committee/C00241349/?tab=filings&amp;cycle=1998
* User Agent: Amazon CloudFront

**Comment by PaulClark2** [comment]
This seems to be fixed.

![image.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/ce0ca3aa-ba8e-4593-9d8d-769912222416)
