### ISSUE TITLE
Write introduction for "Download bulk data" section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1532]
@PaulClark2 commented on [Fri Sep 29 2017](https://github.com/18F/openFEC-web-app/issues/2321)

Write something about bulk data to help people understand why they might need it
- [ ] Review the user need behind the data below 👇 
- [ ] Write the descriptions 

Related to https://github.com/18F/openFEC-web-app/issues/2318 "Complete mapping data catalog and FTP data to advanced data pages"

---

@PaulClark2 commented on [Tue Oct 03 2017](https://github.com/18F/openFEC-web-app/issues/2321#issuecomment-333981410)

http://classic.fec.gov/finance/disclosure/ftp_download.shtml

http://classic.fec.gov/finance/disclosure/ftpdet.shtml

http://classic.fec.gov/finance/disclosure/ftpsum.shtml

Data Catalog, http://classic.fec.gov/data/DataCatalog.do: each data set has a description 

---

@jenniferthibault commented on [Thu Oct 26 2017](https://github.com/18F/openFEC-web-app/issues/2321#issuecomment-339696155)

**Clarification:**

This issue is specifically about the text that introduces the "Download bulk data" tab on the Advanced data section. It is a content design task which might start with gathering input from data & press folks. 

<img width="1044" alt="screen shot 2017-10-26 at 11 00 27 am" src="https://user-images.githubusercontent.com/11636908/32060554-0d0a0abc-ba3d-11e7-885c-514a509b89f6.png">

Developing the individual descriptions for each data set will be a separate task that @PaulClark2 is making an issue for. 

---

@jenniferthibault commented on [Fri Oct 27 2017](https://github.com/18F/openFEC-web-app/issues/2321#issuecomment-340015702)

And some extra background on the difference between the data available for download as .CSVs in the other sections, and the data collected for download in this bulk data section:

In https://github.com/18F/openFEC-web-app/issues/2318 we were figuring out how the data on the classic site mapped to the architecture of the new site. 

It's important to know that this was about integrating two types of data:
- Data from the data catalog (which are .CSV files that most users of diverse skill levels could use if they wanted)
- Data from the former FTP site (which is huge and used mainly by expert level data-heavy folks who are setting up their own databases)

Originally we wanted to integrate all of it into the existing sections, as seen in this [InVision prototype](https://gsa.invisionapp.com/share/QCDMN3I3D#/256573032_Advanced-Data_Raising) from the design issue #2265 

Then we realized that the FTP data files don’t split nicely along those lines. For example, there are files that contain receipts _and_ disbursements, so they wanted to have them listed in both Raising and Spending sections. This broke our principle of ~ “Only have content in one place”… so instead of putting the same data set in two places, we moved the FTP downloads into its own “Download bulk data” tab.

We're hoping that the introductory text this issue focuses on can help to communicate the relevant bits of this that are useful to people's understanding of what the data in the tab is and is not.

**Comment by jenniferthibault** [comment]
A light reminder that this issue blocks https://github.com/18F/fec-cms/issues/1396 , which is moving toward completion.

**Comment by PaulClark2** [comment]
Does this work for an introduction to the bulk data section?

`These files contain data from statements and reports filed with the Commission. These files were previously located on the Commission's file transfer protocol (FTP) server and are probably most useful to users wanting to do more in-depth research into campaign finance. Some files contain transaction level data and are large. The update schedule of these files varies from daily to weekly. Expand the file's accordion to read more about each file.`

@AmyKort @jwchumley @dorothyyeager

**Comment by AmyKort** [comment]
Downloadable bulk data files contain data from statements and reports filed with the Commission in a form that may be useful to users performing in-depth campaign finance research. The files, which were previously located on the Commission's file transfer protocol (FTP) server, can be very large because they contain transaction-level data. The update schedule of these files varies from daily to weekly. Expand each file's accordion to read more about what is contained in the file.

**Comment by AmyKort** [comment]
Is this ready to close?
