### ISSUE TITLE
Investigate slow queries

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1534]
@AmyKort commented on [Tue Nov 28 2017](https://github.com/18F/openFEC-web-app/issues/2343)

We experienced API outages on 11/15/17, and undertook a series of mitigation steps. https://github.com/18F/openFEC/issues/2756

One outstanding issue is to investigate slow queries, which we'll be undertaking now.

---

@AmyKort commented on [Tue Nov 28 2017](https://github.com/18F/openFEC-web-app/issues/2343#issuecomment-347658601)

@patphongs  Could you tack on the post-mortem doc? Thanks!

---

@patphongs commented on [Tue Nov 28 2017](https://github.com/18F/openFEC-web-app/issues/2343#issuecomment-347667934)

Post mortem document started by @LindsayYoung is [here](https://docs.google.com/document/d/1tizrfTK0o7j2CrptDvXX_7MqopL7LoSlt3sy2gsDj1A/edit#) :lock:

**Comment by vrajmohan** [comment]
Added logging of queries that take longer than 1s to execute on all the RDS databases using the AWS console. Also created a PR https://github.com/18F/fec-infrastructure/pull/40 to make this logging permanent.

Used [aws cli](https://aws.amazon.com/cli/) to download the logs from AWS using commands of the form:
```
aws rds download-db-log-file-portion --db-instance-identifier fec-govcloud-prod-replica-2 --log-file-name "error/postgresql.log.2017-12-04-01" --output text > postgresql.log.2017-12-04-01.log
```

Analyzed the downloaded logs for a 10 hour period on 2017-12-04 using [pgBadger](http://dalibo.github.io/pgbadger/) . `pgBadger` can be installed on `OS X` using `Homebrew`.
The command to analyze the logs (as RDS appears to use a custom log) is:
```
pgbadger --prefix '%t:%r:%u@%d:[%p]:' *.log
```
This yielded a nice HTML report that is easy to analyze. Attaching a sample: [out.html.gz](https://github.com/18F/fec-cms/files/1536376/out.html.gz)

**Comment by vrajmohan** [comment]
The next step is to analyze the slow queries.

**Comment by vrajmohan** [comment]
Tagging @ccostino, @LindsayYoung and @patphongs to see attached pgBadger report ^^^.

**Comment by ccostino** [comment]
Thank you so much, @vrajmohan!  Will take a look very soon!

**Comment by vrajmohan** [comment]
Created a wiki page - https://github.com/18F/openFEC/wiki/Analyzing-slow-queries
