### ISSUE TITLE
Missing 24/48 hour from schedule E

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1536]
@jwchumley commented on [Wed May 31 2017](https://github.com/18F/openFEC-web-app/issues/2094)

https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00053553&is_notice=true&min_date=01%2F01%2F2017&max_date=05%2F31%2F2017

This should show 35 transactions but it isn't showing any. It also doesn't show any for 2016 where there should be many more.

The transactions are in the underlying tables:
select * from disclosure.nml_sched_e
where link_id in (
select sub_id from  disclosure.nml_form_24
where rpt_yr=2017
and cmte_id in ('C00053553')
)

Is the 24/48 hour toggle not including transactions related to form_24?

---

**Completion criteria**
- [ ] Add the missing data
- [ ] Double-check that all other sources are included in this endpoint

---

@noahmanger commented on [Tue Jun 13 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-308214128)

Likely related to https://github.com/18F/openFEC/issues/2473

---

@noahmanger commented on [Wed Jun 21 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-310211377)

Re-flagging this @jontours and @LindsayYoung .  Will this be solved by the F5 fix we put in? I'm testing locally against the dev api and the problem is still there.

---

@jontours commented on [Wed Jun 21 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-310214049)

My first instinct was that the F5 PR _wouldn't_ resolve this, but the issue evolved so much that I got a little lost in the discussion.  So, for the endpoint referenced above, no the F5 fix won't solve it.  I think the PR that @ccostino is working on will, though.

---

@noahmanger commented on [Mon Jun 26 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-311083705)

Results are better with those changes, but I'm seeing 23 records vs. the 35 @jwchumley says should be there: https://api-stage.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=true&data_type=processed&committee_id=C00053553&is_notice=true&min_date=01%2F01%2F2017&max_date=05%2F31%2F2017&sort=-expenditure_date&per_page=30

----

Update: I had the wrong parameter in there. With `is_notice=true` there's actually 0 results.

---

@jontours commented on [Mon Jun 26 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-311133474)

Arghhhhh.  Found the problem with this, `expt_dt`, which is the date that `min_date` and `max_date` are filtering here, is null for these filings.  This committee notoriously files bad data.

---

@ccostino commented on [Mon Jun 26 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-311145330)

Oh, d'oh!  There's really no fix for that. 😢 

---

@jontours commented on [Fri Jun 30 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-312374998)

Update on this issue, using @PaulClark2 suggestion we are using dissem_dt when exp_dt is null so as to not filter out records that should be there.  For the query up above this creates some inconsistencies, namely there are only 23 records and not 35.  This can be understood by looking at this query ```select dissem_dt from ofec_sched_e where rpt_yr = 2017 and cmte_id = 'C00053553' and is_notice = true order by exp_dt asc; ```

`dissem_dt` has some dates that are outside of the filter range for the query, 12 to be exact:

```
      dissem_dt      
---------------------
 2016-02-29 00:00:00
 2016-02-29 00:00:00
 2016-02-29 00:00:00
 2016-02-29 00:00:00
 2016-08-21 00:00:00
 2016-08-21 00:00:00
 2016-08-21 00:00:00
 2016-08-21 00:00:00
 2016-08-21 00:00:00
 2017-04-05 00:00:00
 2017-04-05 00:00:00
 2017-04-05 00:00:00
 2017-04-05 00:00:00
 2017-04-06 00:00:00
 2017-04-11 00:00:00
 2017-04-11 00:00:00
 2017-04-11 00:00:00
 2017-04-11 00:00:00
 2017-04-19 00:00:00
 2017-04-19 00:00:00
 2017-04-19 00:00:00
 2017-04-19 00:00:00
 2017-04-19 00:00:00
 2017-04-19 00:00:00
 2017-04-27 00:00:00
 2017-04-27 00:00:00
 2017-05-19 00:00:00
 2017-05-19 00:00:00
 2017-05-22 00:00:00
 2017-05-25 00:00:00
 2017-05-25 00:00:00
 2017-05-30 00:00:00
 2017-06-14 00:00:00
 2017-06-14 00:00:00
 2017-06-15 00:00:00
```
Is this ok?  This is some messy data.

cc @jwchumley @PaulClark2 

---

@AmyKort commented on [Thu Nov 30 2017](https://github.com/18F/openFEC-web-app/issues/2094#issuecomment-348230049)

Moving to CMS repo

**Comment by AmyKort** [comment]
@PaulClark2 and @jwchumley  What are the next steps for this?

**Comment by AmyKort** [comment]
Can we close this?

**Comment by ccostino** [comment]
I think we can, @LindsayYoung and I were just talking about this - schedule E data now just gets rebuilt every night (note that we have [an issue](https://github.com/18F/openFEC/issues/2813) in place to make sure it still gets rebuilt with the recent DB migration work), so nothing should be missing anymore.  If we've not been receiving reports or seeing missing data, then I'd say this has been resolved.
