### ISSUE TITLE
minify assets

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1558]
@LindsayYoung commented on [Fri May 12 2017](https://github.com/18F/openFEC-web-app/issues/2037)

---

@noahmanger commented on [Mon May 22 2017](https://github.com/18F/openFEC-web-app/issues/2037#issuecomment-303188233)

All the code is in place for this to work correctly, but it seems that the `prod` environment is not being [picked up here](https://github.com/18F/openFEC-web-app/blob/develop/gulpfile.js#L25).

@xtine can you look into this?

---

@noahmanger commented on [Tue May 23 2017](https://github.com/18F/openFEC-web-app/issues/2037#issuecomment-303559410)

Does this variable need to be set for Travis specifically?

---

@ccostino commented on [Thu May 25 2017](https://github.com/18F/openFEC-web-app/issues/2037#issuecomment-303998319)

Oh good question - it is being set here in the [production manifest](https://github.com/18F/openFEC-web-app/blob/develop/manifest_prod.yml#L10), but it's not set anywhere in [`.travis.yml`](https://github.com/18F/openFEC-web-app/blob/develop/.travis.yml).  I imagine it has to be set either in the `env` section toward the top or exported explicitly in the `before_deploy` section (like the `PATH` environment variable is) in order for Travis to know to minify things before deploying. 

---

@noahmanger commented on [Thu May 25 2017](https://github.com/18F/openFEC-web-app/issues/2037#issuecomment-304043132)

Cool. Could you add this so we can take advantage with the next hotfix deploy?

---

@ccostino commented on [Thu May 25 2017](https://github.com/18F/openFEC-web-app/issues/2037#issuecomment-304087116)

Added to your hotfix for the coverage dates, @noahmanger!

One thing though, this will affect all deploys through Travis, so the assets may also be minified in dev.

**Comment by xtine** [comment]
This is no longer a relevant issue.

**Comment by AmyKort** [comment]
Thanks!
