### ISSUE TITLE
Replace "Election cycle" filter label with "Two-year period" language on election summary pages 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1605]
History in https://github.com/18F/fec-cms/issues/1444
____

The phrase "Election cycle" can confuse expert users who expect that to mean the period of time from one general election to another. What we are using here is calendar years. (There is a history to calendar year/other time intervals that I'm not qualified to summarize but is discussed in depth in the issue linked from the top).

To replace this language on election summary pages, we discussed an approach that would relabel the drop-down from "Election cycle" to "Two-year period", since you can only ever view two years of activity at a time by design. Relabeling this let's us state that up front, and there's no complicated logic to adjust it on other templates, since it's the standard presentation. 

**Currently:**
![screen shot 2017-12-01 at 11 36 21 am](https://user-images.githubusercontent.com/11636908/33492737-02ee03ba-d68c-11e7-97f4-23b120f1b3e2.png)

**Proposed:**
![screen shot 2017-12-01 at 11 36 27 am](https://user-images.githubusercontent.com/11636908/33492738-02fcf852-d68c-11e7-8da6-9060788ed334.png)

**Known pages templates where this change needs to populate:**
House election summary: https://www.fec.gov/data/elections/house/DC/00/2018/
Senate election summary: https://www.fec.gov/data/elections/senate/CA/2018/
Presidential election summary: https://www.fec.gov/data/elections/president/2016/
Committee profile: https://www.fec.gov/data/committee/C00574145/?cycle=2016

- [x] Research the `election_cycle_select` template to see which pages this change would impact
- [x] Identity any logic or template changes
- [x] Make the necessary changes
- [ ] Once the work is reviewed and ready, we decided it makes sense to check in on merging toward staging to make sure it's in sync with design work needed in issue #1613 (originated in #1444) or if it can move forward independently.

**Comment by cptechiegal** [comment]
The  election_cycle_select template impacts the following web system features / web pages:
a) elections/candidate-comparison-tab template
Navigate to:Compare Candidates For This Office webpage
   section-1 Feature: Candidate Financials Totals
   webpage title: Compare candidate financial totals
examples:
- House election summary:
 https://www.fec.gov/data/elections/house/DC/00/2018/
AKA https://www.fec.gov/data/elections/house/DC/00/2018/?tab=totals
- Senate election summary:
 https://www.fec.gov/data/elections/senate/CA/2018/
AKA https://www.fec.gov/data/elections/senate/CA/2018/?tab=totals
- Presidential election summary: 
https://www.fec.gov/data/elections/president/2016/
AKA https://www.fec.gov/data/elections/president/2016/?tab=totals

b) elections/detailed-comparison-tab template
Navigate to:Compare Candidates For This Office webpage
   section2 Feature: Individual Contributions
   webpage title: Compare individual contributions to candidates
examples:
https://www.fec.gov/data/elections/house/DC/00/2018/?tab=contributions
https://www.fec.gov/data/elections/senate/CA/2018/?tab=contributions
https://www.fec.gov/data/elections/president/2016/?tab=contributions

**Comment by cptechiegal** [comment]
The Committee profile page: https://www.fec.gov/data/committee/C00574145/?cycle=2016
is not using the election_cycle_select component / template.
Instead it is using the committee_cycle_select component / template.
[ ] Additional research for the committee_cycle_select template
Research found that this template change impacts the following web system features / web pages:
a) committee/about-committee
b)committee/between-committees
c) committee/filings
d) committee/financial-summary
e) committee/raising
f) committee/spending

**Comment by cptechiegal** [comment]
There are also Candidate Profile pages that contain the words: Election Cycle
where other pages would just display: Election
(These pages use the candidate_cycle_select template)

Changes to this candidate_cycle_select template will impact the following kinds of subpages:
a) candidate/raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=raising
b)candidate/spending
https://www.fec.gov/data/candidate/S2MA00170/?tab=spending

Is a change be needed to these pages for the wording (for this template)?
If yes, it may make sense to create it as a different issue since it is a different kind of component.

**Comment by jenniferthibault** [comment]
@cptechiegal I'm not immediately sure where "Committee to committee disbursements" renders on the site either, but I can try to find out.

The change to the "Election cycle" label is the other half of what we were discussing back in #1444 , which was split out from that issue to consider design improvements to the interaction (that might thus improve the language) in #1613 . We will definitely make the separate implementation issue for that label when ready out of 1613 👍

**Comment by jenniferthibault** [comment]
`Between committees` used to be a tab under the Committee profile pages, but since the data was self-reported it introduced weirdness that made it seem like it was not accurate enough to display ( https://github.com/18F/openFEC-web-app/issues/1448 )

In https://github.com/18F/openFEC-web-app/issues/1819 and https://github.com/18F/openFEC-web-app/issues/2019 it looks like that information was gathered under the `Spending` tab to make consistent models across the site, and reconfigured into `Disbursement transactions`, so we no longer use or need the .jinja template. I'll file that as a new issue. Good find!

**Comment by cptechiegal** [comment]
Made a change to the candidate_cycle_select macro to only change the filter text from: Election Cycle to: Election.  If further changes to this Candidate Profile subpages are needed, see separate issue --> https://app.zenhub.com/workspace/o/18f/fec-cms/issues/1647
