### ISSUE TITLE
Mass 3 and Washington 8 not showing up on map

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1615]
Mass district 3 isn't showing up on the zip code map at https://www.fec.gov/data/elections/?cycle=2018&state=MA&district=3 . It's also not listed among the Mass districts. Users report that it did appear at one point. The same is true for Washington 8. We need to restore that functionality and ensure that we're not missing any other districts.

**Comment by PaulClark2** [comment]
closed in favor of https://github.com/18F/openFEC/issues/2844
