### ISSUE TITLE
Glossary updates and maintenance for next release

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1633]
With all the terms people have suggested now in the glossary after the December 6 release, it's time for some updating and maintenance. This issue is to ensure the new terms are coded into the Help for Committees pages and also to doublecheck that what's in there now is typo- and error-free.

Completion criteria:
- [x] Code the new terms that were added in #1394 (there aren't many).
- [x] Do a thorough proofreading and link-check on the current glossary.
- [x] Document how the glossary is updated (for any future updates), including a second pair of eyes to proofread, how to suggest new terms, and where the documents used for it are stored.

**Comment by dorothyyeager** [comment]
For @jwchumley @llienfec  - thank you for offering to help proof the glossary. Mainly it just really needs a second pair of eyes beyond mine to check for typos and to ensure the links work and go to the correct regulation.

The easiest way is probably to go through the glossary on the home page and check each one. Alternatively, I can share a spreadsheet with you that we use to populate the glossary (but that might be harder to check links with). Let me know if you'd like me to send that.

If you find anything, just let me know. I'll start a sheet of fixes for the next release and add it.

**Comment by dorothyyeager** [comment]
I've begun working on a google doc to document how the glossary is maintained. It can be found here: 

https://docs.google.com/document/d/1u1ksIbb44JgbquwcYXpJz9he8lz5fyhYAmwpA129f34/edit?usp=sharing

**Comment by dorothyyeager** [comment]
Glossary coding for the new terms has been completed. I'll be updating the new SSF pages with glossary coding as they are created, so that will be folded into #1482

**Comment by rhoughfec** [comment]
@dorothyyeager I reviewed the glossary and sent you an email with a couple little edits. Otherwise it looked good to me!

**Comment by dorothyyeager** [comment]
@lbeaufort is the pull request whisperer and with the addition of one missing term and fixing some minor typos and tweaks suggested by @rhoughfec, we are able to go ahead and close this issue.
