### ISSUE TITLE
Create a feature workspace so new concepts can be tested away from the release cadence

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1640]
Designers and researchers need to be able to prototype new/improved concepts in code in an environment that's separate from the release pipeline environments, `dev` and `staging`. Currently, our only option is to run a local instance of the site or to deploy testing features to `dev`, which has resulted in features prematurely being merged into a release, or merged without thorough review. 

Access to a `feature` space on the `fec-cms` repo will: 
- Allow us to better simulate complex interactions with real data
- Create a publicly shareable URL that doesn't require researchers (or users) to run the site locally in order to conduct usability tests. 
- Prevent sudden blockers to release schedules because a feature being tested in `dev`tests poorly. requires further design changes based on testing, or isn't otherwise fully release-ready. 

**Completion criteria:**

- [x] Credentials are added to cloud.gov for `fec-cms`  
- [x] Make a CMS database
- [x] Import latest CMS data into database
- [x] Push the CMS app (via Lindsay "We wouldn't add API, celery worker celery beat, eregs or proxy to it")
- [x] Hook up the `FEC_API_URL` to dev
- [x] Create S3 bucket to store wagtail uploaded files and images
- [x] Add instructions to README on creating, maintaining, and using a feature space
- [x] GitHub branches can be directed toward the new feature space :ta-da:

**Comment by jenniferthibault** [comment]
It's perhaps helpful to know that this is a capability we used to have, but I'm not sure why it went away. Could be something to do with merging all of the github repositories?

**Comment by ccostino** [comment]
It largely went away due to resource constraints in our cloud.gov org account, and having to manually deploy to keep it up to date.  As long as we have the resources (and I believe we do), this shouldn't be difficult to setup now.  We might still need to do the manual deployments for the time being but we could try and tie-in some workflows with CircleCI for automated ones as well in the future I imagine. :-)

**Comment by ccostino** [comment]
This is mostly ready to go!  The last thing I'm unsure about is wiring up the S3 bucket for this space.  I did create a new one and bound it to the app, but I just need to double check what else is needed to use it.

The only other thing left is getting some instructions written up.

**Comment by ccostino** [comment]
All set and ready for review!

**Comment by ccostino** [comment]
**NOTE:**  There is no automated deployer setup with the `feature` space, and for now that's intentional; you can only manually deploy to it.  If we want to support automated deploys to it, I think that should be a separate issue and work.

**Comment by ccostino** [comment]
Looks like we're all set with this, including automatic deploys!  Are we good to close, @LindsayYoung and @patphongs?

**Comment by patphongs** [comment]
@ccostino I would say so, the feature space is working out very nicely! This is huge for us, especially for UX and design to be able to test out new things. Thank you for getting this done!

**Comment by ccostino** [comment]
Excellent, I'm glad this is helping out! :-)
