### ISSUE TITLE
404 error for some AL senate special candidates

### ISSUE THREAD

**Issue by lbeaufort** [18F/fec-cms#1642]
I got a 404 error, and incorrect cycles for an AL senate candidate. Check all AL senate candidates to make sure they have the correct election cycle dropdowns.

found this 404 error: https://www.fec.gov/data/candidate/S8AL00308/?cycle=2017&election_full=true

Steps to reproduce: Click on candidate page https://www.fec.gov/data/candidate/S0AL00156/ and choose "2017." 

- [x] Should redirect to 2018 cycle

**Comment by cptechiegal** [comment]
Similar issue that doesn't show correct Election years list but not giving a 404 not found error"
https://app.zenhub.com/workspace/o/18f/openfec/issues/2811

**Comment by lbeaufort** [comment]
404's no longer appearing for these candidates - likely resolved by API changes.

cc: @patphongs @PaulClark2 @AmyKort 

![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/9bdbf5a0-3398-4b19-936d-23a95b3e23e1)

![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/58b77799-a38c-4aad-b8ec-9f4d922ad8ea)
