### ISSUE TITLE
Make sure odd-numbered special election years work correctly on candidate's "election" drop down

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1644]
To make make the election year (election period) more clear to users, we should include both the odd and even year in the drop down option's text. 

Our data is generally aggregated by two-year periods, a candidate running for election in 2017 would still show 2017-2018 data. ( for example, https://www.fec.gov/data/candidate/S0AL00156/?cycle=2002&election_full=false )

Completion criteria:
- [x] display 2018 in Election pull down menu instead of 2017 (odd year)
    fix odd year inclusion in drop-downs as even year
- [x] display 2017-2018 in Time Period
- [ ]  add text explaining what's included in the election years
i.e., special elections (2017)
- [ ] Determine what text to display and where on the screen - design / user research subtask#https://github.com/18F/fec-cms/issues/1732

![image](https://user-images.githubusercontent.com/13237823/33907628-c2fec78c-df53-11e7-9293-8f590e786726.png)

Related Issues:
- Issue 1642 / PR https://github.com/18F/fec-cms/pull/1677
-  Related to https://github.com/18F/openFEC/issues/2845
- Related issue issue# https://github.com/18F/fec-cms/issues/1647
 The Raising page has the election year: 2018 but should probably display as 2 year periods instead
(note: this data is from cycles data)

**Comment by lbeaufort** [comment]
@PaulClark2 here's the WIP PR to pass only even years: https://github.com/18F/fec-cms/pull/1677

**Comment by PaulClark2** [comment]
We might be able to borrow text from the statistical releases. They include language that explicitly explains we include special elections in our financial summary data. See the last sentence of paragraphs three and four of Section II. Congressional candidates, https://www.fec.gov/updates/statistical-summary-six-month-campaign-activity-2017-2018-election-cycle/.

We might use something a little more generic, like this, "These totals include financial activity for the special elections."

@AmyKort

**Comment by cptechiegal** [comment]
Senate Candidate Doug Jones 
 https://www.fec.gov/data/candidate/S0AL00156
Seems to be correct now in Prod since Elections pulldown option is showing correctly as 2018 (had been incorrect as 2017 in the past)


Senate Candidate Karen Handel
https://www.fec.gov/data/candidate/H8GA06286
Elections pulldown options is showing incorrectly as 2017 (should be 2018 for 2017-2018 period)

**Comment by cptechiegal** [comment]
Also, need clarification on the following:
1) where to display on the webpage the text explaining what's included and 
2) the final text to display

**Comment by patphongs** [comment]
> We might be able to borrow text from the statistical releases. They include language that explicitly explains we include special elections in our financial summary data. See the last sentence of paragraphs three and four of Section II. Congressional candidates, https://www.fec.gov/updates/statistical-summary-six-month-campaign-activity-2017-2018-election-cycle/.
> 
> We might use something a little more generic, like this, "These totals include financial activity of special elections."
> 
> @AmyKort

@JonellaCulmer there appears to be a design task here for one of the completion criterion for this ticket. Product owners have requested the ability to `add text explaining what's included in the election years i.e., special elections (2017)`. Is there an existing design pattern you think we can use for this? cc @PaulClark2 @AmyKort @cptechiegal

**Comment by jwchumley** [comment]
Paul and I are both OK with implementing the code as it is in the current PR. Even numbered years in the pull down include off year elections in the data. If we want to circle back later and improve it that's OK but it's currently broken in production and this makes the data available.

**Comment by patphongs** [comment]
> add text explaining what's included in the election years
> i.e., special elections (2017)
>  Determine what text to display and where on the screen - design / user research subtask##1732

These 2 completion criteria have been moved over to issue #1732. The rest of this ticket is now complete with PR https://github.com/18F/fec-cms/pull/1708. Closing.
