### ISSUE TITLE
Update  Help 'Term' and No Data pages that use the term 'Cycle'

### ISSUE THREAD

**Issue by cptechiegal** [18F/fec-cms#1646]
The current website design has references to the term 'Election Cycle' which is now changing to ensure terminology correctness and consistency (see issue 1444 for more background).  
To that end, many web pages are being updated with changes as follows:
- Change of Election filters from 'Election Cycle' to  'Election' 
- Election Time Periods from 'Full Cycle' to 'All Years'

Additionally, Help pages need to be reviewed and advised on the terms to be updated as well.
The following front end files contain the term: Election Cycle

1.  Terms in fec-cms/fec/fec/static/js/data/terms.json

- "term": "Election cycle",
 "definition": "The period beginning the day after the previous general election for a given federal office and ending on the date of the general election for that office. The number of years in an election cycle differs according to the federal office sought. The election cycle spans two years for House candidates; four years for presidential candidates; and six years for Senate candidates. See 11 CFR <a href=\"https://www.fec.gov/regulations/100-3/CURRENT#100-3-b\">100.3(b)</a>."

-  "term": "Personal funds of a candidate",
  "definition": "The personal funds of a candidate include: <ol><li>Assets which the candidate has a legal right of access to or control over, and which he or she has legal title to or an equitable interest in, at the time of candidacy;</li><li>Income from employment;</li><li>Dividends and interest from, and proceeds from sale or liquidation of, stocks and other investments;</li><li>Income from trusts, if established before the election cycle;</li><li>Income from trusts established by bequests (even after candidacy)</li><li>Bequests to the candidate;</li><li>Personal gifts that had been customarily received by the candidate prior to the beginning of the election cycle; and</li><li>Proceeds from lotteries and similar games of chance.</li></ol> 11 CFR <a href=\"https://www.fec.gov/regulations/100-33/CURRENT#100-33\">100.33(a) and (b)</a>."

2.  No Data message in fec-cms/fec/fec/static/js/templates/tables/noData.hbs

- div class="message message--info"
  A filing deadline has passed, but the FEC hasn’t finished processing the financial data</li>
  To find the most recent activity for this candidate or committee, try changing the election cycle.

3.  Description for  Data tables that summarize campaign financial activity by filer type, election cycle and reporting period
in fec-cms/fec/data/templates/advanced.jinja:
- div class="content__section"
Detailed data files
Historical statistics
Here you will find the committees, candidates and linkages, itemized records, contributions to candidates, individual contributions and cperating expenditures files.
These files contain committee, candidate and campaign finance data for the current election cycle and for election cycles through 1980. The files for the current election cycle plus the two most recent election cycles are regularly updated. The committees, candidates and linkages files are updated daily. The itemized records, contributions to candidates, individual contributions and operating expenditures files are udated weekly on Sunday. Please note that complete entry from each reporting period takes about 30 days. It is important to be careful when making conclusions from these data because some information may not have completed the entry process when these files where create. Committees do not have the same filing requirements. You should be careful when comparing financial information about committees with different filing requirements.

Completion Criteria:
- [x] Review these descriptions to determine if updated terminology is needed
 if yes, determine replacement terminology for 'cycle' in these term descriptions and no data warnings
- [x] Research where these terms and no data warning pages are displayed (navigation steps)
- [x] Consider adding terms for FEC reporting by 'Election Period' instead of 'Election Cycle'

**Comment by rhoughfec** [comment]
Thanks for catching these Cristl. For items on the Help for Candidates & Committees pages, the terminology is correct as is when it references election cycle. These definitions are often pulling from the actual statute, regs, or previously approved Commission language. Anything on the H4CC pages & legal resources is regularly updated and reviewed to reflect changes in laws or FEC practice by Info & RAD so you shouldn't need to worry about any content there. Thanks again! FYI - @AmyKort

**Comment by AmyKort** [comment]
Just a plus 1 to what @rhoughfec said. We only need to address the "cycle" language in the very narrow instances in the data section where the data reported is January to January. References in Help for candidates and committees, Legal resources and elsewhere are correct. Thanks!
