### ISSUE TITLE
Sticky Menu Offset Issue

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#165]
The sticky menus inside of the registration and reporting section is offset in particular instances. When you try to click on the previous menu item, it will set the is-active state on the one above, and not on the one that was clicked

![sticky-nav-bug](https://cloud.githubusercontent.com/assets/12799132/11848491/b77afc14-a3f0-11e5-88bf-522ad091feca.gif)

**Comment by noahmanger** [comment]
This issue is captured in https://github.com/18F/fec-cms/issues/244 so I'm closing.
