### ISSUE TITLE
Historical data page displaying oddly

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1651]
The Historical data page (https://transition.fec.gov/press/campaign_finance_statistics.shtml ) contains year-by-year links to press releases, but there are several screens of white space showing up between the introductory paragraph and the links themselves, which might make it hard for users to find the links.

**Comment by dorothyyeager** [comment]
I think I have fixed this or at least fixed the one issue. There was actually a lot of data in those blank lines, but also a piece of code that looked like it was in the wrong place. I moved the code to its own line and now the missing data is appearing.

**Comment by johnnyporkchops** [comment]
Is this page broken now. Clicking on the expandable  areas (+) does nothing. @dorothyyeager --should I look at the JS to see whats going on?

**Comment by johnnyporkchops** [comment]
I did not clear the cache, so I saw the old page. But I think it still might be messed up (?)

**Comment by AmyKort** [comment]
Awesome! Thank you!

**Comment by dorothyyeager** [comment]
@johnnyporkchops Hi John - yes, that's the part I thought was weird - Can't get the top part (which didn't show up before but now does) to collapse and can't get the part under "Election Cycle" to expand.

**Comment by AmyKort** [comment]
Oh--sorry @johnnyporkchops . I think our comments passed one another.

**Comment by johnnyporkchops** [comment]
So, It looks like we are just leaving everything expanded because we could not get the old expandable content to work in the transition site, is that correct?

**Comment by AmyKort** [comment]
Would we be better off trying to move this page's content into the CMS, rather than trying to fix it on transition?

**Comment by dorothyyeager** [comment]
@johnnyporkchops I haven't worked with this particular page before but that makes sense. I am not sure how to do that myself, to be honest. I just noticed the section that was showing had its line saying "start this ..." on its own line but the section that wasn't showing didn't have that line by itself. So that's all I moved.

@AmyKort I sort of wondered about that but not sure how much work that would involve. The page has a lot of javascript now and I'm not very familiar with how to do that or if we'd want to do it a different way on the CMS.

**Comment by dorothyyeager** [comment]
The content that wasn't displayed before is displayed now, so the immediate problem has been solved. @johnnyporkchops when he has time may want to look at the javascript to see why we can't make it work properly; I haven't been able to figure that out. But at least at this point, people are able to access the data. This is the Press Office's content and seems like moving it on to the CMS, while it would solve the issue of javascript vs. the transition site, would involve a redesign process that they should be involved in.

**Comment by dorothyyeager** [comment]
Just had a chance to chat with @johnnyporkchops and he's in agreement that with the immediate problem of the data not showing resolved, we can go ahead and close this issue. We can open a new issue if a redesign or new page is desired.
