### ISSUE TITLE
Change references to Chair and Vice Chair for 2018

### ISSUE THREAD

**Issue by rhoughfec** [18F/fec-cms#1665]
As of January 1, the Chair of the Commission is Caroline Hunter and the Vice Chair is Ellen Weintraub. We will need to ensure that we update all references on the website accordingly. This is a start of a list of places we'll need to adjust:

**Static page** Addressed by https://github.com/18F/fec-cms/pull/1682
- [x] Homepage - Chair and Vice Chair photos and links to bio pages need to be adjusted (Chair, Vice Chair, then alphabetical) 

**Wagtail changes**
- [x] Leadership & structure page
- [x] Bio pages (Hunter, Weintraub, & Walther). Their title is under their photo on the bio page 
- [x] Make sure Chairman is changed to Chair

**Comment by AmyKort** [comment]
Let's try to get this into the January 3 deployment.

**Comment by rhoughfec** [comment]
tagging @dorothyyeager and @lbeaufort who both volunteered to help if needed. Thank you!

**Comment by patphongs** [comment]
This should be relatively easy to do. Commissioner's Titles can be updated right on their profile page, and updating their bios can be done there as well.

**Comment by patphongs** [comment]
PR has been made for the update to the Commissioner's on the homepage: https://github.com/18F/fec-cms/pull/1682 The rest of the pages can just be updated by changing the Commissioner Title in their profile pages.

**Comment by dorothyyeager** [comment]
Wagtail pages updated and Chairman is now Chair. https://www.fec.gov/about/leadership-and-structure/.
