### ISSUE TITLE
Identify References to FEC Headquarters address

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1667]
When the FEC moves its headquarters next year, we'll want to change the references to our address on the website. This issue represents the first step in that effort, which is to identify all of the places where we'll need to make the change. Let's create a spreadsheet that documents the changes we need to make and where they are located (footer, contact us page, paper filing instructions, any references on transition pages, etc.). We can also identify any pdfs that will need to be updated. This work will help us quickly respond when it's time to make these changes on the website.

Completion criteria 
- [x] Create spreadsheet - Created at https://docs.google.com/spreadsheets/d/1xCH8wriV3Vh0eCN-1wIVhtjlltEK-BqDFJOI9nX0gvI/edit?usp=sharing
- [x] Identify pages and PDF files that will need to be updated with the FEC's new address

**Comment by dorothyyeager** [comment]
Here is the Federal Register notice that addresses the address change. (It is not yet on SERS.)

https://www.gpo.gov/fdsys/pkg/FR-2017-12-26/pdf/2017-27683.pdf

**Comment by dorothyyeager** [comment]
Updated URL for  FR notice: http://sers.fec.gov/fosers/showpdf.htm?docid=369302

Researching how we covered our last move in 1985, I found these Record articles and thought I'd share in case they are useful in figuring out where to announce new address:
https://www.fec.gov/resources/record/1985/december1985.pdf (on page 1)
https://www.fec.gov/resources/record/1986/february1986.pdf (new phone numbers, page 1)
https://www.fec.gov/resources/record/1986/april1986.pdf (on page 2)

**Comment by dorothyyeager** [comment]
Just noting pages as I find them while working on the classic redirect issue at #1472 

Contact the IG: https://transition.fec.gov/fecig/contact.shtml

**Comment by dorothyyeager** [comment]
I've started a spreadsheet for this. It's pinned to the content channel in Slack and I'll put the link here: https://docs.google.com/spreadsheets/d/1xCH8wriV3Vh0eCN-1wIVhtjlltEK-BqDFJOI9nX0gvI/edit?usp=sharing

**Comment by LindsayYoung** [comment]
Did a quick search in the code:
No mentions off 999 E Street in openFEC or fec-eregs

Found 2 reults for fec-cms:
https://github.com/18F/fec-cms/search?utf8=%E2%9C%93&q=999+E+Street

https://github.com/18F/fec-cms/blob/459a0f6462a9a1b71ab9f40b52da1414b8f4d1a9/fec/data/templates/layouts/main.jinja

https://github.com/18F/fec-cms/blob/459a0f6462a9a1b71ab9f40b52da1414b8f4d1a9/fec/fec/templates/base.html

**Comment by AmyKort** [comment]
Awesome! Thank you @LindsayYoung !

**Comment by dorothyyeager** [comment]
Thanks @LindsayYoung One heads up on eregs - the Commission did amend one regulation to add the new address into its regulations. The cite affected is 11 CFR 1.2. It's actually in effect now (see Federal Register notice), and will be in the 2018 edition of 11 CFR.

**Comment by dorothyyeager** [comment]
Have gone through both the main site and the transition site and identified many PDFs and pages that will need to have the address updated.

The spreadsheet is at https://docs.google.com/spreadsheets/d/1xCH8wriV3Vh0eCN-1wIVhtjlltEK-BqDFJOI9nX0gvI/edit?usp=sharing

Will update the spreadsheet as work continues on #1472 as working on that issue has yielded both a list of transition pages that need to be retired and uncovered various transition pages with the address that did not turn up when searching for the FEC address in the search function.
