### ISSUE TITLE
Understand all requirements for implementing topic-specific GovDelivery signup form

### ISSUE THREAD

**Issue by jameshupp** [18F/fec-cms#1670]
This builds on #1194. It's distinct from #1669 (now completed), which just implements in the footer. I'm separating these because I think 1669 is a lot more straightforward to implement and close. This one may take testing as it's an actual email submission form, not a button that takes the user elsewhere.

This is a research issue; the implementation issue is #1778.

We want to start with the [Latest Updates](https://www.fec.gov/updates/) page.

Assets:
Here's a mockup, divorced of all microcopy (thus the first item on the checklist).
![usfec_topicmockup](https://user-images.githubusercontent.com/6314097/34270016-b355bfd6-e654-11e7-8995-33a0477f09ee.jpg)

And here's the HTML snippet from GovDelivery:
[USFEC_QSP1.txt](https://github.com/18F/fec-cms/files/1732654/USFEC_QSP1.txt)

- [x] Finalize signup microcopy (James)
- [x] Figure out the best way to manage signup forms in accordions<sup>1</sup>
- [x] Pull together Latest updates category ID and the relevant topic IDs (James)
- [x] Research feasibility of adding the signup accordion based on the topic chosen in the dropdown for updates (John)
- [ ] ~Figure out what the confirmation of success/failure looks like (John)~

<sup>1</sup> This one's a bit of a challenge, since we essentially need to choose between making these editable in Wagtail or forcing content managers to ask a developer every time they want to make changes. I _think_ we want the latter, since these shouldn't be edited very often, and adding new capabilities to Wagtail seems harder. But I just want to be sure there's agreement on this.

**Comment by dorothyyeager** [comment]
From my perspective (being the person who sends these for all Record and policy items) - I would definitely want the ability in Wagtail to do any needed editing and adjustments myself, as much as possible. (Of course, if development of our final product on the technical end necessitates developers later on to make adjustments, then that's that. My overall view is that as much as we can leverage Wagtail to let content people do some lifting, that's what we should do, given how strained our resources are in development.)

Tagging in @gsmaragdis for more Info division thoughts.

**Comment by jameshupp** [comment]
I've just edited down the checklist here and changed the name. I want to keep this as the issue for doing the requirements research, since a lot of the mockups and attachments here will help us understand them. Tagging in @johnnyporkchops, though I'm not going to assign the issue yet, since I think that'll come up during sprint planning.

**Comment by jameshupp** [comment]
The mockup above is from GovDelivery. The concept is about right, but some of the styles are off. [Jen mocked up designs for this](https://github.com/18F/fec-cms/issues/1044#issuecomment-321915091) last year and I'd like to get our styles as close to her version as we can. There may be some issues around success/failure confirmation.

**Comment by jameshupp** [comment]
Given the limits of what we're implementing right now, we're not going to worry about the Wagtail piece. If someone really needs another form at some point, what we've figured out for Latest Updates should make it pretty easy to create a new signup in a template. If lots of signup forms become a line of work, someone can pick up the Wagtail work later.

**Comment by jameshupp** [comment]
Here's the copy for the pieces. This is pulled from the earlier mockups, which I actually think were great. There's one outstanding technical answer that might mean we don't need the links to GovDelivery or the success/failure messages, but I included them here just in case.

- Title: Get email updates
- Intro: 
- Field name: EMAIL
- Signup button: Subscribe
- Links to GD’s domain - this is tentative, depending on interaction
  - Edit: [Edit an existing subscription](https://public.govdelivery.com/accounts/USFEC/subscriber/topics?qsp=CODE_RED)
  - Privacy: [Privacy policy](https://insights.govdelivery.com/Communications/Subscriber_Help_Center/GovDelivery_Privacy_Policy)
- Interaction messages (success/failure) - this is tentative, depending on interaction
  - Success
    Success!
    You will now receive [topic] updates by mail.
  - Failure
    Subscription failed
    That didn’t work, try again.

**Comment by jameshupp** [comment]
Turns out we're not going to complete the signup on FEC.gov. There are long term questions about whether the category and topic structure is right that are much easier to manage if we leave all that to be managed on the GovDelivery domain. So I am replacing the code snippet linked above with a different but similar one.

So what we no longer need:
- the text links to GD's domain
- the privacy policy from GD

The conditional accordion and the actual email submission form and field are both still relevant.

The flow is:
1. User selects which _Latest updates_ list they want to see.
2. User opens email signup accordion.
3. User inputs email address and clicks "Submit".
4. Clicking takes user to the relevant page on the GovDelivery domain (an example is in the new code snippet), which I believe has the user already subscribed to the relevant topic.

**Comment by jameshupp** [comment]
Relevant topic IDs:

FEC Record: USFEC_111
Latest releases: USFEC_1
Tips: USFEC_16
Weekly digest: USFEC_39

I will track down the category-wide quick subscribe page.

**Comment by AmyKort** [comment]
Is this work complete?

**Comment by jameshupp** [comment]
@johnnyporkchops I think we can call this closed, can't we? And move on to #1778? I certainly don't think it's blocking 1778 anymore, so I'm inclined to say it's closed.
