### ISSUE TITLE
C9 committeess (Form 5 filers) regular reports are showing up with the 24 and 48 hour reports

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1691]
Form 5 filers (Committee ID starts with "C9" file both regularly filed reports (Quarterlies, Year Ends, etc) and 24 and 48 hour reports. On their profile pages under "Filings" only RFAIs show up in the "Regularly filed reports" section.  The quarterlies appear below that in the 24 and 48 hour reports section. They need to be moved to the Regularly filed reports section.

**It looks like this section is set up properly for PACs ("C00" F3X/F24 filers) but not non-committee filers ("C9" F5/F24 filers).**

Example: https://www.fec.gov/data/committee/C90013301/?cycle=2016&tab=filings

API Call for "Regularly filed reports": https://api.open.fec.gov/v1/committee/C90013301/filings/?api_key=DEMO_KEY&sort_hide_null=true&sort=-coverage_end_date&sort=report_type_full&sort=-beginning_image_number&per_page=100&page=1&form_type=F3&form_type=F3X&form_type=F3P&form_type=F3L&form_type=F4&form_type=F7&form_type=F13&form_type=RFAI&cycle=2016

API Call for "24- and 48-hour reports" (note F5's appear here) :https://api.open.fec.gov/v1/committee/C90013301/filings/?api_key=DEMO_KEY&sort_hide_null=true&sort=-receipt_date&per_page=100&page=1&form_type=F5&form_type=F24&form_type=F6&form_type=F9&form_type=F10&form_type=F11&cycle=2016

I believe all that's needed is to move F5's up to the  "Regularly filed reports" section and remove it from the "24- and 48-hour reports". @jwchumley @PaulClark2 am I understanding the business logic properly?

**Comment by lbeaufort** [comment]
Addressed by https://github.com/18F/fec-cms/pull/1818, merged
