### ISSUE TITLE
On the Committee Page, Receipts Tab, clicking on a state doesn't filter receipts table

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#17]
When looking at state by state breakdown of spending, the numbers are hyperlinked to the full receipts table. However, clicking a state does not fire the filter for that state. 

URL: https://fec-dev-web.18f.gov/committee/C00580100?tab=receipts 
to URL: https://fec-dev-web.18f.gov/receipts?committee_id=C00580100&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016

![clicking on a number doesn t load state filter](https://cloud.githubusercontent.com/assets/474916/9420346/9fbb1ee8-4832-11e5-9732-566eea81fa15.gif)

**Comment by jmcarp** [comment]
The aggregate links in the state table now include the correct state, and further filtering by state seems to work as expected. @onezerojeremy would you mind taking another look and letting me know if there's more to fix here?

**Comment by onezerojeremy** [comment]
works great! Love it! 

I spotted a couple other little :bug:s around this page but they aren't related, so I'll file them separately.
