### ISSUE TITLE
Implement Alert Homepage Banner

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1717]
**What we're after:** Following the government shutdown, we received feedback that the banner announcing the agency's closure could not be seen. We have designed a new alert banner for situations in which greater prominence/attention is required. This issue will implement the design created in issue #1714. 

**Design:**
![screen shot 2018-01-24 at 8 23 23 am](https://user-images.githubusercontent.com/31663028/35341453-c1e29812-00f3-11e8-8b57-bd909d6c37ea.png)
Announcement copy: title (bold), announcement (regular), 18pt, gandhi serif
Link copy: 14pt, karla regular

**Completion criteria:**
- [ ] Refine front-end (as seen in [prototype](https://user-images.githubusercontent.com/31663028/35339834-9d7cb4d4-00ef-11e8-82e8-4e4d943a1f7b.gif)) based on design (above)
- [ ] Incorporate logic to ensure this prominent banner remains at the top, in the event multiple banners are in use
- [ ] Finalize prior to February 8, 2018

**Comment by jenniferthibault** [comment]
@johnnyporkchops could you post a screenshot of the wagtail interface for this? I saw an initial screenshot in #1714 , but not sure if that's still accurate. I'd like to make sure that the wagtail interface is adequately informative of what this feature is, and when (not) to use it.

**Comment by jenniferthibault** [comment]
Oh gosh, @johnnyporkchops I'm sorry, I thought this was the PR... I now see that's in #1719 where there is a screenshot of wagtail. I'll head over there!
