### ISSUE TITLE
Bad IE link on committee summary page

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1720]
**What we are after**:
We need to provide users the correct link to IEs from committee summary pages.

**Current state**:
The link from committee summary pages to IEs 404s. The link is incorrect. 

Incorrect link (NOTE: missing `/data/`)
https://www.fec.gov/independent_expenditures/?committee_id=C00495861&two_year_transaction_period=2018&cycle=2018

Correct link (NOTE: `/data/`
https://www.fec.gov/data/independent-expenditures/?committee_id=C00495861&two_year_transaction_period=2018&cycle=2018

**Completion criteria**:
- [ ] update committee page to provide correct IE link

**Related issues or PRs**:
See https://github.com/18F/FEC/issues/5089

This will need a hotfix.

**Comment by johnnyporkchops** [comment]
In addition to missing `/data`, the `/idependent_expenditure` part of the link should be `independent-expenditure` (dash instead of underscore)

**Comment by jenniferthibault** [comment]
@johnnyporkchops—a similar issue with this bug pattern was just reported in https://github.com/fecgov/FEC/issues/5452 

Flagging that here in case seeing this scenario impacts the approach in the PR you filed

**Comment by AmyKort** [comment]
Merged, so closing. Thanks everybody!
