### ISSUE TITLE
Review and Prioritize Feedback Received from Audit Team

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1724]
We received great feedback from the audit team on the audit search currently in development. You can track that work here: https://github.com/18F/fec-cms/issues/1304

So that we can keep track of the feedback, we have a document of all we have received here: 
https://docs.google.com/document/d/1oOIPdsIMhxfymYo6Scmny5kMseb499jefw8ZinLwQGE/edit#

Some of the work is currently in progress, others need to be discussed and prioritized. 

cc: @jwchumley @patphongs @fec-jli

**Comment by JonellaCulmer** [comment]
I've updated the feedback document to prioritize the recommendations/suggestions received into three categories: `What we can do`, `What we should do later`, and `What we can't do`. 

These categories are mainly to keep us organized and `What we can do` include task to ensure the implementation of a functional and usable audit search. `What we can do later` items are mostly "nice to have's" but are not critical to the successful launch of our audit search. Feedback listed under `What we can't do`, are things that are not supported by the user testing we've completed, run contrary to the rest of the site's design, or will not improve the usability of the search.

Here's the link again: https://docs.google.com/document/d/1oOIPdsIMhxfymYo6Scmny5kMseb499jefw8ZinLwQGE/edit#

cc: @jwchumley @patphongs @fec-jli @johnnyporkchops

**Comment by llienfec** [comment]
@AmyKort asked me to :eyes: the audit priority document ^.  @JonellaCulmer did a great job analyzing the priorities and the items in each category make a lot of sense to me based creating an MVP, ranking longer term work, and only making changes that are supported by the usability testing that we conducted in 2017.

**Comment by AmyKort** [comment]
Thanks, @llienfec and @JonellaCulmer !

**Comment by JonellaCulmer** [comment]
Okay, great! Thanks @llienfec!

**Comment by fec-jli** [comment]
good job Jonella.
1)for "What we can do now" part:
I agree with you. to add into current PR.
I have fixed "audit report result count is always 1000" problem. I will continue to work on others.
John will help to fix CSS issue.

2)for "What we should later" part:
I have done "Party committees into separate section" on my local. compare with classic auditsearch page. I remove useless committees type filters. will deploy to feature space later. 
for other requirements, we can do later.
Thanks

**Comment by JonellaCulmer** [comment]
Thanks, @fec-jli. Since the Party committee move is already in progress I've moved it up to the `What we can do now`. Thanks again for taking a look. 

@johnnyporkchops if you could take a look as well, I would greatly appreciate it.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , re- the "What we can do now" document, I agree that we can do:
-- The top justification of all columns 
-- the sub category indent  on the primary/sub category pair pf inputs

**Comment by johnnyporkchops** [comment]
I have 
- [ ] added the top justification for the  results table 
and I am
- [ ] working on the category/sub-category indentation styles.

**Comment by AmyKort** [comment]
Should we close this ticket and make a new one for the work we'd need to do to add the category/sub-category indentation styles?

**Comment by fec-jli** [comment]
I think we can close this one and John will open new one for adding new css for category/sub-category indentation. Thanks @AmyKort

**Comment by AmyKort** [comment]
Thanks!
