### ISSUE TITLE
Update links on Compliance map pages to point to current H4CC pages

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1725]
Various links on the compliance map pages that explain the related rules need to be redirected or rewritten to point to current pages in H4CC (rather than old retired brochures that are out of date). 

Specifically:
Coordination Periods - related info should link to

https://www.fec.gov/help-candidates-and-committees/making-disbursements/coordinated-communications/

Federal Election Activity Periods should link to (ONLY ON COMPLIANCE MAP). Need to make a separate change to the link on the compliance map for FEA

https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/

Electioneering Communication Periods (related info) should link to

https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/making-electioneering-communications/

Completion criteria 
- [x] Create redirect for electioneering communications and coordinated communications information (Done - see PR https://github.com/18F/fec-proxy/issues/70)
- [x] Update link for FEA related info to point to link above (a redirect would have messed up other redirects on the site, so the link itself needed to be corrected - see discussion in https://github.com/18F/fec-proxy/issues/70)

**Comment by patphongs** [comment]
Proxy just deployed, these redirects are now in place.
