### ISSUE TITLE
Add Extended FECFile Manual to fec.gov

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1733]
User contacted us needing advanced FECFile help.  The information they needed is covered in the "Complete User's Manual" that is not currently on www.fec.gov.  

The link to this doc is also broken on classic.fec.gov: http://efilingapps.fec.gov/fecfiledoc/
![image](https://user-images.githubusercontent.com/22914750/35696896-b37f457c-0756-11e8-8aac-accb55fd1b13.png)

### Small scope of work:
- [x] Find "Complete User's Manual" - reach out to EFO.
~~- [ ] Upload manual in Wagtail.~~ - not needed - it's an external link.
- [x] Find a place to make it public on www.fec.gov, likely on this page: 
https://www.fec.gov/help-candidates-and-committees/filing-reports/fecfile-software/

Adding this as a separate issue because it is affecting our ability to help users and the information is not currently available across any of our sites.  It's related to #1727, #1728, #1729.

**Comment by AmyKort** [comment]
@llienfec @jwchumley @PaulClark2 @dorothyyeager 

Thanks for filing this! Let's see if we can address this quickly.

**Comment by dorothyyeager** [comment]
I can help with uploading the complete manual if they've got it.

I will update that classic spreadsheet to note that the efiling apps link is dead. I tried to add "s" to http to see if that changed it but it's still a dead link.

**Comment by dorothyyeager** [comment]
Just heard from EFO - they are working on making a link active and will forward it when it is available.

**Comment by dorothyyeager** [comment]
The new link is http://efilingapps.fec.gov/fecfiledoc/.

**Comment by AmyKort** [comment]
Awesome! Is this ready to close?

**Comment by dorothyyeager** [comment]
Yes, we can close it now that it's got its new home.
