### ISSUE TITLE
As a researcher/journalist, I want to quickly and easily identify the most recent filings near a filing deadline so that I can feel confident that I'm seeing all there is to see

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1741]
Users looking at election summary pages might not notice that recent eFiling data does not show in processed data. As a first step, we're going to improve the language introducing our Processed and Raw data toggle.

- [ ] Develop new language for Processed
- [ ] Develop new language for Raw

This is a placeholder issue for longer-term design improvements to issues identified in https://github.com/18F/fec-cms/issues/1735#issuecomment-362743038

**Comment by AmyKort** [comment]
cc @llienfec

**Comment by llienfec** [comment]
We are working to improve the descriptive language for the `processed` and `raw` data tabs.  The main goal is to help users understand the differences and trade-offs when looking at/using the two data types.  

### Current drafts:

#### Processed
> **Processed** data has been categorized by the FEC. It may not include the most recently submitted electronic filings. **Raw** data may show more recent filings.

#### Raw
> **Raw** data comes from electronic filings as they are received by the FEC. It does not include paper filings and the data has not been categorized by the FEC. **Processd** data shows data that has been categorized.

**Comment by AmyKort** [comment]
I'm happy with both of these. What do you think, @PaulClark2 and @jwchumley ?

**Comment by PaulClark2** [comment]
The proposed language works for me.

**Comment by AmyKort** [comment]
We've agreed on this language, so I'm closing this ticket. I'll come back and update it with the implementation ticket when I have it.
