### ISSUE TITLE
Implement migration of yearly coordinated party expenditure limits

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1749]
Every year the FEC is responsible for calculating and publishing the annual coordinated party expenditure limits. While published in the Federal Register, the FEC has also had a web page for each year of these limits. (The 2017 page is at https://transition.fec.gov/info/charts_cpe_2017.shtml.) These pages are important for users who need to track spending under these limits.

This issue implements work completed in https://github.com/18F/fec-cms/issues/1197 

Completion of this work is dependent on approval from OGC.

Implementation criteria for putting our new coordinated party expenditure pages into production include:

- [x] Implementing any edits 
- [x] Publish pages.
- [ ] Edit transition quick answer to point to the new page.

**Comment by dorothyyeager** [comment]
OGC has approved the content and given us their edits (minor ones, mainly adding a citations block on one new page). Will make the edits and prepare to post on Monday 2/12 when the 2018 limits are published in the Federal Register.

**Comment by AmyKort** [comment]
Can we close this?

**Comment by dorothyyeager** [comment]
I think so. Will edit transition in just a minute.

Pages:

The limits (and their archive): https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/coordinated-party-expenditure-limits/

Calculating the limits: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/calculating-coordinated-party-expenditure-limits/

**Comment by dorothyyeager** [comment]
And I've updated the quick answers for party committees links to point to the new page on the limits, so we are ready to close. The transition edit should go live within the hour.

**Comment by AmyKort** [comment]
You are the best! Thanks so much @dorothyyeager for making all of this happen!

**Comment by dorothyyeager** [comment]
For reference purposes, users looking for the new coordinated party expenditure limits pages can access them via a link on the party disbursements landing page: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/.

Users can also find the new pages as "read next links" on the page explaining what coordinated party expenditure limits are: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/.
