### ISSUE TITLE
Publish bulk data meta data pages

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1755]
We're migrating the bulk data metadata into Wagtail. Designs are complete and content for these pages has been created and reviewed. ( great discussion at https://github.com/18F/fec-cms/issues/1399 )

We're ready to deploy these pages

- [ ] @PaulClark2 reviews and makes any changes
- [ ] Deploy pages

**Comment by PaulClark2** [comment]
combined with https://github.com/18F/fec-cms/issues/1756
