### ISSUE TITLE
Update CMS (Wagtail) to reflect Commissioner Departure

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1757]
Commissioner Goodman is leaving the Commission, effective February 16. We'll need to make changes to our website to reflect this change in leadership. These changes need to be implemented the morning of February 20.

In the CMS, we'll need to update
- [x]  https://www.fec.gov/about/leadership-and-structure/ to move the Commissioner's page to all Commissioners, change the image to the blank icon and vacant seat pattern, and re-order the images so that both vacant seats appear at the bottom of the list.
- [x] https://www.fec.gov/press/resources-journalists/commissioners/ to remove the Commissioner

**Comment by rhoughfec** [comment]
The wagtail edits have been made:
- instead of "currently serving" now shows term dates of Oct 2013 - Feb 2018. Edits to home page will be made thru regular release scheduled for today.
- Edits to Resources for Journalists made.

**Comment by AmyKort** [comment]
Thanks!
