### ISSUE TITLE
Update Homepage to reflect Commissioner Departure

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1758]
Commissioner Goodman is leaving the Commission, effective February 16. We'll need to make changes to our website to reflect this change in leadership. These changes need to be implemented the morning of February 20. We'll need to deploy the change to the homepage as an expedited deployment

We need to update the list of Commissioners at the bottom of the homepage to show the Commissioner's departure by:

- [x] Make the PR ahead of time and merge into the release branch
- [x] Removing Commissioner Goodman's picture and link
- [x] Adding another Vacant Seat icon/text to the bottom of the list.

**Comment by patphongs** [comment]
@johnnyporkchops has made the PR and I have reviewed and merged into the 2/20 release. Closing as this is now complete
