### ISSUE TITLE
CMS-rebuild production without cache

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1761]
What we're after:
In order to ensure that rebuilding the CMS uses the latest versions of component parts (for security reasons) we need to rebuild the CMS without cache.

- [ ]  the rebuild is completed (Confirm Pat has done this already)

**Comment by rjayasekera** [comment]
@LindsayYoung @ccostino @patphongs Could someone please tell me what I should be checking?  I am not sure where to start on this. The check box say that I need to  - Confirm Pat has done this already
Thanks in advance.

**Comment by ccostino** [comment]
Ah this is with the CircleCI config for the CMS - essentially this is removing the two build steps of [restoring the cache](https://github.com/18F/fec-cms/blob/develop/.circleci/config.yml#L38-L42) and [saving the cache](https://github.com/18F/fec-cms/blob/develop/.circleci/config.yml#L60-L64).

@LindsayYoung is there anything else you wanted to add to this?

**Comment by AmyKort** [comment]
@rjayasekera will pick this up today. Thanks!

**Comment by rjayasekera** [comment]
@AmyKort I am running the 2/20/18 fec-cms build without cache now. This issue can be closed.

**Comment by AmyKort** [comment]
Thanks so much!
