### ISSUE TITLE
Adjust House/Senate district race view to point to prior notice pages

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1766]
We're building a graphic overview of House and Senate races by district to help users get more comprehensive at-a-glance information about particular races. Part of this work includes offering compliance information for users who are participating in the election or have particular compliance questions about the election.

What we're after in this ticket: We're testing designs of this graphic overview at our February conference. Adjustments we need to make to existing designs include:
 - [x] Adjust design to point to prior notices page
 - [ ] We won't show contact info prior notice link if it is not in the current election cycle; so we'll need a design solution to account for the null state

**Comment by AmyKort** [comment]
Should we close this if it is no longer relevant?

**Comment by JonellaCulmer** [comment]
@AmyKort Yes, I think so. I don't believe we've added issues for later sprints (3-7), and the work left in this ticket can be handled when we "finalize" the designs for these pages during that time.

**Comment by AmyKort** [comment]
Thanks!
