### ISSUE TITLE
Mock up House/Senate race overview pages

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1768]
So we can test our assumptions about our new House/Senate district race pages, we're going to mock up our revised designs in InVision or code prototype.

- [ ] create InVision display for conference
or
- [ ] code prototype

**Comment by JonellaCulmer** [comment]
@llienfec @rhoughfec Working on finishing the designs for the election summary pages prior to testing and I was hoping the two of you could assist with language, specifically the text in pink in the below screenshot, that explains the data that appears in the candidate financial totals section. 

Right now the section reads: Totals reflect the sum reported by all of a candidate's authorized committees.

<img width="976" alt="screen shot 2018-02-12 at 9 03 25 am" src="https://user-images.githubusercontent.com/31663028/36100550-9cbfb4b2-0fd4-11e8-96e5-9e7da9e95f37.png">

**Comment by jwchumley** [comment]
Closing in favor of 1771
