### ISSUE TITLE
Test election summary prototypes and mega menu (A/B) at Arizona Conference

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1769]
We have an opportunity to test the design of our new House/Senate district overview at the Arizona conference.

**Comment by JonellaCulmer** [comment]
Testing script for Arizona conference below.

# February 21-22, 2018 Test Script
###  Quick connection links:
**Notetaking:**
Notetaking folder
**Mural board:**
TBD
## Features to test:
### Election summary race pages
Tested on prototype: https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2016/ 
Usability of race page
### Mega menu: Learn more
Tested on feature: https://fec-feature-cms.app.cloud.gov/
Navigation
Open-ended feedback
### Mega menu: No menu
Tested on feature: https://fec-feature-cms.app.cloud.gov/  or use separate machine to test if there is no time to deploy to feature
Navigation
Open-ended feedback
## Introduction script:
*Start by asking how much time they have. That will help gauge how many mini-tests you can conduct. It will also reflect well on us, having taken the time to ask and respecting their time.

Hi, I'm ___, and I'm working on the Federal Election Commission website redesign, and we'd like to get some quick feedback on new features and content we're adding. Before we start, I want to make it clear that we're testing the designs, not you. You can't do anything wrong here and all your answers will be the right ones. Also, please don't worry that you're going to hurt our feelings. We're doing this to improve the site, so we need to hear your honest reactions.
Although it may seem a little weird, I'm going to ask you to think out loud as much as possible as you look at the designs. Describe what you're looking at, what you're trying to do, and what you're thinking. This will be a huge help to us. Sound good?
[wait for user confirmation; clarify things if user asks questions]
(credit: Krug)
## Introduction questions:
1. What is your job in campaign finance?
2. Do you visit FEC.gov often?
3. When you visit FEC.gov what kinds of information are you interested in?
## Topic questions:

### Election summary race pages 
Tested on feature: https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2016/ 

Orienting scenario: You’re doing research on the 2016 Arizona district 1 election. And you’ve come to this page to learn more about this election.  *Prompt them to go back to these election summary pages if they navigate away.* 

1. Who raised the most money in the 2016 Arizona district 1 election?
2. Wendy Rogers was a candidate in this election. When was her committee supposed to file their pre-primary report?
3. Where would you go to find out about outside spending in this election?
4. How much did the DCCC spend in this race?
5. Can you tell me when the DCCC was required to report those expenditures?
6. Can you tell me when the 2016 primary election was held in this district?
7. If you wanted to double check if a particular candidate is on the ballot, where would you go for that information? 
8. Let’s say you want to check when these candidates need to file all their reports. How would you do that?
9. Can you tell me which candidate is raising the most money in the current election for this district?
What is your overall impression of these pages?

## Mega menu: Learn more 
Tested on feature: https://fec-feature-cms.app.cloud.gov/ 

1. **_All users:_** What is a typical task you would try to complete on the FEC website? Can you try to do that again now?
2. **_All users:_** What is another reason you might come to FEC.gov? Can you show me how you would do that with what you see here?

3. **_Campaign filer:_** A committee you work with received a contribution that you’re not sure you can keep. How would you find out if the committee can keep the money?
_Success path 1:_ H4CC menu → H4CC landing or menu link to Guides → Candidates and their authorized committees → Taking in receipts → Handling a questionable contribution
3. **_PAC filer:_** Imagine you work for Pepsi. You're pretty sure Pepsi can raise and spend money to support or oppose federal candidates, but you're not sure how that works. Can you find information about how Pepsi can raise and spend money? 
_Success path 1:_ H4CC menu → H4CC landing or menu link to Guides → Corporations and labor organizations → Fundraising for an SSF
3. **_Data user:_** Let’s say you’re researching the upcoming Pennsylvania district 18 special election and would like to see how the candidates compare financially to one another. How would you go about accomplishing that goal?
_Success path 1:_ CFD menu → Find elections menu button → Select state they are interested in researching and optionally select a district → Election summary page
_Success path 2:_ CFD menu → Click CFD heading link or learn more button to landing page → Find compare candidates in an election section → Select state they are interested in researching and optionally select a district → Election summary page
3. **_Legal user:_** Pretend you’re advising an association PAC client. They’ve asked you about ways to solicit their members, and you want to send them some recent guidance. How would you go about accomplishing that goal? 
_Success path 1:_ Legal resources menu → Select specific legal resources link from menu
_Success path 2:_ Legal resources menu → Select heading link or learn more to landing page → Legal resource search or Browse legal resources

### Mega menu: No menu 
Tested on Pat’s local

1. **_All users:_** What is a typical task you would try to complete on the FEC website? Can you try to do that again now?
2. **_All users:_** What is another reason you might come to FEC.gov? Can you show me how you would do that with what you see here?

3. **_Campaign filer:_** A committee you work with received a contribution that you’re not sure you can keep. How would you find out if the committee can keep the money?
_Success path 1:_ H4CC menu link → H4CC landing → Guides → Candidates and their authorized committees → Taking in receipts → Handling a questionable contribution
3. **_PAC filer:_** Imagine you work for Pepsi. You're pretty sure Pepsi can raise and spend money to support or oppose federal candidates, but you're not sure how that works. Can you find information about how Pepsi can raise and spend money? 
_Success path 1:_ H4CC menu link → H4CC landing → Guides → Corporations and labor organizations → Fundraising for an SSF
3. **_Data user:_** Let’s say you’re researching the upcoming Pennsylvania district 18 special election and would like to see how the candidates compare financially to one another. How would you go about accomplishing that goal?
_Success path 1:_ CFD menu link → CFD landing page → Find compare candidates in an election section → Select state they are interested in researching and optionally select a district → Election summary page
3. **_Legal user:_** Pretend you’re advising an association PAC client. They’ve asked you about ways to solicit their members, and you want to send them some recent guidance. How would you go about accomplishing that goal? 
_Success path 1:_ Legal resources menu link → Legal resources landing → Legal resource search or Browse legal resources
## Closing questions:
1. **_If we have time: *start from homepage*_** When you need to find your upcoming report deadlines, where would you go to find that information?
2. Any last thoughts about the features you looked at today?
3. Any other general feedback you’d like to provide, or any questions for me?
4. **_Not a question:_** Mention feedback button/github.

**Comment by AmyKort** [comment]
Can we close this one?

**Comment by patphongs** [comment]
Yes, this is complete as of last week. Thanks!
