### ISSUE TITLE
Reorganize structure of existing election page data to support new House/Senate district race view

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1771]
We're building a graphic overview of House and Senate races by district to help users get more comprehensive at-a-glance information about particular races. Part of this work includes offering compliance information for users who are participating in the election or have particular compliance questions about the election.

What we're after in this ticket: This is a front-task end that changes the election profile pages to go from multiple data pages to a single data page and the about this election page, and that requires reorganizing the structure of the existing election page data. 

We'll need to complete this in sprint 5.1 if we are going to test the new overviews in a coded form. If we choose to test in Invision, this doesn't necessarily need to happen now.

**Comment by patphongs** [comment]
Code for testing has been pushed up to our feature branch: https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2016/

Any changes will be made there before we do testing

**Comment by llienfec** [comment]
@JonellaCulmer - here's requested language from issue #1768.  I took the language that we came up with for `processed` vs `raw` data from issue #1741.  This way, it won't matter if the mock up pages reference coverage date or not.  Let me know if this works for you.  Sorry for the delay.  cc: @rhoughfec 

> Candidate financial totals come from processed data that has been categorized by the FEC.  It may not include the most recently submitted electronic filings.  Raw data may show more recent filings.



![image](https://user-images.githubusercontent.com/22914750/36229320-d97a005c-11a4-11e8-99ca-1f8d4783f46d.png)

**Comment by JonellaCulmer** [comment]
Thanks @llienfec!

@patphongs Can you add this language into the feature prototype? I'll add it into the design in Sketch. I plan to take printed versions of the designs with me to the conference as a backup.

**Comment by patphongs** [comment]
Thanks @llienfec @JonellaCulmer. I have added the text and it is being deployed to feature now. Should be up shortly: https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2016/

**Comment by rhoughfec** [comment]
language looks good to me! sorry for the late response!

**Comment by AmyKort** [comment]
Is this one ready to close?
