### ISSUE TITLE
Messaging for potential move related outages

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1773]
The FEC is moving to a new headquarters, starting this month. While we don't anticipate any disruptions in our work, we want to be ready in case we need to make extra announcements about staff availability, using our existing announcement capacities.

- [x] Determine possible disruptions, if any
- [x] Develop copy 
- [x] Develop communications strategy--whether tied to the website or not.

cc @rhoughfec for visibility

**Comment by rhoughfec** [comment]
Pushing back 2 weeks
