### ISSUE TITLE
Second level review for Bulk Data Metadata Migration

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1774]
We're migrating the bulk data metadata into Wagtail. Designs are complete and content for these pages has been created and reviewed. ( great discussion at #1399 )

We've completed the first round of review for these pages:

 All candidates file metadata
 Candidate master file metadata
 Candidate-committee linkages file metadata
 Current campaigns for House and Senate file metadata
 Committee master file metadata
 PAC and party summary file metadata
 Contributions by individuals file metadata
 Contributions from committees to candidates file metadata
 Any transaction from one committee to another file metadata
 Operating expenditures file metadata

Great discussion at https://github.com/18F/fec-cms/issues/1399

Our next step will be to ask Press and Public Records to review.

- [ ] Provide pages to reviewers in a form that will allow them to read and comment
- [ ] Incorporate feedback

**Comment by PaulClark2** [comment]
Combined with https://github.com/18F/fec-cms/issues/1775
