### ISSUE TITLE
Share Search Engine Optimization (SEO)-enhancing practices with the FEC team

### ISSUE THREAD

**Issue by jameshupp** [18F/fec-cms#1779]
As part of the transition from three domains to one, it's going to be incredibly important to give people confidence they're finding the right information quickly when they search for it. Pull together recommendations for how to structure content and important components to pay attention to.

- [ X] Finish introductory document. This is well along, but we want to include information about the effect of multiple servers.
- [ X] Share with content team for feedback.
- [ ] Finalize and turn over to FEC to control and manage.

**Comment by karareinsel** [comment]
SEO pairing and training scheduled for March 7.

Updates to SEO document underway.

**Comment by karareinsel** [comment]
[ ] Finalize and turn over to FEC to control and manage. Recommend doing this after the training on March 7. So with that in mind, I would say this ticket is closed. @jameshupp sound good?
