### ISSUE TITLE
Add "copy to calendar" button on event tooltips

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#179]
**[Story](https://18f.storiesonboard.com/m/fec/!card/H11GDQZbuNu_CjnUFKPJ-Q):** So that users can understand their dates and deadlines for reporting, make it easy to add single events to their personal calendars.

This should be in the calendar event tooltip. 

Steps:
- [x] @jenniferthibault design
- [ ] I'll implement

**Comment by jmcarp** [comment]
@jenniferthibault: I should have time to implement something here soon, if you'll have time to design and/or talk this through with me.

**Comment by jenniferthibault** [comment]
Based on the interactions and language we defined here: https://github.com/18F/fec-cms/issues/126#issuecomment-163347699

### Functionality
The "Add to calendar" should have the same functionality as the "subscribe" button, as Noah pointed out.  The user selects their desired calendar from the drop-down, and it will open in that calendar app.

### Interaction
**Closed, inactive**
<img width="419" alt="screen shot 2016-01-13 at 12 28 17 pm" src="https://cloud.githubusercontent.com/assets/11636908/12302056/45304026-b9f1-11e5-816d-ba338f01beec.png">

**Open, active**
<img width="392" alt="screen shot 2016-01-13 at 12 27 42 pm" src="https://cloud.githubusercontent.com/assets/11636908/12302065/536d36c6-b9f1-11e5-8e38-9affba18a3e8.png">

There's a new icon to our library, which I can PR into whatever branch you're working off of @jmcarp .

Is there any part of the interaction or functionality I've overlooked or needs further clarification?

**Comment by jenniferthibault** [comment]
This has been implemented, with follow-up styling issues in https://github.com/18F/openFEC-web-app/issues/1039 and https://github.com/18F/openFEC-web-app/issues/1040
