### ISSUE TITLE
Make Monthly Reports show on Homepage calendar events

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1793]
The FEC homepage alerts users to the next upcoming reporting deadline. Currently, this function isn't picking up code 26 (monthly filings) and isn't showing the February 20 filing date. We need to add code 26 to JS fecfiling. With the next report due Feb. 20, this will require a hotfix.

Completion criteria:

We need to add '26' to this line,  `.js-next-filing-deadline': ['21', '27']`, of this file (https://github.com/18F/fec-cms/blob/475586990cac43eeb76c8ca1e6fea59dc649429e/fec/fec/static/js/modules/home-events.js#L20)

cc @LindsayYoung @PaulClark2 @fec-jli

**Comment by patphongs** [comment]
Hotfix has been deployed successfully to fix this issue
