### ISSUE TITLE
Incorrect categories in "all filing deadlines" link

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1794]
What we are after: 
Update the "all deadlines" link to the most recent category codes.

Current state: 
The link uses old category codes: https://www.fec.gov/calendar/?category=report-E&category=report-M&category=report-MY&category=report-Q&category=report-YE

Screenshot:
![image](https://user-images.githubusercontent.com/11817734/36332984-75fef060-1342-11e8-8971-acaa3169498d.png)

**Comment by LindsayYoung** [comment]
closing in favor of #1803
