### ISSUE TITLE
Broken image link for commissioners without bio photos

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1810]
On the commissioners page, it shows a broken image link icon: https://www.fec.gov/about/leadership-and-structure/commissioners/
<img width="1037" alt="screen shot 2018-02-20 at 6 30 45 pm" src="https://user-images.githubusercontent.com/11636908/36455008-441d451a-166c-11e8-9b1e-09b1f4ae14aa.png">

On his bio page, nothing shows up: https://www.fec.gov/about/leadership-and-structure/donald-f-mcgahn/
<img width="1059" alt="screen shot 2018-02-20 at 6 31 38 pm" src="https://user-images.githubusercontent.com/11636908/36455016-51058b2a-166c-11e8-91c2-ba2476ba488e.png">

**Comment by rhoughfec** [comment]
@jenniferthibault maybe we just need an icon for when we don't have a headshot rather than the text?

**Comment by jenniferthibault** [comment]
Oh! @rhoughfec do you mean we don't have an image for this commissioner at all? It's not just broken?

**Comment by jenniferthibault** [comment]
In those cases, we could definitely use the placeholder grey circle that we use on the homepage for vacant seats without an image. Looking at the code, it looks like that's actually what's _supposed to be_ showing up on the All commissioners page, but isn't! So it is a broken image link there that needs to be repaired. 

After a little poking around, it looks like the cause of this is that the page is trying to find a .png image, but that circle is a .jpg. This should be a quick HTML fix for anyone looking for practice with pull requests of HTML!

`img/headshot--no-photo.png` should be changed to `img/headshot--no-photo.jpg` in the following places:
- https://github.com/18F/fec-cms/blob/develop/fec/home/templates/partials/commissioner.html#L10
- https://github.com/18F/fec-cms/blob/develop/fec/home/templates/partials/current-commissioners.html#L13
- https://github.com/18F/fec-cms/blob/develop/fec/home/templates/partials/current-commissioners.html#L26

In a weird bit of history, it looks like part of this was fixed before by @johnnyporkchops , as you can see in [this commit history](https://github.com/18F/fec-cms/commit/0810f1948bc277bfa5065b3644438c07e3d5cedb) so I'm not sure how/when/why it was overwritten. That just makes him a great person to pair with if the person who picks up this issue gets stuck :) 

I'm going to stop working on this issue now that I've gone down the rabbit hole 🐰 🕳 , but glad to help with any more grooming needed whenever it gets moved into a sprint

**Comment by AmyKort** [comment]
Thanks @jenniferthibault !

**Comment by AmyKort** [comment]
Merged, so closing
