### ISSUE TITLE
Update fec repo link

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1814]
This is a sub-task that came out of moving the FEC repo to the FEC org. I need to make a copy for the 18F repo for record keeping but when I do that, we won't be linking to the right repo- we are using the GitHub redirect at the moment so everything still works.

I found one, I want to make sure I am not missing more
https://github.com/18F/fec-cms/blob/efcaaf2581401b2675a952e04bdc7ae8e2fb042c/fec/fec/static/js/templates/feedback.hbs#L23

**Comment by LindsayYoung** [comment]
Just double checked that there are no 18f/fec/ repo references in eregs or the API

**Comment by LindsayYoung** [comment]
Thanks @lbeaufort we have this going in dev and prod

**Comment by AmyKort** [comment]
Is this ready to close?
