### ISSUE TITLE
Content: Headlines in report subsections

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#182]
Working on the legal resources pages, I noticed that all our report pages have a headline construction:

> Learn more about xxx report

For example, this page on [48 Hour Notices](https://beta.fec.gov/registration-and-reporting/48-hour-notices/)

I'm wondering if it would be better and more concise to re-headline all pages without "Learn more about..."
For example, 
> Quarterly reports
48-Hour notices

I think that would help readers scan pages more easily. @AmyKort @amypike? 

(p.s. I always welcome thoughts from Jen, Jeremy, Noah on these types of things, but don't go out of your way to make time for this!)

**Comment by AmyKort** [comment]
I think it's a good idea.

**Comment by emileighoutlaw** [comment]
Complete!
