### ISSUE TITLE
Prototype calendar data entry

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#183]
Based on conversation with @noahmanger, it would be useful to estimate development time to enter data for calendar events via the CMS. I'm planning to work up a prototype of this feature to figure out how much work would be involved in a usable version.

* Use Wagtail snippets for data entry: http://docs.wagtail.io/en/v1.3.1/topics/snippets.html
* Use Wagtail API (backed by Django Rest Framework) for API: http://docs.wagtail.io/en/v1.3.1/reference/contrib/api/index.html

cc @LindsayYoung

**Comment by noahmanger** [comment]
Just noting that once this is up on staging, we'll want to demo with FEC and discuss if this is an approach we want to take.
