### ISSUE TITLE
Create sitemap from story map and review with FEC

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#186]
In order to kickstart the content creation process in partnership with the FEC, let's create a sitemap based on the needs we've identified in our story map and then review with FEC.

**Comment by emileighoutlaw** [comment]
I'm going to dive into this this week! 

**But** it's been 17 days since we decided to do this, and now my memory is hazy, so I have a few questions. 

1. Is this a sitemap of all the content (data, calendar, reg. and reporting) we've identified so far, based on Stories on Board? 

2. Is there a preferred tool I should use for this? I've used MindMeister in the past for this sort of thing, but I am always excited to try new tools.


(Also looping @jenniferthibault into this comment, because I'm sure I'll be collaborating with her on this.)

**Comment by emileighoutlaw** [comment]
Update: Emileigh will finesse cards from Stories on Board into a site content map. (In process of tracking down an Omnigraffle license). 

@noahmanger this is my fault for not documenting this the second we got off chat (and having too much swimming in my brain): of these three sections `data`, `calendar` and `registration and reporting` which did we say we wanted to collect into this map? I remember it being 2 of the 3, but not which 2. :(

**Comment by noahmanger** [comment]
Well, I'd say it's mostly Registration and Reporting and a bunch of the other cards to the right of that. Here's a breakdown, with some rough groupings (I converted it to 2-layer view for ease of viewing):

![map](https://cloud.githubusercontent.com/assets/1696495/13098248/08501774-d4dd-11e5-8a1e-f9b1aa829f07.png)

The eRegs / Legal column may  have static content, but it will likely mostly be dynamic, data-driven content, so I no need to focus on that.

**Comment by emileighoutlaw** [comment]
I'm curious if other folks have thoughts on this, but here's how I think the content for betaFEC is shaping up. There's a huge bubble of (?) TBD content that we won't be able to flesh out until after auditing and migration planning. 

[FEC Sitemap.pdf](https://github.com/18F/fec-cms/files/145214/FEC.Sitemap.pdf)


This has been a v. helpful exercise for me. After y'all take a look (and chime in with thoughts), I think we can close this issue in favor of many new issues we'll need to open related to audits and migration.

**Comment by jenniferthibault** [comment]
It feels huge just to be able to start seeing some of these categories, how many/few there are and what clusters start to take shape. Very cool @emileighoutlaw !

I have a few open questions, and I'm not sure we know the answers to them. But just jotting them down for air:
- Does calendar truly live on its own? Or could it a part of a cluster, such as "About FEC" or "Resource Library"
- I think "Data" is probably "Campaign Finance Data" and might have child topics, such as the Advanced Data Tables and Dashboards, however those end up being organized
- What's "Main Site Content" ? is that fec.gov?

**Comment by emileighoutlaw** [comment]
Great comments — since we're focusing our efforts elsewhere at the moment, I'm going to close this issue. Will incorporate Jen's awesome notes if we re-open here or elsewhere in the future. :)
