### ISSUE TITLE
Content: -ing verbs in subheads

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#190]
I just read some really great guidance from GOV.UK on using -ing verbs in headers and subheads.

>Titles and sub-headers that start with verbs
Use active verbs where appropriate, but use verbs with an ‘-ing’ at the end if the active verb would be misleading (e.g., if it sounds like an imperative, or something you can do right here and now where it’s just content about the thing).

It got me thinking that some of our content pages default to active voice (File electronically) and _would_ sound less imperative if we made them "Filing electronically." 

@amykort, what do you think about making this change?

**Comment by AmyKort** [comment]
I think that's a great point, especially in the example you use where we don't want to suggest an across the board imperative. I, personally, am a fan of the "ing."

**Comment by emileighoutlaw** [comment]
Awesome! :)
