### ISSUE TITLE
Calendar Question: Presidential reporting deadlines

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#201]
Via Slack this morning: "On the calendar we should not be showing presidential pre-primary report due dates, correct? Presidential committees during the election year file monthly and don't file pre-primary reports, correct? Do any committees file presidential pre-primary reports in an election year?"

**Comment by LindsayYoung** [comment]
Reports are imported from `trc_report_due_date` that is probably where this change should be made.

**Comment by ChristianHilland** [comment]
@noahmanger and @LindsayYoung, please let me know if this doesn't make sense. 

@paulclark2 and @apike, please let me know if I missed anything.

On the calendar we should not be showing presidential pre-primary report due dates, correct? 
- That is correct. 

Presidential committees during the election year file monthly and don't file pre-primary reports, correct? 

- A presidential candidate's committee is required to file monthly reports in a presidential election year if it raises or spends more than $100,000 (or expects to cross this threshold) in that election year.

It is plausible that a presidential candidate's committee doesn't raise or spend more than $100,000, and therefore, may file quarterly reports in addition to a pre-primary election report for each primary election that the committee is involved in.  In theory, this could be 50+ pre-primary election reports. However, the FEC does not send out reporting notices for pre-primary presidential reports.  Committee treasurers are responsible for determining whether the committee must file a pre-election report.  As an alternative, presidential committees that don't cross the $100,000 threshold may file monthly to avoid the quarterly and pre-primary reporting requirements.

Do any committees file presidential pre-primary reports in an election year?" 

- Yes, those presidential candidate committees that have not raised or spent more than $100,000 during an election year.  And PACs and party committees that file quarterly and make previously undisclosed contributions or expenditures in connection with a presidential primary election.

**Comment by noahmanger** [comment]
Ok, so as I understand it we just want to remove all events where the description is "Presidential Election Pre-Primary Due"? This seems like a change that should be made to the data, rather than simply hiding them on the frontend. @LindsayYoung what do you think?

**Comment by PaulClark2** [comment]
@ChristianHilland I agree with your answers.

@LindsayYoung  can't we just exclude "12C" and "12P" when office sought is "P" and election year is even
`select 
trdd.report_year, trdd.report_type, trdd.due_date, te.office_sought, te.election_state, te.election_district,  te.trc_election_type_id, tet.election_desc
from trc_report_due_date trdd, trc_election te, trc_election_type tet
where trdd.trc_election_id = te.trc_election_id
and te.trc_election_type_id = tet.trc_election_type_id
and trdd.report_year = 2016
and trdd.report_type in ('12C', '12P')
and te.office_sought = 'P'
order by trdd.due_date;`

REPORT_YEAR | REPORT_TYPE | OFFICE_SOUGHT | ELECTION_STATE | TRC_ELECTION_TYPE_ID | ELECTION_DESC
---    |    ---    |    ---    |    ---    |    ---    |    ---
2016    |    12C    |    P    |    IA    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    NH    |    P    |    PRIMARY
2016    |    12C    |    P    |    WA    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    NV    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    SC    |    P    |    PRIMARY
2016    |    12C    |    P    |    NV    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    SC    |    P    |    PRIMARY
2016    |    12P    |    P    |    GA    |    P    |    PRIMARY
2016    |    12P    |    P    |    VT    |    P    |    PRIMARY
2016    |    12C    |    P    |    AS    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    TX    |    P    |    PRIMARY
2016    |    12P    |    P    |    AL    |    P    |    PRIMARY
2016    |    12P    |    P    |    TN    |    P    |    PRIMARY
2016    |    12P    |    P    |    VA    |    P    |    PRIMARY
2016    |    12P    |    P    |    MA    |    P    |    PRIMARY
2016    |    12P    |    P    |    OK    |    P    |    PRIMARY
2016    |    12P    |    P    |    AR    |    P    |    PRIMARY
2016    |    12C    |    P    |    MN    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    CO    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    AK    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    KS    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    KY    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    ME    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    LA    |    P    |    PRIMARY
2016    |    12P    |    P    |    PR    |    P    |    PRIMARY
2016    |    12C    |    P    |    ME    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    MI    |    P    |    PRIMARY
2016    |    12P    |    P    |    ID    |    P    |    PRIMARY
2016    |    12C    |    P    |    HI    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    MS    |    P    |    PRIMARY
2016    |    12C    |    P    |    GU    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    DC    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    MP    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    PR    |    P    |    PRIMARY
2016    |    12P    |    P    |    MO    |    P    |    PRIMARY
2016    |    12P    |    P    |    IL    |    P    |    PRIMARY
2016    |    12P    |    P    |    FL    |    P    |    PRIMARY
2016    |    12C    |    P    |    MP    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    OH    |    P    |    PRIMARY
2016    |    12C    |    P    |    VI    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    UT    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    ID    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    AS    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    ID    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    UT    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    AZ    |    P    |    PRIMARY
2016    |    12C    |    P    |    HI    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    WA    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    AK    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    WI    |    P    |    PRIMARY
2016    |    12C    |    P    |    WY    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    NY    |    P    |    PRIMARY
2016    |    12P    |    P    |    RI    |    P    |    PRIMARY
2016    |    12P    |    P    |    PA    |    P    |    PRIMARY
2016    |    12P    |    P    |    CT    |    P    |    PRIMARY
2016    |    12P    |    P    |    MD    |    P    |    PRIMARY
2016    |    12P    |    P    |    DE    |    P    |    PRIMARY
2016    |    12P    |    P    |    IN    |    P    |    PRIMARY
2016    |    12P    |    P    |    NE    |    P    |    PRIMARY
2016    |    12P    |    P    |    WV    |    P    |    PRIMARY
2016    |    12P    |    P    |    OR    |    P    |    PRIMARY
2016    |    12P    |    P    |    KY    |    P    |    PRIMARY
2016    |    12P    |    P    |    WA    |    P    |    PRIMARY
2016    |    12C    |    P    |    WY    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    VI    |    C    |    CAUCUS/CONVENTION
2016    |    12C    |    P    |    PR    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    CA    |    P    |    PRIMARY
2016    |    12P    |    P    |    NM    |    P    |    PRIMARY
2016    |    12P    |    P    |    MT    |    P    |    PRIMARY
2016    |    12C    |    P    |    ND    |    C    |    CAUCUS/CONVENTION
2016    |    12P    |    P    |    NJ    |    P    |    PRIMARY
2016    |    12P    |    P    |    SD    |    P    |    PRIMARY
2016    |    12P    |    P    |    DC    |    P    |    PRIMARY
2016    |    12P    |    P    |    UT    |    P    |    PRIMARY

**Comment by PaulClark2** [comment]
@noahmanger I'm pretty sure this is something we can control by changing a query.

**Comment by LindsayYoung** [comment]
I am not opposed to adding this on the API side since we also have an endpoint will all the reporting deadlines and we document why they are different. I think we can add this in the release after the initial calendar debut.

**Comment by PaulClark2** [comment]
If at all possible we should try to remove / hide the presidential pre-primary / pre-caucus / pre-convention report due dates from the beta calendar prior to release.   Report type "12C" or "12P" when office sought is president.  

![presidential pre-primary report example](https://cloud.githubusercontent.com/assets/11817734/13130706/19f7aaf0-d5b4-11e5-98b2-a04e27db991e.png)


>Ok, so as I understand it we just want to remove all events where the description is "Presidential >Election Pre-Primary Due"? 
and these:   "Presidential Election Pre-Convention Report Due" and ""Presidential Election Pre-Caucus Report Due"
