### ISSUE TITLE
So that users have the latest, update "New features" and "Coming soon" parts of the landing page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#202]
Once the calendar is released, we won't have any more "coming soon" features. Let's figure out how we want to reposition this section, or update the existing sections. @noahmanger @emileighoutlaw @leahbannon  

![screen shot 2016-02-16 at 3 20 11 pm](https://cloud.githubusercontent.com/assets/11636908/13089937/133693e6-d4c1-11e5-86ac-6ccac492c840.png)

**Comment by leahbannon** [comment]
In the mean time, we could add "**Coming soon:** blah blah blah" to the description text" (although it's already kinda long)

**Comment by leahbannon** [comment]
What's the best way to figure out what to do with this section? 

I have some ideas I can throw out, but that may not be the best way to do this... One idea, for addressing the user need to pull users into the site more could be to add a lot more icons with less text to indicate more specific features we have and features we're adding, like downloads, legal resources search, eregs, data viz, more specific icons for different guides...

**Comment by noahmanger** [comment]
So I removed the coming soon for now, but let's pick this task up in a future sprint.

**Comment by emileighoutlaw** [comment]
Closing this in favor of: https://github.com/18F/openFEC/issues/1677#issuecomment-223596023
