### ISSUE TITLE
Move required pages to migration scripts

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#203]
Some CMS pages, like the home page and calendar, should always exist. We're currently auto-creating the home page in the initial migration per wagtail default, but all other pages have to be created manually. As I was just discussing with @ccostino, this is unnecessary work for the user, and creates opportunities for things to go wrong. We may want to enumerate the set of pages that should always exist and write a migration script to create them automatically. The calendar page would definitely fit into this category, but I'm not sure what else we might want to auto-create--what do you think @noahmanger?

**Comment by LindsayYoung** [comment]
Sounds good to me too

**Comment by ccostino** [comment]
I'm definitely a +1 on this; anything that is essentially required for the site to run/work properly should be provided from the start, especially to mitigate the potential for things to go wrong (as what happened with me!).

**Comment by noahmanger** [comment]
What should the criteria be for creating a page automatically in the initial migration vs. creating it via a database import? Do we only want to auto-create pages that would never be edited in the CMS?

**Comment by jmcarp** [comment]
One criterion: would the page header include dead links if the page didn't exist? That would mean we'd want to auto-create the "contact" and "registration and reporting" pages. But if we auto-create "registration and reporting", we'd also have to auto-create the linked "essentials" pages, since there would be dead links otherwise. Which doesn't seem right, since the essentials pages are actually managed by the CMS. We could also say that any pages whose contents are fully controlled by HTML templates, and not by the CMS, should be auto-created.

I think this will get simpler when we start moving more content from the templates to the CMS--for example, once more of the page header is managed by the CMS and not hard-coded as HTML (see #1).

**Comment by noahmanger** [comment]
Agreed that this will change once we get more CMS functionality going. What if for starters we say that any page that uses a unique template (and which doesn't have any content provided by the CMS) gets auto built? That would mean:
- Contact (/contact/)
- Calendar (/calendar/)
- Reporting and Registration (/registration-and-reporting/)
- Candidate and committees essential page (/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/)

**Comment by noahmanger** [comment]
Just checking in on this. Does this sound like a good place to start? If so, can we re-assign this to someone to implement?

**Comment by noahmanger** [comment]
Assigning to Carlo for implementation.
