### ISSUE TITLE
Calendar 508 issues

### ISSUE THREAD

**Issue by nickbristow** [18F/fec-cms#207]
https://fec-proxy.18f.gov/calendar/
 
- [x] The filters in the left panel, events is a legend, but each set of checkmarks should be its own fieldset with the legend being that top label. You can also group with aria if you wish
- [ ] The 'X More' links are not keyboard accessible
- [x] The calendar events need aria to describe the day they are on. "Friday February 19th, Other Event"
- [x] ~~Download calendar buttons need `aria-describedby=" ID of div/span with info in it"`~~
- [ ] Need to distinguish event category by more than color (text on the bubbles, pattern, highlight, shape)

**Comment by noahmanger** [comment]
Thanks, Nick. A couple questions (I know I'll have more):

1. On the aria to describe when each event is, what would the correct attribute for that be? 
2. The calendar download buttons are the same pattern we use elsewhere (such as the state dropdown in the left), where we use `aria-haspopup=true`. Is that not right? Do we need both?
3. For distinguishing the categories, I'm not sure what to do. In most cases, the title of each event effectively describes the category it's in. Is that not enough? If not, would icons work?

The "X More" links not being keyboard accessible is just a bug. They work _most_ of the time, but for some reason they lose their tabindex in certain situations, so I'll try to figure that out.

**Comment by nickbristow** [comment]
@noahmanger 

So I think i was referring to something else with that download button...I'm reading that now and it doesn't really make sense to me. I think i was looking at a different page, I'll try and figure it out. 

For each calendar event you could do `aria-label='{Event Text} Sunday February 31, 2016, {Event Type}'`

Yeah, icons would work, or some kind of text at the start of each event. (RD = reporting deadlines) (O = Outreach). If you do that, include it after each category header on the left.

**Comment by noahmanger** [comment]
Gotcha. Ok, I added the aria-label here https://github.com/18F/fec-cms/pull/216

On the issue of the "__ More" links not having tabindex, it seems to be a weird bug where they have it and I can control them with the keyboard as expected, but after I open and close the Chrome inspector, it gets removed. I can't tell if there's some re-render or something that's happening or what. Any insight? Can you verify that it works if the inspector isn't open?

Also, I need to tag @jenniferthibault in on the question of how to distinguish event categories in a way other than color. (Sorry! I totally should have caught this earlier!). We're really pressed for space so I'm not sure what the best way to go here is.

**Comment by jenniferthibault** [comment]
Ah, I should have spotted the calendar color issue. I'm going to make that a separate issue and assign it to myself.

**Comment by nickbristow** [comment]
@noahmanger if you give the more link an href, it should be tab accessible.

**Comment by noahmanger** [comment]
Well I gave it a tabindex which makes it focusable. If I load the page with the inspector open, the element keeps its tabindex. But if I load it with it closed, I can tab to it (suggesting it has its tabindex), but then when I open the inspector, it loses it. 

It makes me think that maybe the inspector is triggering the calendar to re-render something, but the custom code we call to add the tabindex isn't being called?

**Comment by noahmanger** [comment]
@nickbristow sorry to bug, but can I just get a sanity check on this last question? I'm pretty sure we're good as is, but I'd like to close this out with peace of mind.

**Comment by nickbristow** [comment]
@noahmanger the tab index thing or the color?

**Comment by nickbristow** [comment]
Ok, yeah, just verified without the console and it appears to work fine. I would say its ok.

**Comment by noahmanger** [comment]
Thanks. Ok, we've got the color issue in a separate issue, so I'm going to close this. Resolved by https://github.com/18F/fec-cms/pull/216
