### ISSUE TITLE
Weekly calendar event position ignores start date

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#209]
Originally reported in https://github.com/18F/FEC/issues/251. I looked into this briefly, and I'm guessing events are showing up at the wrong time on the weekly view because of a combination of our custom styles and because we aren't including some necessary rules from fullcalendar. Events show up at the correct time in the weekly view when we include the fullcalendar styles, although of course everything else looks awful:

<img width="453" alt="screen shot 2016-02-22 at 10 06 46 am" src="https://cloud.githubusercontent.com/assets/1633460/13222284/45a38006-d94d-11e5-9cba-c5c3e8ef56ea.png">

But without the fullcalendar styles, all events on the day with the most events start at the same time, and then space out at even increments thereafter, regardless of start time:

<img width="433" alt="screen shot 2016-02-22 at 10 11 31 am" src="https://cloud.githubusercontent.com/assets/1633460/13222329/81fcccd8-d94d-11e5-85f7-158c3de97b07.png">

We should also improve spacing on event titles for the weekly view, which don't have any spacing between the time and title, e.g. "10:00Executive Session".

**Comment by noahmanger** [comment]
Gah. Ok. What do folks think about simply turning off the weekly view until we can solve these problems?  @jenniferthibault ?

**Comment by jmcarp** [comment]
How long would this take to fix? If it would take significant time and/or nobody's available to do it, disabling the weekly view for now sounds fine.

**Comment by jenniferthibault** [comment]
Yeah I'd only disable if we can't get to it soon. I went hunting in Google analytics to see if I could learn anything about traffic to this page, but either we don't have any event trackers on week/month/quarter views, or I couldn't find them.

If we don't have them, could we add them in so that we can learn if people actually use weekly view?

**Comment by jmcarp** [comment]
Switching calendar views doesn't trigger a URL change, so we don't currently track analytics per view.

**Comment by noahmanger** [comment]
My vote is to disable it for now. I think we've learned that given the way the event data tends to look, the week view as currently provided by the library isn't useful (there's just not enough time-specific events to make it worth it).

I could see a different week view that includes full event descriptions (or at least full titles), which could be useful. But I'd want to prioritize that as a separate task. 

I'll submit a hotfix PR that disables it for now.

**Comment by noahmanger** [comment]
Resolved this with the removal of the week view in favor of a month list view.
