### ISSUE TITLE
Event times in week view not in correct time slot

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#210]
In the Week view, items that have a particular start time don't seem to be showing up in the correct time slot.

![calendar-weekview-time](https://cloud.githubusercontent.com/assets/11817734/13224831/5343137e-d958-11e5-84fb-15cd88706028.png)

**Comment by jmcarp** [comment]
Thanks for reporting @PaulClark2! This describes the same problem as #209, so I'm going to close this, but we're working on the issue.
