### ISSUE TITLE
Calendar: Event sorting

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#211]
It might be nice to collapse the event types, so all of the top level categories appear on the screen at one time.

![calendar-collapse-events](https://cloud.githubusercontent.com/assets/11817734/13224916/afcef086-d958-11e5-9ff5-c69a8c1f4d03.png)

**Comment by jenniferthibault** [comment]
This is in progress! Discussion about categories and groupings is happening over here, so I'm going to close this out. https://github.com/18F/fec-cms/pull/233

**Comment by emileighoutlaw** [comment]
Reopening this issue to continue discussion of our calendar filters. 

![unnamed](https://cloud.githubusercontent.com/assets/10552702/13889619/efc90d56-ed1d-11e5-8c15-8d4c41d4b94d.png)


Proposed possible new filters:

> ### Reporting and elections
- Elections
- Reporting deadlines

**************
> - Reporting periods
- FEA periods 


> ### Meetings and outreach
- Commission meetings
- Outreach

> ### Legal 
- Advisory opinions and rulemaking



My understand of the question we are trying to hash out is how to address the state filter, which applies only to the items underneath the proposed "Elections and reporting" category.

cc @jenniferthibault @LindsayYoung @noahmanger

**Comment by jenniferthibault** [comment]
Visually, we could do some separation like this:
![screen shot 2016-03-21 at 12 55 34 pm](https://cloud.githubusercontent.com/assets/11636908/13926799/4bd87972-ef64-11e5-9f7b-49ec83831d6e.png)

I'm not quite sure I have the category children correct. Specifics aside, the order of the title and elements should be consistent, whichever way we have it:
**Elections and reporting**
- Elections
- Reporting deadlines

or 

**Reporting and elections**
- Reporting deadlines
- Elections

**Comment by emileighoutlaw** [comment]
I agree that consistency is the most important piece. I think we could make a case for either order — I usually default to alphabetical ( `Elections and reporting` ), unless there's a strong case for a different organizing principle. What that would look like is:


> **Elections and reporting**
- Elections
- Reporting deadlines

**************
> - Federal Election Activity (FEA) periods 
- Reporting periods

**Comment by noahmanger** [comment]
Ok, so here's what we have as of now:

![image](https://cloud.githubusercontent.com/assets/1696495/14030456/df376f68-f1c4-11e5-99c4-e340f28b73d2.png)

I really think the clearest way to associate the state filter with the two filters it actually applies to is to keep those and only those in the same section.

This requires landing on a category label for FEA Periods and IE and EC periods, which I put in there as "Reporting periods" but maybe there's a better title?

Unfortunately @amykort is out at the moment but when she's back we should finalize this.

**Comment by AmyKort** [comment]
Should we have separate check boxes for AOd and rule makings? If the data support that, I think that would be good. I think we can remove the litigation filter. I like the reporting and compliance section--looks good!

**Comment by noahmanger** [comment]
Please tell me you're not commenting from :roller_coaster: ! 

I'll axe litigation ( @LindsayYoung am I remembering correctly that there's no actual data for that category?). AOs and rulemaking are the same category in the data, so we can't separate.

**Comment by AmyKort** [comment]
Sounds great! Thank you!

(I am not on a roller coaster. Just taking a break from my FABULOUS vacation. Is there an emoji that indicates sarcasm?)

**Comment by noahmanger** [comment]
Thank you! Enjoy. I'm closing this issue out.

**Comment by emileighoutlaw** [comment]
I don't know if there's an emoji @amykort, but there is always this:

![medium](https://cloud.githubusercontent.com/assets/10552702/14032724/4af082aa-f1eb-11e5-87f9-eaf403ec95ab.jpg)

**Comment by AmyKort** [comment]
That's perfect. I'm keeping that forever. Thank you!
