### ISSUE TITLE
Calendar - outreach event type - roundtables

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#212]
Under the Outreach event type, we'd like to change "Roundtables" to "Webinars," since all of these are exclusively online now.

**Comment by noahmanger** [comment]
I believe the "Roundtables" category comes from your tables. Do you want us to just change the label of the filter? Or every instance of it?

**Comment by PaulClark2** [comment]
Noah if "roundtables' is coming from our data, I think just changing the label will work.  Let me double check with the @amykort and @amypike

**Comment by AmyKort** [comment]
I'm sorry, I don't understand the distinction. We've made a change in our outreach program so that we invite people to online webinars rather than asking them to come into the building for a round table. So, we'd like the calendar to always refer to these small events (that are smaller than conferences) as webinars. Does that help?

**Comment by noahmanger** [comment]
Ok, thanks. That makes sense. What I should have asked: do you want to change your data or have us change it on our end? ( ping @LindsayYoung )

**Comment by AmyKort** [comment]
Purely from a program standpoint, I don't think we care, but I will leave that to Paul. Thank you, Noah!

**Comment by PaulClark2** [comment]
Thanks Amy and Noah.  I think the quick fix is to change the label on the front-end.  I think the data entry for the calendar that Info uses label's those events "roundtables"  I'll leave it to Noah to tell us if that's an "ugly" way to solve this issue.   I think changing the entry system for the calendar would not happen quickly.

**Comment by noahmanger** [comment]
Yeah, doesn't seem to be ugly. I've included the change in this PR: https://github.com/18F/fec-cms/pull/218

**Comment by PaulClark2** [comment]
great! and thanks
