### ISSUE TITLE
Calendar - smaller banner?

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#213]
Would it be possible to shrink the maroon-colored banner in order to get more of the calendar on the screen?

![calendar-banner-comment](https://cloud.githubusercontent.com/assets/11817734/13224979/f2e200ac-d958-11e5-8641-f56e1b788ad9.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/256
