### ISSUE TITLE
Calendar - add FEA dates

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#214]
Are the Federal Election Activity (FEA) dates (under Other Events) available in the database?  We haven't manually entered the dates on the existing 2016 calendar yet, but if they're in the database, it's probably worth adding them.

**Comment by jmcarp** [comment]
There are a few FEA dates in the database, and we do expose a filter to highlight them--but it looks like the most recent FEA dates we have access to are from 2007:

```
fec=> select event_name, start_date from cal_event join cal_event_category using (cal_event_id) where cal_category_id = 38 order by start_date desc limit 10;
       event_name       |     start_date
------------------------+---------------------
 OH-5 FEA Period Starts | 2007-09-14 00:00:00
 AS FEA Period Starts   | 2006-09-01 00:00:00
 VI FEA Period Starts   | 2006-08-21 00:00:00
 LA FEA Period Starts   | 2006-08-11 00:00:00
 WA FEA Period Starts.  | 2006-07-28 00:00:00
 FEA Periods Start      | 2006-07-28 00:00:00
 HI FEA Period Starts   | 2006-07-25 00:00:00
 MN FEA Period Starts   | 2006-07-18 00:00:00
 VT FEA Period Starts   | 2006-07-17 00:00:00
 NY FEA Period Starts   | 2006-07-13 00:00:00
(10 rows)
```

We might actually want to *remove* the FEA filter until we have access to more recent FEA dates, since it could be confusing to filter for an event type that users are effectively never going to find.

cc @LindsayYoung

**Comment by noahmanger** [comment]
@PaulClark2 & @amykort do you still want us to add these?

**Comment by AmyKort** [comment]
Yes, but did we decide to wait until we figured out the category filters? I thought we were looking for an intuitive way to combine these in a filter with IEs and ECs.

**Comment by noahmanger** [comment]
Going through old issues and found this. @LindsayYoung did we ever resolve this?

**Comment by LindsayYoung** [comment]
We are showing the FEA dates in `cal_event` there are 85 of them and the most recent is in 2007, like Josh said. If they add them to the table there, they will show up but won't have date filtering.

I am going to close this for now and we can make a new issue for adding the FEA dates in a state-sortable way when we get that data, or if they can tell us how to calculate it.

**Comment by LindsayYoung** [comment]
Though, maybe we want to get rid of that filter in the meantime- that would still be a separate issue.
