### ISSUE TITLE
Redundant content on checklist

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#219]
I was auditing some of our existing content today (while reviewing OGC comments on our SSF draft).

We have this quick explanation of when to register on the checklist:
<img width="882" alt="screen shot 2016-02-15 at 12 26 23 pm" src="https://cloud.githubusercontent.com/assets/10552702/13326836/6b5db2ca-dbb5-11e5-962c-29b8ca15824c.png">

But this information is captured again on the registering page. I'm wondering now if there's a user benefit to having it in two places?

**Comment by emileighoutlaw** [comment]
By which I mean, I'd love to omit this text but can't remember if there was a reason we had it in the first place.

cc @jenniferthibault @noahmanger

**Comment by jenniferthibault** [comment]
It IS also in the design mockups, so it's not there by accident. I would have put it there if we decided we wanted it there.

You tested this content though right? Anything in your notes about user response to it? Don't want to send you on a good chase though, if you don't want it, let it be gone.

**Comment by jenniferthibault** [comment]
OR— anything in your OGC notes specifically asking for it to be there?

**Comment by emileighoutlaw** [comment]
Oh my gosh! I'm sure I asked for it! I didn't mean to imply that it got snuck in somehow.

I just can't remember if it was an Emileigh-only decision or an Emileigh+others decision. 

OGC approved the content, but they didn't ask for it. So *if* it was an Emileigh-only decision, I'm feeling now like we'd be better off pruning away this little branch of words.

**Comment by jenniferthibault** [comment]
Oh i didn't mean it like that! Sorry. My mental rationale didn't translate well to written words. Just meant, if it was in the design file, some combination of us thought it should be there, but heck if I can remember why. 

Usually my first line of investigation into "why is a thing there?" is "is it supposed to be there?" and i try to answer that by seeing what our last design mockups look like. In this case, since it's in the design file, I know it's not showing up on the site by accident or error, but that's all :)

**Comment by emileighoutlaw** [comment]
Cool! Any objections to seeing how the site functions without it? I think cutting it out aligns with our main principle of "content only lives in one place." Also my general push for "as few words as possible" :)

@amykort, pulling you into this conversation now. Do you see any negative impact of letting this content live in just one place (on the registration page)?

**Comment by AmyKort** [comment]
Let's try cutting it out. Thanks!

**Comment by emileighoutlaw** [comment]
Love how fast you are, Amy!
