### ISSUE TITLE
Content: "Registering" and "How and why" pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#220]
### Background
Doing some content reviews today (as I'm working through OGC edits)

As it stands, we divided up our registration into two sections "Registering" and "How and why." 

If I remember correctly, we divided this into two pages thinking folks might use the "Registering" page to *actually register*. In practice, it became as a single place to collect links to the many form options (PDF, screen-fillable PDF, etc.)

This being the case, I think we could combine the two into just one page. Any thoughts on that or objections to that? 

### The two pages in question
<img width="885" alt="screen shot 2016-02-25 at 2 50 10 pm" src="https://cloud.githubusercontent.com/assets/10552702/13332426/ebe6854c-dbcf-11e5-8295-5a22beb226aa.png">
 
<img width="813" alt="screen shot 2016-02-25 at 2 50 20 pm" src="https://cloud.githubusercontent.com/assets/10552702/13332436/faf1918a-dbcf-11e5-80f2-0360797dd64d.png">

### Proposed new content
> Congressional candidates must register with a Statement of Candidacy (Form 2) within 15 days of becoming a candidate. You need to file a Statement of Candidacy for every election you run in, even if you run for the same office in a different election cycle.

> **Senate candidates** file by paper with the Secretary of the Senate.

> **House candidates** file with the FEC, electronically or by paper.

> Candidates who file electronically are required to use the Form 2. Candidates who file by paper can use either the Form 2 or a letter with the same information that’s captured on the Form 2.

> The Statement of Candidacy requires a candidate’s signature. It collects some basic information, including your name and address. It’s also where you authorize any campaign committees working for you. As a candidate for federal office, you’re required to designate at least one authorized committee.

> Register as a candidate using one of the options below.

> Web form
PDF
Screen-fillable PDF with audio instructions

**Comment by emileighoutlaw** [comment]
@amykort @amypike, I'd love your thoughts on this.

**Comment by AmyKort** [comment]
Looks okay to me.

**Comment by emileighoutlaw** [comment]
You're the best! Thanks. :)

**Comment by emileighoutlaw** [comment]
Addressed in Wagtail, so I'm closing this now.
