### ISSUE TITLE
Design solution to calendar list view problems

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#224]
As discussed on the call this week, our partners would like us to address some of the challenges people have been having with finding a list view of events on the calendar.

The consensus is that the "quarterly" toggle is not where people expect to go to find a list view, and the old "week" view was too focused on start times, which very few events in the system actually have.

I can think of a few ways to solve this problem, ranging from simplest to most complex:

1. Add a new toggle for "Month - List" and rename the current "Month" option to "Month - Grid". 
2. Add a new "Week" view that is just an implementation of the list view.
3. Add a new set of toggles to "Month" for "Grid" / "List".
4. Design a new "Week" view that doesn't break things down by specific start times but does give more room for event text.

Anyone else have thoughts or other ideas? I'm inclined towards one of the first three, but will spend some time with it today and tomorrow.

**Comment by noahmanger** [comment]
Ok, spent an hour on this and here's what I came up with. I think it actually works pretty well (heavily inspired by @jenniferthibault 's early designs):

![gif](http://g.recordit.co/npoxTswdSo.gif)

**Comment by jenniferthibault** [comment]
:+1: :+1:  I might later tweak the icon, but interaction looks sharp @noahmanger 

Are we losing the "today" or current whatever button/functionality entirely?

**Comment by LindsayYoung** [comment]
Instead of month and quarter could we say something like "calendar" and "list"?

**Comment by noahmanger** [comment]
Oh yeah I removed the "Today" button just to see how it felt since they asked about it on the call again. I think I agree that it doesn't actually add much functionality, and the confusion it causes seems to make it not worth it.

I'm split on just going with "Calendar" and "List" instead of "Month" and "Quarter". On the one hand, it's definitely simpler than having two sets of toggles. On the other, I still think it's useful to have a full quarter view, though again, maybe the confusion makes it not worth it.

**Comment by LindsayYoung** [comment]
I think you can show a quarter's worth of data, that just isn't the main difference in the views so I think the names should reflect the name. 

Or perhaps combine the toggles, from for into 2, so it is [quarter {list image}]  [month {calendar image}]

**Comment by noahmanger** [comment]
Ah yeah, that would be simpler! @jenniferthibault ?

**Comment by jenniferthibault** [comment]
I could see it causing some confusion to combine them, but worth a try & a test!

**Comment by AmyKort** [comment]
Weighing in on behalf of Greg: His preference would be to replace the Month and Quarter options with "Grid View" and "List View." He doesn't see the need to have a "Quarter" view.

**Comment by AmyKort** [comment]
For myself, I am a fan of the list and grid icons you have in the sketch up above and the way they display content. Thanks!

**Comment by emileighoutlaw** [comment]
I've been eyeing this issue, and now I have a question:

Amy, is your suggestion that we winnow our options down to two things: an icon for a calendar (which would show a month) or an icon for a list (which would show a list of everything this quarter)? 

Generally, I'm a fan of as few options as possible, but I want to make sure I totally understand. :)

**Comment by AmyKort** [comment]
My preference is just to have the two icons. But, that's just my two cents. 

Also, I'm not sure how the list function would look if we limited it to the quarter. If you click the list icon on the day before the end of the quarter, does it only show you two days (or a list with only two relevant days)? Do you have to go back to the month view to see what comes after that?

**Comment by emileighoutlaw** [comment]
I don't actually remember in usability testing how often (or if at all) that people used the "quarter" view. Was that before you were in testing @brethauer (was that when you and I were working on things, @onezerojeremy)?

What I'm getting at is that my content brain thinks its fine if we only have 1. a month calendar view and 2. a TBD list view (of whatever time period/length makes the most sense). But I can't remember the provenance of the quarterly view.

**Comment by noahmanger** [comment]
Here's how it could look if we just have "Month" and "List", where "List" is actually a quarter's worth of dates:

![screen shot 2016-03-09 at 1 40 34 pm](https://cloud.githubusercontent.com/assets/1696495/13651609/e48fb796-e5fc-11e5-8783-7334907d3ed6.png)

The way it works now is the "List" button is always set to show the full quarter that we're currently in. So if it's March 30th, you'll still see Jan - March. 

I recall the decision to have a quarter view was based on the fact that people responsible for reporting think in terms of fiscal quarters and could therefore benefit from seeing a full quarter's worth of activity at once. Though this may not be as big of a use case as we once thought.

**Comment by AmyKort** [comment]
Thanks! Looks good to me. I don't necessarily have an opinion on the quarter view--I can see wanting to look at things by quarter if you are a quarterly filer. It just struck me as limiting my options for the list view in a case where I liked that view better, and didn't want my list to end on March 30 (or start two months ago).

**Comment by jenniferthibault** [comment]
@noahmanger It seems confusing to me that you get a different amount of time just because you're viewing a list. I think we should keep time period and viewing format as separate ideas, and not mix them in toggles. 

All that said, we are making assumptions here, as none of this is being tested with users now. I think we should add analytics watchers on the buttons to see what format is used, do a mini-release to go with a hypothesis (one of the two design options below) and then adjust based on the analytics if one view isn't being used after a sufficient period of time or if we hear feedback that indicates people would like to see more time. Given that it never came up as an issue in testing the calendar earlier on, I don't think it bothered people to have a quarterly view, but that doesn't prove a need.

Design hypothesis:
- _People want the option to view quarterly info and monthly info._ Have two toggles: one for month | quarter and one for [grid view icon] | [list view icon] [Like Noah did in this mockup](https://github.com/18F/fec-cms/issues/224#issuecomment-193486290)

- _The need for quarterly view isn't strong enough to warrant it's own view at this point._ Get rid of quarterly view, have only monthly increments, and have one toggle for [grid view icon] | [list view icon]

**Comment by jmcarp** [comment]
@jenniferthibault I took a look at the current analytics, and if I'm reading this right (I'm always at least a little confused looking at GA), we're getting just a handful of views to the calendar page per day--like, maybe around 30. Which might represent single digits of daily users. I'm wondering if adding more analytics is going to give us good information here.

**Comment by noahmanger** [comment]
Good point @jenniferthibault . I agree, we should get something out to test against a hypothesis, but agree with Josh that traffic is probably too small at the moment to give us a reliable signal.

I'm inclined to go with your second hypothesis as it's a simpler layout, which would have a list view that is also for the span of a month, so they stay consistent:

![gif](http://g.recordit.co/VTnW46e8b5.gif)

**Comment by jenniferthibault** [comment]
:+1: Sounds good to me.

Is there any way to avoid that very visible grid load lag when you toggle from list to grid?

**Comment by LindsayYoung** [comment]
:+1:

**Comment by AmyKort** [comment]
My vote would also be for a list view that is a span of a month. We can see what people think. Thanks!
