### ISSUE TITLE
Design and content: Breadcrumbs on reporting and registration pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#227]
We're close to having SSF content ready to launch on our reporting and registration home! (yay!)

We'll be re-using some of the pages from our candidate/committee section (for example, getting an e-filing password, electronic filing overview, etc.)  That being the case, will the breadcrumbs at the top of the page be an issue? We won't want the parent page to be `Essentials for House and Senate Candidates and Committees` if people are accessing the page from the SSF essentials checklist.

Does that make sense? Maybe there's already a design-y or dev-y answer to this that I just don't know yet...
  
<img width="1072" alt="screen shot 2016-03-09 at 1 07 28 pm" src="https://cloud.githubusercontent.com/assets/10552702/13645214/e65b7fc4-e5f7-11e5-83ea-61d24f201dab.png">

cc @noahmanger @jenniferthibault

**Comment by jenniferthibault** [comment]
Weeeeeeee thought about this on some github issue before while @onezerojeremy was around. Let me see if I can find it.

In other news, we for sure need to move those breadcrumbs out of the main red bar on these pages, and make them normal sentence case instead of all uppercase.

**Comment by jenniferthibault** [comment]
Found it! No action was taken against it, but the trail of thinking starts here:
https://github.com/18F/fec-cms/issues/144

**Comment by jenniferthibault** [comment]
Going back to the design files, I found more pieces that opened up questions around breadcrumbs (the next/previous articles)

I worked in a small placement and format change to the existing breadcrumbs, but also wonder if we don't need breadcrumbs on the Essentials pages? More open questions than not at this point.

![screen shot 2016-03-09 at 10 04 36 pm](https://cloud.githubusercontent.com/assets/11636908/13658236/343a774a-e643-11e5-894b-c3f7635e5378.png)
![screen shot 2016-03-09 at 10 04 51 pm](https://cloud.githubusercontent.com/assets/11636908/13658237/343ac04c-e643-11e5-9330-5ee27e371e5c.png)

**Comment by emileighoutlaw** [comment]
It's easier for me to imagine losing some of the top nav items, rather than all. 

What I mean is, it's not to painful for me to lose access to "previous" and "next" as well as the "essentials for other registrants" buttons. 

But I have a harder time letting go of the breadcrumbs at the top— I'm just going on a gut feeling that it will be harder to maneuver in and out of pages without that top `Essentials... // Getting a ....` I *hate* hitting the back button on my browser (surely I'm not the only one who feels this way?).

Could we drop everything but the top breadcrumbs for this release, or are you too swamped with other design issues (I know you want to make it sentence case and move it out of the red bar)? 

And are there still front-end issues to figure out with the breadcrumbs on pages we're re-using (that's probably a @noahmanger question).

**Comment by jenniferthibault** [comment]
I think we are slightly talking past each other (only because it's easy to do when not specifically pointing at physical things)— let's chat about this on video w/ screenshare this afternoon?

**Comment by emileighoutlaw** [comment]
Sounds good! Just put a time on our calendar

**Comment by noahmanger** [comment]
Do we want to close this since we resolved it for the release? I think what we came up with is a good solution for now until we learn otherwise.

**Comment by emileighoutlaw** [comment]
Yep! Sounds good.
