### ISSUE TITLE
Content: Inconsistency between "submit" and "file"

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#232]
One of our goals is to get more language consistency across the website I've noticed that sometimes we tell people to "file" reports and sometimes we tell them to "submit" reports. I like the word "file," since "submit" tends to sound a little ... dominant.

Would there be an issue if we made this consistently "file" ? Can we make this language change? 

cc @amykort @amypike

<img width="869" alt="screen shot 2016-03-11 at 11 36 56 am" src="https://cloud.githubusercontent.com/assets/10552702/13708639/bc9bc0b8-e77d-11e5-8128-e9c2c24d8fcf.png">

<img width="599" alt="screen shot 2016-03-11 at 11 36 01 am" src="https://cloud.githubusercontent.com/assets/10552702/13708644/c0cff654-e77d-11e5-964d-c6a2b54cbaf8.png">

<img width="422" alt="screen shot 2016-03-11 at 11 35 26 am" src="https://cloud.githubusercontent.com/assets/10552702/13708655/ca453316-e77d-11e5-9d2f-b7430fda310a.png">

**Comment by AmyKort** [comment]
This is more complicated than a simple word swap. File, filed and filing are defined at 11 CFR 100.19, and we would have to make sure that we are using those terms consistent with that definition. The language at 11 CFR 100.19 also uses the terms delivered, deposited and sent. We'd want to spend a little time on these edits were we to decide to make them.

**Comment by emileighoutlaw** [comment]
_Of course_ it isn't simple ;) (it wouldn't be fun if it were, right?). We can sit down and chat about this in person sometime.

In the meantime, can we delete this sentence on the "Post-general" page: `You must submit your report by 30 days after the election.` That same content is repeated directly below it in the chart. https://beta.fec.gov/registration-and-reporting/post-general-election-reports/

Other than that, there are only four other pages that have the word submit on them, and we can talk about those in the future (since this isn't a top priority item):

https://beta.fec.gov/registration-and-reporting/file-electronically/
https://beta.fec.gov/registration-and-reporting/file-paper/
https://beta.fec.gov/registration-and-reporting/48-hour-notices/
https://beta.fec.gov/registration-and-reporting/get-filing-software/

**Comment by AmyKort** [comment]
I agree that's a good sentence to delete.

I'll take a look at the other links. Thanks!

**Comment by noahmanger** [comment]
Where are we at on this?

**Comment by AmyKort** [comment]
Ice box, I think. We should come to a more natural solution here as we continue to address more content.

**Comment by emileighoutlaw** [comment]
Related: https://github.com/18F/fec-cms/issues/311

**Comment by emileighoutlaw** [comment]
We've sorted this out in our "Build shared language" issue, so I'm marking this as "done"
