### ISSUE TITLE
Add SSF Essentials Page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#234]
I've got the basic template of this together, but I have some questions for @emileighoutlaw :+1: 

1. Is there supposed to be an introduction paragraph(s) before the checklists? This is how the candidate one works, and I think it would be good to follow the same pattern. Should we just use the text from the "options" page?

2. Can you specify which links in the checklist are to the existing pages vs. which ones are to new pages?

**Comment by evankroske** [comment]
What does SSF stand for?

**Comment by emileighoutlaw** [comment]
Hey @evankroske — Separate Segregated Fund! We'll be sure to make that clear on the page.

Noah— 

##### 1. We were planning on using the text from the registration options page for the intro (I think that's how it works for candidates, too). Here's the text:

> Corporations and labor organizations **can't** contribute to federal candidates, but they **can** establish and administer a special kind of political committee: the separate segregated fund (SSF). 

> An SSF can raise funds to make contributions to candidates — including expenditures that are coordinated with candidates — within the applicable contribution limits.

> ##### Who can set up an SSF?
- Corporations (including those without capital stock)
- Labor organizations
- Incorporated membership organizations (including trade associations)
- National banks
- Incorporated cooperatives

> The sponsoring corporation or labor organization is called the SSF’s “connected organization.”  The connected organization can use its own money to solicit contributions to the SSF and to pay the costs of establishing and operating the SSF, for example staff salaries and office space.

> SSFs may solicit contributions only from a limited group of people, including the connected organization’s executive or administrative personnel, its stockholders (if the connected organization is a corporation), or its members (if the connected organization is a labor organization or a membership organization).




##### 2. Checklist page (*new* page or **existing** page key):

Registration
- Getting a tax ID and bank account **(existing)**
- Getting a treasurer **(existing)**
- Registering an SSF *(new)*

How to file
- Electronic filing **(existing)**
    - Getting an e-filing password **(existing)**
    - Electronic filing overview **(existing)**
    - Mandatory electronic filing **(existing)**
- Paper filing *(new)*
- Filing software **(existing)**

Regular filing
- Filing requirements *(new)*
- Election years *(new)*
    - Quarterly filers *(new)*
    - Monthly filers *(new)*
    - Independent expenditures *(new)*
- Non-election years *(new)*
    - Semi-annual filers *(new)*
    - Monthly filers *(new)*
- Terminating an SSF *(new)*

Troubleshooting
- Missed deadlines **(existing)**
- Responding to a Request for Additional Information (RFAI) **(existing)**
- Administrative fines **(existing)**
- Contact us **(existing)**

**Comment by noahmanger** [comment]
Resolved in https://github.com/18F/fec-cms/pull/238
