### ISSUE TITLE
Wagtail: It's getting hard to navigate pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#237]
This doesn't need to be a top priority, but as we add registration and reporting sections, we're getting a lot of pages in Wagtail. It's already a little unwieldy to sort through the many CMS pages (with just the candidate pages in). 

I poked around a little but didn't see any way to add folders or subsections or other organization to this. 

![wagtail](https://cloud.githubusercontent.com/assets/10552702/13746812/8562f562-e9cb-11e5-80e9-2f2932f4a9ae.gif)

**Comment by noahmanger** [comment]
Ah I see how that's annoying. It *is* possible to use the side nav menu to navigate deeper in, but still not folders or whatnot. 

However, I don't think we should be worrying about this right now, so I'm going to move to the icebox and we can revisit when we're looking at CMS improvements.

**Comment by emileighoutlaw** [comment]
Sounds good!

**Comment by tomdyson** [comment]
Hi @noahmanger and @emileighoutlaw, I head up the Wagtail team here at Torchbox. There are various approaches for handling large numbers of pages in Wagtail (the biggest site we know of has ~200k pages), and I'd be very happy to talk you through these if that would be helpful.

**Comment by noahmanger** [comment]
Hi @tomdyson . Super helpful to here! Thanks for chiming in. Yeah, we'd love to learn more. If there's a place you can point us, that's great, or else we could find time to chat.

**Comment by emileighoutlaw** [comment]
@tomdyson — just following up on this. Would you have time to chat this week with me (and possibly 1–2 of my wonderful colleagues)? We'd love to talk Wagtail organization strategy with you!

**Comment by tomdyson** [comment]
@emileighoutlaw @noahmanger for sure! Shall we schedule over email? my-first-name @ torchbox.com.

Are any of you going to Djangocon next week? I'd be happy to go through this in person, if that's easier.

**Comment by johnnyporkchops** [comment]
I would love to help on this, I have a little experience configuring the editor interface
