### ISSUE TITLE
Checklist navigation doesn't highlight selected section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#244]
Not an uber priority, but I just noticed this —

If you're on an essentials page, clicking to move to a different subsection leaves the highlight on the wrong text. (This is kind of hard to explain clearly in words. Video below.)

![registrationnav](https://cloud.githubusercontent.com/assets/10552702/13813923/7d2acc7c-eb5a-11e5-8e31-c9844d701b68.gif)

**Comment by noahmanger** [comment]
I'm not able to replicate this, but have seen it elsewhere. Can you take another look and see if it's still a problem?

**Comment by emileighoutlaw** [comment]
I still see it on my Chrome browser. Is it possible it's related to the _size_ of the browser window (I'm on my smaller than Thunderbolt laptop screen right now)?

**Comment by emileighoutlaw** [comment]
Same thing on registration home :/

![registrationnav](https://cloud.githubusercontent.com/assets/10552702/13892810/3b7452c6-ed30-11e5-9d88-e657918f81a5.gif)
