### ISSUE TITLE
Pre-release: Make corporations and labor organizations link live

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#245]
On the [candidate/committee essentials page](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/), I think we still need to make the link to corporations and labor organizations live. 

We'll also want to change the header to remove `Coming soon` from the header.

<img width="415" alt="screen shot 2016-03-16 at 9 24 10 am" src="https://cloud.githubusercontent.com/assets/10552702/13814104/68500d48-eb5b-11e5-8c8c-0026590a4e93.png">

It's possible @noahmanger has already noticed and put this in a PR ;)

**Comment by noahmanger** [comment]
Oops! Good catch.

**Comment by noahmanger** [comment]
Resolved.
