### ISSUE TITLE
Candidate guide at bottom of SSF page

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#246]
https://fec-stage-proxy.18f.gov/registration-and-reporting/essentials-corporations-and-labor-organizations/

The link at the bottom of the SSF page takes you to the "Candidate" guide instead of the "Corporations and labor organizations" guide.

**Comment by noahmanger** [comment]
Good catch! Just fixed this in #247

**Comment by noahmanger** [comment]
Resolved.
