### ISSUE TITLE
Figure out how to do HTML tables in CMS

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#26]
Some of the registration content pages need simple HTML tables and we need to figure out how to do this.

**Comment by noahmanger** [comment]
@jmcarp any thoughts on this? This would be a really good thing to get going for launch as it really helps the formatting of certain pages.

**Comment by jmcarp** [comment]
The simplest thing here would be to add raw HTML as a content type in the streamfield sections. WYSIWYG editing for HTML tables is notoriously lousy, and it seems like many editors just skip it. Should we give that a try?

**Comment by noahmanger** [comment]
Sounds good to me. I agree, it always gets nasty.

**Comment by noahmanger** [comment]
This has been figured out!
