### ISSUE TITLE
Nonconnected content: Assist FEC as they draft PAC essentials

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#263]
FEC is writing the next essentials content section! They'll be using the existing content as a guide, but we need to be available to assist and answer questions as they arise.

**Comment by emileighoutlaw** [comment]
@amykort — tagging you here so you know this is on my radar. Anything I can do to be helpful as y'all strike off on the path of content creation? I'm so excited for y'all to do this!💃

**Comment by AmyKort** [comment]
I'll check to see the status of this content--I haven't heard anything in a few days. Thanks!

**Comment by emileighoutlaw** [comment]
Yay! Thanks, Amy!

**Comment by emileighoutlaw** [comment]
Completed. Closing this now.
