### ISSUE TITLE
Firefox: Calendar event text not appearing on grid view

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#277]
https://fec-stage-proxy.18f.gov/calendar/

<img width="1392" alt="screen shot 2016-04-13 at 1 19 23 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502665/65d78db8-017a-11e6-8aae-afcc7a7dc67c.png">

**Comment by noahmanger** [comment]
Fixed!
