### ISSUE TITLE
Firefox: Calendar button icons rendering slightly out of place

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#278]
In Firefox, icons inside calendar control buttons are appearing slightly off-center, but in different directions:

<img width="242" alt="screen shot 2016-04-13 at 1 15 40 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502699/9872107c-017a-11e6-8bbf-16ff74b091ca.png">

<img width="142" alt="screen shot 2016-04-13 at 1 15 50 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502698/98702190-017a-11e6-988a-8219432149f0.png">

I'd call this non-urgent for the release, but something we should patch.

**Comment by noahmanger** [comment]
We updated these styles and this is no longer relevant.
