### ISSUE TITLE
Firefox: Calendar filter panel not extending to edge of screen

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#279]
On both grid and list view

<img width="1392" alt="screen shot 2016-04-13 at 1 16 02 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502740/d9bc7932-017a-11e6-96bd-080984df05b2.png">

<img width="1277" alt="screen shot 2016-04-13 at 1 23 11 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502749/e865e748-017a-11e6-9455-dfb96d4894c0.png">

**Comment by noahmanger** [comment]
This is resolved in the latest release.
