### ISSUE TITLE
Content: Registration and reporting home

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#282]
Doing some auditing today, I had the thought that we could make the `Registration and reporting` home more clear to users. 

What we have now was a great MVP, but it's a little hard to understand what the `Registration and reporting` section is about from reading the current blurb:

<img width="1021" alt="screen shot 2016-04-22 at 12 01 53 pm" src="https://cloud.githubusercontent.com/assets/10552702/14747518/9902cc48-0882-11e6-8429-b60dc3603747.png">

The headline says `What does it mean to register and report?` But the paragraph covers a range of topics:
- What the FEC does (help citizens make informed voting decisions) should go on a mission/about page
- How data is made available should go in the data section

Keeping that in mind, here's a proposed new blurb:

> Federal candidates and political committees must register with the FEC when they reach certain monetary thresholds. Once registered, they make regular reports about their financial activity. 

> Learn more about those groups and the requirements that apply to them. 

cc'ing @amykort and @amypike for their thoughts on this one. Would also be happy to hear from @jenniferthibault or @noahmanger

**Comment by AmyKort** [comment]
Looks good to me. Should we make it "when they reach certain thresholds" instead of "monetary thresholds" now that we have the SSF content on the site?

**Comment by emileighoutlaw** [comment]
Also, we should link candidate and committee to glossary definitions

**Comment by emileighoutlaw** [comment]
Ooooo— interesting thought about "thresholds" vs. "monetary thresholds." And good consistency catch.

I'm waffling on whether "monetary thresholds" is more clear (i.e., we're talking about money) or less clear ("monetary" is a kind of technical word). This might be something we can test with our users!

**Comment by AmyKort** [comment]
Mostly, since SSFs might need to register before they hit any monetary threshold, I didn't want to mislead anyone.

**Comment by emileighoutlaw** [comment]
Ahh! Genius! So:

> Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they make regular reports about their financial activity.

Learn more about those groups and the requirements that apply to them.

**Comment by jenniferthibault** [comment]
Sounds good to me!

**Comment by AmyKort** [comment]
Looks good.
