### ISSUE TITLE
To improve performance and reduce costs, compile to static site

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#3]
Example implementations:
- http://docs.wagtail.io/en/latest/reference/contrib/staticsitegen.html
- https://github.com/mhnbcu/wagtailbakery

**Comment by noahmanger** [comment]
Moving to story map: https://18f.storiesonboard.com/m/fec/!card/GSF2g9Npg_1o8znUD8RvAQ

**Comment by jmcarp** [comment]
?
