### ISSUE TITLE
Redundancy in calendar filters

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#307]
Having a header that says "Advisory opinions and rulemakings" directly above a filter for "Advisory opinions and rulemakings" feels very unhelpful. Can we eliminate the header? Was there anything else we were going to add here in the future?

<img width="344" alt="screen shot 2016-05-20 at 3 43 12 pm" src="https://cloud.githubusercontent.com/assets/10552702/15440122/bba32aba-1ea1-11e6-8eec-6edd254383b3.png">

**Comment by jenniferthibault** [comment]
Not that I recall. We could remove the header (and use the full word in the checkbox to accommodate for the acronym) for now, and if things are added later that need hierarchical distinction, could introduce one then.
