### ISSUE TITLE
Political party committee 404-ing on staging

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#308]
![2mil8k2yw5](https://cloud.githubusercontent.com/assets/11636908/15441278/03877006-1ea8-11e6-9d03-ed52be452d8b.gif)

**Comment by noahmanger** [comment]
Fixed https://fec-stage-proxy.18f.gov/registration-and-reporting/essentials-political-party-committees/

**Comment by jenniferthibault** [comment]
@noahmanger  I'm also getting 404's on the following pages:

- https://fec-stage-proxy.18f.gov/registration-and-reporting/ssf-registration/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/ssf-file-paper/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/ssf-filing-requirements/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/ssf-election-year-filing/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/quarterly-filers/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/monthly-filers/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/independent-expenditures/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/non-election-year-filing/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/semi-annual-filers/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/non-election-monthly-filers/
- https://fec-stage-proxy.18f.gov/registration-and-reporting/terminating-a-party-committee/

Which is quite a lot... what's going on?

**Comment by noahmanger** [comment]
We don't make these pages on staging because it requires making them in the CMS specifically for staging, which is tedious. Playing with fire a little bit, but we're going to address this when we do our overall CMS improvement.
