### ISSUE TITLE
Deliver style guide to FEC

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#311]
I'm opening this issue to track some of the language inconsistencies we're trying to think about:
### Questions to answer
- Do we use the form number (`Form 1`) when or form name (`Statement of Organization`) when we talk about filings?
- Do committees `submit`, `deposit` or `file` filings? (https://github.com/18F/fec-cms/issues/232)
- Are all these lowercase `political action committee`, `party committee`, `authorized committee`, `nonconnected committee`, `separate segregated fund` ?
### Things with distinct meaning

Money coming in:
- Contributions
- Fundraising
- Receipts

Money going out:
- Spending
- Disbursements
- Expenditures

Filings (all the different types)
- Statements
- Reports
- Notices
### Capital or not capital (as it should be used)
- Administrative Fine Program
- Alternative Dispute Resolution Program
- advisory opinion
- Commission, Commissioners
### Other style things
- Always "for example," and never "e.g.".
- `instructions`, rather than `step-by-step instructions`
- `electronic filing`, rather than `e-filing` or `efiling` etc.
- Use the n dash `–` for ranges

(Will keep updating)

**Comment by emileighoutlaw** [comment]
<img width="440" alt="screen shot 2016-06-02 at 3 41 14 pm" src="https://cloud.githubusercontent.com/assets/10552702/15758406/75bf9056-28d8-11e6-94b9-78d507ae190d.png">

**Comment by AmyKort** [comment]
My 2 cents:  advisory opinion, not Advisory Opinion, unless it is a specific opinion, like Advisory Opinion 2016-50 (but in that case, I think we pretty much always say AO 2016-50).

We prefer Commission to commission.

I feel like we could go either way on alternative dispute resolution program and administrative fine program. Right now we capitalize those in our press releases and other publications.

The best word for what you do with a filing is to say you "file" it. But then you end up saying folks file their filings with us (ugh). That's how we ended up with "submit." I would avoid "deposit" because that has a separate use in our regulations as it applies to the definition of "file."

**Comment by emileighoutlaw** [comment]
Woohoo! 

I agree with everything you wrote! High fives!

Here's what that means:

- Lowercase for advisory opinions. Uppercase for everything else.

To put it another way (so I can remember my thinking in the future): capitalizing things that are proper nouns is helpful for people who are unfamiliar FEC programs and hierarchy. It's the same reason we like `Secretary of Senate` — giving that term the weight of capital letter makes clear the significance of the position (as opposed to a secretary who works in the Senate building). Capital `C` for `Commission` is most easy to understand for novice readers. I also like `Alternative Dispute Resolution Program` (it's a formal thing; this makes it look formal) and `Administrative Fine Program` (same reason).

Let's see if we can't be super savvy in all our writing and use `file` all the time and also avoid ever saying `file a filing` (which is 😁)

**Comment by adborden** [comment]
I would love to have a copy section in the styleguide or on the wiki. I'm a big fan of glossaries, and even though we have one for users, I think it would be good to have one "internally" for consistency.

**Comment by AmyKort** [comment]
Still chipping away at our list . . .

Maybe we should go with Statement of Candidacy and Statement of Organization, because these are what they are called when you look at data--so for example, at the bottom of the candidate's landing page you are invited to view the Statement of Candidacy. Also, these are words that might actually mean something to someone. Form 2? Not as much.

**Comment by AmyKort** [comment]
I would go with instructions over step-by-step instructions (only because it is shorter).

E-Filing, E-filing, e-Filing, eFiling, electronic filing . . . I think we've been all over the place on this one. What do you think is most clear to folks?

**Comment by emileighoutlaw** [comment]
I'd love to consistently call it `electronic filing`, which is the most clear because there's no abbreviation. 😁

**Comment by AmyKort** [comment]
Sounds great to me!

**Comment by jeanninehunter** [comment]
If a term is mentioned more than once on a page, on first reference, we should spell out terms followed by the abbreviation in parentheses then use the abbreviation in subsequent references. For example,  separate segregated fund (SSF) and advisory opinions (AO).

**Comment by emileighoutlaw** [comment]
Awesome! Thanks Jeannine. 

FEC is definitely no Oxford comma. You didn't find any in the audit, did you? Same with lowercase `federal` and lowercase `government` right? 

I like the idea of using `to` in ranges, when used in content. When used in data tables, I think the n dash is easiest to read.

We'll keep the discussion going here, but I'm going to start collecting decisions into a single Google Doc: https://docs.google.com/document/d/1cIWTO4X9kNvjL-Lpq8A6t9NrA3ZtWvSZ5mKS1ic0-Js/edit

**Comment by emileighoutlaw** [comment]
Jeannine and I are going to keep chipping away at this, but since it's a long-term goal, I'm moving the issue itself into the backlog.

**Comment by emileighoutlaw** [comment]
We have a draft content guide: https://docs.google.com/document/d/1cIWTO4X9kNvjL-Lpq8A6t9NrA3ZtWvSZ5mKS1ic0-Js/edit?pli=1#

It will continue to grow as @jameshupp nurtures it (and FEC will take it over at some point), but I don't think we need to keep this particular issue open.
