### ISSUE TITLE
Refine beta homepage content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#318]
It's been some time since we messed with the homepage content, and I'm feeling like it's a little unwieldy. I think some of this text was useful when we first introduced the beta, but I think we start trimming the word tree. 

**Reasoning**:
We already know people don't read. They come to the site to perform functions, and this content is telling them _how_ to perform those functions. We spent so much time and energy in research and development, they should be able to use the site seamlessly, without us explaining so much. 

**What we have now**:
<img width="1013" alt="screen shot 2016-05-31 at 1 22 48 pm" src="https://cloud.githubusercontent.com/assets/10552702/15685591/68c7ddbc-273a-11e6-99ee-f2458e1ee0d7.png">

**Proposed new**:
<img width="787" alt="screen shot 2016-05-31 at 2 10 01 pm" src="https://cloud.githubusercontent.com/assets/10552702/15685604/7933dae8-273a-11e6-81c7-2a3cef9bfacd.png">
(with tiny edit, because my inspector froze in the last second. The first block should say `Explore our data to see how money is raised and spent in federal elections.`

**Comment by AmyKort** [comment]
If we don't want to say "explore campaign finance data," could we just say "explore data"? It's a small difference, but we receive campaign finance reports and make that information available to the public. I worry that "our data" makes it sound like this is data the agency generates some other way.

**Comment by emileighoutlaw** [comment]
I think that's a great comment. And actually, we may be changing this to be something else entirely and highlight our newer features better. Let me link this up with another issue that Jen started.

**Comment by emileighoutlaw** [comment]
Closing this issue in favor of: https://github.com/18F/openFEC/issues/1677#issuecomment-223596023

You can pop over there @AmyKort 😄
