### ISSUE TITLE
Calendar: on list view, allow filter panel to extend to bottom of the page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#319]
I know this has been a known issue for a while, but wanted to document it in order to help us work it into a sprint. Now that the list view is the default view, it's harder to gloss over.

![screencapture-beta-fec-gov-calendar-1464722055120](https://cloud.githubusercontent.com/assets/11636908/15687411/838cf3be-2742-11e6-8b7e-c65a8c29cfe8.png)

**Comment by noahmanger** [comment]
Occurs to me that I should sync up with @adborden about how we want to handle this, considering that we need this to work for legal resources as well.

**Comment by adborden** [comment]
Good point @noahmanger. Currently it lives in the filter panel. I think we should pull out the logic to handle the height and the toggle (the `X`) into it's own UI component with js and styles. Somehow the Legal team has avoided taking on this work, but we've got at least two places where this is an issue.

**Comment by noahmanger** [comment]
Ok! I think I solved this. Curious what you think of the approach in https://github.com/18F/fec-style/issues/404
