### ISSUE TITLE
Current section state not showing up on Reg/Reporting side

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#330]
Current section state is showing up on the data side, but isn't showing up on the Registration & reporting side. I'm not sure if it was overlooked or overwritten in the release, but capturing it just in case.

<img width="1212" alt="screen shot 2016-06-06 at 10 10 11 am" src="https://cloud.githubusercontent.com/assets/11636908/15824812/003985f4-2bcf-11e6-9183-23faecadf299.png">

<img width="669" alt="screen shot 2016-06-06 at 10 10 53 am" src="https://cloud.githubusercontent.com/assets/11636908/15824813/003cf8b0-2bcf-11e6-8a96-2d20870a842e.png">

cc @noahmanger

**Comment by noahmanger** [comment]
This is potentially tricky, so moving to the next sprint to include in that release rather than trying to force it in to this one.

**Comment by noahmanger** [comment]
I'd still like to try to get this in this release, but need someone's help with more Django experience. @ccostino , @LindsayYoung or @adborden anyone have capacity to help out with this? 

Basically we need the CMS to pass some variable that we can use to apply a class to the current parent nav item.

**Comment by ccostino** [comment]
I can help you out, @noahmanger!  Would you like to pair on this later today?

**Comment by noahmanger** [comment]
We don't need to pair necessarily; you can just do it if you have time. The basic criteria is:

So that users who are on a page on the CMS understand what section they're in, show an active state on the nav item or parent item.

Criteria for completion:
- [ ] When on any page in the Registration and Reporting section, the `.is-parent

**Comment by adborden** [comment]
Thanks @ccostino for volunteering, assigning to you.
