### ISSUE TITLE
Content for calendar tooltips

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#337]
This is an issue for the content needed in: https://github.com/18F/fec-cms/issues/298#event-681561455

Scratch pad: https://docs.google.com/document/d/1GB7Rox8kIXm7MqpCucDJeO-gwH_t-FRSPV8sjLn2oDg/edit

**Comment by emileighoutlaw** [comment]
Hey @amykort and @amypike— 

Here's a draft of some tooltip explainers for the calendar. Can you take a look? I feel pretty unsure about EC and IE periods, but the other stuff is pretty boilerplate.



**Election:** Federal elections. These include primary, general and special elections as well as caucuses and conventions.

**EC periods:** Electioneering communications periods apply to primary elections, general elections and special elections. During these periods, individuals and groups must file a report within 24 hours, anytime they make electioneering communications that add up to (aggregate) $10,000 or more. 

**Executive sessions:** Regular meetings during which the Commission discusses pending enforcement actions, litigation and other matters that — by law — must be kept confidential.

**IE periods:** 24- and 48-Hour Reports. Filers add up (aggregate) the money they spend on independent expenditures to determine whether they must file these reports. They aggregate on a per-election and per-office basis within each calendar year.

**Open meetings:** Regular meetings during which the Commission adopts new regulations, issues advisory opinions, approves audit reports of political committees and more.

**Roundtables:** These online workshops focus on specific topics, which range from election year communications to reporting. Register to access online materials and technical information.

**AOs and rules:** These deadlines apply to advisory opinions and rulemaking. Advisory opinions are official Commission responses about how to apply campaign finance regulations to specific, factual situations.

**Comment by amypike** [comment]
@emileighoutlaw   Nice!  I am also unsure of the EC and IE period tool tips.  Let's talk more about those two.  @amykort  My suggestions: 

Executive Session: Regular meetings that are closed to the public in which the Commission discusses pending enforcement actions, litigation and other matters that — by law — must be kept confidential.

Open Meetings: Regular public meetings during which the Commission adopts new regulations, issues advisory opinions, approves audit reports of political committees and takes other actions to administer the campaign finance law.

Roundtables: These voluntary compliance online workshops focus on specific topics, which range from election year communications to reporting. Register to access online materials and technical information.

AOs and rules: These deadlines apply to advisory opinions and rulemaking activities. Advisory opinions are official Commission responses about how to apply campaign finance regulations to specific, factual situations.  The Commission writes rules and regulations and publishes them in the Federal Register.

**Comment by emileighoutlaw** [comment]
I love it. Great suggestions! 

Maybe we can get these first ones included and keep working on EC and IE (with legal?)? 

How about:

**Executive Session:** Regular meetings that are closed to the public in which the Commission discusses pending enforcement actions, litigation and other matters that — by law — must be kept confidential.

**Open Meetings:** Regular public meetings during which the Commission adopts new regulations, issues advisory opinions, approves audit reports of political committees and takes other actions to administer the campaign finance law.

**Roundtables:** These online workshops are voluntary focus on specific compliance topics, which range from election year communications to reporting. Register to access online materials and technical information.

**AOs and rules:** These deadlines apply to advisory opinions and rulemaking activities. Advisory opinions are official Commission responses about how to apply campaign finance regulations to specific, factual situations. The Commission writes rules and regulations and publishes them in the Federal Register.

**Comment by AmyKort** [comment]
Roundtables: These online workshops are voluntary focus on specific compliance topics, which range from election year communications to reporting. Register to access online materials and technical information.
^^^ I think there might be a word missing in this one. Also, this description doesn't necessarily tell me that these are training opportunities FEC staff offer to people required to file reports with us and others interested in learning more about how to comply with the campaign finance law. So, I know some of the topics, but not who they are for and why someone would sign up.

AOs and rules: These deadlines apply to advisory opinions and rulemaking activities. Advisory opinions are official Commission responses about how to apply campaign finance regulations to specific, factual situations. The Commission writes rules and regulations and publishes them in the Federal Register.
^^^ I have some concern about the word "activities," although, as usual, I'm not sure why. Maybe I think activities is too broad and doesn't really capture the Commission's role in issuing guidance. Since the header is AOs and rules, maybe we can skip ahead to something like: "These deadlines apply to the steps the Commission must follow in issuing new guidance and rules.  . . . " But not that exactly, because that's awful.

Meeting explanations are great. Thanks!

**Comment by emileighoutlaw** [comment]
Sorry for the delay. These are great comments, Amy. Thank you! Here's another go around:

**Executive Session:** Executive sessions are regular, closed meetings during which the Commission discusses pending enforcement actions, litigation and other matters that — by law — must be kept confidential.

**Open Meetings:** Open meetings are regular, public meetings during which the Commission adopts new regulations, issues advisory opinions, approves audit reports of political committees and takes other actions to administer the campaign finance law.

**Roundtables:** Roundtables are training opportunities offered to FEC filers and those interested in learning about campaign finance law. These voluntary, online workshops focus on specific compliance topics. Register to access online materials and technical information.

**AOs and rules:** The Commission follows these deadlines when issuing new guidance and rules. Advisory opinions are official Commission responses about how to apply campaign finance regulations to specific, factual situations. The Commission writes rules and regulations and publishes them in the Federal Register.

**Comment by emileighoutlaw** [comment]
Pinging @amykort just so this doesn't fall off our radar 😄 (but this isn't urgent; I know you're busy!)

**Comment by AmyKort** [comment]
I'm still back and forth on AOs and rules. But, I will make a commitment tomorrow. I promise.

**Comment by noahmanger** [comment]
I'm noticing that we don't have tooltip content for reporting deadlines like:

![image](https://cloud.githubusercontent.com/assets/1696495/16212466/a0c848ce-36fc-11e6-9a0e-421e08b47f04.png)

Is that by design? I thought we were renaming these categories too?

**Comment by emileighoutlaw** [comment]
That's a great question. @LindsayYoung, once we remove the report codes, will we only have one box that says "Report" for all reports due? I can write something generic about reporting, if that's the case.

**Comment by AmyKort** [comment]
I think we should go ahead with the language you suggested, Em. Thanks for the extra time!

**Comment by emileighoutlaw** [comment]
Thanks so much, Amy. I'll keep working on report content, but get the pieces that are good to go into implementation.

**Comment by emileighoutlaw** [comment]
@amypike — what if we relied only on the legal definitions of IE and EC periods for these? That would mean the content would look like this (and this content is already on the beta site):

> **IE period**: Independent expenditures are expenditures for a communication:
- That expressly advocate the election or defeat of a clearly identified candidate and
- That are not made in cooperation, consultation or concert with, or at the request or suggestion of, any candidate, or his or her authorized committees or agents, or a political party committee or its agents. 11 CFR 100.16.

> **EC period**: Electioneering communications are any broadcast, cable or satellite communication that 
- Refer to a clearly identified candidate for federal office,
- Are publicly distributed within certain time periods before an election, and 
- Are targeted to the relevant electorate. 11 CFR 100.29.

**Comment by LindsayYoung** [comment]
@emeligh, I misunderstood your question before, the report codes only show up in the discription or title if there are no matches for the code name. The boxes on the side are the categories. Making the reporting codes have granular categories makes them easy to filter by the type of report.

**Comment by amypike** [comment]
@emileighoutlaw  -- That sounds great!  It is consistent and legally accurate.  THANK YOU!

**Comment by noahmanger** [comment]
@LindsayYoung sorry if I'm missing something, but now I'm confused. In this instance:
![image](https://cloud.githubusercontent.com/assets/1696495/16436318/c085dffe-3d51-11e6-9db5-20f610c0a191.png)

... shouldn't the category label on the right be the same as the filter option? That's the way it works for everything else. And if the filter param is `?category=report-E` why does this category show up as `report-12P`?

**Comment by noahmanger** [comment]
^ This applies to all "filing deadline"-type events. Shouldn't the categories be "Monthly filing deadline", "Quarterly filing deadline" and "Pre- and post-election" deadline?

**Comment by LindsayYoung** [comment]
@emileighoutlaw In the API, `report-E` will return all the pre and post election kinds of reports and `report-12P` will only return the pre-primary reports.

Here are the calls if you want to take a look:
(I would use a json view plugin to look at them)

https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&category=report-E&min_start_date=2016-06-01&max_start_date=2016-07-01

https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=500&category=report-12P&min_start_date=2016-06-01&max_start_date=2016-07-01

**Comment by noahmanger** [comment]
Gotcha. Separating the issue of what the API returns from what we display on the front-end: can we map the API category responses to human-readable terms on the front-end? I see the value of having granular codes for API users, but seems that these should be translated on the interface.

**Comment by LindsayYoung** [comment]
I think the easiest would be to replace category report-* with a "reports" category on the web app

We could do the mappings, we are using the mappings to make the api calls, so that would not be a ton of work either.

**Comment by noahmanger** [comment]
For consistency, I think we should map them to the language we use on each checkbox. Every other category corresponds to a checkbox filter (typically shortened), so something like:

- "Filing deadline: Monthly"
- "Filing deadline: Quarterly"
- "Filing deadline: Pre- and post-election" 

It's a little long. @emileighoutlaw and @AmyKort , whenever you're back, would love your input.

**Comment by noahmanger** [comment]
Trying this out, and I think we want to go with the shorter version:
![image](https://cloud.githubusercontent.com/assets/1696495/16471011/dfa8dc8e-3e0e-11e6-85f0-b6a7ffc0adbf.png)

However, this makes it inconsistent with the rest. Should we instead be using the category label above the checkboxes as the category on each event?

**Comment by emileighoutlaw** [comment]
I think the point of consistency is to make things clear for our readers. 

In this case, "Reporting and compliance periods" seems very unclear to me as a category (especially as an option that goes with "Filing deadline.") So I think we can dispense with that option. 

So we know we want to keep `IE period` and `EC period`, but we'd still like to be consistent. How about we use some sort of blended category/checkbox approach, a la:
> Monthly deadline
> Quarterly deadline
> Pre- and post-election deadlines

or

> Filing: monthly
> Filing: quarterly
> Filing: pre- and post-election

(I think I prefer the first option to the ones that start with `Filing:`, although either would work well, I think).




_Last note_: how easy/possible is it to change the content of these boxes? If possible, we should definitely get rid of the acronyms:

> Independent expenditure period
> Electioneering communication period

Those are long names, unfortunately. So maybe they won't work?

**Comment by noahmanger** [comment]
I like the "monthly deadline" etc approach. But spelling out the full acronyms (as well as "pre- and post-election deadlines") really breaks the design:

![image](https://cloud.githubusercontent.com/assets/1696495/16626952/f26fcf70-435f-11e6-9838-3f7225446b22.png)

@jenniferthibault curious if you have any ideas or insight.

**Comment by emileighoutlaw** [comment]
It's still too long if we remove "period" right, and just have `Independent expenditures` and `Electioneering communications` ?

**Comment by noahmanger** [comment]
Is it a useful label without the word "period"? I worry it's confusing.

**Comment by jenniferthibault** [comment]
My lightest weight improvement would be to allow the tag to span two columns (Which I think is what Noah has in the adjustment above) and bump the text size down from `1.6 rem` to `1.4 rem` to make it appear more as a detail than as a feature of equal priority with the event details. 

I'd be in favor of dropping the acronyms, so want to make the design accommodate, but rethinking it would be better for a later task.

**Comment by emileighoutlaw** [comment]
I think "independent expenditure" is not a full picture, but I think it's a fuller than "IE period," as our research indicates many people won't understand acronyms.  

If the tag is two columns, how many words will that accommodate? Also, I appreciate that we want the design to accommodate the content, but I don't want to sacrifice the brilliant design work either.

**Comment by noahmanger** [comment]
So there's basically no way to get around these needing to break onto two lines. Here's how it looks at a medium sized window (larger than a tablet): 
![image](https://cloud.githubusercontent.com/assets/1696495/16787681/e4996b16-4852-11e6-90c2-9b962c62f38b.png)

If I expand my window, all of them except EC's work:
![image](https://cloud.githubusercontent.com/assets/1696495/16787690/f94964b2-4852-11e6-8827-4eb3ad4def05.png)

I think we either need to go with acronyms (which might well be ok with tooltips) or think of a different design.

**Comment by emileighoutlaw** [comment]
Thanks for updating this, Noah. If it's okay with y'all, I'm going to brainstorm this for a second and see if I can think of anything else other than acronyms to use.

**Comment by emileighoutlaw** [comment]
h/t to @jenniferthibault who just gave me a breakthrough on this.

**What**
Let's go with:
> [ IE period _(i)_ ] 
Independent expenditure period. Independent expenditures are expenditures for a communication:
- That expressly advocate the election or defeat of a clearly identified candidate and
- That are not made in cooperation, consultation or concert with, or at the request or suggestion of, any candidate, or his or her authorized committees or agents, or a political party committee or its agents.

> [ EC period  _(i)_ ]
Electioneering communications period. Electioneering communications are any broadcast, cable or satellite communication that:
- Refer to a clearly identified candidate for federal office,
- Are publicly distributed within certain time periods before an election and
- Are targeted to the relevant electorate.

**Why**
I think what I was missing in feeling good about using an acronym was a good, logical reason why.

The deal with acronyms is that they came to prominence in 1900s United States in places where space was limited for writing, like train cars (`Richmond, Fredericksburg and Potomac Railroad → RF&P`) 

The deal with tooltips is that they are intended to give more information.

In this case we have limited space (the very reason for acronyms!) _and_ a way to give more information (the very reason for tooltips!). 

I think I can communicate this very clearly in our FEC content style guide.

**Comment by jenniferthibault** [comment]
👏  @emileighoutlaw  and thanks for pushing this @noahmanger 

Here's also a small tweak to the tooltip pattern that will help with the spacing awkwardness, whether one line or two:

![screen shot 2016-07-13 at 7 40 36 pm](https://cloud.githubusercontent.com/assets/11636908/16823387/c7ccd240-4931-11e6-90f1-f7d53657c5cc.png)

**Comment by noahmanger** [comment]
I love it! Really appreciate your commitment to only doing things that can be codified as rules in the style guide. And good suggestion on the design, @jenniferthibault . Here's what we have now:

![image](https://cloud.githubusercontent.com/assets/1696495/16825273/232c5de0-4928-11e6-8db2-4ac6d46cb4ba.png)

Now we just need definitions for monthly, quarterly, and pre- and post-election deadlines, right?

**Comment by emileighoutlaw** [comment]
@AmyKort and @amypike — I've been searching through FEC.gov and the campaign guides, but I can't find any existing definitions for _what is_ a quarterly report, monthly report, pre-election report or post-election report. 
 
In our new registration and reporting section, we tell folks _when_ to file these reports, but not _what_ they are. Other than saying some variation of "Form such and such," any ideas how we might define these (that wouldn't be a huge legal sticky wicket) for our calendar tooltips?

**Comment by AmyKort** [comment]
Filers submit regularly scheduled, periodic campaign finance disclosure reports throughout the year. The reports are defined in the regulations according to their due dates and coverage periods. How specific do you want to be? The July Quarterly Report is the committee's campaign finance disclosure report covering activity through June 30, and is due on July 15. 

Does that help at all?

**Comment by emileighoutlaw** [comment]
This is very helpful! 

What I'm hearing is that the CFR breaks down filing requirements in a pretty granular way. For example, [104.5(a)](https://www.gpo.gov/fdsys/pkg/CFR-2016-title11-vol1/pdf/CFR-2016-title11-vol1-sec104-5.pdf) explains when quarterly reports are due for House and Senate candidate committees. And not even 11 CFR lays out a description of what the reports are.

This being the case, it seems like we have two options:

1. Tailor the tooltip content very specifically:
    - per registrant type,
    - per report type, and 
    - taking into account any possible extenuating circumstances, which make the event distinct from others like it.
1. Something broad that explains more about what reports are and do.

My initial feeling is that we should write something broader, because the burden of maintaining so much variable and specific content is very high. And I believe the risks of communicating something incorrectly  probably outweigh the benefits of specificity.

How about a broad bucket like the following:

> Throughout the year, filers submit regularly scheduled reports about their campaign finance activity. These reporting requirements are outlined in 11 CFR and vary, depending on the type of filer. Learn more(link to registration and reporting home).


Curious what you think of this approach, @noahmanger

**Comment by noahmanger** [comment]
I think that something broad will suffice. We're putting these tooltips here primarily for areas that really need clarification, like where we use acronyms, or where there may be ambiguity about what counts as an "election". I think something that explains what a reporting deadline is would do fine. I'd prefer to not include links, though, as that would require require re-implementing (they show on hover & focus, which makes it hard to click a thing in there).

**Comment by emileighoutlaw** [comment]
Oh right, that makes sense about the links.

@amykort, for our tooltips explaining report types, how would you feel about something like: 

> Throughout the year, filers submit regularly scheduled reports about their campaign finance activity. These reporting requirements are outlined in Title 11 of the Code of Federal Regulations (CFR) and vary, depending on the type of filer.

**Comment by emileighoutlaw** [comment]
Circling back around before the weekend — any thoughts on the above proposal, @AmyKort ?

**Comment by AmyKort** [comment]
Looks good to me. Thanks.

**Comment by emileighoutlaw** [comment]
@noahmanger —would you like to move this to implementation, or shall I? 

Final content for all report tooltips:
 
> Throughout the year, filers submit regularly scheduled reports about their campaign finance activity. These reporting requirements are outlined in Title 11 of the Code of Federal Regulations (CFR) and vary, depending on the type of filer.

**Comment by emileighoutlaw** [comment]
Oh wait! Just remembered you're still out early this week. I'll see if I can figure it out. :)
