### ISSUE TITLE
User stated expectation/preference for search-first navigation on mobile

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#342]
During usability testing, users expected to see a search box right away on the mobile view. Users were looking for something they could _anything_ type into: typed "bernie sanders presidential". One user did not understand the hamburger menu as a visual cue to trigger the menu in mobile view. [tested 6-9](https://github.com/18F/FEC/blob/master/test_scripts/2016-6-9.md) 

[Navigation feature set in research repo](https://github.com/18F/FEC/blob/master/feature_sets/ia_primary_nav_menu.md)
tagging: @jenniferthibault @noahmanger @jeanninehunter @emileighoutlaw @edmullen as likely interested parties.

**Comment by edmullen** [comment]
I think there are a number of signals that point to a need for a unified search across most resources on the site, not just on mobile. This place seems to be as good as any to lay out some thoughts about this issue that affects all FEC teams. This is a big lift, but work has already been done that could pave the way for this and make the lift manageable: 

1. @jenniferthibault and I worked through some [new search input design patterns.](https://github.com/18F/fec-style/issues/370#issuecomment-225254525).
2. We have [design patterns for cross-type, clustered search results](https://github.com/18F/fec-style/issues/318) that are currently in use on the legal side and will be used on the data side.
3. The work @tony has done with elasticsearch on the legal side has the potential to be expanded to include non-legal types on content.

INPUT

The new input pattern [defined in fec-style/#370](https://github.com/18F/fec-style/issues/370) presents search in a band below the header/breadcrumb.

![image](https://cloud.githubusercontent.com/assets/2654503/16120953/5e68adb6-33af-11e6-93ff-f87965313d19.png) 

CLUSTERED RESULTS

Given the differences in the resources available, the approach we've taken on the legal side is to allow a simple natural language input that feeds into elastic search. Search at this level is fairly simple, without the ability to filter results on any type-specific metadata. The results from this level of search are presented in clusters by type, allowing users to understand the categories of result items. If the user wants to dig deeper into a specific type of content, they can view all results of that type where they will see type-specific filter/facet options.

![legal search results](https://cloud.githubusercontent.com/assets/2654503/16121241/8c2f42ae-33b0-11e6-9a12-020b81977d51.jpg)

EVOLING TOWARD A UNIFIED SEARCH

As part of the exploration for [issue #370](https://github.com/18F/fec-style/issues/370#issuecomment-225254525), we considered the potential for a unified search. The patterns we're implementing now for landing pages and cross-type search results in legal and data can be extended to a site-wide cross-type search. Here is an example of potential placement and design:

![image](https://cloud.githubusercontent.com/assets/2654503/16120540/c48bca76-33ad-11e6-9c04-076199c329db.png)

ASSISTED SEARCH

As part of the legal work, I needed to define a way to reveal some information about the search operators available as part of elasticsearch. Additionally, I think the scope menu could become unwieldy as the types of content searchable increases. This led to the work in [fec-eregs/#94](https://github.com/18F/fec-eregs/issues/94)

![image](https://cloud.githubusercontent.com/assets/2654503/16121436/3e6af116-33b1-11e6-8146-5a47ca2b3a40.png)

NOT ALL TYPES

It's worth noting that not all data and content must be included in a site-wide search. This would need some thought. Individual contributor receipts would likely produce too much noise to be useful. But including pathways to those receipts would likely be helpful (maybe a landing page or typeahead suggestion). Candidates and committee entities on the other hand would be very helpful.

cc @porta-antiporta @adborden

**Comment by jenniferthibault** [comment]
@edmullen is my design summarizing write-up idol. 🙌
