### ISSUE TITLE
Add link to demo glossary on home page card

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#35]
Text should link as following:

Current state:
![screen shot 2015-09-09 at 11 57 37 am](https://cloud.githubusercontent.com/assets/11636908/9767022/0e10ea42-56ea-11e5-976a-cf06e68e7e81.png)
Preferred text link:
![screen shot 2015-09-09 at 11 57 43 am](https://cloud.githubusercontent.com/assets/11636908/9767021/0e0f2ffe-56ea-11e5-9290-bf0c3af75bb9.png)

**Comment by noahmanger** [comment]
Done!
