### ISSUE TITLE
Reviewing and editing release notes

### ISSUE THREAD

**Issue by jeanninehunter** [18F/fec-cms#351]
Linked from the beta homepage (mentioned in #18F/openFEC: Issue #1677), an "Latest release notes" link or "Full release notes" link would appear in one of the following formats for every sprint:
- A link to a markdown page on GitHub (see @noahmanger's example in last release)
- A pop up or modal on the site with a bullet list of changes
- A Release page on the main GitHub repo
 
Will reach out to @noahmanger @porta-antiporta to collect information or backread/edit their notes before they're released. 

Also, seek guidance in:
- [x] Determining an agreed-upon format
- [x] Deciding where release notes live
- [x]  Deciding if we're keeping coming soon content.

**Comment by jenniferthibault** [comment]
Link to previously mentioned issue, where this began (for easy reference): https://github.com/18F/openFEC/issues/1677

**Comment by noahmanger** [comment]
We have a good solution for this and it's ready to go for the release. Thanks for the editing @jenniferthibault ! Closing.
