### ISSUE TITLE
Build assets on CI and drop buildpack-multi

### ISSUE THREAD

**Issue by adborden** [18F/fec-cms#352]
We had to revert the changes made from https://github.com/18F/openFEC/issues/1643. The `collectstatic` step still requires the `fec-style` source. To address this we'll have to move the `collectstatic` step into Travis.

**Comment by adborden** [comment]
So I believe the last remaining issue is that we're using [django-compressor](https://github.com/django-compressor/django-compressor) to process the SCSS at runtime. This wouldn't work anymore because we're not shipping `node_modules` (and don't want to), so the SCSS files won't be available at runtime.

I see some options
1. Configure `django-compressor` to process files at build time or `collectstatic` time (I'm not familiar with the project, so I'm not sure if this is even a feature).
1. Drop `django-compressor`, and include the same SCSS build process that exists in the web app.

cc @jmcarp

**Comment by noahmanger** [comment]
Is this still something we want to do?

**Comment by adborden** [comment]
I think so, because fec-cms is still depends on the multi-buildpack which is deprecated.

**Comment by adborden** [comment]
Fixed by https://github.com/18F/fec-cms/pull/353

**Comment by noahmanger** [comment]
Resolved by #353
