### ISSUE TITLE
Content for statutes landing page

### ISSUE THREAD

**Issue by jeanninehunter** [18F/fec-cms#354]
Subpage linked off Legal Resources landing page that defines statutes and includes a link to a PDF of the statutes.

<img width="1031" alt="legalresourceslandingpageininvision" src="https://cloud.githubusercontent.com/assets/9824273/16160394/e6f4f3b0-3495-11e6-8038-3ed968ec9a32.png">

**Comment by emileighoutlaw** [comment]
Closing in favor of https://github.com/18F/fec-eregs/issues/199
