### ISSUE TITLE
Legal resources hero has the campaign finance copy

### ISSUE THREAD

**Issue by adborden** [18F/fec-cms#374]
![screen shot 2016-06-29 at 4 46 57 pm](https://cloud.githubusercontent.com/assets/509703/16470377/b084da10-3e0a-11e6-91f9-577cfd7696b4.png)

This is in a partial, which is unique to legal resources so I think it's okay to just swap the copy.

**Comment by adborden** [comment]
I believe this is the correct copy https://github.com/18F/fec-style/issues/370#issuecomment-223596807

**Comment by noahmanger** [comment]
D'oh. Dump copy and paste error on my part.
