### ISSUE TITLE
Legal: Advisory Opinion search (content)

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#384]
# The situation
Chatting with @porta-antiporta this morning, one of the things that came up is that when our Advisory Opinion content and search goes live, the search will be missing a small subset of advanced search options that exist on FEC.gov. We'll add most of them over time, but there are a couple rarely used advanced search tools that we'll never bring over to betaFEC. 

We don't want users to freak out that they aren't able to do everything on beta that they can on FEC.gov.

# Solutions
My initial reaction was:

1. Redirect people to FEC.gov for some advanced searches (except I hate to direct people off betaFEC. They should use our new, awesome tool!)
2. Warn people that the Advisory Opinion search isn't fully completed (except I haaaate disclaimers.)

One problem is that we don't have a great sense how often used these super advanced search features are (things like "I want to find Advisory Opinions that have specifically term X and term Y within the same paragraph"). We aren't sure if it'll affect a lot of users or just a few. 

We had similar discussions on the data side of things, like when we sent people to FEC.gov before downloads were ready. If I'm remembering correctly, we had a disabled button and tooltip that explained downloads were coming soon. Would a similar solution here? If there's no advanced search functionality yet, maybe it could be something like "Advanced search coming soon" ? 

I don't want to get too in the interface and design weeds without @adborden, but I do think we want to add as little content as possible (no one wants to read!)

**Comment by noahmanger** [comment]
Good question! We've definitely dealt with this on the data side since the very beginning. I see no real problem with sending people over to the legacy site, but it'd be good to set it up to be a) not intrusive and b) give us the best possible data. 

Is there a design for how the advanced options will be implemented? For instance, if we knew they were going to be in an accordion, we could have that be just like it will be, but when people open it up it contains a message and a link to fec.gov. Then you could track how many people are opening the accordion (using a custom event) and how many people are clicking through.

**Comment by adborden** [comment]
As a side note, when search results come up empty, we give the user an
option to run the same search by clicking "Try fec.gov"

https://beta.fec.gov/data/legal/search/?search_type=regulations&search=asdf+asdf+asdf

--
Aaron D Borden
Human and Hacker

**Comment by emileighoutlaw** [comment]
Ohh, interesting. I wonder if that isn't sufficient in and of itself. (I'm generally in favor of qualifying things less and adding as little explanatory content as possible.) @porta-antiporta, what do you think?

**Comment by emileighoutlaw** [comment]
pinging @porta-antiporta again on this, since he was out for some of last week :)

**Comment by emileighoutlaw** [comment]
I think the empty results warning should be sufficient. Closing this now. We can revisit later if we need to!
