### ISSUE TITLE
Content: Pipe versus dash in page title

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#385]
h/t @edmullen for noticing this.

We've been inconsistent in our use of pipes versus dashes in page titles. For example

> - Pre-election reports | beta.FEC.gov 
> - Browse candidates for president - beta.FEC.gov

The only difference is pipe vs. dash. And it seems we’re showing current page only. 

I've done some poking around, and I think pipes are easier for people to read quickly (and as conventional as any other choice), and we should stick with those.

Anyone object to this approach? cc @jenniferthibault @noahmanger

**Comment by jenniferthibault** [comment]
No objections!

**Comment by edmullen** [comment]
I also was thinking the `beta.FEC.gov` created some debt we'd need to undo once we flip the switch. Could this just be...

Pre-election reports | **_FEC_**

Related issue: https://github.com/18F/fec-eregs/issues/173

**Comment by emileighoutlaw** [comment]
@noahmanger @jenniferthibault, what do y'all think? Any reason why we can't say ` | FEC` ?

**Comment by noahmanger** [comment]
Love it! Let's do it

**Comment by emileighoutlaw** [comment]
I'm on it!

**Comment by noahmanger** [comment]
Resolved.
