### ISSUE TITLE
Create banner that links back to beta

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#389]
## Summary

We're hoping to begin the content migration in the next few weeks, and one our tactics is going to be linking our navigation to both betaFEC pages and FEC.gov pages. This will help us test our burgeoning navigation system before we get everything migrated into our CMS. 

That said, once we've ported people over to FEC.gov, we need a way for them to return to betaFEC. 

The pattern I've seen used most often for this (and thus element I think would be the best) is a banner that lets users go back to beta.fec.gov. 

Creating one of these will likely include me, @jenniferthibault, and @noahmanger. And I don't know how early we want to start on this or get it on our radar, so I'm opening this issue now for discussion.
## Tasks to completion
- [ ] Content design
- [ ] Visual design
- [ ] Approvals
- [ ] Implementation

**Comment by jenniferthibault** [comment]
A thing to keep in mind for context is that the FEC has currently implemented this call to action for the beta site, which is available on every page of their site. We may want to tweak it as part of this change.

<img width="1279" alt="screen shot 2016-07-11 at 5 44 38 pm" src="https://cloud.githubusercontent.com/assets/11636908/16747933/414a7f18-478f-11e6-832e-c0aff903a78d.png">

**Comment by emileighoutlaw** [comment]
Resurfacing this here. @patphongs and @LindsayYoung— per our PDF chat yesterday, is a banner that links between the old and new site something we need to tackle before we finish the `Latest updates` and `Press` migration?

**Comment by emileighoutlaw** [comment]
This issue is outdated and can close.
