### ISSUE TITLE
Content: Identify folks to build CMS pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#390]
# The issue
@AmyKort, this issue is for you! (Comments from anyone else on the FEC/18F team are also very welcome). I've been thinking of content in three buckets lately:

1. Content we know needs to be edited (or combined) before we publish it on betaFEC
1. Content we're still deciding what to do with
1. Content we know generally won't change

#### 1: Content we know needs to be edited (or combined) before we publish it on betaFEC
Amys, Jeannine, and I should focus our efforts here. These pages are trickiest and need experienced folks working on them, shepherding them through approvals. We can bring in other content managers to help us with this, but we'll comprise the core team.

#### 2: Content we're still deciding what to do with
Still working through this. More soon. (I'm looking at you historical election results PDFs.)

#### 3: Content we know generally won't change
There are thousands of content pieces that fall into this category. With only a few hours training, I believe, a team of FEC folks could work on adding them to CMS at the same time as our team works on the more complicated pieces. This strategy will help us get the migration much further underway before the end of the fiscal year. It's good for the project, and it's also a good success indicator for our FEC partners.

# To do
I opened this issue is to think through what content pieces will be unchanged and to identify some FEC folks who can help us do the rote, _very enjoyable ;)_ work of adding thousands of Wagtail pages. 

**These are the things I think qualify as "Content we know generally won't change":**
- FEC Records
- Press releases
- OIG reports
- FEC Forms
- Historical meeting agendas, public hearing agendas, Sunshine notices of meetings

In total, this is ~10,000 FEC.gov pages (25% of the website). I want to have a conversation about whether there's a research/historical/recordkeeping need for all of these items (there may be! I just want to double check). No matter what, there's certainly room to get people involved in helping us with this. 

**_Last note:_** We won't actually start migrating pages until we have our new information architecture finalized and buy-in where we need it from FEC. We'll also need to think through how different content types get treated in Wagtail and design, etc. That's to say, there's a lot in line to happen before this does. But I don't see any reason to hold off on thinking about this and planning strategically for when we are ready.

**Comment by AmyKort** [comment]
Thanks for thinking through all of this. I will start looking for folks who can help with Wagtail--this will be a good opportunity for our staff to practice using the new CMS.

I want to make a plug for hanging onto the historical election results, compilation of state election laws, etc. As far as I know, this is information that doesn't exist in this form anywhere else. For researchers who would like to look at state-by-state election results, we're a fantastic resource you can access without having to leave your desk. I feel the same way about the other things we have listed as "content we know generally won't change." This is information that exists for research purposes on our website and not a lot of other places. So, at least within whatever records management structure applies to these documents, I'd like to maintain easy public access to them.

FEC Forms might be a little different. The current forms obviously need to be on the website. I see a pretty big downside to having obsolete forms on the website where people might find and use them.

**Comment by emileighoutlaw** [comment]
I totally agree that we should keep the historical election results! :) I just haven't figured out what exactly we should do with them yet. I'm thinking thousands of PDFs might not be the ideal format. But you're totally right that there's historical value in these things.

**Comment by AmyKort** [comment]
The historical election results (and the state/federal directories and the compilations of state campaign finance laws) were all conceptualized as books and then broken up into small pieces on the website. Whatever we do with them, I think we should try to put them back together. 

Since these are of interest to researchers, but not "active" information, is it bad to have them as single, book length pdfs? If you want to look at the information, you have to read the book? (says the person who spent 6 years in a glass room reading books that had to rest on pillows)

**Comment by emileighoutlaw** [comment]
I think we've got a good head start identifying folks who might be willing to help out. We've got other GitHub issues where we're working on ways to get this work done with as little disruption to FEC folk as possible leading up to the election. So I'm going to close this one, and as we need to start pulling people in, we'll open up more tailored issues, as needed.
