### ISSUE TITLE
Identify content types for content migration

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#392]
We need to identify the FEC content types before we can decide what kind of look and feel we want each to have in the CMS. Here's a rough first-pass at the content types that exist on FEC.gov

A note about duplication: In short, it's okay! More on that here: https://github.com/18F/fec-cms/issues/400

# FEC content types

### Archived content
Content that's no longer being updated and is clearly denoted as such. This is content that's:
- Outdated
- Useful for historical record (for example, publications that have been split into new betaFEC pages)

Archived content can look something like this:
![52d56226c6ba5dbf34000015](https://cloud.githubusercontent.com/assets/10552702/16784972/4d7eeb5a-4840-11e6-936a-c0b13c65e919.jpeg)
**Picture above:** This is GOV.UK. On archived pages they include a banner that says when content was archived and why. This page is super specific, but, it might be possible for us say something like _"This content was archived as part of the FEC.gov redesign on July 11, 2016 and is no longer being updated."_

### Bio page
These are pages for top-tier folks in the FEC hierarchy (i.e., Commissioners). GOV.UK has a great example of an effective bio page: http://alphagov.github.io/govuk-content-best-practices/snapshots/will-cavendish

### Guidance
Guidance are manuals, handbooks and other documents that give advice or practical steps to users. It's often process oriented.

This includes:
- Electronic filing how-tos
- Best practices
- Reporting help

### Forms
These are forms (and form instructions) users need to complete either online or in hard copy. 

### Legal page
This encompasses a lot of things and may need to be additionally broken down:
- Laws
- Regulations
- Advisory Opinions
- Matters Under Review
- Explanations and Justifications
- Alternative Dispute Program
- Administrative Fine Program
- Matters Under Review
- Requests for additional information

### News stories and press releases 
This includes Record articles, press releases, Weekly Digests, Tips for Treasurers. 

### Organization page
These are pages that give an overview of an FEC or FEC Department's work, responsibilities and priorities.

### Publications
These are things like Campaign Guides and Brochures. Publications stand alone. They're date stamped.

### Reports
The titles of these pages should describe specifically what they are about.

- Audit reports
- FOIA reports
- Inspector General reports
- Performance and accountability reports
- Employee surveys

A little different than the other reports
- Anniversary reports
- Reports about historical election results

**Comment by emileighoutlaw** [comment]
@AmyKort @patphongs — we can talk more about this in our meeting tomorrow morning (how this applies to the migration), but here's a first look at the different content types I pulled from looking at our [full-site content inventory](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit#gid=1605377718)

**Comment by noahmanger** [comment]
Is this issue still in progress, or have you broken everything out to separate issues?

**Comment by emileighoutlaw** [comment]
I think it's done— we'll need to reference this issue in the future, but the task itself is complete. :)
