### ISSUE TITLE
Consider linking to Record articles on Registration and Reporting pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#393]
This issue is to start thinking about if there are Record articles we might want to link to in our "Additional resources" sidebar on checklist pages.

@AmyKort— the Record archive is pretty expansive. Are there particular articles that are popular among filers? Or there are folks whose brilliance we could tap into who know what these useful articles are?

It seems important to identify which articles we'd want to use before we decide how and when to link to them. 

This issue is per discussion in: https://github.com/18F/fec-cms/issues/387#issuecomment-231894174

**Comment by AmyKort** [comment]
All good questions! I don't have any answers! I will start looking for help identifying Record articles that might belong in a sidebar.

**Comment by emileighoutlaw** [comment]
Let's just start with a very small sampling! I don't want Amy Kort to be reading through the entire archive of the Record! Your time is too valuable!!

**Comment by AmyKort** [comment]
Sounds good. For now, let's just focus on the items on this list (not all of them are brochures). 

http://www.fec.gov/pages/brochures/brochures.shtml

**Comment by emileighoutlaw** [comment]
Great! I'll start thinking about this :)

**Comment by emileighoutlaw** [comment]
We've already figured this out in other issues! Closing. :)
