### ISSUE TITLE
Guidance on content duplication

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#400]
Our content principle is "singularity," which means we don't want to unnecessarily repeat content on betaFEC. This is a tricky topic in large, complicated organizations that have a lot of different content types. 

As @AmyKort so wisely pointed out, FEC might encounter the following situation:

An Advisory Opinion is issued, and it changes Registration and reporting guidance. As a result, the following content is produced:
- Full-text Advisory Opinion published in `Legal resources`
- An explanation of the Advisory Opinion published in the `FEC Record`
- A press release announcing and explaining the Advisory Opinion is sent out to media subscribers and saved in the `Library` of publications
- Practical guidance to committees is updated for the `Registration and reporting` content
- Later, when campaign guides are being edited (in their own publication cycle), they're updated as well.

This seems like a lot of duplication, but it isn't! (hooray!) I think it's easiest to explain this in the context of what "one content one place" intends to do:
- Reduce the burden on busy FEC content managers tasked with updating information on the website
- Reduce the burden on users trying to find information they need on the website 
### The burden on content managers

Content managers won't ever have to update the FEC Record, the press release, the tweet, or the full-text Advisory Opinion. They're snapshots in time, part of the historical record, and they don't ever change.

The only pieces of content that might need updating are campaign guides and Registration and reporting content. That's a manageable amount of content to track and update. 

Limiting the amount of content that might need updating protects the FEC from a situation where a content manager is tasked with updating "Everything that talks about X topic," and that content manager misses a page or two — suddenly the website has conflicting information. Conflicting information is one of the worst possible situations in content.
### The burden on users

We want our users to feel confident:
- They're in the right place
- They've found everything they need
- They know what to do next

What's important about each created piece of content (which Amy so smartly identified) is that each serves a different purpose for a different audience. A lawyer will likely read the full-text Advisory Opinion. If there's news interest, a journalist will likely report from the press release. A filer will go to the registration and reporting section of the website to find the requirements that apply to them. 

What we're trying to avoid with "one content one place" is the user feeling they haven't found everything they need to find. This happens on FEC.gov when there are multiple pages that cover similar topics for _the same audience_. Candidate registration is a good example of this.

There's the candidate registration brochure: http://www.fec.gov/pages/brochures/candregis.shtml
There's also the registration toolkit: http://www.fec.gov/info/toolkit.shtml
There's also the candidate quick answers: http://www.fec.gov/ans/answers_candidate.shtml

For candidates to fully understand how and when to register, they need to find and read all of these pages. Finding them all is hard, because the website structure is a little opaque right now. And once they've found them, they might wonder "if there are at least three pages, how do I know there aren't four or five that I'm missing?"

**Comment by emileighoutlaw** [comment]
@AmyKort — let me know if this is helpful for thinking through what you brought up in the GitHub thread about FEC brochures: https://github.com/18F/fec-cms/issues/387

**Comment by AmyKort** [comment]
This is super helpful--especially reading it alongside the results from the IA testing. The idea of evaluating content as either a "snapshot" or as something we need to maintain really clarifies my thinking. Thank you!
