### ISSUE TITLE
Improve nonconnected committee registration page

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#407]
I'm working on unifying our registration and reporting landing, and fell down a rabbit hole that led me to our [nonconnected registration page](https://beta.fec.gov/registration-and-reporting/nonconnected-committee-registration/).

Basically, here's what it looks like now:

<img width="897" alt="screen shot 2016-07-25 at 2 41 08 pm" src="https://cloud.githubusercontent.com/assets/10552702/17118999/38e34870-5278-11e6-9d36-6780faa103aa.png">

By adding one sentence and a few resource sidebar items, this page would be much more comprehensive and helpful. It will also have some added benefits for our registration and reporting landing page, but that's a [separate issue](https://github.com/18F/fec-cms/issues/299). Here's what it could look like with one extra sentence (highlighted) and a couple new resources in the sidebar:

<img width="819" alt="screen shot 2016-07-25 at 2 55 40 pm" src="https://cloud.githubusercontent.com/assets/10552702/17119053/7c0e71b0-5278-11e6-90f3-9cb37c535277.png">

What do you think of this idea, @amykort @amypike?

**Comment by amypike** [comment]
@emileighoutlaw, I like that idea very much.  The fix makes the generic nonconnected material also appropriate for folks interested in information about IEOPCs and Hybrid PACs (and the addition of that sentence means we don't necessarily need to create a separate space for those groups).  The sentence seems very straightforward to me and hews closely to the agency's press releases and the information on our current website but I will run it past our law-talking people here, as well.

**Comment by emileighoutlaw** [comment]
This isn't relevant anymore :)
