### ISSUE TITLE
Essentials checklist styling

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#408]
This is an idea that I think will make it easier for readres to understand reporting requirements on each of the essentials checklist pages.

Right now the checklist pages all look something like this:
<img width="497" alt="checklist styling old" src="https://cloud.githubusercontent.com/assets/10552702/17120745/55d739d6-5283-11e6-9185-6c0cc615d333.png">

The overview of filing requirements is on the same level as the detailed explanation of each report. I don't think that properly captures the fact that the "Filing requirements" page is a general introduction to filing, and the specific report pages are more accurately children of that introduction.

I think the page should look like this instead:

<img width="606" alt="checklist styling proposed" src="https://cloud.githubusercontent.com/assets/10552702/17120790/8aa4c5a2-5283-11e6-9e27-047b7fc01207.png">

We could call that parent page either `Overview of filing requirements` or `Regular filing requirements`.

What do you think @amykort? 

I'd also be curious if @jenniferthibault had any visual design objections.

**Comment by AmyKort** [comment]
Let me run that past our legal review folks. Thanks!

**Comment by AmyKort** [comment]
Generally I think that's a good idea.  One thing (that has caught my eye off an on as we've gone through this) is - can we not have a separate heading for "filing software"  and put it under "Electronic Filing"?  I know it's one more click then to get to it, but it has nothing to do with "Paper Filing" so it seems odd to have it on the same level.  

Otherwise, I think this is fine - assuming that none of the previously agreed upon language is changed and it's just a reorg.

**Comment by emileighoutlaw** [comment]
That's a great question about the filing software page. My understanding was that paper filers often use filing software to prepare their reports and then submit on paper? But I trust that you know much more than I do about this.

We can definitely move the filing software under the electronic heading. How about something like:

<img width="235" alt="screen shot 2016-07-27 at 8 40 09 am" src="https://cloud.githubusercontent.com/assets/10552702/17181774/16bee484-53d6-11e6-943f-96a4a9a7994b.png">

**Comment by AmyKort** [comment]
Good point about the software issue. The solution you propose looks great!

**Comment by emileighoutlaw** [comment]
Great! I'll get a PR in with those changes today. :)
