### ISSUE TITLE
Content migration: Design of library landing page and subpages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#410]
This might be too big for a single issue (and @jenniferthibault can let me know if it is). But I'm trying to make sure we have issues open for migration tasks so FEC can keep an eye on them and see how we prioritize them in our workflows (alongside data needs and legal needs). So here we go!

The first wave of migration from FEC.gov to betaFEC will be the `Library`. To begin moving content we need to design the following pages:

- Library landing page 
    - The Record subpage
    - Press release subpage
    - Weekly Digest subpage
    - Tips for Treasurers subpage

Issue for the content on these pages: https://github.com/18F/fec-cms/issues/409

**Comment by jenniferthibault** [comment]
First step: wireframing! Determine what lives where & in what formats

**Comment by noahmanger** [comment]
Wireframes done. Next steps are visual styling #455 and documenting #426
