### ISSUE TITLE
Make contact page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#42]
So we don't actually have a contact page. We have a link for it in the utility nav and several points in the content link to it. @emileighoutlaw have you thought about this?

**Comment by noahmanger** [comment]
Disregard. Of course you have! I just found it. I'll make it.

**Comment by noahmanger** [comment]
BUT. We don't have an about page though have a link for it in the utility nav. Do we want that still?

**Comment by emileighoutlaw** [comment]
Good thought! Let me reach out to Amys about it!

**Comment by emileighoutlaw** [comment]
This has been added. :)
