### ISSUE TITLE
Update comms strategy for FEC

### ISSUE THREAD

**Issue by jeanninehunter** [18F/fec-cms#420]
I'm opening this issue to update some of the benchmarks/milestones and communication/outreach approaches outlined in a [plan developed near the start of the project](https://docs.google.com/document/d/1zFk9rpV8LcdbaaS25K1msRzGnEoi7i0QNR2vrcENatQ/edit#heading=h.luo7pdd2ubbk). 

Will keep in mind specific project management related communication such as our established meetings and what to consider when setting expectations and boundaries for various forms of communication including (but not limited to):
### What is the best message type?
- Status reports
- Meetings
- Updates for the project
### What is the schedule? Frequency?
- Monthly
- Weekly
- Daily
### What is the best delivery method for the message?
- Email
- Meetings
- Blog posts
- News articles/magazine profiles
### Who is the source?
- PMs
- Project team(s)
- developers, designers or other individuals at 18F and FEC 
### What is the target audience?
- civic tech community
- politicos
- community-based organizations and government
  members

(Will keep updating)

**Comment by emileighoutlaw** [comment]
I think we're going to put this on hold for now. Moving to the icebox. Thanks!
