### ISSUE TITLE
Document content migration templates

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#426]

**Comment by onezerojeremy** [comment]
Ok, I have annotated a few of things which won't be easily interpretable from the wires and mock-ups, from an interaction design perspective: 
## Record Article
![recordarticle-desktop-v2-annotated](https://cloud.githubusercontent.com/assets/474916/17607671/3b0dc9ce-5ff5-11e6-8caf-1b55c3e0cefd.png)

## Weekly Digest
![weeklydigest-desktop-v2-annotated](https://cloud.githubusercontent.com/assets/474916/17607676/476c9934-5ff5-11e6-8b1d-f1586b5397e8.png)

## Tips for Treasurers

![tipstreasurers-desktop-v2-annotated](https://cloud.githubusercontent.com/assets/474916/17607693/648d4aea-5ff5-11e6-84a1-04b206633466.png)

## Press Release
![pressrelease-desktop-v2-annotated](https://cloud.githubusercontent.com/assets/474916/17607696/6932a54a-5ff5-11e6-8361-5a97375d0b03.png)

I think we should probably wrap these up in a pdf, but wanted to get eyes on them first.
