### ISSUE TITLE
Work on plan for home page design

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#432]
*Criteria for completion:*
- Write a draft plan for how to attack the home page design; could include:
  - Identify what we need before we can start 
  - Principles about what the home page is and isn't

**Comment by noahmanger** [comment]
The design team met yesterday to start sketching out this plan. The full notes [are here](https://docs.google.com/a/gsa.gov/document/d/1IYauM0cFDDv-7Vi0nARX0XiBYTKvx9_P9vilqzSepJc/edit?usp=drive_web). The notes address the various threats, opportunities and outstanding questions we have about this project, but for the purposes of this issue I just want to highlight the high-level take-aways for our plan moving forward:

The task of designing the new home page for fec.gov is both a product design task in the sense of designing and building a new page that serves user needs, and a process design task in that it will need to address key questions of governance within the organization. We need to work on these two threads in tandem, and our high-level plan reflects this. 

The basic plan:
- Step 1: Stakeholder and user research 
- Step 2: Identify and build consensus around principles and goals for the home page
- Step 3: Design, develop and iterate home page while working through key questions of governance

## Details
### 1. Stakeholder and user research
Before we begin the work designing the page, we've  identified a set of topics and research tasks we need to conduct. This doesn't necessarily entail a full-scale research project, but we want to make sure we have all of the big things understood before go forward.

- Who are the stakeholders? i.e. Who at the FEC has an active stake in what goes on the home page and how those decisions are made
  - What are their needs and concerns?
  - What is their own internal understanding of user needs when it comes to the whole site and the home page in particular?
- What do we currently know about user needs and priorities for fec.gov and what does that tell us about what the home page should do? 
  - Create a re-consolidated, re-synthesized understanding of user needs/priorities, and areas for further research
  - Based on what we currently know, identify holes and opportunities for further user research into priorities
  - Accumulate the research (well organized tests, cropped video snippets, etc)
- Gather Inspiration/examples of successful home pages (especially in government or campaign finance)
- How does the new home page need to accommodate the eventual transition?

### 2. Goals and principles
In order to move forward with actual designs, we need to build consensus with stakeholders around the **principles** the page (and therefore the governance of the page) will live by, and the **goals** it needs to achieve. This will give us a shared yardstick to measure design decisions against, so locking these down early on is key.

### 3. Design, development and iteration
Even though this is the home page, we'll still be following our normal processes when it comes to prototyping, testing, deploying and iterating in the open. We don't need to get this exactly right the first time. Instead we want to build in time to learn from a live implementation via feedback, usability testing and analytics to see if it's meeting the agreed upon goals. 

---

@jenniferthibault @onezerojeremy @nickykrause @porta-antiporta anything to add that I didn't capture here?

**Comment by jenniferthibault** [comment]
👍  to my 👀 . Thanks for the great read-out @noahmanger !

**Comment by noahmanger** [comment]
Copied over to the notes doc as well. Going to close this.
