### ISSUE TITLE
As a user who wants to do everything 100% correctly, I want to see the laws that support information on the FEC's site, so that I understand the legal requirements

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#44]
We need to link to the actual regulations in places where we reference it. Not sure the best resource to use for this. (Eventually it will be eRegs).

![screen shot 2015-09-09 at 11 38 59 pm](https://cloud.githubusercontent.com/assets/1696495/9781697/0f905a1c-574c-11e5-8532-c37ed979aa30.png)

**Comment by noahmanger** [comment]
@jmcarp what's the best way to make changes to CMS content? Should I make them to the production CMS? Or on staging?

**Comment by jmcarp** [comment]
Unlike features that are implemented using code, CMS changes don't automatically propagate from dev to staging, and we haven't talked about a process for keeping the two in sync. Using Wagtail's draft feature might be a good approach here--we can save work-in-progress content in the CMS without publishing it for everyone to see. Sounds like it would be worth talking through a good process here at some point.

**Comment by noahmanger** [comment]
Yeah, we should figure that out eventually. I'm going to go ahead and just make the edits on the production cms now.

**Comment by noahmanger** [comment]
Done.
