### ISSUE TITLE
Create three new Wagtail templates

### ISSUE THREAD

**Issue by adelevie** [18F/fec-cms#440]

**Comment by agriffis** [comment]
Hello!  @scampersand won this contract so I'll be working on it with @amygriffis

Just for reference, the details are in the micropurchase at https://micropurchase.18f.gov/auctions/32

We're planning to dummy up the templates first, then build the page models to support them. We'll add a WIP PR as soon as we have something, so we can get feedback over the course of development.

Please jump in if there's anything else we should know!

**Comment by adelevie** [comment]
Hi @agriffis, thanks for bidding. Looking forward to you send us. We'll do our best to give feedback as often as you need it.

**Comment by noahmanger** [comment]
Resolved by #451
