### ISSUE TITLE
Create "Press kit" for "News" section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#441]
Steps
- [x] Complete research on website PR
- [x] Propose new structure for press kit (not FAQ)
- [x] Submit to FEC for approval
- Implement (UX, design, front end)

**Comment by noahmanger** [comment]
Is there any more you want to do on this, or is it ready for design?

**Comment by emileighoutlaw** [comment]
This is ready for design. I'm reworking some links in the content to be more accessible, but I have a rough draft to share, if we want to open a new issues for design and implementation.

**Comment by noahmanger** [comment]
Closing in favor of new issues for design and implementation
