### ISSUE TITLE
Scrape "FEC Record" pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#457]
So that we can import the content from the FEC Record quickly, scrape all of the pages into a database.

Hopefully this work can build on the scraper built for the press releases in https://github.com/18F/openFEC/issues/1895

**Comment by LindsayYoung** [comment]
http://www.fec.gov/pages/fecrecord/fecrecord.shtml

**Comment by noahmanger** [comment]
There's an improved, work-in-progress display that [they've been putting together here](http://www.fec.gov/pages/fecrecord_redesign/fecrecord.shtml) which will be way easier to scrape.

One thing that I'm seeing, though, is that the taxonomy is different than we had the models originally designed for. It looks like in addition to the category we'll also need a keywords field that can have multiple values.

**Comment by tadhg-ohiggins** [comment]
Not quite sure where to check this in, so I've put it in a gist for the moment. This Python3 script <https://gist.github.com/tadhg-ohiggins/6f62923b0674a5eb915e405e0c252bc8> appears to successfully scrape all of the 1638 articles referred to at <http://www.fec.gov/pages/fecrecord_redesign/fecrecord.shtml>

**Comment by noahmanger** [comment]
Nice! Yeah @LindsayYoung where should these live? Should we just set up a separate repo that contains all the scraper scripts?

**Comment by ccostino** [comment]
Recapping some conversations that took place in Slack, we came to the conclusion that living within the CMS makes the most sense since these are scrapers intended to scrape content to go into the CMS.

**Comment by noahmanger** [comment]
Just made a PR to add it. I ran it once and everything seemed to work as expected. Can we close this issue and move to the next step of importing? @ccostino are you still good to tackle that?

**Comment by ccostino** [comment]
Yes, I should be able to spend some time on that tomorrow (today?) to keep the ball moving forward!  I merged the PR and continue on elsewhere.
