### ISSUE TITLE
Scrape Weekly Digest data

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#458]
So that we can import the content from the FEC Record quickly, scrape all of the pages into a database.

Hopefully this work can build on the scraper built for the press releases in https://github.com/18F/openFEC/issues/1895

**Comment by LindsayYoung** [comment]
http://www.fec.gov/press/weekly_digests.shtml

**Comment by noahmanger** [comment]
I forked @pkarman 's scraper and modified it to get all weekly digests:  https://github.com/noahmanger/fec-scraper/blob/master/fec-digest-scraper

And it worked!

**Comment by noahmanger** [comment]
Going to consider this done since @LindsayYoung loaded it in.
