### ISSUE TITLE
Gather inspiration for home page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#464]
Step 1 of our [home page plan](https://github.com/18F/fec-cms/issues/432) involves various types of research. This issue captures the task of gathering and synthesizing inspiration for the home page.

**Criteria for completion:**
- [x] Collection of home page examples from inside and outside government in one place
- [x] Key findings pulled out

**Comment by jenniferthibault** [comment]
I'm starting [a Murally to collect examples](http://mur.al/bVn2G58w). If you'd like to contribute sites you feel are comparable to the FEC and use successful design approaches, please add in:
- A screenshot
- The URL
- What you find successful about the approach (doesn't have to be scholarly, a few short bullets will do :) )

cc @emileighoutlaw @nickykrause @onezerojeremy

**Comment by porta-antiporta** [comment]
This article in the slacks may be of use: https://18f.slack.com/archives/design/p1471972627001696
