### ISSUE TITLE
Introductory copy for Press homepage

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#481]
@amykort — for our new Press page we have a few new sections of content that we need to write.

I can make a rough draft  of content for them, but since the Press Office is full of brilliant writers, I'd like to give Judy/Christian/etc. the chance to take the reins. 

Needed content:
- [x] 1—2 sentence description of Press Office (for the top of the Press page).
- [x] 1—2 sentence introduction to `Resources for media professionals` (what used to be `Resources for reporters`).

Do you think Press folk would like to take a stab at this in the next couple days, or should I take the wheel? I'm very happy either way. ☺️ 

![image](https://cloud.githubusercontent.com/assets/10552702/18354098/0768d21a-75aa-11e6-8bc3-2c849650e05e.png)

**Comment by AmyKort** [comment]
For the about the press office, can you re-purpose anything from this page? http://www.fec.gov/about/offices/press/press.shtml

**Comment by AmyKort** [comment]
Also, maybe if you have time to write the intro to the resources section, it would be better. That way the press folks can have something to respond to.

**Comment by emileighoutlaw** [comment]
Absolutely. I can definitely repurpose and write something for the Resources intro. I'll get that to you today.

**Comment by emileighoutlaw** [comment]
@amykort — How about this as a jumping off point for sharing and editing with Press folk? 


> ## Press
> The Press Office releases information about Commission actions and campaign finance activity. They respond to press inquiries and help media professionals navigate and understand campaign finance law and data.



> ## Resources for reporters
> This section provides plain language, introductory information about the FEC, enforcement matters and campaign finance law and regulation.

**Comment by AmyKort** [comment]
How about this for the Intro?


The Press Office educates reporters about Commission actions and campaign finance activity, law and regulations. The Office keeps the public up-to-date on Commission activities through press releases and a weekly digest.


And this:


This section provides useful links, background information on Commission regulations and reporting requirements, tutorials on how to download FEC data, and a submission form to request data or ask questions.

**Comment by emileighoutlaw** [comment]
Hey @amykort! The first blurb ( `Press`) looks great to me. 

The second one — for `Resources of media professionals` — still needs a tweak, I think. That section will only have content, and not the inquiry submission form. So how about something like: 

> ## Resources for media professionals
This section provides useful links and background information on the Commission, regulations and committee reporting requirements.

**Comment by AmyKort** [comment]
what about the tutorials?

**Comment by emileighoutlaw** [comment]
Yes! They're coming, but we haven't talked about out how to deal with the videos in the design yet, so they're just a touch behind the rest of the information.

**Comment by AmyKort** [comment]
so, should the blurb address the tutorials now? or is that a second iteration?

**Comment by emileighoutlaw** [comment]
I think it's a second iteration, but a really fast follow. Unless you think it's super urgent? What do you think?

**Comment by emileighoutlaw** [comment]
It's a new week, so I'm resurfacing this! What if the blurbs looked like this, @AmyKort:

> ## Press
> The Press Office releases information about Commission actions and campaign finance activity. They respond to press inquiries and help media professionals navigate and understand campaign finance law and data.


> ## Resources for media professionals
This section provides information on the Commission, regulations and committee reporting requirements.

> _Coming soon_: Tutorials on how to download FEC data.


That way it's clear tutorials are coming soon, but we don't say something exists that doesn't yet exist?

**Comment by AmyKort** [comment]
For the resources text, I think the main issue was that the tutorials weren't listed. So, I think we're probably good there. For the initial text, I think the Press Office preferred:  The Press Office educates reporters about Commission actions and campaign finance activity, law and regulations. The Office keeps the public up-to-date on Commission activities through press releases and a weekly digest.

**Comment by emileighoutlaw** [comment]
Sorry — I pasted the wrong thing there. Mea culpa.

> ## Press
> The Press Office educates reporters about Commission actions and campaign finance activity, law and regulations. The Office keeps the public up-to-date on Commission activities through press releases and a weekly digest.

> ## Resources for media professionals
This section provides information on the Commission, regulations and committee reporting requirements.

> _Coming soon_: Tutorials on how to download FEC data.


And I may actually be able to get the data tutorials into our template before demo tomorrow, in which case we won't have to have _Coming soon_ and can go back to:

> ## Resources for media professionals
> This section provides useful links, tutorials on how to download FEC data and background information on Commission regulations and reporting requirements. 

 :)

**Comment by AmyKort** [comment]
You're awesome! Thank you!

**Comment by noahmanger** [comment]
Sounds like this is resolved. Thanks!
