### ISSUE TITLE
Re-write asset paths on scraped content to go to S3 assets

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#486]
So that all images and PDFs linked to / displayed in press releases and weekly digests show up, rewrite all links to go to the assets in the S3 bucket.

**Depends on:** @patphongs uploading all necessary assets to S3 bucket.

**Comment by LindsayYoung** [comment]
@patphongs has moves a lot of content.

Still working on making the bucket public and then will want to make the bucket named something better.

**Comment by noahmanger** [comment]
For making the bucket public, @anthonygarvan suggested making a manage.py task, a la: http://stackoverflow.com/questions/38196758/how-to-make-s3-bucket-public-in-python

This feels like something for someone other than me to do. Maybe @jontours ?
