### ISSUE TITLE
QA press release and weekly digest content

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#488]
In order for all imported content to look as good as possible, do a QA process of all imported press release and weekly digest content and publish.

Tasks:
- [x] Figure out how far back we care about

**Comment by emileighoutlaw** [comment]
If this becomes an all hands on deck situation (depending on how much we need to review and the turnaround time), I can shift content focus and devote most of my time to review.

**Comment by noahmanger** [comment]
Ok, as I'm beginning to do this work, I'm finding some style things we should decide. 

1. Should the headings be `h2` and sentence case?
Old:
![image](https://cloud.githubusercontent.com/assets/1696495/19166478/86e4ab40-8bbc-11e6-8a0e-e80719921118.png)

Suggested:
![image](https://cloud.githubusercontent.com/assets/1696495/19166491/92cf51bc-8bbc-11e6-9f32-2b50217ef719.png)

2. When do we use bulleted lists?
There's several places where sections contain multiple items. The default style is for them to each be a paragraph, but maybe we should be using bulleted lists?

https://beta.fec.gov/updates/week-of-september-5-september-9-2016/
![image](https://cloud.githubusercontent.com/assets/1696495/19166553/c379f0d8-8bbc-11e6-9db9-a6a2394f89ef.png)

3. Do we bold terms at the beginning of items like this?
![image](https://cloud.githubusercontent.com/assets/1696495/19166560/c98bcfbe-8bbc-11e6-8143-e0cea29a0cff.png)

Here's an example of a page that I cleaned up: https://beta.fec.gov/updates/week-of-september-5-september-9-2016/

And here's the default imported style: https://beta.fec.gov/updates/week-of-august-29-september-2-2016/

cc @jenniferthibault @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Definitely I agree that headings should be sentence case.

Bolding terms can be useful to users when it underscores important words and phrases. In this case, it doesn't feel very useful to have very similar dates as the only thing in bold. Mostly, the bold feels like a way of highlighting where one event ends and another begins. In which case _I do_ think a list would do that equally well.

> ### Upcoming educational programs
> - September 22: Roundtable Workshop/Webinar on Reporting PACs and party committees. More information is available _linkedy link_.
- September 22: Roundtable Workshop/Webinar on FECFile for PACs and party committees. More information is available _linkedy link_.
- September 28: Roundtable Workshop/Webinar on Reporting for for candidate committees. More information is available _linkedy link_.
- September 28: Roundtable Workshop/Webinar on FECFile for for candidate committees. More information is available _linkedy link_.

versus

> ### Upcoming educational programs
> **September 22:** Roundtable Workshop/Webinar on Reporting PACs and party committees. More information is available _linkedy link_.

> **September 22:** Roundtable Workshop/Webinar on FECFile for PACs and party committees. More information is available _linkedy link_.

> **September 28:** Roundtable Workshop/Webinar on Reporting for for candidate committees. More information is available _linkedy link_.

> **September 28:** Roundtable Workshop/Webinar on FECFile for for candidate committees. More information is available _linkedy link_.



As to whether a list or bold is the _right_ visual styling, I'll defer to @jenniferthibault and say that my preference is for list.

**Comment by noahmanger** [comment]
That makes sense to me. I think I prefer bullets in those instances. What about with stuff like this, though ([page](https://beta.fec.gov/updates/week-september-19-23/))

![image](https://cloud.githubusercontent.com/assets/1696495/19172853/e95bdcaa-8bd8-11e6-97dc-fb07aca62963.png)

A lot of content in the digests is essentially lists. Should they all be bulleted?

**Comment by jenniferthibault** [comment]
I'm totally ok with bullets being the default format for lists.

I'm seeing a distinction though that may be helpful. 

Advisory opinions and Audits seem to have a document title with a full explanatory paragraph beneath. In these cases, I think setting each off with the title as an `h4` gives them some distinction, and helps keep it from feeling tooooooooo over-listed.

<img width="1240" alt="screen shot 2016-10-06 at 11 27 21 pm" src="https://cloud.githubusercontent.com/assets/11636908/19178205/9dfd7cdc-8c1e-11e6-9029-7151ec4f6377.png">
<img width="984" alt="screen shot 2016-10-06 at 11 33 28 pm" src="https://cloud.githubusercontent.com/assets/11636908/19178204/9dfa2cc6-8c1e-11e6-9fbe-cd15a13e0d33.png">
<img width="1078" alt="screen shot 2016-10-06 at 11 39 03 pm" src="https://cloud.githubusercontent.com/assets/11636908/19178206/9dff4d6e-8c1e-11e6-98cf-29af97a72312.png">


That means the list/paragraph choice is determined by category:

**Commission meetings:**
- _bullet list_

**Advisory opinions:**
_paragraph_

**Enforcement:**
_intro paragraph_
- _bullet list_

**Alternative dispute resolution**
_intro paragraph_
- _bullet list_

**Audits:**
_paragraph_

**Litigation:**
- _bullet list_

**Outreach:**
- _bullet list_

**Educational programs:**
- _bullet list_

**Press releases:**
- _bullet list_

**Campaign finance reports:**
- _bullet list_

**Upcoming commission meetings and hearings:**
- _bullet list_

**Upcoming educational programs:**
- _bullet list_

**Upcoming reporting due dates:**
- _bullet list_

**Disclosure initiatives:**
- _bullet list_

**Additional research materials:**
_paragraph_


______________________________________________________

While I did this, I noticed something weird. There seem to be duplicate/redundant categories:
- `Educational programs` and `Upcoming educational programs`
- `Commission meetings` and `Upcoming commission meetings and hearings` 

Is this something we want to get into now?

**Comment by noahmanger** [comment]
I never responded, but I really like these suggestions. My only issue is that sometimes the category content varies from week to week. Sometimes a category that you identified as a bullet style either only has one item or it has several rather lengthy items. Do we want to bullets in this case?

I finished all of the 2016 press releases and have done several weekly digests. The digests are definitely more time consuming. They take about 5 minutes each (compared to just 2 for the press releases), and there's about 45 left, which means 3.5-4 hours of work to get through 2016. Before we invest all that time, I'd like to run our suggested formatting by the press office to make sure they agree with our choice of bullets, headings, etc., and with our partners to make sure they want us to spend that time cleaning up prior digests.

**Comment by jenniferthibault** [comment]
I finished making the 2016 Weekly Digests consistent. For a next step, I created an issue to make a formatting guide for these documents so that it's easy to keep them consistent (and in some cases improve existing formatting decisions) in the future. https://github.com/18F/fec-style/issues/544

**Comment by jenniferthibault** [comment]
All 2016 press releases done too!

**Comment by noahmanger** [comment]
Thank you! Closing.
