### ISSUE TITLE
Restore Wagtail admin user bar

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#49]
We disabled the Wagtail user bar in 754fcaef73a4fc40689859f562a0a7e39e6e89ad due to a configuration issue such that the user bar widget cannot be included in an iframe. At the time, we discussed a possible resolution with @dlapiduz: modifying the cloud foundry nginx config to not override `x-frame-options` if that header is already included in the response. Now that we're getting closer to a public launch, it would be great to revisit this issue.

@dlapiduz: is this something we can get onto the devops queue? Would we need formal justification of the request? I'd like to set `x-frame-options` to `sameorigin` instead of `deny`, which AFAICT should be safe for our application.

**Comment by jmcarp** [comment]
Ping @dlapiduz

**Comment by dlapiduz** [comment]
@jmcarp can you give it a try now? you need to send the header though

**Comment by jmcarp** [comment]
@dlapiduz looks like it's working--thanks for the fix!
