### ISSUE TITLE
Develop updatable visualization of the progress of the website

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#491]
As a follow-on to [1809](https://github.com/18F/openFEC/issues/1809), having a way to vis

**draft completion criteria**
A tool or visualization... 
- [ ] which shows the abstract site structure, based on the [IA](https://github.com/18F/openFEC/files/364672/Proposed.IA.pdf)
- [ ] working off of the content plan, shows where decisions have firmed up high level categories and where items need to be brought in
- [ ] is easily updatable based on progress
- [ ] is easily linkable to issues in github

we'll know we're successful when we have a tool we can use at sprint planning to help show what is done and what is coming, where we need input

this may be too much to load onto a single tool, if we need to drop back we can keep track of it here.

**Comment by noahmanger** [comment]
Thanks for starting an issue for this. Perhaps as part of this tool — or perhaps adjacent to it — it might be good to think of a way to track this IA to the existing content on the site. @emileighoutlaw has a great spreadsheet of _every single link_ on the FEC.gov, and while it's enormous, I think it's useful for keeping our understanding concrete.

That said, I'm not sure _how_ to do it. But that's why I work with smart people :)

**Comment by jenniferthibault** [comment]
Nice completion criteria @onezerojeremy !

Just wanted to say that. Nothing more for the moment, but if I can be useful to you, just let me know.

**Comment by emileighoutlaw** [comment]
I have a document that _I think_ lays out clearly which sections of the IA the FEC feels good about and which sections are in limbo. It also has page counts:

https://docs.google.com/document/d/1gjszYKkFHeeYOalvxVZGD08kb3i1XExEF6_XVRft1Ig/edit

I'd love to talk about how we can turn this into a tool. This is the kind of thing I think would be super interesting for this project and probably helpful to many others. 

What can I do to be helpful? Schedule time for some of us to talk?

**Comment by emileighoutlaw** [comment]
It seems like getting something useful made would help us reach an important, related goal, which is to help our partners communicate the progress of this project to the Commission (and the Commission to oversight and the public). 

That being the case, my questions are:

- What's the easiest format for visualization?
- What's the easiest format for updating as we go?
- What's the easiest format for sharing with our partners?

I asked in our Content Huddle today, and no one has made or used a tool like this before (or worked on something quite like this large-scale beast of a migration). But when I'm asking the questions above, I'm not sure Sketch feels like the most useful way to do this. 

This could be way off base, but as a starting point, what about using:
- A spreadsheet (for easy IA visualization, easy sharing, and easy updating of overall progress through the site in terms of % done) 
- [GitHub Projects](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) for visualizing our streams of work in the CMS

**Comment by onezerojeremy** [comment]
Good points! 

I approached with basically the same principles, namely, keep the day to day migration updating happening in a spreadsheet, and keep the migration work tracked in github. The only thing those don't really give us is a way to see how all these pieces fit together. Which, I think, is where a tool like sketch really excels. 

There are a bunch of pieces of this to bring you all up to date on what I've been working on, so bear with me for the long post. 

### 1. abstract site structure, based on the [IA](https://github.com/18F/openFEC/files/364672/Proposed.IA.pdf). 
Easy part first. Took a crack at porting the IA over and building down the tree of content in one of the branches we've already built out, to see what the relationships looked like and to see how deep our tree was getting. 
#### [Information Architecture, Draft 4, with Registration Detail](https://github.com/18F/fec-cms/files/486492/IA.Draft.1.3.-.top.w.Reg.detail.pdf)


### 2. Show decisions made, and to be made
Concerns I think I heard [articulated](https://docs.google.com/document/d/1QrfA8XHLIOUekQaA1jd_fWEm_9SXI8OYHq3viPLcgDA/edit#) was that they didn't want to lose content, and wanted to be able to communicate the process. Building off the work of the triage buckets, one natural next step in understanding where things are in the process is to understand the process. Well, ahem, processes: the process for content in triage bucket A (retire) is different from that of triage buckets B, C, D, is different from.. you get the point. Oh, and different content has different approval flows, which maybe for some are even TBD. Fun So how do we track where things are in different processes? 

A crack at showing both a given bit of content process is, and to also show where it is in that process: The good news is that these processes have similar elements. 

#### Triage Buckets and Roadmaps

_A. Content that doesn’t meet a user need and which has unanimous agreement at the FEC that it’s not important to keep up in any form. This content will be retired._  *roadmap:*
  1. Triage
  2. Retire

_B. Content that’s required by law (OIG reports, FOIA stuff, etc.) to be included and just needs a home.
C. Documents that have been published, need to be retained for the historic record, and simply need to be accessed (press releases, FEC record, etc.).
D. Content without a clear user need, but for which there’s a clear business need (Commissioner pages). It’s not worth rewriting or transforming this content, but it should be organized in a way that it’s findable and usable. These *roadmaps* feel similar_
  1. Place (in site architecture)
  2. Name
  3. Port
  4. Approve 

_E. Content that’s already good and for which there’s a clear user need (Press content). This content will be lightly edited or re-organized to fit the current style, but doesn’t need a top-to-bottom transformation. Perhaps the roadmap looks like this_
  1. Place (in site architecture)
  2. Name
  3. Port
  4. Edit
  5. Approve

_F. The content that requires the most work. There is a clear user need and we know that the current content is not meeting it. This is where the bulk of energy will be spent._
  1. Research need
  2. Place (in site architecture)
  3. Name
  4. Port
  5. Heavy edit / rewrite
  6. Approve Level 1, 2, 3? (not clear here, but assuming a more involved approval process)


In light of the goals above to show where things are in the process, one way to visualize this might be to see these pieces of the process as a boxes to be checked, with longer processes employing more boxes corresponding to their tasks:
![roadmap](https://cloud.githubusercontent.com/assets/474916/18737209/c5e68784-805c-11e6-9f27-dabe64136484.png)
with a simple one showing just the few steps needed for it:
![roadmap simple](https://cloud.githubusercontent.com/assets/474916/18737212/c88a01f0-805c-11e6-8b3f-93251d5a5dc8.png)
finally, we could in theory have these embedded in the IA 
![sample](https://cloud.githubusercontent.com/assets/474916/18737214/ca3bb2f0-805c-11e6-9cbd-786874b881e1.png)
(though for now, leaving it out)


### 3. Easily updatable, based on progress
Ok so this is a very imperfect solution, and perhaps too imperfect to try. Agreeing that we can and should keep the spreadsheet as the main place of updaing the tracking work; Sketch actually makes it relatively straightforward to grab data from the spreadsheet. If we add a few columns to our spreadsheet
<img width="997" alt="screen shot 2016-09-21 at 11 02 07 pm" src="https://cloud.githubusercontent.com/assets/474916/18737249/1fac6572-805d-11e6-9478-01d55781f8a0.png">
Export a given sheet to csv and translate that to a json file (i used [csv2json](http://www.csvjson.com/csv2json), we can then auto-grab that data and put it in sketch which shows up as filled-in-symbols. 
![screen shot 2016-09-22 at 12 43 19 am](https://cloud.githubusercontent.com/assets/474916/18737316/be75f330-805d-11e6-98c4-8f8980a8e49f.png)
That process is actually really pretty easy, but a downside is that sketch will not keep up with the changes we make in the spreadsheet, so we'll have to re-grab (and probably re-place, frown). Not quite sure how big a deal this will be, or how often we'd need to do it, but pretty sure there are things we can do to make this process easier. (placement-centric numbering in the spreadsheet, tree placeholders in the sketch file, off the top of my head) 


### 4. linkable to github. 
no problem. if we have a link to github in the spreadsheet, we can easily have each content bit linked to it's issue. fun times. (just remember to export those sketch files as pdfs) see: 
[sample.pdf](https://github.com/18F/fec-cms/files/486514/sample.pdf)


### Next steps!
- Feedback, of course! Smart people: I've been moving a lot of little gray boxes around, so I might well be off my rocker. What pieces of this feel valuable? Which feel like a bridge too far? It's possibly time for another synchronous session, after our homepage fun, possibly?

**Comment by onezerojeremy** [comment]
links i forgot last night: a version of the content inventory 
https://docs.google.com/spreadsheets/d/1ZIpbvlLM7cwuB4kCn5YVdSehQ9FozkXejfRYR6vJOSc/edit#gid=1605377718

[IA draft 4 - zipped sketch file](https://github.com/18F/fec-cms/files/487476/IA.draft.4.zip)

**Comment by jenniferthibault** [comment]
This. is. such. a. cool thing!

I'm about to drop a lot of questions, but please don't think they are critical. I am a total IA-diagram n00b, so there's a lot I just don't understand.

I'd also like to nominate that we bring this to next week's design pairing session to walk & talk through, because I think seeing it in action is critical to understanding if it meets our "easy to" criteria.

Ok so the questions I have — which can totally wait to be answered in person, if easier.

**1. Abstract site structure, based on IA**
 - What do you mean by “abstract" here?
 - Are elections pages part of “Profiles” pr part of “Elections near you” ?
 - Listed Candidate profiles, but not Committee profiles or Elections pages. Should those go on here in a spot?
 - What does the gear symbol mean?
 - What does it mean about hierarchy/depth when something goes from 2.3 to 2.4? 
  - related, I think some aren’t updated in the 2.8 spot, and maybe the end of the 3._’s and 5._’s, but I’m not sure because I don’t know how to understand what the number system should be telling me..especially "2.all.4" (IA n00b, sorry!)
 - Do the red outlines on certain boxes mean something? (Administrative fines, enforcement home)
 - If something (like Contribution Limits) is shown under Legal Resources Home and Enforcement Home ands a unique number in each column, does that mean its two pages? That seems to break content principles

**2. Show decisions made, and to be made**
 - Would we really say commissioner’s bio pages don’t have a user need? 
 - Port = migrate? transfer?
 - Conveyer belt/tetris piece. awesome.

Would especially love a demo on what updating this looks like. Your breakdown is really helpful, but I can’t tell if it feels “easy” per @emileighoutlaw  criteria. Maybe with a demo we can all think through if this could do Less to make it mini-vp-er.

**Comment by onezerojeremy** [comment]
These are all really good questions! I'm going to follow up on them, promise, but first: 

After thinking on it a bunch and worrying about things getting out of sync, I think there may be a way we can keep things tied a little tighter to the spreadsheet, which would make the updating process easier.  It's pretty limited, but you can create an [org chart](https://docs.google.com/spreadsheets/d/1ZIpbvlLM7cwuB4kCn5YVdSehQ9FozkXejfRYR6vJOSc/edit#gid=1337743467) in spreadsheets. I tried doing this, and here's what it looks like: 
![screen shot 2016-09-26 at 1 51 43 pm](https://cloud.githubusercontent.com/assets/474916/18845618/7185c2c6-83f0-11e6-8dc9-1ee9c7f81019.png)
