### ISSUE TITLE
Styling for lists and tables

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#494]
With the updated Wagtail (I think that's the issue), we've having some style snaffus with unordered lists, ordered lists, and tables. This is what they're looking like right now:

An unordered list (no styles showing up):
<img width="936" alt="screen shot 2016-09-15 at 9 34 31 am" src="https://cloud.githubusercontent.com/assets/10552702/18553935/16d5167c-7b28-11e6-849d-9a4f7b4c32b9.png">

A table (weird styles and hard to read):
<img width="1032" alt="screen shot 2016-09-15 at 9 33 58 am" src="https://cloud.githubusercontent.com/assets/10552702/18553936/18688186-7b28-11e6-96f1-c2bdd8df80b7.png">

I think it's pretty important these get fixed before Press previews the pages (this change being a sensitive part of the project), but I suspect this might be a visual design or front end challenge. 

cc @jenniferthibault @noahmanger @xtine

**Comment by jenniferthibault** [comment]
Thanks for flagging this @emileighoutlaw — I'd love to know how/where you're getting this up and running in order to see this so that I can help proof in the future!! I haven't seen how any of the scraped stuff looks in the new templates yet.

I am guessing ( but need our front end experts to say for sure) this is a result of the content having been scraped, but not put into the new HTML structures for lists and tables. ?

**Comment by emileighoutlaw** [comment]
Hey Jen! This actually isn't scraped content. It's the `Resources for media professionals` pages, which I entered from scratch. 

Sometimes Wagtail brings in weird styles when we move stuff from Google Docs to Wagtail, but I'm not 100% convinced that's the case with the table styles (which are different in the new version of Wagtail than the old one).

Do you know how to log into Wagtail? If not, can show you how, and you can check these out!

**Comment by jenniferthibault** [comment]
There goes my hypothesis. Stumped.

I'll take the other "how to see this" part of this to Slack. Thanks Emileigh!

**Comment by noahmanger** [comment]
Ah ok. I see what the issue is and it should be an easy fix to make. There's some different classes generated when using the actual table block in the editor, and I made a change to list styling to support the new resources for reporters page. I'll take this one one.
