### ISSUE TITLE
Archive press relase pages by decade

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#496]
There are a lot of pages that are over 10 years old and we created a page for each with a title and and the body is just "PDF" I think in those specific cases, we would be better off with one page of press releases for the decade like:

<img width="1200" alt="screen shot 2016-09-15 at 2 01 33 pm" src="https://cloud.githubusercontent.com/assets/4406333/18568030/de9ce5dc-7b4f-11e6-9514-cf349630977a.png">

Ran this by @emileighoutlaw and she seemed favorable, @onezerojeremy does that sound like a good idea to you too?

**Comment by emileighoutlaw** [comment]
I do think this sounds like a good idea. We'll have HTML press releases going back until ~2006. 

For the things older than that, having one page for each preceding decade that acts as a landing page for these very old PDFs makes complete sense to me. 

👀 also to Jeremy.

**Comment by noahmanger** [comment]
We decided not to do this, so closing.
