### ISSUE TITLE
Discussion: Make a way to publish pages only for authenticated users

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#503]
Something we're encountering as we build out the CMS is that you can't link to pages that only exist in draft form. This is an issue when building out a page of links to other pages that are all sitting as drafts, or when trying to demo a feed of imported press releases. 

My proposal is that we add a model field to pages that basically can be set to true or false if the page should be visible to non-authenticated users. If true, non-authenticated users will be sent to a 404, while authenticated users will see the page as expected. 

I think something like this will be helpful as content teams work through content, but I'm not sure the best way to implement.

Paging @adborden @LindsayYoung @xtine @ccostino for suggestions.

**Comment by LindsayYoung** [comment]
Can you just make them links to where the page is going to be:
<img width="964" alt="screen shot 2016-09-19 at 6 21 21 pm" src="https://cloud.githubusercontent.com/assets/4406333/18654462/1806ff76-7e96-11e6-96bc-828ab8cac15f.png">

**Comment by noahmanger** [comment]
Yep, and that's what we're doing now, but I think that makes it a lot more difficult for content managers to get a feel for what it will be like live and also to review and edit pages.

**Comment by adborden** [comment]
Sad this kind of thing isn't already supported. I would look at
Wagtail's Private Pages[1]. It's different, but maybe in looking at the
implementation we'll see a good way to extend the behavior to what we're
looking for.

[1] http://docs.wagtail.io/en/v1.6.2/advanced_topics/privacy.html


--
Aaron D Borden
Human and Hacker

**Comment by noahmanger** [comment]
Ok, we're using the password protection for now and it seems to be working fine. We can revisit if it seems like another solution would be more helpful.
