### ISSUE TITLE
Weird space around embedded videos

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#505]
I just embedded a YouTube video into a press page, and the spacing below the video is weird in Preview mode:

![video](https://cloud.githubusercontent.com/assets/10552702/18654933/6e3f2d32-7eaa-11e6-9fb8-8b3e7c4b758d.gif)

But it doesn't look like there's any extra space in Wagtail (I looked with "inspect" too). 

If this is a hard thing to fix, I'll pull the embedded video out before we demo with Press Office tomorrow.

cc @noahmanger

**Comment by noahmanger** [comment]
Fixed it by embedding the video in a separate HTML block in the editor:
![image](https://cloud.githubusercontent.com/assets/1696495/18676423/603905a4-7f0a-11e6-977f-3577c964d96c.png)

**Comment by emileighoutlaw** [comment]
Ah thank you!
