### ISSUE TITLE
Auto-generated name for "Latest updates" feed isn't as expected

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#506]
I can't figure out why, but the "Press" landing page is auto-naming the "Latest updates: for media professionals" so that it's called "Press releases" in the sidebar. 

<img width="975" alt="screen shot 2016-09-19 at 9 13 36 pm" src="https://cloud.githubusercontent.com/assets/10552702/18655396/1d795982-7eae-11e6-9a45-613a831415d3.png">

I looked to the extent of my capabilities in the Wagtail template, and I can't figure it out. Tagging in @noahmanger

**Comment by noahmanger** [comment]
Oops. It's a hard-coded value. Got it!
