### ISSUE TITLE
Clean Press section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#508]
Per our demo with Press, before launch we need to:

- [x] Change "media professionals" to "journalists"
- [x] Unify styles for phone numbers on Contact page
- [x] Update FEC Press phone number to 202-694-1220
- [x] Eliminate toll free number
- [x] "Possible violations" and not "violations"
- [x] Fix links in legal resources sidebars from 2 U.S.C. to 52 U.S.C.
- [x] Delete campaign finance data section

Will keep adding to this as feedback comes in. 

@amykort, as we get feedback from the lovely Press folks, if you want to post i here, we'll triage.

**Comment by noahmanger** [comment]
More issues have come in. 

This one seems pretty unobjectionable:
- [ ] Change the photo on the press landing page

These ones require some discussion:
- Disagreement over whether titles should be sentence case
- Request to break out Press Releases and Weekly Digest embedded feeds on the Press landing page into two separate feeds
- Request to (in addition to separate feeds above) also add a button to the Latest Updates page
- Request to change the order of the content on Press Landing page to:
```
Press Releases
Nullam quis risus eget urna mollis ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at lobortis.

[link to Updates page with Release filter preselected]

Weekly Digest
Weekly Digests, published every Friday, summarize the agency's publically disclosed activity such as Advisory Opinions, rulemaking initiatives and closed enforcement matters.

[link to Updates page with Digest filter preselected]

Resources for Journalists
This section provides useful links, tutorials on how to download FEC data and background information on Commission regulations and reporting requirements.

[link to Resources page]

Contacts

Local
202-694-1220 7:00 a.m. to 6:00 p.m., M-F, Eastern Time
press@fec.gov

If you need to reach the Press Office during non-business hours, please call the FEC's Press Officer, Judith Ingram, at (202) 531-2882.

Agency Updates
Nullam quis risus eget urna mollis ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at lobortis.

[link to Updates page no filters applied --- default chronologic descending order]
```

**Comment by noahmanger** [comment]
So, my $.02 on the separate feed issue is that I don't necessarily have a problem with breaking out the press releases from the weekly digest on the press landing page. I wanted to see how that looked, so here it is:

![image](https://cloud.githubusercontent.com/assets/1696495/18732981/155f1d76-801c-11e6-8344-37821078a7f0.png)

I also made a few other small tweaks:
- Moved the "view all" button to the bottom of the feed (again, just to see how it looked)
- Removed the tag from each post, since it's not necessary when there's only one of each. 

---

On the separate-but-related issue of _also_ including a link to the "All updates" view, with no filters applied: this to me feels a little odd. Maybe just because press items are the only ones there. But maybe it's not weird. It could also be something that's more of a call-to-action card in the side.

**Comment by noahmanger** [comment]
And I should add that the number of posts visible on each one could definitely change. I just had a couple samples in my local db, which is why only a few are showing up in each feed.

**Comment by AmyKort** [comment]
We can go ahead and make the titles sentence case. Thank you!

**Comment by emileighoutlaw** [comment]
Just to keep things organized, these are the things we need to sort through:
- [ ] New press photo
- [ ] Split press releases and Weekly Digests into separate feeds
- [ ] Reorder page: Press releases, Weekly Digests, Resources for journalists, contact info

I know we need more info about the press photo, but I generally vote that we make these changes so we can go live and do real testing with users. Let me know if I'm being too trigger happy, though

**Comment by jenniferthibault** [comment]
On the photo—yep, a straightforward change to make, I just need more information (as you said) from Christian and Judy about what they're looking for in that spot, and why the current one isn't a good fit. That will give me better direction to go hunting in, and come back with options. 

What's the best way for me to get in touch with them? @emileighoutlaw do you already have conversations planned with them this week that I could piggyback off of? Or should I email/call them separately?

**Comment by noahmanger** [comment]
Recapping from our conversation earlier, we're going to go with the suggested edits and then test them.

**Comment by noahmanger** [comment]
Ok, here's what I've got, minus the new photo (ignore the floating menu and wagtail button).

![press - fec](https://cloud.githubusercontent.com/assets/1696495/18896528/3fe74b80-84d7-11e6-88c0-54e43d104ade.png)

I extended the pattern we're using elsewhere to show "related content" to include the "Latest updates" card there (we would need an icon for it). And then I took the opportunity to also include links to the calendar and campaign finance data, both of which seem highly relevant, though they're new ideas.

@jenniferthibault feel free to comment here or we can find time to pair too.

**Comment by jenniferthibault** [comment]
I can look at this tomorrow. Today I need to find photo options for Judy.

**Comment by emileighoutlaw** [comment]
Looks like we need to split the intro for press releases and Weekly Digests into two intros. We could do something more comprehensive, like

> Press releases are published as news happens and cover topics like enforcement matters, litigation, meetings information and advisory opinion actions.

> Weekly Digests are published every Friday and summarize the week's publicly disclosed activity, including enforcement matters, litigation, meetings information and advisory opinion actions.

But that feels rather redundant to me, and honestly like more than I want to read. What if we cut it down? So we just get at this:

> Press releases are published as news happens.

> Weekly Digests are published every Friday.

And the more I think about it, I'd like to start with something minimal for testing anyway, to see if journalists actually need any additional information to be successful in their tasks.

**Comment by AmyKort** [comment]
Sounds good. Let's try it.

**Comment by noahmanger** [comment]
I showed this to our critique group (which includes @nickykrause ) and one thing that came up was that the blurb for the press releases in this context might not be super helpful, but that it could be helpful to have specially written blurbs for the Weekly Digests. I don't know that we want to take action on this now, but something to look for in usability testing next week.

**Comment by jenniferthibault** [comment]
These photo options are off to Judy for review:

![screen shot 2016-09-29 at 11 14 40 am](https://cloud.githubusercontent.com/assets/11636908/18961107/dcf2f060-8639-11e6-92b2-43dc057a97ff.png)

![screen shot 2016-09-29 at 11 15 21 am](https://cloud.githubusercontent.com/assets/11636908/18961108/dcf32940-8639-11e6-8256-b7eb3c7e5066.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/535
