### ISSUE TITLE
Legal resources on resources pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#513]
We have some `Resources for reporters` pages that contain outdated Legal resources references.

@AmyKort, can you help me figure out what the correct resources are? 

https://beta.fec.gov/press/resources-journalists/commission-meetings/
<img width="1024" alt="screen shot 2016-09-22 at 11 25 06 am" src="https://cloud.githubusercontent.com/assets/10552702/18756919/4f1cdeae-80b7-11e6-8388-8d1fb38ec141.png">

https://beta.fec.gov/press/resources-journalists/fecs-response-possible-violations/
<img width="1032" alt="screen shot 2016-09-22 at 11 26 00 am" src="https://cloud.githubusercontent.com/assets/10552702/18756939/60d87b58-80b7-11e6-8a2b-2c09a6b0df13.png">

https://beta.fec.gov/press/resources-journalists/fec-enforcement-programs/
<img width="965" alt="screen shot 2016-09-22 at 11 26 35 am" src="https://cloud.githubusercontent.com/assets/10552702/18756959/77c39d5c-80b7-11e6-92cd-62e992b712e7.png">

https://beta.fec.gov/press/resources-journalists/presidential-senate-and-house-candidates/
<img width="830" alt="screen shot 2016-09-22 at 11 27 28 am" src="https://cloud.githubusercontent.com/assets/10552702/18756995/9d64ca7c-80b7-11e6-8eff-a9690bd1b2de.png">
_This one is 5 CFR, so maybe it isn't oudated?_

Related: https://github.com/18F/fec-cms/issues/508

**Comment by AmyKort** [comment]
Sure. There's a conversion chart that starts on page v : http://www.fec.gov/law/feca/feca.pdf

2 U.S.C. 437c(d) = 52 U.S.C. 30106(d)
2 U.S.C. 438(b) = 52 U.S.C. 30111(b)
2 U.S.C. 437g(a)(12) = 52 U.S.C. 30109(a)(12)

**Comment by emileighoutlaw** [comment]
Awesome! Thanks so much

**Comment by AmyKort** [comment]
Thank you!

**Comment by emileighoutlaw** [comment]
We're good to go on this one. Wagtail has been updated. Closing now.
