### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by pratheekrebala** [18F/fec-cms#522]
Hey,

I'm not sure if this is the correct repo to report this on -- It looks like the SSL cert for beta.fec.gov has expired; And because of HSTS settings, the site is completely inaccessible on Chrome, Safari or Firefox (works with exception to cert)

`Expired: Saturday, September 24, 2016 at 7:59:59 PM Eastern Daylight Time`

Thanks,
Pratheek

**Comment by LindsayYoung** [comment]
Thanks for writing in! We are working on getting a new certficate deployed ASAP

**Comment by pratheekrebala** [comment]
Looks like the site is back online now and the certificate is updated, Thank you for the quick resolution!
