### ISSUE TITLE
"Other" language

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#523]
We've heard a number of times, in several places on the website that users would like more clarification about our "other" categories.

## Raising and spending overviews 

<img width="813" alt="screen shot 2016-09-27 at 10 31 05 am" src="https://cloud.githubusercontent.com/assets/10552702/18880474/8aa83df8-849d-11e6-8e93-524a884e843f.png">

Amy K asked for a better explanation of the "other" category.

## Disbursements by purpose

<img width="700" alt="screen shot 2016-09-27 at 10 30 21 am" src="https://cloud.githubusercontent.com/assets/10552702/18880455/7954b608-849d-11e6-83d7-ea99be8a02fd.png">

![image](https://cloud.githubusercontent.com/assets/11817734/17480776/8f96710e-5d47-11e6-9e1a-3ea8172f69b0.png)

Quote from FEC review:
> The by-purpose option is problematic because "Other" is almost always the biggest category.
> Disbursement by recipient tab has bad data or unintelligible data - by purpose isn't useful because of all the "other" data.

**Comment by emileighoutlaw** [comment]
I think this is a @jwchumley or @PaulClark2 question —

Where can I look to figure out the things included as "Other" in these two sections (raising/spending groups and disbursement purposes) ? I've been poking around but not having much success, and it is my fervent hope that one of y'all can help me limit the time I spend hunting that info down.

**Comment by PaulClark2** [comment]
@emileighoutlaw 

"Other" includes contributions and independent expenditures reported by persons other than political committees (Form 5 filers),  communication costs by corporations and membership organizations (Form 7 filers) and donations and disbursements for electioneering communications (Form 9 filers).

Short answer, it's Form 5, Form 7 and Form 9 filers. Of course, all the contributions and donations are in the receipt chart and the disbursements and expenditures are in the spending chart.

**Comment by PaulClark2** [comment]
Form 5
Line 6 - total contributions
Line 7 - total independent expenditures

Form 7 (no line number)
Total communication costs for this perid

Form 9
Line 9 - total donations this statement
Line 10 - total disbursements/obligations this statement

http://www.fec.gov/pdf/forms/fecfrm5.pdf
http://www.fec.gov/pdf/forms/fecform7.pdf
http://www.fec.gov/pdf/forms/fecfrm9.pdf

**Comment by PaulClark2** [comment]
@emileighoutlaw  "other" for purpose of disbursement is somewhat complicated. See openFEC/data/functions/purpose.sql.  "Other" is everything that is not included in one of the other categories. 

```
when code in ('24G') then 'TRANSFERS'
when code in ('24K') then 'CONTRIBUTIONS'
when code in ('20C', '20F', '20G', '20R', '22J', '22K', '22L', '22U') then 'LOAN-REPAYMENTS'
when code in ('17R', '20Y', '21Y', '22R', '22Y', '22Z', '23Y', '28L', '40T', '40Y', '40Z', '41T', '41Y', '41Z', '42T', '42Y', '42Z') then 'REFUNDS'
when cleaned ~* 'salary|overhead|rent|postage|office supplies|office equipment|furniture|ballot access fees|petition drive|party fee|legal fee|accounting fee' then 'ADMINISTRATIVE'
when cleaned ~* 'travel reimbursement|commercial carrier ticket|reimbursement for use of private vehicle|advance payments? for corporate aircraft|lodging|meal' then 'TRAVEL'
when cleaned ~* 'direct mail|fundraising event|mailing list|consultant fee|call list|invitations including printing|catering|event space rental' then 'FUNDRAISING'
when cleaned ~* 'general public advertising|radio|television|print|related production costs|media' then 'ADVERTISING'
when cleaned ~* 'opinion poll' then 'POLLING'
when cleaned ~* 'button|bumper sticker|brochure|mass mailing|pen|poster|balloon' then 'MATERIALS'
when cleaned ~* 'candidate appearance|campaign rall(y|ies)|town meeting|phone bank|catering|get out the vote|canvassing|driving voters to polls' then 'EVENTS'
when cleaned ~* 'contributions? to federal candidate|contributions? to federal political committee|donations? to nonfederal candidate|donations? to nonfederal committee' then 'CONTRIBUTIONS'
else 'OTHER'
```

**Comment by emileighoutlaw** [comment]
Thank you! I'll take a look at this first thing tomorrow.

**Comment by emileighoutlaw** [comment]
Cool! So I think I understand what's happening with these two.

**"Other groups"** should be reasonably easy to explain in plain language. 

But **"other disbursements"** is trickier. It's hard to describe things by what they aren't (for example, saying `an elephant is not a plant or a mineral` gives a vague idea of what an elephant isn't, but doesn't actually tell you much about what it is). 

Is there any way to say what these "other" disbursements include? What kinds of general things they cover? It doesn't have to be a comprehensive list, just a sampling of things that can give folks an idea of what it might mean in some instances?

**Comment by PaulClark2** [comment]
I think we will need to revisit openFEC/data/functions/purpose.sql. I don't think it includes enough terms to capture disbursements we could categorize. For example, "payroll" is not included in the "administrative" category but "salary" is included.

I ran a query on purpose of disbursement descriptions of operating expenditures disclosed on Line 17 of Form 3, Line 17 of Form 3P and Line 21(b) of Form 3X. I excluded 78 purpose of disbursement descriptions (listed in my next post) and still found over 31,000 distinct purpose of disbursement descriptions in the data. The top 100 are below.

PURPOSE	|	COUNT(*)
----	|	----
VOUCHER PRIZE PAYOUTS	|	3747
EVENT SUPPLIES	|	3567
GRASSROOTS POLITICAL ORGANIZING SERVICES (SEE AMERICAN EXPRESS)	|	2915
PAYPAL	|	2577
SUBSCRIPTION	|	2146
TAXES	|	2067
TAXI FARE	|	1936
SERVICE FEE	|	1819
COMPLIANCE SERVICES	|	1772
DELIVERY	|	1765
SEE MEMO ITEMS	|	1739
FUEL	|	1721
REIMBURSEMENT	|	1694
EVENT TICKETS	|	1665
STORAGE	|	1650
WEB SERVICE	|	1644
GENERIC CMTE. SUPPLIES	|	1585
SEE MEMO ENTRIES	|	1568
SERVICE CHARGE	|	1398
SUPPLIES	|	1387
TELEMARKETING	|	1346
COMPUTER EQUIPMENT	|	1318
GENERIC CMTE. EVENTS/MEETINGS	|	1305
DATABASE SERVICES	|	1275
FLOWERS	|	1153
EMAIL SERVICES	|	1065
PULL FROM ADVANCE FOR I.E. LINE 24	|	1047
SUBSCRIPTIONS	|	1001
ADVERTISEMENT	|	976
EMAIL SERVICE	|	897
POLLING	|	881
VENUE	|	859
WEBSITE	|	847
WEBSITE SERVICES	|	845
SEE MEMO	|	841
SERVICE FEES	|	837
RESEARCH	|	835
SEE BELOW	|	833
TAXI	|	819
GENERIC CMTE. TELEMARKETING	|	816
DONATION	|	807
TELECOMMUNICATIONS	|	780
MEETING REFRESHMENTS (SEE CAPITAL ONE)	|	722
CONTRIBUTION	|	718
WEB SERVICES	|	699
WEBSITE HOSTING	|	693
MEMBERSHIP DUES	|	685
WEB HOSTING	|	679
HOTEL	|	657
SEE MEMOS	|	644
EVENT PRODUCTION	|	643
DIRECT MARKETING	|	635
DATA SERVICES	|	623
BING	|	611
TELECOMMUNICATIONS SERVICES	|	601
MERCHANDISE FULFILLMENT	|	581
DATABASE	|	570
REIMBURSEMENT (VENDORS THAT AGGREGATE OVER $200 LISTED BELOW)	|	559
FACEBOOK ADS	|	545
DATA MANAGEMENT	|	534
IN-KIND CONTRIBUTION	|	531
EVENT SPONSORSHIP	|	525
WIRE SERVICES/ ON LINE SVCS.	|	524
STAFF REIMBURSEMENT	|	511
COMPUTER SERVICES	|	500
EQUIPMENT PURCHASE	|	499
COPYING	|	497
DELIVERY SERVICE	|	497
FILING FEE	|	492
IT SUPPORT/MAINTENANCE	|	491
BUILDING MAINTENANCE	|	483
FEE	|	479
SEE MEMO ENTRY	|	477
REGISTRATION FEE	|	473
STAMPS	|	460
DATA SERVICES SUBSCRIPTION	|	460
BOOKKEEPING	|	458
FEES	|	454
PHOTOGRAPHY	|	452
RESEARCH (SEE AMERICAN EXPRESS)	|	449
DELIVERIES	|	439
WEBSITE MAINTENANCE	|	437
PHOTOGRAPHY SERVICES	|	435
PUBLICATIONS & SUBSCRIPTIONS	|	426
COMPUTER SUPPORT	|	418
CAR SERVICE	|	417
TELECOMMUNICATION SERVICES	|	415
DATABASE MANAGEMENT	|	412
CAB FARE	|	400
TRAIN FARE	|	394
EVENT PLANNING SERVICES	|	384
GIFTS	|	384
GENERIC CMTE. SUBSCRIPTIONS	|	382
MEETING REFRESHMENTS (SEE AMERICAN EXPRESS)	|	378
RESEARCH MATERIALS	|	376
CAMPAIGN STAFF	|	376
EMPLOYEE BENEFITS	|	370
AUDIO VISUAL SERVICES	|	369
TECHNOLOGY SERVICES	|	368
ORGANIZING SERVICES	|	362

**Comment by PaulClark2** [comment]
These 78 purpose of disbursement descriptions include those found in openFEC/data/functions/purpose.sql plus descriptions I added -- like "payroll" and "wages."

```
and purpose not like '%SALARY%'
and purpose not like '%SALARIES%'
and purpose not like '%PAYROLL%'
and purpose not like '%OVERHEAD%'
and purpose not like '%TRANSPORTATION%'
and purpose not like '%MILEAGE%'
and purpose not like '%GAS%'
and purpose not like '%PARKING%'
and purpose not like '%BANK%'
and purpose not like '%AIRFARE%'
and purpose not like '%MERCHANT%'
and purpose not like '%CONSULTING%'
and purpose not like '%INTERNET%'
and purpose not like '%TRANSACTION%'
and purpose not like '%SHIPPING%'
and purpose not like '%INSURANCE%'
and purpose not like '%PROCESSING%'
and purpose not like '%BINGO%'
and purpose not like '%SOFTWARE%'
and purpose not like '%FLIGHT%'
and purpose not like '%AIRLINE%'
and purpose not like '%UTILITIES%'
and purpose not like '%WAGES%'
and purpose not like '%HEALTH%'
and purpose not like '%FOOD%'
and purpose not like '%PER DIEM%'
and purpose not like '%ADVERTISING%'
and purpose not like '%PHONE%'
and purpose not like '%RENT%'
and purpose not like '%POSTAGE%'
and purpose not like '%OFFICE%'
and purpose not like '%FURNITURE%'
and purpose not like '%BALLOT%'
and purpose not like '%PETITION%'
and purpose not like '%PARTY FEE%'
and purpose not like '%LEGAL%'
and purpose not like '%ACCOUNTING%'
and purpose not like '%TRAVEL%'
and purpose not like '%AIRFARE%'
and purpose not like '%CREDIT CARD%'
and purpose not like '%COMMERCIAL CARRIER TICKET%'
and purpose not like '%PRIVATE VEHICLE%'
and purpose not like '%CORPORATE AIRCRAFT%'
and purpose not like '%LODGING%'
and purpose not like '%MEAL%'
and purpose not like '%DIRECT MAIL%'
and purpose not like '%FUNDRAISING EVENT%'
and purpose not like '%FUNDRAISING%'
and purpose not like '%MAILING LIST%'
and purpose not like '%CONSULTANT%'
and purpose not like '%CALL LIST%'
and purpose not like '%INVITATIONS INCLUDING PRINTING%'
and purpose not like '%CATERING%'
and purpose not like '%EVENT SPACE RENTAL%'
and purpose not like '%GENERAL PUBLIC ADVERTISING%'
and purpose not like '%RADIO%'
and purpose not like '%TELEVISION%'
and purpose not like '%PRINT%'
and purpose not like '%RELATED PRODUCTION COSTS%'
and purpose not like '%MEDIA%'
and purpose not like '%OPINION POLL%'
and purpose not like '%BUTTON%'
and purpose not like '%BUMPER STICKER%'
and purpose not like '%BROCHURE%'
and purpose not like '%MASS MAILING%'
and purpose not like '%PEN%'
and purpose not like '%POSTER%'
and purpose not like '%BALLOON%'
and purpose not like '%CANDIDATE APPEARANCE%'
and purpose not like '%CAMPAIGN RALL%'
and purpose not like '%TOWN MEETING%'
and purpose not like '%PHONE BANK%'
and purpose not like '%CATERING%'
and purpose not like '%GET OUT THE VOTE%'
and purpose not like '%CANVASSING%'
and purpose not like '%DRIVING VOTERS TO POLLS%'
and purpose not like '%CONTRIBUTIONS%'
and purpose not like '%DONATIONS%'
```

**Comment by emileighoutlaw** [comment]
Thanks so much, @PaulClark2 ! This is incredibly helpful and comprehensive. I'm going to mull this and sketch some ideas. I'll report back soon

**Comment by emileighoutlaw** [comment]
For the raising and spending charts, I think the lowest interaction cost would be to add a definition in the glossary for "other" groups. That could look like this:


<img width="1104" alt="screen shot 2016-10-11 at 8 23 55 am" src="https://cloud.githubusercontent.com/assets/10552702/19272007/89a47292-8f8c-11e6-9d0e-139ca0417cb9.png">


I don't there's anywhere else on the website where we have `"other" groups`, which is the only reason a glossary definition would be problematic.

**Comment by noahmanger** [comment]
Ok, I added this definition to the glossary. For parity, I also changed the label on the chart to "Other groups" instead of "Other":

![image](https://cloud.githubusercontent.com/assets/1696495/19541639/a3a0aa30-961c-11e6-944c-522d20194e06.png)

I left out the quotes around "Other" because as it's currently coded up it can't support quotes. Is that ok?

**Comment by emileighoutlaw** [comment]
I do think it's slightly more clear with quotes, but it's not a deal breaker to leave them out.
