### ISSUE TITLE
Search content consistency

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#531]
We have many different styles for placeholder text across searchable sections of the website:

<img width="273" alt="screen shot 2016-09-29 at 2 54 15 pm" src="https://cloud.githubusercontent.com/assets/10552702/18969922/e17611ce-8654-11e6-819a-b7de7b3502e8.png">

<img width="871" alt="screen shot 2016-09-29 at 2 55 08 pm" src="https://cloud.githubusercontent.com/assets/10552702/18969927/e4639f0a-8654-11e6-84f0-643bf03b3f0e.png">
<img width="1034" alt="screen shot 2016-09-29 at 2 54 09 pm" src="https://cloud.githubusercontent.com/assets/10552702/18969934/e6b32c62-8654-11e6-9a2c-c22700c727a5.png">
<img width="267" alt="screen shot 2016-09-29 at 2 54 00 pm" src="https://cloud.githubusercontent.com/assets/10552702/18969924/e2e220de-8654-11e6-8020-176ba8a8dae8.png">
<img width="751" alt="screen shot 2016-09-29 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/10552702/18969938/e8cbcd38-8654-11e6-9532-7984b1de2d22.png">

My preliminary reaction is to say we should _eliminate_ the placeholder text and see how it goes. 
- Because of content research done by GOV.UK, we know that people don't understand what `e.g.` means, so that likely is adding confusion to our glossary
- On the beta.fec.gov/data landing page search box `Search for` doesn't particularly contain any helpful information. And it feels like it's a cut-off phrase.
- In the case of the mega-menu, we're basically repeating the content directly above the search box, and we know that adding extra words makes it harder for readers to focus their attention.
- We have a number of places on the website where search boxes are already blank, and we have tested those extensively, and they seem to be working pretty well.

I'd like to open this for discussion, esp. with @jenniferthibault @nickykrause @onezerojeremy and @noahmanger who might have also thought about this. The only thing I'm 100% set on is hammering out some logic and consistency for what we do with placeholder text on this site.

**Comment by jenniferthibault** [comment]
I love love looooove this. 100% in support of consistency, and trust your guidance on the best content strategy to carry it through. I don't see any visual/style implications.

**Comment by nickykrause** [comment]
Hooray for consistency! Thanks for logging this, @emileighoutlaw 

A few thoughts:
- I totally agree about maintaining consistency whenever possible
- I also agree that some of those placeholder text options are not particularly useful (e.g., "search for")
- There is [some evidence from Nielsen Norman](https://www.nngroup.com/articles/form-design-placeholders/) to suggest that placeholder text can be harmful, and that there are better options for providing in-context hints to help people use entry fields.

Building on the last point, if there are places where specific in-context hints would be helpful (or even essential), then we should keep some kind of assist mechanism. In some of the examples you provided, the assist already seems to be there.

For example, the Location search box requires that users search by ZIP, but there is already text denoting that above the field:

<img width="356" alt="screen shot 2016-09-30 at 12 41 11 pm" src="https://cloud.githubusercontent.com/assets/1450173/19000965/e3d71772-870a-11e6-9ef5-63710aadbdb4.png">

Also, the campaign finance data search field has an example beneath it:

<img width="528" alt="screen shot 2016-09-30 at 12 43 10 pm" src="https://cloud.githubusercontent.com/assets/1450173/19001045/22b33322-870b-11e6-8bbf-01f0db3afb75.png">

The glossary is the only one of the examples you showed that could maybe use an outside-the-box assist:
<img width="225" alt="screen shot 2016-09-30 at 12 42 13 pm" src="https://cloud.githubusercontent.com/assets/1450173/19001073/47d80e98-870b-11e6-8373-907089592889.png">

**Comment by emileighoutlaw** [comment]
Rad! It sounds like we're all on the same page. Steps to completion:

- [ ] Audit all searchbars
- [ ] Remove existing placeholder text
- [ ] Add outside-the-box assists to the Glossary/anywhere else it doesn't currently exist

**Comment by emileighoutlaw** [comment]
Renamed this issue to "search content consistency" because I'd like to add more completion criteria.

Currently, we use the phrase "search term" — because elected officials also serve "terms" this could lead to confusion. I propose that we move to "search keyword" instead.


New steps for completion:
- [ ] Audit searchbars
- [ ] Remove existing placeholder text
- [ ] Add outside-the-box assists to the Glossary/anywhere else it doesn't currently exist
- [ ] Replace `term` with `keyword`
