### ISSUE TITLE
Link header to homepage on mobile

### ISSUE THREAD

**Issue by porta-antiporta** [18F/fec-cms#537]
@fec-issue-bot commented on [Wed Oct 05 2016](https://github.com/18F/FEC/issues/486)
## What were you trying to do and how can we improve it?

When I click on the &#34;Federal Election Commission&#34; header it reloads the page instead of taking me to index page. 

Note, this only occurs on mobile.  Desktop works as expected.
## General feedback?

You&#39;re killin it! So many great features. 
## Details
- URL: https://beta.fec.gov/legal-resources/
- User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1

---

@porta-antiporta commented on [Wed Oct 05 2016](https://github.com/18F/FEC/issues/486#issuecomment-251691779)

Thanks for the feedback.  Going to clone this to `fec-cms` where the code change will be needed to be done

**Comment by porta-antiporta** [comment]
@adrianwebb heads up on this issue.  not high priority, but may be a quick fix.

**Comment by emileighoutlaw** [comment]
I just tested this on my iPhone, and it seems like an issue with the Registration and reporting section and the Legal resources section but not the Campaign finance data section
