### ISSUE TITLE
Update legal resources sidebars

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#538]
In our `Registration and reporting` section, we have legal resources sidebars, all of which link to the GPO regs. This needs to be updated to highlight our rad `Legal resources`

<img width="1083" alt="screen shot 2016-10-05 at 4 16 55 pm" src="https://cloud.githubusercontent.com/assets/10552702/19132805/f11d0680-8b1a-11e6-81e4-45ccc151c3f6.png">

---

**Completion criteria:**
- [x] All references to regulations go to our site rather than GPO

**Comment by noahmanger** [comment]
This is done.
