### ISSUE TITLE
Unify legal citations

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#544]
h/t to @jenniferthibault for noticing a couple areas we need consistency for our legal citations.

<img width="892" alt="screen shot 2016-10-07 at 10 13 43 am" src="https://cloud.githubusercontent.com/assets/10552702/19195383/0ed0911c-8c77-11e6-8f79-877d59b6570c.png">

- [x] It's weird to call the sidebars in `Registration and reporting` _Legal resources_, since this isn't the same as the section of our website called `Legal resources`. I vote we change these to _Legal citations_.
- [x] We have some inconsistency in our linking, whether our hyperlinks are [11 CFR 111.11]() or 11 CFR [111.11](). 
  - Because we often have several citations in a row — _11 CFR [111.11(a)](), [(b)]() and [(c)]()_ —  I think we should unify our style to match what's currently in `Registration and reporting` (i.e., **not** hyperlinking the 11 CFR part). 
- [x] All citations should point to our website, not to GPO
- [x] Style question: Do we use periods, a lá `U.S.C.`, or no periods a lá `CFR`
- [x] Style question: Do we use  `§` or `section`
Pinging @amykort, in case she has concerns about this microcopy decision!

**Comment by AmyKort** [comment]
Sounds good!

**Comment by emileighoutlaw** [comment]
Note: this could be a good early task for content managers.

**Comment by emileighoutlaw** [comment]
For discussion: Our use of `§` vs. `section` has been inconsistent, too.

**Comment by emileighoutlaw** [comment]
Hey @AmyKort — a couple of style questions! (If you aren't the right person to answer, can you help us track down the right person? Cheryl maybe?)

1. Should it be `U.S.C.` or `USC`? 
1. Should it be `C.F.R.` or `CFR` ?
1. Should it be `§` or `section` ?

**Comment by AmyKort** [comment]
U.S.C.
CFR
The symbol--don't write it out.

**Comment by emileighoutlaw** [comment]
Perfect! Thanks, Amy.

**Comment by emileighoutlaw** [comment]
One more question — 

Is it:
> 11 CFR § 112.1(a)

or

> 11 CFR 112.1(a)

**Comment by emileighoutlaw** [comment]
Answered in person!

**Comment by emileighoutlaw** [comment]
Preferred style is as follows:

Regulations
> 11 CFR 112.1(a)

Statutes
>  52 U.S.C. §30123


Moving to implementation

**Comment by emileighoutlaw** [comment]
This will be complete when we have unified
- [ ] Interface text citations
- [ ] Candidate registration and reporting citations 
- [ ] Corporation and labor organization registration and reporting citations 
- [ ] Nonconnected committee registration and reporting citations 
- [ ] Party committee registration and reporting citations

**Comment by emileighoutlaw** [comment]
We have one outstanding inconsistency to deal with in our legal citations:

Currently, there’s inconsistency in we use the section symbol for CFR sections:
- In sidebar references and in paragraph text, we don’t use the section symbol, for example, `11 CFR 111.11` (See the [Getting a treasurer](https://beta.fec.gov/registration-and-reporting/get-treasurer/) page for an example of this style)
- Conversely _inside_ the CFR viewer, we do use the section symbol, for example  `§ 111.11` (see the [eRegs viewer](https://beta.fec.gov/regulations/9031-1/2016-annual-9031#9031-1) for an example of this style)

Tadhg and I consulted GPO style, and (surprise!) it also is inconsistent and seems to lack clear guidance about this question. So I think we’re safe to make our own decision about how and when to use the section symbol.

In print editions of the CFR, the “section" symbol indicates to readers that they have moved into another section of the reg. That’s doesn’t feel necessary in an eRegs viewer, where sections are given discrete screen space. 

It also seems like there’s nice consistency for users that if they click a link called `111.11`, they go to a page labelled `111.11`. (It also eliminates the question about whether we use a space after the `§`, which could lead to further inconsistency in the interface).

That seems to indicate to me that we should move from this:

<img width="895" alt="screen shot 2016-11-21 at 4 00 05 pm" src="https://cloud.githubusercontent.com/assets/10552702/20503856/30d6bb40-b00a-11e6-82d5-e86bec73c121.png">



To this:

<img width="889" alt="screen shot 2016-11-21 at 3 59 57 pm" src="https://cloud.githubusercontent.com/assets/10552702/20503850/29ef2fc4-b00a-11e6-8a79-f6083a53bb8b.png">



That said, this is not a hill to die on. So if there’s strong feelings about this over at FEC, we should go with that. 

Any thoughts on this @amykort ?

**Comment by emileighoutlaw** [comment]
Hey @AmyKort — any thoughts on the above comment?

**Comment by AmyKort** [comment]
Thanks for pinging. I think we can live with this inconsistency for now.

**Comment by emileighoutlaw** [comment]
Thanks Amy! This issue is done for now, then. I'll make an icebox issue for the eRegs viewer, which we can look at again later, if we have time.
