### ISSUE TITLE
Design template for statistical press release

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#550]
These types of press releases are a little more structurally complex than regular press releases, and might need their own template. They often include multiple sections, tables, and footnotes.

Here's an example: http://fec.gov/press/press2016/news_releases/20160627release.shtml

**Comment by patphongs** [comment]
@jenniferthibault -- Found this ticket today that relates to helping the press office be able to publish statistical releases a little easier using design templates. The major pain point is the construction of the tables, which involves a lot of manual copy and paste to be able to construct. Also aligning the financial tables in the tables have been another issue. cc @AmyKort

**Comment by jenniferthibault** [comment]
Yes! This is exactly the existing issue I was talking about, (though funny, I thought Noah made it, not me).

I'm adding the Sprint 6 label so this comes up in sprint planning next week, and will link it from the issue we filed for addressing this, and the other feedback points today in https://github.com/18F/fec-cms/issues/762

Thank you @patphongs !

**Comment by jenniferthibault** [comment]
I'm focusing on three areas where the design is of these press releases differ from regular releases: 
- More hierarchy and sections within each press release
- Table formatting: financial total & regular data listings
- Footnotes for these tables


### More hierarchy
This is the easy one! We should use the same heading formatting and structure that we do in all other Latest Updates materials

### Table formatting
We've also established design patterns for these two scenarios. I'm thinking that for mobile, 

#### Financial total tables
Designed by not yet implemented: We've just set the pattern for tables that need to show basic totals and subtotals on the [Candidate profile pages](https://github.com/18F/openFEC-web-app/issues/1783#issuecomment-276089226)

Here though, there are more categories and more columns. It might be necessary to allow these tables to escape the content container and be full-width. ❓ Is something like that possible in the CMS? 

![screen shot 2017-01-31 at 4 21 59 pm](https://cloud.githubusercontent.com/assets/11636908/22485466/d1ff8bf4-e7d3-11e6-8416-76b5b70622f6.png)
![screen shot 2017-01-31 at 4 22 15 pm](https://cloud.githubusercontent.com/assets/11636908/22485465/d1fb7668-e7d3-11e6-83f5-1b59d9214db1.png)


#### Data tables
This format is definitely nothing new, but I'm not sure it it's available in the CMS interface yet ❓ 
![screen shot 2017-01-31 at 4 39 56 pm](https://cloud.githubusercontent.com/assets/11636908/22485493/ec8103b8-e7d3-11e6-81c1-ed9544c544bd.png)


❓  @noahmanger / @xtine is something like this possible? I'm not sure what data entry looks like for tables in the CMS, and how much of this design would mean too much customization.

#### Mobile formatting for tables
The mobile pattern we use for data tables probably also makes sense here: reduce the table to the first column, then put the remaining columns' information in the panel:

<img width="399" alt="screen shot 2017-01-31 at 4 45 00 pm" src="https://cloud.githubusercontent.com/assets/11636908/22485760/dd8a792e-e7d4-11e6-8089-9554b04193cd.png">
<img width="398" alt="screen shot 2017-01-31 at 4 45 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/22485759/dd840fda-e7d4-11e6-824a-a84317c94b8e.png">



### Footnotes for these tables
- As seen above, I think we can use our `t-note` class. Again, the complexity probably lies in the CMS interface ❓ 


### Overall
I'm wondering if these approaches make sense. Would love @noahmanger and @xtine 's thoughts.

**Comment by noahmanger** [comment]
Thanks for thinking forward to implications for implementation! I really like the use of the new styles here and think it helps a lot. But oof, I'm pretty stumped as to how this would be easy to edit in the CMS. Here's what the built-in table editor looks like:

![image](https://cloud.githubusercontent.com/assets/1696495/22534241/98c200c2-e8a7-11e6-9dcf-4dd15f935df6.png)

It gives you the option to set table headers and column headers, but other than that, there's really no way to format the rows differently. 

While it might be possible to customize this, I can't imagine that it would be particularly easy. Can you think of any way we might be able to work within these constraints? Perhaps we break things up into separate tables rather than larger complex tables?

Alternatively, we could achieve your design by just editing raw HTML in the posts. I can't speak to the viability of this, but it's something we could check on. Especially if it's just a matter of copying and pasting a code snippet and then changing the numbers, maybe that's ok.

The same goes for the details panel. This is a pretty advanced component that we created for the data tables, and would be really tough to extend to this case. For mobile, what if we simply set it to scroll horizontally? It's not ideal, but it works.

**Comment by xtine** [comment]
Like @noahmanger mentioned, Wagtail does support a TableBlock (http://docs.wagtail.io/en/v1.5/reference/contrib/table_block.html), but it is limited in that just the first column/row can be headers.

@jenniferthibault: if it's possible to design tables with just just the first row and/or colums as headers, then it shouldn't be difficult as the customization of that style of built-in TableBlock shouldn't be difficult. I think it's anything beyond those constraints that we would have to really think outside the box (table? ha ha) but could be more challenging or time-consuming to implement.

**Comment by jenniferthibault** [comment]
Working within the default structure will result in more tables per table (if that makes sense) but looks do-able. It will require more training for FEC users, and changes to how they're used to presenting data, so I'd like to check with them.

Going this route, there are a few styling and structural changes that would make for much better reading experiences. 

I reworked [the table above](https://cloud.githubusercontent.com/assets/11636908/22485465/d1fb7668-e7d3-11e6-83f5-1b59d9214db1.png) using defaults built in on wagtail staging. Then I used what came of that to tweak small things manually in design files & come up with improvements. Left & right mockups respectively below.

The biggest challenge in converting to these styles in mockups on the left, the only way you can achieve a title for the table is alternating`paragraph block` + `table block`. This results in text that's  too far away to feel related. On the right, is a better scenario that I'm hoping we can achieve by finding a way to put a paragraph field inside the table field. Too far-fetched?

![screen shot 2017-02-06 at 5 39 02 pm](https://cloud.githubusercontent.com/assets/11636908/22669601/6148369e-ec93-11e6-9614-83656c2b5351.png)

Here's my list of what I'd tweak (from the pink in-line notes). I'd love to know what's possible out of this:

- [ ] Need ability to have complex Paragraph style headers close to table

- [ ] Add column divider lines

- [ ] Right-align integers.   
Is it possible to do that only for numeric fields? Wouldn’t want the left-hand column of text to be right-aligned

- [ ] Set minimum top/bottom margin between text and row edge

**Comment by noahmanger** [comment]
All those suggestions look do-able to me. It would require some minor tweaks to the Wagtail components, but should be straightforward to do. I think we'd basically make a new component for financial summary tables that had subcomponents (a title and a table) and we could then control styling on that component.

But yeah, let's check with them about if this will work.

**Comment by jenniferthibault** [comment]
Editing my comment above to include a request for a footnote field in the table block ^.

**Comment by jenniferthibault** [comment]
👋 @AmyKort and @patphongs come on down! Looking at Wagtail's table functionality, we're wondering if you think the there's a possibility of adjusting the format used for tables in statistical press releases. (Details below.) Who should we tag into this issue to show & talk with about it?

Since it's hard to add custom formatting to only certain rows in a table besides the first row or first column, it makes it hard to distinguish totals within tables. We could work within this by separating tables into a small series.

So a table like the one below [from this press release](http://fec.gov/press/press2016/news_releases/20160627release.shtml)

![screen shot 2017-02-07 at 9 54 58 am](https://cloud.githubusercontent.com/assets/11636908/22696693/048de75c-ed1d-11e6-83b8-efa57387f9fb.png)

Would end up in a sequence of three, a new table for every category totaled:
![screen shot 2017-02-07 at 10 08 01 am](https://cloud.githubusercontent.com/assets/11636908/22696781/598afe84-ed1d-11e6-9ab9-eef8c6f434d0.png)

This does good things for readability—smaller, bite-sized tables—but takes up more space and will be a change in how the tables have been built by folks in the press office up until now, so we want to check before moving forward.

**Comment by AmyKort** [comment]
@ChristianHilland , what do you think about the proposal above for creating tables in Wagtail?

**Comment by ChristianHilland** [comment]
Sorry for the delayed response. First, thanks to everyone for working on this issue as formatting data summary press releases through Contribute has always been a herculean task. We appreciate your efforts to make it a more manageable process moving forward.  

The smaller tables presented above is fine with us, and we are open to other suggestions and changes that may be in store. One suggestion: would it be possible to right-justify the figures in the cells?

A separate issue involving these releases is that at one point we discussed moving this out of the Press Office's area. Rather than calling it a release, this would be an auto-generated report that would live somewhere on the FEC's website.  @AmyKort and @PaulClark2 does this ring a bell?

**Comment by AmyKort** [comment]
Yep, we were just talking about that. That's still the plan. But I'm really glad we have this table functionality worked out in Wagtail too. Thanks, everyone!

**Comment by jenniferthibault** [comment]
That's great, thanks so much @ChristianHilland ! It's been a while, but I remember formatting most things in Contribute feeling like a Herculean task. 

Aligning numbers to the right should be do-able if I'm interpreting @noahmanger's [comment above](https://github.com/18F/fec-cms/issues/550#issuecomment-277851431) without too much false hope . It definitely makes skimming and comparing numbers much easier, and would match our approach to the (much larger, built differently, but still tables) data tables.

@noahmanger the task of formatting for new table component is ready to go to implementation.

Do you know if you incorporated relocating these while thinking about the site map work? It sounds familiar that we might have talked about having a section for these in the Advanced Data page, but that may not have been settled. Should we make a separate issue?

**Comment by noahmanger** [comment]
Good stuff. I'll make an issue for implementing. 

Re: where they live, I must have misunderstood. I thought we were just using the [statistics from here](http://www.fec.gov/press/campaign_finance_statistics.shtml) but that these "statistical press releases" like [this](http://www.fec.gov/press/press2017/news_releases/20170113release.shtml) would still be press releases?

**Comment by AmyKort** [comment]
I think we'd hoped to be able to automate the process somewhat, where we could set the search criteria and have that information captured periodically automatically in the Advanced Data section rather than publishing the information as a press release. @ChristianHilland and @PaulClark2 , please jump in because I'm talking about things I probably don't understand.

**Comment by noahmanger** [comment]
I remember that conversation now. I totally agree and think it would be an excellent feature. In the mean time, I made a new issue for implementing this table. Thanks all!
