### ISSUE TITLE
Unify taxonomy for FEC documents

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#553]
This is a placeholder issue that's for figuring out what taxonomy scheme we're using for documents like the FEC record and press releases or other pieces of content.

**Comment by patphongs** [comment]
Thanks @noahmanger for creating this ticket. @emileighoutlaw I would like to start using Wagtail to start keeping track of our documents/audio/transcripts and allowing users to upload there documents to this. This would include using Wagtail to upload documents even if their page is only a transition page. Content that is frequently uploaded include:

[Audits](http://www.fec.gov/audits/audit_reports.shtml) (Different types of audit documents)
[Litigation](http://www.fec.gov/law/litigation.shtml) (Court case documents)
[Outreach](http://www.fec.gov/info/outreach.shtml) (Webinar agendas and course docs)
[Commission Meeting Documents](http://www.fec.gov/agenda/agendas.shtml) (meeting documents, audio, transcripts)
[Commissioner Statements](http://www.fec.gov/members/members.shtml)(Both joint and individual statements from commissioners)

**Comment by noahmanger** [comment]
Nice memory tracking this down @patphongs but @emileighoutlaw made a new issue here that has more recent discussion https://github.com/18F/fec-cms/issues/851

Closing this in favor of that.
