### ISSUE TITLE
Create map of FEC cycles by user group need

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#554]
The idea is that a visualization of the FEC's cycles charted by user group and what they need at each point in the cycle could help decide which content is prioritized when, and for how long on the home page.

This will be paired with wireframes in https://github.com/18F/fec-cms/issues/518 to show the content slots and how they would change.

cc @nickykrause 

🎩 hat tip to the brilliant Liz Goodman for helping me distill that this cycle visualization would be a helpful decision-planning tool as we present home page wireframes.

**Comment by nickykrause** [comment]
thanks, @jenniferthibault! (and: ❤️ Liz.)

**Comment by jenniferthibault** [comment]
I've started sketching out a spreadsheet to work on this in Google Drive: [Hompage needs - FEC cycles](https://docs.google.com/a/gsa.gov/spreadsheets/d/1NakZpGwtdH772kmfG9m16y5gfWkN7eiSU1YCN3xrbkk/edit?usp=sharing)

So far I'm choosing to make explicit separate categories for Candidates & All committees in Senate, House, and Presidential elections, but that might turn out to be unnecessary.

For the other user categories, I've referenced our earlier [personas](https://docs.google.com/a/gsa.gov/presentation/d/1ifsusW8FJQogCVFLMSP47qyLS6CC_8l-AA82soeas4o/edit?usp=sharing). 

I'm going to start fleshing this out preliminarily with Lindsay tomorrow morning, then I hope to circulate it to some of the folks from last week's home page meeting (Duane, Debbie, Greg, Christian/Judy) and ask them about what their department specifically prepares for each group at each part of the cycle.

**Comment by jenniferthibault** [comment]
Quick update: this is with Greg & Amy for their additions, and we should be getting it back by middle of this week. After that I'll probably want a little synthesis time with it, possibly tagging in @emileighoutlaw

**Comment by jenniferthibault** [comment]
I've now collected a complete first draft of the content and it's in the spreadsheet: [Hompage needs - FEC cycles](https://docs.google.com/a/gsa.gov/spreadsheets/d/1NakZpGwtdH772kmfG9m16y5gfWkN7eiSU1YCN3xrbkk/edit?usp=sharing)
From the extra review time, we got a tremendous amount of info on what the FEC makes available to users at different points in the cycle, especially in the outreach, filing, and compliance categories. 

The whole timeline is certainly incomplete. Certain events may be off by a month in either direction at different points in time. I expect we'll learn that as we go to apply what's in it to the home page.

I'm starting some synthesis notes in the second tab. @nickykrause I know you excel at this, and will need to digest this on your own for our understanding of how the home page could use this cycle for content placement. I'd ❤️ so much if you'd also share your synthesis/brain dump, either in there or in another doc. I don't have an attachment to where it lives.

@noahmanger and @xtine once we have preliminary take-aways, and an understanding of how/where these may live on the homepage (or while those thoughts are underway?), I'd love to talk with you about what options we have for automating some of this, either from the CMS or...? I don't know all the questions to ask yet, but the FEC has an interest in making the cyclical content post automatically, to whatever extent possible. I don't know how much cart-before-horse we want to do, but I'd like to start thinking about that, and be prepared to talk about it when we demo the wireframes.

**Comment by jenniferthibault** [comment]
Closing this issue because the events have been mapped (see existing spreadsheet above). 

As part of the [New home page epic](https://github.com/18F/fec-epics/issues/13), we'll be using this map to [create an editorial calendar for the home page](https://github.com/18F/fec-cms/issues/605) sometime around sprint 2.

Implementing what will dynamically populate has moved to #606, but is dependent on #605
