### ISSUE TITLE
Build out content management spreadsheet

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#555]
@emileighoutlaw commented on [Mon Oct 17 2016](https://github.com/18F/fec-epics/issues/41)

Our [Content migration spreadsheet](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit#gid=1062425065) :lock: will help us visualize progress throughout the content migration and track old and new URLs, categorize work effort, and manage information architecture decisions.

Tasks to completion:
- [x] Build content inventory
- [x] Organize tabs consistently
- [x] Triage content 
- [x] Build visualizations

cc @amykort

**Comment by emileighoutlaw** [comment]
Happy early birthday to us! The visualizations are done: https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit?pli=1#gid=1062425065

Take a gander!

cc @amykort

**Comment by noahmanger** [comment]
Now that we have visualizations I'm going to close this.
