### ISSUE TITLE
Confirm "retired" content status with content managers

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#556]
@emileighoutlaw commented on [Mon Oct 17 2016](https://github.com/18F/fec-epics/issues/42)

As we triage content, our team will identify content that can be "retired," which means it will not need to move from the legacy FEC site to betaFEC. 

We need to confirm that plan with FEC content managers for each page slated for "retirement" before we can officially mark it as "done" in our content migration tracking spreadsheet.

cc @amykort

**Comment by emileighoutlaw** [comment]
We're good to retire:
- [ ] Old conference and webinar agendas
- [ ] Past years of "What's New"

**Comment by emileighoutlaw** [comment]
@amykort —Thanks for chipping away at this! I know we're good to retire conference agendas. Are we also okay to retire:
- [flyers like this one](http://www.fec.gov/info/state_outreach/2009/kscitymissouriflyer09.pdf)?
- [registration materials like these](http://www.fec.gov/info/roundtable_materials/2016/candidate_registration_2016_screen_fillable.pdf)?
- [general conference info like this](http://www.fec.gov/info/conferences/2016/orlando.shtml)?

**Comment by AmyKort** [comment]
yes

**Comment by emileighoutlaw** [comment]
This can close. We may have to do additional rounds of this in the future, but this task can be closed.
