### ISSUE TITLE
Get FEC content managers set up with Slack and GitHub

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#558]
I can take the lead on this, but I'd like to chat through strategy with you, @noahmanger .

**Comment by noahmanger** [comment]
Do you think the instructions in the 18F handbook would suffice? Or should we tailor for this audience? https://handbook.18f.gov/github/

**Comment by emileighoutlaw** [comment]
Content managers are: Greg, Lauren, George, Dorothy, and Christian

**Steps to completion:**
- [ ] Content managers are set up with Slack
    - Dorothy, Christian, Lauren have an account
    - Greg and George still need an account
- [ ] Content managers have a GitHub account

**Slack:**
@amykort — can I be helpful in getting Greg and George set up with Slack? It seems like y'all have a good process for getting folks into our Slack channel.

**GitHub**
As a starter, it could be helpful for folks to read this overview of GitHub: https://handbook.18f.gov/github/ . It's possible that introduction is a little too detailed (and might be overwhelming).

I'm going to look to Amy and FEC partners again. Do you remember when you were getting set up with GitHub for the first time? What resources were helpful for you? Would it be a good idea to set up a meeting with content managers so they can sign up for GitHub accounts and talk about how GitHub works?

**Comment by AmyKort** [comment]
Usually, as far as I know, our folks get onto Slack because someone on your end creates an account or permission or whatever, and then Slack sends them an email to sign up. Did that already happen?

When I signed up for Github, @PaulClark2 sent me a link and said "Amy, go to this link and sign up." Does that count as a resource?

**Comment by emileighoutlaw** [comment]
Awesome. @noahmanger — do you know who sends that Slack email? Can we resend an invite to George and Greg? (I can pass along their emails to whomever.)

I think I'm going to take a stab at writing a "GitHub for content managers" document that's a little less technical than the advice we have on our website. I'll share here when I have a draft ready.

**Comment by emileighoutlaw** [comment]
Update: 

**Slack**: invites sent to George and Greg.

**GitHub**: I'm going to take a stab at writing up some documentation about GitHub for content managers. We might want to share this tutorial: https://www.youtube.com/watch?v=1-gLxOjkh4k&feature=youtu.be

**Comment by emileighoutlaw** [comment]
Slack is up and running for the whole team.

We'll get managers up and running with GitHub in person (1:1 sessions) next week.

**Comment by noahmanger** [comment]
Anything more to do on this?

**Comment by emileighoutlaw** [comment]
They're still getting GitHub set up. But should be resolved in this sprint.

**Comment by emileighoutlaw** [comment]
Update: the only person we need GitHub confirmation from is Dorothy, who's out on vacation this week.

**Comment by emileighoutlaw** [comment]
Still waiting on final confirmation from Dorothy before I close this

**Comment by emileighoutlaw** [comment]
Greg Scott: FECHoosier
George: gsmaragdis
Lauren: llienfec 
Dorothy: dorothyyeager
