### ISSUE TITLE
Build content principles

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#560]
To help us make decisions later in the content migration project, we need a set of content principles we agree upon as a team of FEC content managers and 18F design folk.

[Content principles](https://docs.google.com/document/d/182PbWOwsYUk2m_zUfrlDrr8HsIv_x8NkGUMAHKps3ZA/edit) :lock:

- [x] Draft content principles
- [x] Share with FEC for feedback at content manager roundtable
- [x] Revise principles based on roundtable
- [x] FEC review

**Comment by emileighoutlaw** [comment]
All the content managers gave a thumbs up to our revised content principles, so that’s a nice step forward! 

Thanks for your hard work on this @amykort

**Comment by noahmanger** [comment]
Any further work on this? Can we close it?

**Comment by emileighoutlaw** [comment]
Nope! No further work :)
