### ISSUE TITLE
Capitalization of "President"

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#563]
In general, I've been pushing hard to keep capitalization to a minimum on this project, because lowercase words are more welcoming and easier to read. Because of this, I strongly encouraged not capitalizing "president." 

However, now that we're further into the project, we've made the decision to capitalize other, specific titles (Commissioner, Secretary of Senate), for clarity on the page. Now, having "president" lowercase feels like a snub to that highest office.

<img width="848" alt="screen shot 2016-10-24 at 10 13 58 am" src="https://cloud.githubusercontent.com/assets/10552702/19651497/b4399afa-99d2-11e6-8df7-080234c21b8d.png">

Anyone object to us updating our style to capitalized "President" when referring to the Office of the President?

cc @amykort

**Comment by noahmanger** [comment]
Makes sense to me.

**Comment by AmyKort** [comment]
Sounds good!

**Comment by emileighoutlaw** [comment]
Just realized we have a bunch of `presidents` in the CMS, so I'm adding to the completion criteria:

- [ ] `president`s in CMS

**Comment by emileighoutlaw** [comment]
Hunted all those suckers down. Closing.
