### ISSUE TITLE
Train press office to use Wagtail

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#565]
There's two things that need to happen before we can release the press content. 
1. Train them on how to create and edit press releases and weekly digests
2. Add any documents that have been published in the last couple weeks

**Comment by emileighoutlaw** [comment]
Great! Do you think we can do this as a remote training, or is this something we should add to the list of things to do when we go back in November?

**Comment by noahmanger** [comment]
I think we need to do this like this week or next; as soon as they're available.

**Comment by emileighoutlaw** [comment]
Sounds like we'll need help from @amykort or @paulclark2 finding time in Press' impossibly busy schedules for us to teach Wagtail.

**Comment by noahmanger** [comment]
When we do this, we need to show them the content guide from https://github.com/18F/fec-style/issues/544

**Comment by emileighoutlaw** [comment]
Update: We'll be training Carmen in person at FEC next week.

**Comment by emileighoutlaw** [comment]
Are we good to close this @noahmanger ?

**Comment by noahmanger** [comment]
Yep! There will be more, but we don't need an issue.
