### ISSUE TITLE
Start thinking about the design of candidate compliance content

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#568]
After completing the audit ( #566 ) , start to discuss the shape of the candidate compliance content with the content manager group.

**Completion criteria:**
- [ ] Create draft outline of candidate compliance content

**Comment by emileighoutlaw** [comment]
We're going to have to wait until Tuesday to talk with content managers. Shall I move this to sprint 26 now, or wait until we meet next?

**Comment by noahmanger** [comment]
Sure. I'll move it.

**Comment by emileighoutlaw** [comment]
I think this is captured now in: https://github.com/18F/fec-cms/issues/630

so I'm closing in favor of that issue.
