### ISSUE TITLE
Port PDF content to new bucket

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#569]
@patphongs  and I looked at content categorized as "Port" in the [content inventory spreadsheet](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit#gid=1062425065) :lock:.

We identified the following as a first round of PDFs that can be ported to a new S3 bucket:
- IG reports: The new pathway should be `/about-fec/ig-reports/`
- Commissioner statements: The new pathway should be `/about-fec/commissioners/`
- Audits: The new pathway should be `/legal-resources/enforcement/audits/`

Notes on progress so far:

**IG reports**
- Pat encountered quite a few duplicates in the inventory spreadsheet. 
- These duplicates are likely because content owners accidentally uploaded the file to two locations and referenced it in links in two locations.
- Pat has already done the hard work of marking which are duplicates. 
- 98 documents were copied over to the S3

**Audit reports**
- 1770 files have been copied over to the S3

**Commissioner statements**
- Again, many of the PDF documents are duplicates. In this case, the documents were uploaded to the website twice (once in the legal search and a second time in the commissioner section). 
- Our plan is to link the Commissioner pages to the MUR document in the legal-resources section.

---

Completion criteria
- [x] Audit PDFs are either moved to a new (public) bucket or are marked as duplicates
- [x] IG PDFs are either moved to a new (public) bucket or are marked as duplicates
- [x] We have clarification as to what in Commissioner statements is maintained by the Public Records department and what is not and can be ported over
- [x] Commissioner statement PDFs are either moved to a new (public) bucket or are marked as duplicates

**Comment by patphongs** [comment]
@emileighoutlaw For IG reports, 98 documents were copied over to the S3. This is excluding the duplicates that were flagged in the spreadsheet. This is all complete.

Commissioner statements needs some more clarification as to what is maintained by the Public Records department and what is not and can simply be ported over. Currently, I've flagged SORs that were uploaded to the web server as possible duplicates under this section, since there is a copy of it inside of the legal search system.

**Comment by emileighoutlaw** [comment]
Awesome. IG is checked off as done, and I added the note about clarifying what's under the Public Records Department to the completion criteria. Thanks thanks!

**Comment by emileighoutlaw** [comment]
Also — I marked the "audit" documents as "research," rather than "implement," because we want to do more design thinking around how they're displayed (as opposed to OIG reports, which we're building a template for already).

**Comment by emileighoutlaw** [comment]
After discussion, our plan is to move the duplicative Commissioner PDFs for now (because of time constraints) and maybe do a cleanup in the future. Sound right @patphongs ?

**Comment by patphongs** [comment]
@emileighoutlaw you are correct, the PDF files for the Commissioners have been move over. We have one slight issue with some documents from former Commissioners being in HTML format. We need to do a little extra leg work for that. See ticket #616

**Comment by noahmanger** [comment]
Now that commissioner PDFs are moved and we have a new issue for HTML pages, I'm going to close this issue.
