### ISSUE TITLE
Migrate fec-cms to new cloud.gov for testing and ATO renewal

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#581]
The purpose of this task is to perform an initial migration of the fec-cms app to the new cloud.gov hosting, which requires:

- [x] Move DB and upgrade to PostgreSQL (James Scott said he might help with this; see also https://github.com/18F/cg-product/issues/690)
- [x] Make sure new relic is going
- [x] Make sure deployment works with the invoke task
- [x] Get the app up and running in the `dev` environment
- [x] Get the app up and running in the `stage` environment

Once we have the app up and running in the new environment we can provide information to the ATO and security audit teams to continue with the ATO renewal process.

**Comment by ccostino** [comment]
I'm going to also use this as an opportunity to have the `staging` and `dev` databases be in sync with `prod`.  Should we import tips for treasurers to `prod` before that happens, @noahmanger?

**Comment by noahmanger** [comment]
Sounds good. And yeah, let's import those.

**Comment by ccostino** [comment]
They are imported and in the latest backup!

**Comment by ccostino** [comment]
I was able to migrate our database over and have things starting to run in the Gov Cloud environment, but I noticed the PostgreSQL version is `9.4.7` - it'd be awesome to be running at least the latest `9.5` release, if not `9.6.1` itself (all of which are supported in Amazon RDS itself).

**Comment by ccostino** [comment]
My wish will apparently be granted soon! :-)

https://github.com/18F/cg-product/issues/690 is the cloud.gov issue for tracking the PostgreSQL update in GovCloud being done by Amazon.

**Comment by ccostino** [comment]
New Relic is working with this instance, by nature of tweaking the logging configuration for the app.  Please see the PR for more details: #801

**Comment by ccostino** [comment]
I shifted some of the work in this issue out to a new one (#805) since this is only the initial migration efforts, not the full site flip just yet.  The only remaining task to do here is getting the app to also run in the `stage` space.
