### ISSUE TITLE
Consistency: 24-Hour report capitalization

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#586]
So far, we haven't been consistent in our capitalization of 24- and 48-Hour Reports:

<img width="285" alt="24 48 needs issue" src="https://cloud.githubusercontent.com/assets/10552702/20064308/dea0646a-a4cf-11e6-8d49-eafa1dac1cb0.png">
<img width="766" alt="screen shot 2016-11-07 at 9 51 53 am" src="https://cloud.githubusercontent.com/assets/10552702/20064350/00afe03a-a4d0-11e6-8174-4a297c29f47e.png">
![screen shot 2016-11-07 at 9 50 40 am](https://cloud.githubusercontent.com/assets/10552702/20064358/07c6f1ba-a4d0-11e6-84ee-1b432d1bdc7e.png)

![screen shot 2016-11-07 at 9 49 02 am](https://cloud.githubusercontent.com/assets/10552702/20064366/0fc38e96-a4d0-11e6-831d-999b14adbee5.png)

![screen shot 2016-11-07 at 9 48 20 am](https://cloud.githubusercontent.com/assets/10552702/20064342/fc877b3a-a4cf-11e6-8588-880cfbd9cb81.png)

<img width="895" alt="24 48" src="https://cloud.githubusercontent.com/assets/10552702/20064319/e4826a22-a4cf-11e6-9e8a-09920371e424.png">

Because the FEC form itself capitalizes `24-Hour Report` as a proper noun, my vote is that we consistently capitalize these, the same way we do `Statement of Candidacy`.

cc @PaulClark2 @amykort

**Comment by AmyKort** [comment]
Yes. Thanks!!
