### ISSUE TITLE
Consistency: Hybrid and Super PAC

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#587]
We don't have a style decision on this yet, but we're reaching the point where we need one for consistency. Should hybrid PAC and super PAC be capitalized or lowercase?

> Hybrid PAC

or 

> hybrid PAC

@amykort — do you have any preference on this one?

**Comment by AmyKort** [comment]
I would capitalize them. If I see hybrid PAC, that could mean anything to me. If I see Hybrid PAC, I think I understand that this is the proper name of a specific thing. What do you think?

**Comment by emileighoutlaw** [comment]
That makes sense to me! It's also consistent with the fact that we've been capitalizing "Commission" and "President" etc.

Secondary question— should we also capitalize `Political Action Committee (PAC)` when we have first references?
