### ISSUE TITLE
Add remaining press releases and weekly digests 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#589]
We have the go-ahead to launch the press section this week, but we need to add content that has been published since we last imported. This will be easiest to just do by hand.

We need to:
- [x] Add 5 new weekly digests http://fec.gov/press/weekly_digests.shtml
- [x] Add 4 new releases http://fec.gov/press/news_releases.shtml

cc @emileighoutlaw @jenniferthibault : Do you want to divvy this up at all?

**Comment by emileighoutlaw** [comment]
I can add them if @jenniferthibault would be willing to do a round of QA when I'm done?

**Comment by jenniferthibault** [comment]
Gladly! Also glad to split it up, whichever you prefer.

@emileighoutlaw can you give the Weekly Digests formatting guide from https://github.com/18F/fec-style/issues/544 a whirl to try it out?  I think you'll be able to get straight to the template in wagtail through this: https://beta.fec.gov/admin/pages/4291/edit/

**Comment by emileighoutlaw** [comment]
Press releases for review: 
- https://beta.fec.gov/updates/fec-cites-committees-failure-file-12-day-pre-general-financial-report/
- https://beta.fec.gov/updates/district-court-denies-plaintiffs-motion-summary-judgment-independence-institute-v-fec/
- https://beta.fec.gov/updates/fec-cites-committees-failure-file-october-quarterly-financial-report/
- https://beta.fec.gov/updates/fec-issues-two-advisory-opinions-and-approves-audit-findings/

The Weekly Digests are taking longer than I thought to create, so how about I take on:
- [ ] Week of October 3 - October 7, 2016
- [ ] Week of October 10 - October 14, 2016

And @jenniferthibault, you can do:
- [ ] Week of October 17 - October 21, 2016
- [ ] Week of October 24 - October 28, 2016
- [ ] Week of October 31 - November 4, 2016


Does that sound okay?

**Comment by jenniferthibault** [comment]
Done!

- [x] Week of October 24 - October 28, 2016: https://beta.fec.gov/updates/week-october-24-october-28-2016/
- [x] Week of October 31 - November 4, 2016: https://beta.fec.gov/updates/week-october-31-november-4-2016/

Reviewed the press releases and digests @emileighoutlaw did, and made a few tiny tweaks. Nice work!

Slightly less great news: the h2's in all of the 2016 weekly digests that Noah and I formatted `Use Title Case` annnnd all the ones Emileigh did use `Sentence case`, which I know is the correct way. D'oh! 

I'm about 1/2 way through fixing all of 2016's to be sentence case, and will finish in the morning.

**Comment by jenniferthibault** [comment]
Scratch that, I hustled though them, and all of 2016 now has Sentence case categories. 

@emileighoutlaw could I trouble you to take a quick general peek in the morning in case there were unwritten rules you were following that I may not have?

**Comment by emileighoutlaw** [comment]
You're a star @jenniferthibault :star2: I made a couple more small changes, but everything looks good to go to me!

One thing for @noahmanger — when I look at the list of Weekly Digests, I'm seeing the formatting guide in the list, even though it's not published. Any idea what's going on?
https://beta.fec.gov/updates/?update_type=weekly-digest

<img width="1176" alt="screen shot 2016-11-08 at 10 34 12 am" src="https://cloud.githubusercontent.com/assets/10552702/20107655/eca07224-a59e-11e6-826e-0207d7e403fb.png">

**Comment by noahmanger** [comment]
Oooh I think I know what that is. Fix coming.

**Comment by noahmanger** [comment]
Thank you!!!

**Comment by noahmanger** [comment]
This is done. Thanks for adding, @jenniferthibault !
