### ISSUE TITLE
Implement additional content types to "Latest updates" feed

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#598]
The `Latest updates` feed should surface content specifically created for users. Therefore the feed will be complete when it includes:

- [x] Press releases
- [x] Weekly Digests
- [ ] FEC Record articles
- [ ] Tips for Treasurers
- [ ] Sunshine notices (notices that a meeting is going to happen and generally what will be discussed at that meeting)
- [ ] Meeting agendas (published after Sunshine notices and including more detail)

If these are the documents to be included in `Latest updates` we'll need to:
- [ ] Decide if/how the filters are affected by these new documents
- [ ] How to port/implement remaining content types
    - Record articles
    - Tips
    - Sunshine notices
    - Meeting agendas

**Comment by emileighoutlaw** [comment]
This issue is a continuation of:  https://github.com/18F/fec-cms/issues/524#issuecomment-261983141

**Comment by noahmanger** [comment]
This is a huge thing and each one of these tasks will involve several steps. Can we move the content from this issue to the Latest Updates epic and close this issue? https://github.com/18F/fec-epics/issues/15

**Comment by emileighoutlaw** [comment]
Yup!
