### ISSUE TITLE
Organize candidate compliance content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#599]
FEC content managers met last week to synthesize all existing candidate compliance content. 

We broke down all existing content as best we could from the mindset of our users (aka, in terms of the questions each division receives from real candidates and committees) . 

The resulting list (to follow) isn’t inclusive of all content topics, but it is broad, first idea of how we think we'd like to explore organizing compliance content. It's also not what we'd _call anything_. 

**Things (money, etc.) coming in**
_This bucket covers information including:_
- Receipts
    - Contributions
        - Lobbyist bundled contributions
        - Joint fundraising contributions
        - Earmarked contributions
    - Fundraising
        - By federal officeholders
- Loans
- Transfers
- Disclaimers

**Things (money, etc.) going out**
_This bucket covers information including:_
- Disbursements
    - Operating expenditures
    - Donations
    - Contributions to other committees
- Rates for advertising
- Transfers
- Disclaimers

**Recordkeeping**
_This bucket covers information including:_
- Best practices
- Best efforts
    - Embezzlement
    - Employer occupation
    - Safe harbor (foreign nationals)

**Doing things**
_This bucket covers information including:_
- Other sources of support
- Traveling
- Winding down a campaign

**Presidential public funding**
_This bucket covers information including:_
- Presidential public funding
- Title 26 references

**Outside FEC jurisdiction**
_One thing we'd like to explore is how to weave these topics into pages in the sections above, where they are relevant. This bucket covers information including:_
- FCC 
- IRS
- Ethics

Would love to get any initial design thoughts, if you happen to have them (cc @nickykrause @jenniferthibault @noahmanger )

Once we have an agreed upon organization, the next step will be to start thinking about the naming of the buckets and their subpages and design.

**Comment by emileighoutlaw** [comment]
cc @amykort for visibility :)

**Comment by jenniferthibault** [comment]
@emileighoutlaw I don't have particular thoughts about the items within your organization above, but it does make me wonder about where this all fits in. 

I think most of the templates & flows for these items have been designed (and at various stages of implementation) in this issue: [Create template page for historical archive lists of documents #540 ](https://github.com/18F/fec-style/issues/540)

But before getting deeper in specific design or implementation, I would like to feel more certain about where/how this lives in relation to existing content architecture (home page, registration and reporting).

I know I've thought this aloud before, but I think it would be a promising hypothesis to test out  replacing Reg/Reporting as the top nav item with "Candidate and committee services", and using that as the top organizing category for reg/reporting & compliance. Maybe there's another level needed in between those layers, I'm not sure. A rough sketch would look like this:


- Campaign finance data
  - Profiles
    - Candidates
    - Committees
  - Interactive overviews
    - Raising
    - Spending
  - Election data by location
  - Advanced data
    - all the data tables

- Candidate and committee services
  _- [Is another layer of organization needed between? Entity type?]_
    - Registration and reporting
    - Compliance stuff

- Legal resources
  - Regulations
  - Statutes
  - AOs
  - MURs
  -  etc etc

**Comment by AmyKort** [comment]
@jenniferthibault I agree. I don't think Registration and Reporting is going to make sense as a top line navigation item once we launch the candidate and committee compliance help section. Or, at least that's my prediction.

**Comment by nickykrause** [comment]
@jenniferthibault (cc @AmyKort and @emileighoutlaw): We sort of touched on this in the meeting we had onsite, didn't we? If I'm remembering right, this was one of the first questions that came up: "How will this content relate to Registration and Reporting?"

We didn't really go so far as to determine the implications for navigation, but your suggestion makes sense to me. If both "Registration and Reporting" and "Compliance" (or whatever it ends up being called) are side-by-side in the main navigation, it may misleading suggest that there is a dramatic difference between those two things, when, actually, they are closely related and would cross-reference each other frequently.

Listing Campaign finance data / Candidate & committee services / Legal resources would also have the benefit of parallelism with the three content buckets outlined on the homepage, if we do go that route

**Comment by nickykrause** [comment]
@emileighoutlaw:

During the meeting, I remember that we had a bucket that seemed to span the space between "Things coming in" and "things going out," and I'm wondering where that fits with what you outlined. I am referring to the stickies on which you drew the arrows pointing both ways: <-  ->   

Including in that group, I thought, were things like Transfers, possibly Travel? I see that Transfers is listed as "incoming," though, so I might be wrong.

Just want to make sure I'm reading it right :smile:

**Comment by emileighoutlaw** [comment]
Yep! Nicky is spot on with my thinking!

I had imagined `Campaign finance data` | `Candidate and committee services` |  `Legal resources` as our top-level navigation items. But how we break down the inside of `Candidate and committee services` is still TBD:

I see a couple ways this could play out

Option 1:
> **Candidate and committee services**
> - **Registration and reporting**
    - Candidates and authorized committees
    - Corporations and labor organizations
    - Nonconnected committees
    - Political party committees
> - **Compliance (whatever we call this section)**
    - Candidates and authorized committees
    - Corporations and labor organizations
    - Nonconnected committees
    - Political party committees

Option 2:
> **Candidate and committee services**
> - **Candidates and authorized committees**
    - Registration and reporting
    - Compliance (whatever we call this section)
>  - **Corporations and labor organizations**
    - Registration and reporting
    - Compliance (whatever we call this section)
>  - **Nonconnected committees**
    - Registration and reporting
    - Compliance (whatever we call this section)
>  - **Political party committees**
    - Registration and reporting
    - Compliance (whatever we call this section)

My gut is that Option 2 will end up making more sense once we have all our content chunked out, but I don't think we'll know until we get a little further down this content road. I also suspect we'll want a **Candidate and committee services** landing page, as we do for **Data** and **Legal resources**?

@nickykrause — the two items that spanned both **Coming in** and **Going out** were _Transfers_
and _Disclaimers_; I put added them as sub-categories under each section.

**Comment by jenniferthibault** [comment]
Very interested in option 2! And yes, landing page and possibly drop-down nav menu will be needed. (Drop-down listed as "possible" because it's still up in the air if we are keeping that pattern, I know we have discussed eliminating it all together and making the landing pages work smarter)

**Comment by nickykrause** [comment]
I support option 2 for several reasons:

- Candidate and committee services, as a bucket, already begins to imply that certain user groups' unique needs will be met by that section. It follows naturally, I think, that the subsequent breakdown is by type of candidate/committee.

- I suspect that users who are looking for guidance (or who are just starting out) will have an easier time understanding who they are (a candidate, a corporation, a political party committee, etc), rather than knowing if they are looking for Registration/Reporting versus Compliance. (So, the cognitive effort of option 2 is less).

- Plus, even if users would have an easier time decided that Reg/Reporting or Compliance is what they need (rather than identifying who they are), the setup of Option 1 would still require them to make the "Who am I?" determination immediately, anyway.

**Comment by emileighoutlaw** [comment]
We're going with Option 2, and working with content managers to organize all our subpages. We'll be meeting on Monday to (hopefully) make a final decision about that on Monday.

After chatting with Jeremy and Melissa yesterday, I suspect we'll eventually chunk the content into the following sections:

How to register —> How to run a committee (raising, spending, recordkeeping) —> How to file reports —> How to terminate

**Comment by emileighoutlaw** [comment]
We have largely agreed on an organizational structure, and we're ready to move forward with our next content task (breaking our content down to fit _into_ that structure) 🎉
