### ISSUE TITLE
Review content on home page with content managers

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#603]
Once the home page designs are ready we need to share them with the FEC content managers to get their review of language and links. 

This will be done once we have 👍  from the content manager group.

**Comment by nickykrause** [comment]
@emileighoutlaw: I forgot exactly what we said in sprint planning. The content managers are out this week, right? So, this exercise likely won't happen until early next week?

**Comment by emileighoutlaw** [comment]
We chatted with Amy yesterday and set up a meeting with content managers next Wednesday (11/30) from 2:30 to 4 ET. Would you like to be included on that invite, @nickykrause ?

**Comment by nickykrause** [comment]
Yes, please!

**Comment by emileighoutlaw** [comment]
We've done this, but we'll likely need to do another round before launch. Should we close this issue and open another @noahmanger? (How should we handle things like this that will have multiple reviews?)

**Comment by noahmanger** [comment]
Yeah I think we can close this. We know there will be an approval process.
