### ISSUE TITLE
Identify all links on the home page and where they go

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#604]
As we're finalizing designs for the home page we need to hammer out all of the links that will be on it and where they will link to, specifically if they will link to elements on the new site or old site. 

This will be done when we have specified where each link will go.

**Comment by nickykrause** [comment]
If I understand this correctly, this work is tied up with (and possibly dependent on?) the work outlined in issue: https://github.com/18F/fec-cms/issues/603, "Review content on home page with content managers"

**Comment by nickykrause** [comment]
This is "done," in the sense that [the prototype we used for usability testing](https://gsa.invisionapp.com/share/2U9JSARKH#/screens) includes all the links we were able to identify. This covers everything except: 
- how to run an authorized committee
- the link for info on loan repayment
- the yet-to-be-identified links that will live in the "candidate and committee services" section for the other committee types (corps/labor orgs, PACs, political party committees, and "not sure")

However, the content managers are still reviewing the homepage content, which means that they will be providing changes/updates to some of these elements, so the final determination about homepage linking is yet to come.

**Comment by nickykrause** [comment]
Also, the homepage styles are still changing, but the majority of the link considerations are complete.

One other, big thing that I left out of my previous point was that we haven't determined where to link "Candidate and committee services" (in the main navigation / the homepage section), as that content does not yet exist in that kind of a "bucket."

**Comment by jenniferthibault** [comment]
The designs are updated with their corresponding links in [InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5).

Closing this issue.
