### ISSUE TITLE
Build dynamic content updater for home page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#606]
There will be a few types of content on the home page:
- Some content that should automatically update and rotate new content by itself (feeds)
- Some content that should be able to change on a routine basis (ideal if we can set this to happen automatically, but may have to be done manually) Determined by the [content calendar work](https://github.com/18F/fec-cms/issues/605)
- Some content that will be pretty permanent and stable

I've probably named this the wrong thing, but it's the dev issue that starts implementing the content strategy for the home page.

**Comment by noahmanger** [comment]
I think this is captured over here https://github.com/18F/fec-cms/issues/617 so closing.
