### ISSUE TITLE
Create wiki document(s) that guide a content manager through the Wagtail content management process

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-cms#623]
Guide for non technical content managers to understand the process of managing content through the Wagtail CMS system.

**Comment by emileighoutlaw** [comment]
@adrianwebb — apologies for being behind the times on Wiki contributions. But where/how should I be posting this info?

**Comment by emileighoutlaw** [comment]
ping @adrianwebb again. Let me know where to drop stuff, and I'll put it in!

**Comment by adrianwebb** [comment]
Hey @emileighoutlaw, really sorry for the delay!  Let's put this in (markdown format *.md) inside a top level docs directory.

**Comment by emileighoutlaw** [comment]
These are created in Google Docs but aren't in the Wiki yet:

- Setting up Wagtail: https://docs.google.com/document/d/1_aYvX5VfAlF24LQAhGGLxBTkjiu0jcDiGyb4H-I2TRo/edit
- Using Wagtail: https://docs.google.com/document/d/1X5DNJFAWgzL-jdT9lDBmitQmg1dnAcQnXpzPCp4CRJA/edit#heading=h.qta9lq3zce3
