### ISSUE TITLE
Design "About the FEC" landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#627]
So that users can find specific documents and information about the organization of the FEC, design an "About the FEC" landing page that introduces and organizes all of this information.

---

As we're designing the organization and flow of all aspects of this section (https://github.com/18F/fec-cms/issues/626) we can go ahead and design the landing page.

**Completion criteria:**
- [x] Styled designs for the landing page
- [ ] Approved microcopy

**Comment by jenniferthibault** [comment]
Here is the template we can use for the About landing page with major sections outlined & first photo recommendation.

@emileighoutlaw , are you ready to dig into the microcopy?

![about-landing_v1](https://cloud.githubusercontent.com/assets/11636908/21236524/5ad66f04-c2c9-11e6-916b-6a700b8d6451.png)

**Comment by emileighoutlaw** [comment]
I'll dive in this afternoon! [Google doc started here](https://docs.google.com/document/d/1z7ROcgSmbJHjmPIFDjL5Gdn722Ann2zdkbms9xdj_M8/edit) 🔒

**Comment by emileighoutlaw** [comment]
Here's some initial landing content for us to react to (cc @AmyKort)

A couple quick notes before you dive in:
- The first sentence under **Mission and history** is taken from the anniversary reports. I found it when I was conducting some research, and I think it's a strong, meaningful sentiment.
- You'll notice that all these buttons say "Learn more". We do this in **Registration and reporting** section, and I don't want to force you to re-read through all that reasoning here, but we can talk about it if you want. I think it makes sense in this context.

> ## About
> The FEC is an independent government agency, created by Congress in 1974. 

> #### Mission and history
> The FEC was created to promote confidence and participation in the democratic process. Read more about the FEC’s history, purpose and goals.

> [[Learn more]](url)

> #### Leadership and structure
> The agency is led by six Commissioners; no more than three of whom can belong to the same political party. Find out more about the FEC’s structure and its Commissioners. 

> [[Learn more]](url)

> #### Reports about the FEC
> The FEC regularly publishes information about its performance and objectives. These documents include strategic plans, budgets and procurement reports.

> [[Learn more]](url)

> #### Careers
> More than 300 people work at the FEC. Find current job openings and information about the application process. 

> [[Learn more]](url)

> #### Doing business with the FEC
> Working with experts, vendors and other external stakeholders helps the FEC support its mission. 

> Requests For Proposals (RFPs) and Requests for Quotations (RFQs) are posted by the  General Services Administration, either on its [e-BUY website]() or on its [Federal Business Opportunities website]().

> Reports about FEC procurement and contracting are available in [Reports about the FEC]().

**Comment by AmyKort** [comment]
I like this a lot.

**Comment by jenniferthibault** [comment]
Sounds like this is ok to move forward with so I made https://github.com/18F/fec-cms/issues/679 for implementation. @emileighoutlaw / @AmyKort ok to close this issue?

**Comment by emileighoutlaw** [comment]
Yep!
