### ISSUE TITLE
Build detailed candidate content structure and Wagtail pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#630]
This is a continuation of: https://github.com/18F/fec-cms/issues/599

We've been working on a general structure for our compliance content. For this sprint, our content manager tasks are:
- [x] Chunk existing candidate content (from the campaign guide and FEC.gov) into a detailed outline of our five buckets (Raising/Spending/Debts&Loans/Recordkeeping)
- [x] Make notes of potential bridges we might want to build between content sections
- Train FEC content mangers to use Wagtail
   - [x] Lauren
   - [x] Dorothy
   - [x] Amy Pike
   - [x] George
- [x] Build Wagtail pages from detailed outline
    - Review pages; draft pages titles and section titles
- [x] Document content structure and organization

**Comment by jenniferthibault** [comment]
@emileighoutlaw mentioned at sprint planning that this issue should be renamed in order to have it reflect what it's mean to accomplish this sprint. Want to give that a go?

**Comment by emileighoutlaw** [comment]
Update:

- Dorothy has [built an outline](https://docs.google.com/document/d/1yzSs0MFzZKU5T5j8l7AkZHcbMJ9q055MUA-xM5tOLUU/edit#heading=h.web9keg07nai) 🔒 of that documents the individual pages content structure organization
- We're updating Amy on our progress Wednesday:
    - Where we are
    - Incorporating FEC Record without triggering review
    - What we want to talk to content managers about
- Need to talk through several strategy decisions with content managers
    - Page content grouping choices (long v. short and implications)
    - Design options
    - Page titles

**Comment by jenniferthibault** [comment]
I just mocked up wireframes to help choose the page content grouping in https://github.com/18F/fec-cms/issues/698#issuecomment-270245519

**Comment by emileighoutlaw** [comment]
Just saw that! Thank you ❤️

**Comment by emileighoutlaw** [comment]
This is finished, closing now!
