### ISSUE TITLE
Create section in Wagtail for Compliance content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#632]
This is an (I believe) small-ish developer task. We don't need to design or develop the whole compliance section this sprint, but we do need a place in Wagtail where our content managers can start adding compliance pages using the existing "Custom" template.

**Comment by noahmanger** [comment]
I think this should be as easy as just making a new top-level page that you can then make child pages of, which should only take 30 seconds in Wagtail. Should we just make a page called "Reporting and compliance help"?

**Comment by emileighoutlaw** [comment]
Ah yep! Just did this. Closing now

**Comment by emileighoutlaw** [comment]
p.s. Wahoo that Wagtail is so easy to use
