### ISSUE TITLE
Prepare Complaint Process page for implementation

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#633]
So that users can learn about the process for submitting a complaint, implement the designs for the "Complaint process" page. To do this, we need to resolve a few more questions about this page. 

---

[Designs](https://cloud.githubusercontent.com/assets/1696495/20907733/d962729a-bb04-11e6-85e6-e8df9079da04.png) | [Content](https://docs.google.com/document/d/1XctsE8Lh5A2NCePAAhisyPVi-y4Az9CtIyNh8mtF7Zs/edit)

**Criteria for completion:**
This task will be done and ready for implementation when we've answered the following questions:
- [x] Identify where all the links on the page go and add them to the content doc
- [x] Identify where this page lives in the hierarchy. From what I can tell, the breadcrumbs should be: *[Legal resources](https://fec-stage-proxy.18f.gov/legal-resources/) > [Enforcement matters](https://fec-stage-proxy.18f.gov/data/legal/enforcement/) >  The complaint process*
- [x] Where does the "Filing a complaint" brochure live? Are we porting over [this page](http://www.fec.gov/pages/brochures/complain.shtml) now?
- [x] Add titles to the legal citations

**Comment by noahmanger** [comment]
@emileighoutlaw I missed this one somehow this afternoon so we didn't get to talk about it. Does this issue make sense to you?

**Comment by emileighoutlaw** [comment]
Definitely!

**Comment by emileighoutlaw** [comment]
**Citations and links**
Updated and included in the document!

**Breadcrumbs**
I favor  _Legal resources > Enforcement matters > Complaints_ 
What do you think of that @noahmanger? 

**Brochures**
So far we haven't moved any into the CMS. But we definitely can.

Do you think we'd use a custom page template, as on the [Treasurer page](https://beta.fec.gov/registration-and-reporting/get-treasurer/)? 

Or would we want something different/special to indicate that although brochures are HTML, they're Commission-approved publications

**Comment by noahmanger** [comment]
Yeah, I think nesting it there makes sense. 

For the brochure, I think we don't need to do a lot, but I'm seeing a couple components on that page that we may want to design patterns for, so I'll make a new issue.

**Comment by noahmanger** [comment]
Ok, new issue for designing the patterns in the template https://github.com/18F/fec-cms/issues/650

And a new issue for implementing the first complaints page:  https://github.com/18F/fec-cms/issues/651

I believe both of those tasks will be happening next sprint. Closing this issue.
