### ISSUE TITLE
Implement "Commissioners" portion of home page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#639]
So that users can understand the FEC better, implement a portion of the home page to feature the commissioners and link to the "About the FEC" section.

---

[Full home page design](https://cloud.githubusercontent.com/assets/1696495/20908227/2e474eea-bb08-11e6-9b55-e552a3b5c1cb.png) | This is the section for this issue:

![image](https://cloud.githubusercontent.com/assets/1696495/20908850/a3b824de-bb0c-11e6-93f0-cb521f5a7901.png)

The links for this section won't be active yet, so we can link to the legacy site for now: http://www.fec.gov/about.shtml and commissioner pages http://www.fec.gov/members/members.shtml

The order here is the chair goes first, then the vice chair, and then alphabetical by last name. So on mobile that order will need to be maintained.

**Completion criteria:**
- [x] Design is implemented as shown and all links go to the corresponding page on the legacy site

**Comment by jenniferthibault** [comment]
Design tasks to prepare for implementation:

- [ ] Export headshot images

@xtine do you prefer I export them as circles, or as squares that you use a circular layer mask on the front end for?

**Comment by xtine** [comment]
@jenniferthibault: if the pictures aren't going to be used elsewhere, then circles would be easier.

**Comment by jenniferthibault** [comment]
[Google document](https://docs.google.com/a/gsa.gov/document/d/1bdbScZfwVtlauZRLtXh_-16h1BUUR26hPHC9pCLc-Os/edit?usp=sharing) with all the up-to date content so that it can be more easily copy & pasted 🔒 

[InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5) with final design and link paths

Here's how I was thinking the layout could stack on mobile:

![screen shot 2016-12-07 at 3 25 22 pm](https://cloud.githubusercontent.com/assets/11636908/20985190/67a411b6-bc91-11e6-874c-1f0730c7e8c0.png)

**Comment by xtine** [comment]
@jenniferthibault / @noahmanger: I'm trying to come up with a name to describe the new type of headings next to the headshots. The most similar component would be the `contact-item`. The best I could come up with is "profile-item" ... any other suggestions?

**Comment by noahmanger** [comment]
Ugh naming. Are you trying to think of a name for the component as a whole (pic + text)? Or just the name?

**Comment by jenniferthibault** [comment]
Another similar bit is:

<img width="275" alt="screen shot 2016-12-15 at 3 29 11 pm" src="https://cloud.githubusercontent.com/assets/11636908/21240920/61a9a6b8-c2db-11e6-85fa-cb2509f0d3dc.png">

If it makes sense to bring any of these styles into better alingment so there's fewer, glad to think about what we could do here.

**Comment by xtine** [comment]
Just a class for the heading. What I have right now is:
```
        <div class="grid__item">
          <div class="icon-heading">
            <img class="icon-heading__image" src="{% static "img/headshot--goodman.png" %}" alt="Headshot of Lee E. Goodman">
            <div class="icon-heading__content">
              <h3><a href="http://www.fec.gov/members/goodman/goodman.shtml">Lee E. Goodman</a></h3>
              Republican
            </div>
          </div>
        </div>
```
And I'd like to attach classes to the `h3` and Chairman titles to have them styled appropriately.

**Comment by xtine** [comment]
So I'm able to get mostly there using `_type-styles.scss` to avoid making extra classes:
<img width="899" alt="screen shot 2016-12-15 at 2 15 32 pm" src="https://cloud.githubusercontent.com/assets/24054/21242329/0a0fc95a-c2d1-11e6-93b2-c2713e4f810d.png">

Just need that space before party affiliation, a `<br>` is to much.

**Comment by jenniferthibault** [comment]
@xtine I'm ok with eliminating the extra space. It was designed in so that if the commissioner had a long name that went onto two lines, the part affiliation would still be roughly lined up, but I think it would get pushed down anyways.

**Comment by emileighoutlaw** [comment]
It's kind of a bummer that the way succession plays out the women are all underneath the men, but I know that's not in our control. Just putting that feeling out into the universe.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/662
