### ISSUE TITLE
Scrape the full meeting agenda archive

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#642]
In order to migrate all Meeting Agendas to the Latest updates section, we need to scrape them. 

This content is all available via http://www.fec.gov/agenda/agendas.shtml , though @patphongs has volunteered to run a crawl to get every link, which we could then use to run the scraper.

We can fill this in with more details once we prioritize.

**Comment by johnnyporkchops** [comment]
If we are now focusing on this section, ,could we also look at the pull request to integrate the model/template for building new pages in the editing interface?
https://github.com/18F/fec-cms/pull/490

**Comment by noahmanger** [comment]
Mistakenly made another issue for this over here, which is more detailed https://github.com/18F/fec-cms/issues/704 . So I'm closing this.
