### ISSUE TITLE
Implement "Registration and reporting" section of the home page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#644]
So that users can identify tasks they are looking for in Registration and reporting and navigate to that section of the website, create a section on the home page to showcase the various elements.
__________________________________________

[Full home page design with link paths on InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5) | This is the section for this issue:

![screen shot 2016-12-07 at 4 17 28 pm](https://cloud.githubusercontent.com/assets/11636908/20986929/addf8e1a-bc98-11e6-9ab8-4729314fd008.png)

**Completion criteria:**
- [x] The first card link goes to https://beta.fec.gov/registration-and-reporting/
- [x] The second card links to the calendar with the filing deadlines filters applied
  - This URL will be dependent on this issue: [Calendar filters not saving state in URL · Issue #618](https://github.com/18F/fec-cms/issues/618)
- [x] The third card about RFAIs goes to https://beta.fec.gov/registration-and-reporting/request-additional-information/
- [x] The fourth card goes to the calendar with all filters under the Outreach category applied.
  - This URL will also be dependent on this issue: [Calendar filters not saving state in URL · Issue #618](https://github.com/18F/fec-cms/issues/618)
- Layout responds to smaller screens.

For mobile, this section should follow the pattern established in the [Legal resources implementation issue](https://github.com/18F/fec-cms/issues/638):

![screen shot 2016-12-07 at 4 26 39 pm](https://cloud.githubusercontent.com/assets/11636908/20987300/0feb67c2-bc9a-11e6-858e-6ea295666de4.png)

This section is a requirement for the first homepage release. @xtine is it ok to assign to you?

**Comment by xtine** [comment]
@jenniferthibault: I just assigned myself. :)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/661
