### ISSUE TITLE
Add "parties" term and definition to glossary

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#647]
To complete the intended glossary links from the ["Citizen information" portion of the home page, Issue#646 ](https://github.com/18F/fec-cms/issues/646) we need to add the term "parties" to the glossary with its definition.

![screen shot 2016-12-07 at 7 17 56 pm](https://cloud.githubusercontent.com/assets/11636908/20992407/e0ca9cca-bcb1-11e6-88a0-9e39ff690896.png)

Since #646 isn't necessary for the first home page release, I bet we could do this for sprint 3 @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Ooooo — I could implement during this this sprint, if @AmyKort thinks we can use the party definition from the campaign guides:

> A political committee that represents a political party and is part of the official party structure at the national, state or local level. 100.5(e)(4).

**Comment by AmyKort** [comment]
Do you think we could say "can give to candidates, party committees, and political action committees (PACs)"? That would be more accurate anyway and goes with the definition in the glossary.

**Comment by emileighoutlaw** [comment]
Definitely we can say that, @amykort. Is it also okay to use that existing definition (from my comment above) ?

**Comment by AmyKort** [comment]
Yes. Thank you!

**Comment by noahmanger** [comment]
Late to this, but I just noticed we already have definitions for "political party" and "party committee". 

![image](https://cloud.githubusercontent.com/assets/1696495/21151323/eb0c327a-c116-11e6-8f46-9549c8a33dbe.png)

Is this different?

**Comment by AmyKort** [comment]
I thought were we landed was to say party committee and use the party committee definition. I think if we are talking about how contribution limits apply to recipient committees, the party committee definition makes more sense. Sound okay?

**Comment by noahmanger** [comment]
🙈  it would be really helpful if I actually read the conversation before commenting. Nevermind.

**Comment by emileighoutlaw** [comment]
No sweat!

We'll use the term `party committee` and link to the the existing party committee glossary definition when we implement. 

I think this issue can be closed :)
