### ISSUE TITLE
Move legal and "About FEC" PDFs to new S3 bucket

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#649]
We are ready to move the following PDFs to a new bucket:

In the [Legal Resources](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit?pli=1#gid=498302760
) tab:
- [ ] NPRMs (cells 1,945 to 2,423)
- [ ] Comments (cells 2,439 to 2,554)

In the [FOIA](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit?pli=1#gid=1721383590) tab:
- [x] FOIA documents

In the [Meetings](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit?pli=1#gid=99253360) tab:
- [x] Agendas
- [x] Sunshine notices

Let me know if you have any questions about this, Pat! 💟

**Comment by emileighoutlaw** [comment]
I believe the path to these should be:

> beta.fec.gov/foia
> beta.fec.gov/updates/agendas
> beta.fec.gov/updates/sunshine-notices

I need to consult with Amy on the NPRMs and comments— I know they're in 
`beta.fec.gov/legal-resources` but I'm not sure about if there's another layer beyond that.

**Comment by patphongs** [comment]
@emileighoutlaw any update about the NPRMs and the path they should be under for the content bucket?

**Comment by emileighoutlaw** [comment]
Sorry this took so long, Pat! We've been working hard on figuring out the new site structure, but it's been slow moving. NPRMs and comments should be: 

beta.fec.gov/legal-resources/regulations/nprms
beta.fec.gov/legal-resources/regulations/comments

**Comment by emileighoutlaw** [comment]
For the initial launch, our plan is to link to SERs for NPRMs and link to the old site for anything that isn't included in SERs.

Once the [FOIA documents](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit#gid=1721383590) have been moved to the new S3 bucket (any update on that, @patphongs ?), I think we can close this issue for now and open a new issue for NPRMs specifically later.

**Comment by patphongs** [comment]
@emileighoutlaw FOIA docs have been moved over to the bucket. We are all set to close this ticket and open a new one for NPRMs. Thanks!

**Comment by emileighoutlaw** [comment]
Woohoo! You're the best, @patphongs !
