### ISSUE TITLE
Implement "totals raised/spent over time" chart portion of home page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#652]
@jenniferthibault commented on [Fri Dec 09 2016](https://github.com/18F/fec-eregs/issues/322)

[Full home page design](https://cloud.githubusercontent.com/assets/1696495/20908227/2e474eea-bb08-11e6-9b55-e552a3b5c1cb.png) | This is the section for this issue:

![screen shot 2016-12-09 at 12 08 26 pm](https://cloud.githubusercontent.com/assets/11636908/21057567/38f0bb26-be08-11e6-99b7-84cb00abd7a8.png)

Completion criteria
- [ ] Determine which formulas will allow us to get the best data for as far back in time as we can go
- [ ] $ total in the text underneath both charts should update dynamically when the user hovers over or selects another two-year period column in the bar chart above
- [ ] Two-year period in the text underneath both charts should update dynamically when the user hovers over or selects another two-year period column in the bar chart above
- [ ] $ totals and years should always change together in both charts
- [ ] User can scroll left/right via the arrow panel to see older/newer election columns & data, respectively.
  - [ ] When user is viewing oldest data column, left scroll button disappears
  - [ ] When user is viewing most recent data column, right scroll button disappears
- [ ] Raising overview links to anchor tag: https://beta.fec.gov/data/
  - [ ] Add anchor tag to "Raising" on data landing page
- [ ] Spending overview links to anchor tag: https://beta.fec.gov/data/
  - [ ] Add anchor tag to "Spending" on data landing page
- [x] ~"raised 📖 " and "spent 📖 " open glossary definitions ..... @emileighoutlaw do we have definitions already?~
- [ ] Responds to smaller screens
  - On mobile, closed on load, charts become static "sparkcharts":
  - ![screen shot 2016-12-09 at 12 02 06 pm](https://cloud.githubusercontent.com/assets/11636908/21057361/5d22abc2-be07-11e6-9914-739745544879.png)
  - When sparkchart is selected, panel expands and becomes interactive : 
  - ![screen shot 2016-12-09 at 12 01 58 pm](https://cloud.githubusercontent.com/assets/11636908/21057407/9699a63a-be07-11e6-803e-c9a7ef005e98.png)
  - this interaction is based on the model used on EITI's mobile charts & sparkcharts: https://useiti.doi.gov/explore/

This work is expected for sprint 3, as a follow-up to the first home page release

@noahmanger this is a first stab—please feel free to correct what I have here if it's incomplete

**Comment by noahmanger** [comment]
Final copy from https://github.com/18F/fec-cms/issues/656#issuecomment-268567284:
> Candidates and committees reported raising $1,039,384,282 between January 1, 2015 and December 31, 2016.
> Candidates and committees reported spending $3,039,384,282 between January 1, 2015 and December 31, 2016.

**Comment by emileighoutlaw** [comment]
I think we won't be opening a glossary definition for "raising" and "spending," because they aren't terms of art. But when users click into the data visualizations, the bigger charts have more definitions and explanations. So I think that feels okay!

**Comment by jenniferthibault** [comment]
I just edited the criteria to cross that off the list. Thanks!
