### ISSUE TITLE
Clarify content on raising/spending charts is reported

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#656]
Our homepage is going to feature spark charts for Raising and Spending totals.

![screen shot 2016-12-09 at 12 08 26 pm](https://cloud.githubusercontent.com/assets/11636908/21057567/38f0bb26-be08-11e6-99b7-84cb00abd7a8.png)

As with this issue: https://github.com/18F/openFEC-web-app/issues/1713, we need to clarify that the  numbers are for what was reported, not the actual amount spent or raised.

How about this for the microcopy:
> **$1,039,384,282** in raising* was reported between **January 1, 2015 and December 31, 2016**.

> **$1,039,384,282** in spending* was reported between **January 1, 2015 and December 31, 2016**.

@noahmanger @AmyKort @PaulClark2

**Comment by emileighoutlaw** [comment]
Related to: https://github.com/18F/fec-cms/issues/652

**Comment by noahmanger** [comment]
I think in this case it's actually ok to just say "was raised" or "was spent". The reason we specify "reported" on the other charts is that the numbers at a given point in time aren't reflecting the actual amount, but instead just the amount that has come in by report up until that point.

**Comment by AmyKort** [comment]
I don't understand the microcopy. We won't know what was raised through December 31 until the year-end reports are filed on January 31, 2017. Those reports will generally have coverage dates from November 29 through December 31. In addition to the question of whether we need to clarify "reported," I don't understand how we could implement this language at all until after December 31. Is this for later implementation than I am thinking?

**Comment by ChristianHilland** [comment]
I think "was raised" and "was spent" are fine since we've used similar language in press releases, but I see what Emily is getting at.  If we wanted to be safe , we could use something like:

$1,039,384,282 in receipts was reported between January 1, 2015 and December 31, 2016.
$1,039,384,282 in disbursements was reported between January 1, 2015 and December 31, 2016.

**Comment by AmyKort** [comment]
I like Christian's suggestion above. We've gotten some internal feedback to suggest folks would like to see the "reported" here somehow.

**Comment by emileighoutlaw** [comment]
Hey folks. In trying to bring over language from https://github.com/18F/openFEC-web-app/issues/1713, I clearly missed the mark. Apologies!

Since we make it a point on internal pages to clarify that we're talking about _reported_ numbers, it seems like a good idea to be consistent here, too, if we can (good mental prep for what comes later). 

The main difference I see in Christian's version and my version is that he has replaced the more casual `raising` / `spending` with the more technical `receipts` / `disbursements`. That makes sense to me (and lets us link to glossary definitions, woo!).

Curious what Noah thinks.

**Comment by noahmanger** [comment]
Ah my bad on the language note. I misunderstood things. @AmyKort to your point on the date range, the screenshot above is more of a hypothetical for a future state, after the January 31 report has been filed. But it does raise the question that when we're in the middle of a year, we need to denote that it's still "in progress". Maybe:

> $1,039,384,282 in raising* has been reported so far between January 1, 2015 and December 14, 2016.

...Where "December 14" would always be "yesterday". 

As far as "raised" / "spent" vs. "receipts" / "disbursements" I believe we want to go with "raised" / "spent" for both their more approachable qualities and also because the totals reflect spending, say, that aren't classified as "disbursements" (like independent expenditures). Or at least that's my understanding.

**Comment by emileighoutlaw** [comment]
Pinging @amykort, @ChristianHilland, and @PaulClark2 so this doesn't fall off our radar.

Do you have thoughts on Noah's note about `raising` vs. `receipts`?:
> As far as "raised" / "spent" vs. "receipts" / "disbursements" I believe we want to go with "raised" / "spent" for both their more approachable qualities and also because the totals reflect spending, say, that aren't classified as "disbursements" (like independent expenditures). Or at least that's my understanding.

Which would put us back to something like:
- $1,039,384,282 in raising was reported between January 1, 2015 and December 31, 2016.
and
- $1,039,384,282 in spending was reported between January 1, 2015 and December 31, 2016.

**Comment by AmyKort** [comment]
Paul--am I correct that raised and receipts both work based on the data that supports the chart?

If we want a glossary link, let's go with receipts. Alternatively I am okay with "$123456.78 was reported raised between ..." Does that work as a sentence? One thing I liked about "receipts" was that it got us out of the "in raising was reported" construction. I think that construction works for spending better than it does for raising. @emileighoutlaw Help!

**Comment by emileighoutlaw** [comment]
@AmyKort @PaulClark2 
Could we go with something like:

> - Candidates and committees reported raising **$1,039,384,282** between January 1, 2015 and December 31, 2016.
> - Candidates and committees reported spending **$3,039,384,282** between January 1, 2015 and December 31, 2016.

**Comment by AmyKort** [comment]
Looks great to me!

**Comment by noahmanger** [comment]
Great. Closing. We still need to work out details about the data, but can do that in #652
