### ISSUE TITLE
Implement/Create Commissioner bio page model and template

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#669]
So that users can find information about the biographies, statements, and actions of commissioners past and present, present commissioner information on a single page.

---

🖌 [Designs](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085029_About-Organization-Structure-Commissioner_V1)

The design calls for a several unique values that I think make sense to just code into a new page model and template for these pages:
- Picture
- Dates served: Storing this data would make it easy to automatically generate the page of past commissioners and also to populate the current commissioners on the home page
- Party affiliation
- Email address
- Twitter (optional, I'm assuming)

These are in addition to standard title and body content fields.

Once this model is created we can have other people help populate the content.

**Completion criteria:**
- [x] Create page model with all of the fields
- [x] Create new template as designed

**Comment by xtine** [comment]
I noticed that some past commissioners have been re-appointed on http://www.fec.gov/members/formermembers.shtml

It seems to make sense to only sort by original appointment dates, but to also show reappointment dates if applicable underneath. If we aren't doing any sorting on the reappointment dates would it make sense to make the additional reappointment field as text in the CMS? Thoughts @noahmanger @jenniferthibault ?

Also there are the Ex-Officio commissioners to think about displaying as well.

**Comment by noahmanger** [comment]
Just realized I never answered that question. I think that makes sense to just add them as an extra field. I'll keep this open for now.

**Comment by jenniferthibault** [comment]
+1 to reappointment dates being an extra CMS field that would appear just below the original appointment 
![screen shot 2017-01-11 at 10 32 36 am](https://cloud.githubusercontent.com/assets/11636908/21854593/5357743c-d7e9-11e6-8d1c-a71afb63b44b.png)

And thanks for pointing out the Ex officio commissioners, I totally missed them (heads up, @emileighoutlaw !)

How about using the same format & grid, minus the image field? Like this:

![screen shot 2017-01-11 at 10 57 36 am](https://cloud.githubusercontent.com/assets/11636908/21855581/f7b08764-d7ec-11e6-844d-c5e8eef441c6.png)

That would be placed at the bottom of the page of all Commissioners.

**Comment by emileighoutlaw** [comment]
Yikes— I also totally forgot about the ex officio Commissioners. I think that looks great!

**Comment by emileighoutlaw** [comment]
And I do like the existing description of ex officio (from the current page). The only tweak I'd make to the content is to move the court case into parentheses:

> From 1975 through 1993, the Secretary of the Senate and the Clerk of the House were designated as nonvoting, ex officio Commissioners. In 1993, an appeals court ruled that the presence of nonvoting Congressionally appointed ex officio members on the Commission violated the Constitution’s separation of powers. The Supreme Court dismissed the Commission’s appeal for lack of jurisdiction (_FEC v. NRA Political Victory Fund_). Subsequent to the appeals court decision, the Commission reconstituted itself as a six-member body.

**Comment by jenniferthibault** [comment]
Great! Yeah that case bit confused me, I couldn't tell why it was floating there.

**Comment by noahmanger** [comment]
Resolved by #733 . Good work!
