### ISSUE TITLE
Design flow for "Candidate and committee services | Candidates" section

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#670]
In order to get a better grasp on the new compliance section, this is a task to mock up the flow of the candidate compliance content in particular. 

I think the take-away of this issue should be a series of screens that take you from:

 **Home page**  
⬇️ 
 **"Candidate and committee services" landing page** 
⬇️ 
  **Sub-sections and pages** for this section.  

This is also the time to address how the current [Registration and Reporting essentials](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/) pages fit into this flow.

This won't resolve all design questions, but it should give us a much clearer picture of what we need to do.

Does this make sense @jenniferthibault and @emileighoutlaw ?

**Completion criteria:**
- [x] Series of screens illustrating the templates and hierarchy used to organize compliance and reporting content for candidates
- [x] Identify follow up development and design tasks

**Comment by emileighoutlaw** [comment]
I think this makes sense 👍

**Comment by noahmanger** [comment]
I believe this has been settled in other issues.
