### ISSUE TITLE
Design visuals and microcopy for "Candidate and committee services" landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#671]
So that the regulated community can find the information they need to be compliant, organize a landing page that helps them find the compliance information relevant to them.

---

The task here is to design the visuals and micro-copy for the main Candidate and committee services landing page so that we can implement it in the following sprint.

**Completion criteria:**
- [x] Visual design of "Candidate and committee services" landing page
- [x] Approved copy for the page

Like the About section, we will then break this down section by section for deeper design and implementation, beginning with the Candidate section(https://github.com/18F/fec-cms/issues/670).

**Comment by jenniferthibault** [comment]
@emileighoutlaw I started by thinking about what other parts of the site we should be building bridges between in this section. Initial thoughts:
- Finding or looking up an existing candidate or committee profile (to see what type of entity they are, or as an entry point to view their previous reports)
- Identifying what type of entity they are to the FEC
- Anything else you're thinking of that should be in a wireframe? (cc @nickykrause , you might also have a sense of these pathways)

One thing I don't have a good sense of, is how much this page should function as a vessel of information in its own right (and if so, what that info is) or if it this page functions as more of a home base pointing to trailheads for each entity type, but holds little info of its own.

I've mocked up two options using existing patterns that could fit each scenario: one holding more info, the other more of a directory



![cc-services-v1](https://cloud.githubusercontent.com/assets/11636908/21457696/4d94c228-c8ff-11e6-91f3-25281c825864.png)
![cc-services-v2](https://cloud.githubusercontent.com/assets/11636908/21457697/4d94d9fc-c8ff-11e6-8d00-6f499dd698d0.png)

**Comment by noahmanger** [comment]
My $.02: From a pattern perspective, the second one feels better, but I can't speak to the amount of introductory copy we'd have. 

Another thought: on the registration and reporting page, we use link below the side nav to lead people to the search:
![image](https://cloud.githubusercontent.com/assets/1696495/21535161/13bd0b5c-cd26-11e6-9edc-482b649e6ddc.png)

Which is kind of similar to the not-yet-enabled links on the AO page:
![image](https://cloud.githubusercontent.com/assets/1696495/21535174/45560754-cd26-11e6-8ba3-119f5cf18398.png)

Would we want to stick with this pattern in this case as well, rather than bringing the search box onto the page?

Separate question: where does that "Find out what thing you are" link take you to? Isn't that what this page is doing?

**Comment by jenniferthibault** [comment]
Ooh, good idea, the icon leading to search instead of embedded search box might be a good alternative here. 

Also not knowing a lot about the shape of the copy here makes it hard to tell which format overall will be a better fit—I'd like to wait for @emileighoutlaw before making a call. @noahmanger your question about "Find out what thing you are" is directly related. I took a total stab in the dark about what things we might need this page to do, which will change based on the type of content that fills this page.

**Comment by emileighoutlaw** [comment]
Thanks for giving me brain time on this. 

## What kind of thing?
The content managers are making a first draft of what "What kind of thing am I?" content would look like for the homepage. I'm hopeful that the homepage module and the introductory content on this page will be sufficient (i.e., we won't need another link to "What kind of thing am I?" on this page). But I never communicated that out, so it's my fault Jen was taking stabs in the dark on that. 

## Option 1 or 2?
It seems to me that we're weighing two things when we think about these two designs:
- Which will lead to the most consistent user experience (option 2, as Noah pointed out)
- Which will best support the content we need to convey for users (it depends, I think)

The content for this page can go two ways:

**Option 1:**
- We provide very little introductory content. Users are oriented to groups primarily by the name of the group and 1-2 sentences. This will be the fastest to users to read and probably the most friendly, but it will gloss over some of the complexity.

**Option 2:**
- My assumption is that this design is best if we provide more lush, lengthy introductory paragraphs. Is that true of the design, @jenniferthibault? (If not, perhaps we can start moving forward with Option 2 for consistency, while I keep sorting out if we want brief intros or lengthier ones). 
- Some thoughts on a lengthier intro (if that's what Option 2 calls for):
    - Lengthier introductions will take more time to read (so likely many users won't read it at all), and it will be less welcoming. 
    - Lengthier introductions will probably be more truthful about the complexity of this section.

No matter what we write to introduce these groups, we're going to run up against a problem that each group is defined in different statutes and using different criteria. So we are going to have a content consistency problem (i.e., we can't follow a formula to write equivalent descriptions). It's likely that this inconsistency will be less noticeable if we write 1-2 sentences than if we write 4-5. 

What I'm working on now is a potential draft of what that content might be (both 1-2 sentences and 4-5 sentences), which I think might help us make a more informed decision. But I wanted to get these thoughts out in the meantime. Especially if my assumption about Option 2 is incorrect.

**Comment by jenniferthibault** [comment]
@emileighoutlaw Option 2 could support shorter text, 1-2 sentences would be fine. 

My lingering thought on **What type of thing** is that we can't assume people will get to this section for the first time (and repeated times after) from the home page. They could be coming directly to this page from a bookmarked/sent link, or from the calendar, or probably somewhere else. This may mean that the "What kind of thing am I" module would do better to live **on** or **in** this page, and the home page would link to it, but not embed it. 

Would you agree, or do you feel strongly it has to be embedded only on  the home page?

**Comment by emileighoutlaw** [comment]
### What type of thing
Heyo! I don't feel strongly that the `What type of thing` thing needs to be embedded only on the homepage. What I do feel strongly is:
- The module should be prioritized after bringing over content for the other group types. 
    - We've been overwhelmed by the existing content, and I want to keep our focus there until that's done.
- A thing like this has never been written before, and until we actual start expending our energy and goodwill into it, we aren't going to be sure that we can get something like this approved (or in what form we can get it approved) by the powers that be.

So perhaps my practical concern is that I want the design to be able to accommodate this section eventually (even though we don't have a clear idea what shape that section is going to take), and at the same time be ready to launch (at least initially) without it. That is probably a crazy thing to want? 

### Content for the page
[I've got a first draft up and running for us to talk about](https://docs.google.com/a/gsa.gov/document/d/1bDYMIn9TjqNrhLG4g1B1HWfmir_sUj7GViB9BL_biu4/edit?usp=sharing) :lock:. This is one that will definitely need input from content managers and Amy, but it's a starting line for us.

**Comment by jenniferthibault** [comment]
👍 not crazy! It was probably a crazy thing for me to want to find a place for a thing when we don't know what it is or what' in it. 

I have some questions stored up for our pairing session coming up 🎈

**Comment by emileighoutlaw** [comment]
I think it's safe to mark this as done— Jen has the design ready and can post here on Tuesday :)

**Comment by jenniferthibault** [comment]
Designs:

![cc-services-v2](https://cloud.githubusercontent.com/assets/11636908/21611553/4bc12f6e-d19b-11e6-9b5b-f36746c9f27e.png)

**Comment by noahmanger** [comment]
Excellent. This looks great. Closing.

**Comment by jenniferthibault** [comment]
Just want to flag that this still needs to be reviewed by the content managers

**Comment by noahmanger** [comment]
Oh ok. Let's re-open then.
