### ISSUE TITLE
Design content and layout of About | Mission and history section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#673]
Using the flow from https://github.com/18F/fec-cms/issues/626#issuecomment-266852399
<img width="513" alt="screen shot 2016-12-19 at 10 14 02 am" src="https://cloud.githubusercontent.com/assets/11636908/21317639/f64e5b56-c5d3-11e6-956b-c15d849d4eb7.png">

- [x] Design the content for the Overview section
- [x] Determine strategy for linking to or porting over the 40th anniversary timeline of FEC's history (Differentiate between first release strategy and ling-term migration plan)
- [x] Determine what bridges to build between this content and other parts of the site (cross-linking strategy)
- [x] Design content in template layout

**Comment by emileighoutlaw** [comment]
[First draft of content is ready](https://docs.google.com/a/gsa.gov/document/d/10GC39hUAzucOngCZ-9dSZ_LmG0P1mnUj4zPL9gjmK1I/edit?usp=sharing) 🔒 

I tried to draw strategically from what FEC has already written about itself, so this shouldn't trigger any OGC review (although we should have Amy Kort give it a thumbs up). 

A specific thing I'd like to open up to discussion: I added a `History` section, which gives an overview of how the FEC came into existence. The 40th anniversary timeline is detailed, but it starts in 1971 (whereas the things that shaped the FEC started with Teddy Roosevelt). 

Including a broad, three-paragraph history allows us to cover the early history, but it also repeats some of the timeline info, when it gets to the 1970s. 

My thinking was that we could include a brief `History` section now and consider adding a pre-1970 bullet to the timeline, once we move the actual timeline over to the beta. But I'd love to hear other thoughts on this.

**Comment by jenniferthibault** [comment]
Thanks @emileighoutlaw ! I left you just one question about the content structure in the doc.

Do you have thoughts on what bridges to build between this page/content and other parts of the site? We've called this the cross-linking strategy before, I think.

**Comment by emileighoutlaw** [comment]
_A note on cross-linking/building bridges to other sections of the website_

Current strategy: The FEC uses only in-line links (when they reach a topic that has its own page on the site), which I think is a strategy we're moving away from on the new site. 

Some resources we _could_ highlight from this page:
1. Information about laws that are mentioned
   - Could take users to legal resources or specific laws
1. Information about active groups (PACs, parties, etc.)
   - Could take users to candidate and committee services
1. Information about types of campaigns the FEC oversees (Senate/House/President)
   - I'm not sure we have intro type information on the site about this, but we certainly have data we could surface
1. Information about the FEC structure
   - This exists heterarchically in the About section; linking it from this page feels like a "Read next" content suggestion. 

All of these feel like possible candidates for cross-linking. But without a strong signal of where users _want_ to go from this page, I don't feel 100% comfortable making a guess about which of these (or all of these?) to prioritize. 

Also feels important to note: We're doing our best to make candidate/legal resources warm and welcoming, but if we filter people from this page to pages like candidate services and legal resources, users will be moving away from the super plain language information in the "About" section, which could be jarring.

**Comment by emileighoutlaw** [comment]
👯 Was just posting a comment on that @jenniferthibault

**Comment by jenniferthibault** [comment]
Emileigh and I did some pairing to figure out potential content bridges that we could start with for testing: we landed on pairing the bullets in the first paragraph with the three major content buckets we've established for the site through the home page.

There is one new design element here: an icon for videos.

cc @nickykrause / @noahmanger 

![about-mission-history_v1](https://cloud.githubusercontent.com/assets/11636908/21554663/7aef6e6e-cddf-11e6-81fa-33369427572e.png)

**Comment by noahmanger** [comment]
This is good to go. Moving to implementation in #700

**Comment by emileighoutlaw** [comment]
This issue still needs Amy approval, so I'm reopening and moving to Sprint 4 as a 1 (the same we we handled the Leadership and structure issue)

**Comment by noahmanger** [comment]
Is this still pending?

**Comment by jenniferthibault** [comment]
Like the Leadership & structure section, if the content tweaks for this could happen in the CMS I think it could be closed. @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
Yep!
