### ISSUE TITLE
Design content and layout of About | Leadership and structure section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#675]
Using the flow from https://github.com/18F/fec-cms/issues/626#issuecomment-266852399
<img width="526" alt="screen shot 2016-12-19 at 10 34 59 am" src="https://cloud.githubusercontent.com/assets/11636908/21318345/d2fe5810-c5d6-11e6-9ee6-568e07f30ae2.png">

- [ ] Design the content for the:
  - [ ] Overview section
  - [ ] Commissioners (current) section
  - [ ] Commissioners (former) page
  - [ ] Placeholder copy for Agency structure
  - [ ] Commission directives and policies

We are going to omit the Agency structure section for the time being in favor of doing a deeper design dive on its own in https://github.com/18F/fec-cms/issues/676. For first release, we can do just enough to link it to http://www.fec.gov/about/offices/offices.shtml

- [ ] Determine what bridges to build between this content and other parts of the site (cross-linking strategy)

- [ ] Design content in template layout:
  - [ ] Create page layouts for commissioner bio pages
  - [ ] Create page layouts for agency structure pages (TBD on strategy and flow)

**Comment by emileighoutlaw** [comment]
I have a [content draft](https://docs.google.com/a/gsa.gov/document/d/1EeFut2fBDoRStCeZP5x8rdkEXYWMfX9Y_WY4_R0R9xw/edit?usp=sharing) 🔒  ready for us to talk about!


Re: pathways— I made note of one place where I think we should give users access to the calendar. I’m feeling reticent about other pathways, which I'd love to talk through with you Jen. :)

Basically, I'm feeling like this page already has lots of links on it: 
- Current commissioners (six, individual links)
- Former commissioners (takes users to a child section)
- Agency structure (takes users to a child section)
- Policy (a list of links)

Feels like so many links! We can talk about this more 💟

**Comment by jenniferthibault** [comment]
Emileigh and I are going to be reviewing this with Amy tomorrow and wrapping the remaining details for content & design. They mostly hover around the layout & structure of commissioner bio page.

**Comment by noahmanger** [comment]
This is implemented in a way that any content edits can happen on the CMS. Can we close?

**Comment by emileighoutlaw** [comment]
👍 from me to close. @jenniferthibault ?

**Comment by jenniferthibault** [comment]
👍 ⚡️
