### ISSUE TITLE
Design strategy and content of About | Reports about the FEC section 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#677]
From high-level section flow in https://github.com/18F/fec-cms/issues/626#issuecomment-266852399

and conversation in https://github.com/18F/fec-cms/issues/626#issuecomment-267147474

- [ ] Determine a definitive list of document categories , and which documents fall under each
- [ ] Write necessary microcopy for each document category and/or landing page
- [ ] Determine what bridges to build between this content and other parts of the site (cross-linking strategy)

**Comment by emileighoutlaw** [comment]
Pasting some high-level notes from our earlier issue in here so we continue to track them:

- Keep budget and strategy documents together
- Possibly consider including gift reports and treasury reports here
- Ensure FAIR Act and procurement reports stay are in the procurement and contracting card
- A note to future Emileigh: I'm increasingly feeling like Plain Language, the Privacy Act Notices, and the FOIA information should be special snowflakes that exist in the footer (and are thus accessible from every page) but don't live elsewhere in the site structure).

**Comment by jenniferthibault** [comment]
On policy-like required info that may live in the footer, we have this placeholder issue that captures that general need, but isn't fleshed out: https://github.com/18F/fec-cms/issues/484

We could bring this out of the ice box if you think it's near-ready, @emileighoutlaw

**Comment by emileighoutlaw** [comment]
You're right @jenniferthibault — it's probably near ready, which is why I keep doing the bad thing of making notes about it in other issues. 😞 Although we may need to wait one more sprint to take it out of the icebox, so we can guarantee we have some of Amy's time to help us sort through this.

**Comment by jenniferthibault** [comment]
For a quick refresher, here's where we left off with how this section could possibly be structured (thought the text is probably woefully out of date):

![screen shot 2017-01-04 at 1 36 54 pm](https://cloud.githubusercontent.com/assets/11636908/21654317/0eb76460-d283-11e6-824b-7d8f2fbf6731.png)

![screen shot 2017-01-04 at 1 37 02 pm](https://cloud.githubusercontent.com/assets/11636908/21654321/109750c4-d283-11e6-9929-bc5e8600e271.png)

**Comment by emileighoutlaw** [comment]
More content ready for @AmyKort to review. [Document](https://docs.google.com/document/d/1oS2bXtkoGXZyiQlg6HlHQdoC7eh3H1bRl1o88WplaQw/edit) 🔒 

Preview 😎 
<img width="639" alt="screen shot 2017-01-12 at 8 07 46 pm" src="https://cloud.githubusercontent.com/assets/10552702/21916532/e108661a-d906-11e6-9f99-7ba40506dc96.png">

**Comment by jenniferthibault** [comment]
Here's what those would look like in the templates: [Reports landing page on InVision](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085232_About-OrganizationalReports_V1) | [Document Category feed template on InVision](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085254_About-DocumentFeed)

**Previews**
![about-reports_v1](https://cloud.githubusercontent.com/assets/11636908/21940543/e0b98d1a-d992-11e6-8eb1-1b1368e12f07.png)
![about-documentfeed](https://cloud.githubusercontent.com/assets/11636908/21940547/e33b4cfe-d992-11e6-920a-8596be2c1a7f.png)

**Comment by noahmanger** [comment]
Just chiming in to say this all looks good to me.

**Comment by emileighoutlaw** [comment]
Ping to @AmyKort and @amypike 😄  — how are we feeling about the content in [this doc](https://docs.google.com/document/d/1oS2bXtkoGXZyiQlg6HlHQdoC7eh3H1bRl1o88WplaQw/edit) 🔒

**Comment by AmyKort** [comment]
This looks okay to me. Do you think we could go forward with this as it is planned and then have a little bit of time to let the owners of those reports check out the descriptions before we go forward? I think it would be helpful to folks to see the whole section in context. What do you think @amypike ?

**Comment by amypike** [comment]
I agree that it would be helpful for owners to see the whole section in context.  This sounds like a great plan to me, @AmyKort.  @emileighoutlaw One micro-copy change:  In the FOIA section, can we change "record" to "records" so it reads "...records requests the FEC receives from the public?"  Thank you!

**Comment by emileighoutlaw** [comment]
Yep! We can definitely give folks time to review. 

Amy Pike: Made that change! Sorry to have missed it in the first place. 💟

**Comment by emileighoutlaw** [comment]
@jenniferthibault Are we ready to mark this issue as done?

**Comment by jenniferthibault** [comment]
Yes!
