### ISSUE TITLE
Design content and layout of About | Careers section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#678]
Using the flow from https://github.com/18F/fec-cms/issues/626#issuecomment-266852399

<img width="496" alt="screen shot 2016-12-19 at 11 07 45 am" src="https://cloud.githubusercontent.com/assets/11636908/21319472/64018964-c5db-11e6-9ac2-5710c917b7e5.png">

- [ ] Design the content/microcopy for the: 
  - [ ] Overview section
  - [ ] Current openings section
  - [ ] Application process section (new)
  - [ ] Additional resources section

- [ ] Determine what bridges to build between this content and other parts of the site (cross-linking strategy)

- [ ] Design content in template layout

**Comment by jenniferthibault** [comment]
For a quick refresh on what we have, here was the initial sketch of how this page could be broken down:

![about-careers_v1](https://cloud.githubusercontent.com/assets/11636908/21653776/cfef060e-d280-11e6-8768-6c8c7661ac36.png)

**Comment by emileighoutlaw** [comment]
We have content ready for @AmyKort to review. [Document](https://docs.google.com/document/d/18ssePA2mtIjQwmATXJuPStz08CfzaMWcZ6aSywXiGVU/edit) 🔒 

Preview (sorry that I had to split into two screenshots) 😎 
_Image 1:_
<img width="712" alt="screen shot 2017-01-12 at 8 08 34 pm" src="https://cloud.githubusercontent.com/assets/10552702/21916060/7102c976-d903-11e6-869c-f4e016c54bb4.png">
_Image 2:_
<img width="730" alt="screen shot 2017-01-12 at 8 08 50 pm" src="https://cloud.githubusercontent.com/assets/10552702/21916062/73b79cb4-d903-11e6-8679-84d466870a3f.png">

**Comment by jenniferthibault** [comment]
Here's what that could look like in the templates: [Designs on InVision prototype](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085106_About-Careers_V1)

One area I'm uncertain of is that typically we've translated table data on these pages to our feed pattern, which is what I'm showing in the mockup. But since there are often two postings for one job (one posting for US citizens, one for Status candidates) the number of items can grow pretty quickly. Would this qualify as an exception we'd want to keep the table format for? ( ☎️ @nickykrause @noahmanger )

![screen shot 2017-01-13 at 1 14 57 pm](https://cloud.githubusercontent.com/assets/11636908/21940443/666bc7c6-d992-11e6-9f1a-db8774443abd.png)


**Preview** 
![about-careers_v1](https://cloud.githubusercontent.com/assets/11636908/21940273/90ba9292-d991-11e6-90fe-2bad78195533.png)

**Comment by jenniferthibault** [comment]
I realized I missed the email signup note the first time, so went back and updated the mockups. One slight positioning adjustment I'd recommend @emileighoutlaw is that we put it before the job feed/table instead of after, where it's likely to be overlooked. We often do this with our feed/list calls to action, like on this AO feed:

<img width="926" alt="screen shot 2017-01-13 at 1 47 29 pm" src="https://cloud.githubusercontent.com/assets/11636908/21941472/e37125e6-d996-11e6-9ab9-f5226bc08e47.png">

**Comment by jenniferthibault** [comment]
🛎 ping to @nickykrause & @noahmanger design questions above^^

**Comment by noahmanger** [comment]
Looks good to me. I like using the feed pattern.

**Comment by nickykrause** [comment]
@jenniferthibault: I'm not 100% sure that I understand the question, but I _think_ that you're asking whether or not the list of job openings warrants a departure from the feed pattern, with a tabular display as a possible alternative. 

If that's correct, then here are my thoughts: 

I like the idea of using the table because I think it allows users to more easily scan the available jobs for side-by-side comparison. This ability seems seems (a) valuable given that we're talking about a list of things that have directly comparable attributes (GS level, application window, who can apply), and (b) possibly desirable, since it seems likely that job seekers would indeed want to compare the jobs against each other.

**Comment by johnnyporkchops** [comment]
I can add that we rarely have more than a few open jobs at any time, the most I have ever seen at once has been in the last few weeks--maybe ten at once, and I think that spike is already subsiding. So if that weighs into design decisions on how to display them, I thought it worth mentioning that is usually a short list.

**Comment by nickykrause** [comment]
Good point, @johnnyporkchops! If the list is indeed fairly short, then I am really on the fence, @jenniferthibault. I could see an argument for the table (above), but I'm also cool with using our established feed pattern for consistency, and since the list is likely to be short anyway.

**Comment by jenniferthibault** [comment]
Yep @nickykrause  that was my question, should have articulated better! 👍 Thanks for the job trend insight @johnnyporkchops , really helpful!

Designwise, I think this is done then. Is content wrapped @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
@amykort — Can we move forward with [this content](https://docs.google.com/document/d/18ssePA2mtIjQwmATXJuPStz08CfzaMWcZ6aSywXiGVU/edit)? I think last time we spoke you wanted to chat with someone from FEC HR to get a replacement first sentence for the `Hiring process` section.

**Comment by AmyKort** [comment]
I'll check in with him on Monday. Thanks!

**Comment by emileighoutlaw** [comment]
Any word on this, @AmyKort ?

**Comment by AmyKort** [comment]
I'll ask again.

**Comment by AmyKort** [comment]
Could we go forward with the draft as amended?

**Comment by AmyKort** [comment]
^^ @emileighoutlaw ^^

**Comment by emileighoutlaw** [comment]
Sure thing. Does that mean no "Hiring process" section for now?

**Comment by AmyKort** [comment]
Yes, for now.

**Comment by emileighoutlaw** [comment]
Sounds good. I understand that's been a tough section. Let's get what we can launched and work on improvements in the future. 

This is ready for implementation @noahmanger

**Comment by johnnyporkchops** [comment]
@jen and @emileighoutlaw, for the about/careers/ page design, there is a link in the  EEO section to our current EEO page: http://www.fec.gov/eeo/eeo.shtml.
I assume I should build this out as a child page of the about section in wagtail or leave it as a link to the old site for now. I wanted to check since it has been a while since this mockup was created.

All but three or four links on this page point to the EEOC website: 
https://www.eeoc.gov/

New about/careers/ page:
https://beta.fec.gov/about/careers/

**Comment by emileighoutlaw** [comment]
Whoops. I know this is closed now, but for the sake of openness and future reference, @johnnyporkchops was kind enough to talk through the "no job openings" language with me, and we are all 👍 on content.
