### ISSUE TITLE
Implement structure for "About the FEC" landing page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#679]
## Design: 
Uses the Registration and Reporting landing page template:

![about-landing_v1](https://cloud.githubusercontent.com/assets/11636908/21236524/5ad66f04-c2c9-11e6-916b-6a700b8d6451.png)

## Content

> ## About
> The FEC is an independent government agency, created by Congress in 1974. 

> #### Mission and history
> The FEC was created to promote confidence and participation in the democratic process. Read more about the FEC’s history, purpose and goals.

> [[Learn more]](url)

> #### Leadership and structure
> The agency is led by six Commissioners; no more than three of whom can belong to the same political party. Find out more about the FEC’s structure and its Commissioners. 

> [[Learn more]](url)

> #### Reports about the FEC
> The FEC regularly publishes information about its performance and objectives. These documents include strategic plans, budgets and procurement reports.

> [[Learn more]](url)

> #### Careers
> More than 300 people work at the FEC. Find current job openings and information about the application process. 

> [[Learn more]](url)

> #### Doing business with the FEC
> Working with experts, vendors and other external stakeholders helps the FEC support its mission. 

> Requests For Proposals (RFPs) and Requests for Quotations (RFQs) are posted by the  General Services Administration, either on its [e-BUY website]() or on its [Federal Business Opportunities website]().

> Reports about FEC procurement and contracting are available in [Reports about the FEC]().  

## Notes

This page is ready to be implemented, but none of the sub-sections will be designed & ready for implementation until a following sprint. We may want to ready it, but not release it until we determine what minimum criteria for this section's release is (cc @emileighoutlaw ). We could release it without active content sections and make them live as they are available, or we could hold until a minimum set of content is live as well.

**Comment by jenniferthibault** [comment]
@noahmanger you may want to 👀 for pre-sprint planning grooming.

**Comment by noahmanger** [comment]
I actually already had an issue for this https://github.com/18F/fec-cms/issues/667
