### ISSUE TITLE
Create/share information architecture/outline for "Candidate and committee services" section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#682]
Create (or if it exists already, share) a high-level information architecture outline for the content in the "Candidate and committee services" section. 

This task needs to be completed before  [Designing visuals and microcopy for "Candidate and committee services" landing page #671](https://github.com/18F/fec-cms/issues/671)

**Comment by emileighoutlaw** [comment]
Based on the outline that our content managers have been working on, this is the initial and broad structure of information that will be in the `Candidate and committees services` section

![candidate and committee services](https://cloud.githubusercontent.com/assets/10552702/21370008/50e13740-c6cf-11e6-90cb-b224ee4c9fbc.jpg)

cc @amykort to make sure this aligns with her understanding as well (the only difference between what's here and what was proposed initially, I believe, is that the managers added a new bucket for `Loans and debts`)

**Comment by jenniferthibault** [comment]
Ooooooo exciting! (And I really dig whatever tool you're using, which makes it look so nice, or maybe you made that by hand?).

One quick check—under Candidates, there is a `Filing reports` section, but other categories have `Filing reports with the FEC`. Is there going to be anything different about this section from the others structurally, or maybe it's just a typo? Trying not to assume things I don't know!

**Comment by AmyKort** [comment]
This gets two thumbs up from the Amys. Thank you!

**Comment by amypike** [comment]
@jenniferthibault  I don't think there's going to be anything different about the section, "filing reports" and "filing reports with the FEC" would tackle the same issues but thanks for flagging the inconsistency.  I think "filing reports" is just shorthand.  @emileighoutlaw correct me if I'm wrong.

**Comment by emileighoutlaw** [comment]
Nice catch! I made the Candidates bucket "Filing reports" because Senate candidates file with the Secretary of Senate. But in all the other cases, I think "Filing reports with the FEC" adds some nice clarity to the process.

**Comment by jenniferthibault** [comment]
Awesome. Thank you! Closing this issue and taking the structure into designs for #671 


On the second day of Sprint-mas
my colleague gave to me:
Two thumbs up 👍 👍 
and one closed GitHub issue 🚫 :octocat:
