### ISSUE TITLE
 Make homepage fail gracefully if API issues

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#689]
It seems like we have been getting a minute or two of down time at 2 or 3 AM on the cms after this last release. I am thinking it might be that one of the endpoints that is used on the homepage goes down as a table gets recreated. It is not a huge deal, but I could see a scenario where we have API issues and we don't want the homepage to go down too. 

It would be good to check that the homepage fails gracefully if one or more of the endpoints goes down.

(we should also add some pings to these chart endpoints https://github.com/18F/openFEC/issues/2121)

**Comment by noahmanger** [comment]
Good catch @LindsayYoung . This is probably from the calendar, since that's the only openFEC API currently getting hit from the home page. 

What do you think the right approach is @xtine ?

**Comment by xtine** [comment]
I notice there is occasionally a lag when hitting the calendar endpoint, but it just makes the "Upcoming Events" section blank. I think we could have a message after a timeout/error. It could be a a reload link or message just saying events couldn't be loaded.
