### ISSUE TITLE
Screenreader friendly homepage intro

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#694]
Here's our gorgeous new homepage:

![screen shot 2016-12-29 at 10 05 44 am](https://cloud.githubusercontent.com/assets/10552702/21547906/9dfa0e18-cdae-11e6-9c3b-402f5e8974bb.png)

I pushed us down a content rabbit hole by raising alarms about the word "below," which can be disorienting for folks who access websites with screenreaders (and don't have a visual frame of reference for directional words). 

Eliminating the word "below" so that the links say only "Get started" doesn't feel like a good solution. "Get started" feels like starting an action, so it _does_ feel like a link that would push users to another page.

I spent some time thinking about and working on this, and I'd like to propose we revise the content to be:  
![screen shot 2016-12-29 at 10 04 42 am](https://cloud.githubusercontent.com/assets/10552702/21547942/ce7027da-cdae-11e6-82e5-0a9ba334a458.png)

1. "Learn more" with the downward facing arrow feels like a stronger indicator of moving down the page. Additionally, we could add some more invisible text for screenreaders, perhaps a parenthetical that explains the link jumps readers down the page.

1. I'd like to raise a question about the use of a perceptual flash when users click the "Get started" button. The combination of the perceptual flash and the change in URL (to https://beta.fec.gov/#homepage-registration-and-reporting, for example), feels like the user has left the homepage, even though they haven't. I'm sure y'all have already thought about this, but did we consider a scroll action, rather than a flash for those links? I think that could also be helpful in folks understand the links better. 

1. (This has to go by Amy, but) I'm also proposing we trim the content in the top section:
    -  We know homepages are skimmed by users, and the fewer words we use to convey our message, the better. 
    - We're inconsistent in what we highlight right now for each section. The data blurb explains _what the FEC does_ and _why users need it_. The registration blurb explains only _what the FEC does_. The legal blurb explains _what the FEC does_ and _how that translates to specific features for users_.  
        - Removing "Helping citizens make informed voting decisions" piece from the data section and removing the "Search or browse...." sentence from the legal section both trims the content and makes a consistent message of _what the FEC does_. The specific services are broken down clearly if folks click the "Learn more" link. 

cc @jenniferthibault @noahmanger

**Comment by emileighoutlaw** [comment]
After our design sync, it sounds like we're all on board to try out this content approach:


![screen shot 2016-12-29 at 10 04 42 am](https://cloud.githubusercontent.com/assets/10552702/21547942/ce7027da-cdae-11e6-82e5-0a9ba334a458.png)


If @AmyKort gives us the thumbs up when she gets back.

**Comment by noahmanger** [comment]
I went ahead and implemented this in https://github.com/18F/fec-cms/pull/695 but we can adjust if necessary.

**Comment by AmyKort** [comment]
I like the change to the content, @emileighoutlaw Thanks!!
