### ISSUE TITLE
Design second-level C&C services page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#698]
So that candidates and committees can find all of the information about what they need to do to be compliant, present a second-level page for each type of entity.

---

This is a design task is to determine and design the templates that exist a level below the main "Candidate and committee services" landing page from https://github.com/18F/fec-cms/issues/671

**Completion criteria:**
- [ ] Decide approach for these pages
- [ ] Design page template ready for implementation

**Comment by jenniferthibault** [comment]
I made some mockups to show our content manager group for the first step toward deciding what approach to take for this section. @emileighoutlaw please let me know if I should revise anything before we show them.

### Each option stems from this landing page:

![cc-services-v2](https://cloud.githubusercontent.com/assets/11636908/21625402/7ff876e6-d1d9-11e6-8e97-1c706905797a.png)


## Option 1: Each section on one long page

**Things that are** 👍 
- All documentation is easily printable
- Anchor links could help with sharing/linking to specific sections
- Keeps overall page count low

**Things that are** 👎/ ⚖️ (neutral) 
- Long page risks users overlook information relevant to them
- May need to iterate side nav pattern into a table of contents-like pattern for more granularity

### Info architecture
![ccs-option 1](https://cloud.githubusercontent.com/assets/11636908/21625415/8d042830-d1d9-11e6-8f84-a98e519aa918.png)

### Template mockup: Section page, (level 2)
![cc-services-v2 copy](https://cloud.githubusercontent.com/assets/11636908/21625535/20b3f06a-d1da-11e6-8f40-60caa94125e6.png)


## Option 2: Each sub-section is its own article page
**Things that are** 👍 
- Shorter pages/sections are easier to scan

**Things that are** 👎/ ⚖️ (neutral) 
- Raises overall page count
- Takes many clicks to get into meat of instructions and guidance

### Info architecture
![ccs-option 2](https://cloud.githubusercontent.com/assets/11636908/21625620/7ca4b436-d1da-11e6-96ce-30bc3b4640e0.png)

### Template mockup: Section page, (level 2)

![cc-services-v2 copy 2](https://cloud.githubusercontent.com/assets/11636908/21625622/8205395a-d1da-11e6-9128-547003735ded.png)

### Template mockup: Sub-section page, (level 3)
![cc-services-v2 copy 3](https://cloud.githubusercontent.com/assets/11636908/21625623/820ce722-d1da-11e6-902a-0d7768cf088d.png)

**Comment by emileighoutlaw** [comment]
This is incredibly comprehensive and looks spot on to me, Jen. I can't think of anything else I'd like added, but I'll continue mulling. 

One thought: I would like to give Amy an as-quick-as-possible orientation to this tomorrow, so she knows the kinds of things we're planning to talk to the managers about (i.e., isn't surprised by anything when we get time with them this week)

**Comment by emileighoutlaw** [comment]
Had a great meeting with FEC's content team on Friday. They loved our design proposal for this page. @jenniferthibault, do you think we can mark this task as done?

**Comment by jenniferthibault** [comment]
Almost—I had marked that I need to figure out where/how we plan to accomodate the relevant resources that Greg sent over, and was planning on spinning up some mockups in this issue. Unfortunately not today, because #meetings . 
Does that work for you, or were you thinking this issue is complete without it?

**Comment by emileighoutlaw** [comment]
Oh interesting! I think the second-level pages are introductory, wayfinding pages, rather than learning pages. So I think all the resources the Greg wants to include would be additions to the third level of pages, the Wagtail pages, rather than the first-level or second-level landing pages. So, like this:

![c c](https://cloud.githubusercontent.com/assets/10552702/21815087/0c0ccd48-d721-11e6-8465-1194771201aa.png)

Which makes me _think_ that this issue is done. And we'll need another issue alter for adding new design elements that we need to the Wagtail custom template.

**Comment by jenniferthibault** [comment]
Thanks for getting on the same page about this just now @emileighoutlaw. I'll close this now & make a new issue for considering the new design elements on the Wagtail custom template (4th level?).

I'd like to try to get that knocked out before the end of this sprint if I can, but there are a few other issues I've been neglecting!

**Comment by jenniferthibault** [comment]
Carried over the 4th level page designs to https://github.com/18F/fec-cms/issues/727
