### ISSUE TITLE
Determine release strategy for C&C Services section

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#699]
The purpose of this task is to determine how we want to release sections of the "Candidate and committee services" section considering that it will eventually (but not immediately) replace the "Registration and Reporting" section. Whatever we decide to do, it should:

- Allow for all content on the current beta site to stay available
- Require as little re-work as possible

**Completion criteria:**
This issue should result in a plan for staggered release of content in the C&C services section that accounts for:
- [x] What happens to the main navigation
- [x] What happens to the home page
- [x] What happens to the C&C Services landing page

**Comment by emileighoutlaw** [comment]
@jenniferthibault — do you want to get together and brainstorm on this early next week? Should anyone else (Noah? Nicky?) be there as well?

**Comment by jenniferthibault** [comment]
Just scheduled us for next Tuesday afternoon, and added @noahmanger as optional. Didn't add Nicky in an attempt to protect her schedule and workstream. Maybe instead we could get her feedback on what we come up with during Thursday's design pairing?

**Comment by jenniferthibault** [comment]
Summary of chat with @emileighoutlaw & @noahmanger yesterday, please review & let me know if I got everything right:

**What happens to the Candidate and committee services landing page**

We'll port the existing registration and reporting content to the new structure under "Registering as an X" and "Filing reports" for each group type. The rest of the links will be disabled, and re-enabled as the content is ported. That would look like this:

![cc-services-v2](https://cloud.githubusercontent.com/assets/11636908/21862137/e48ec808-d805-11e6-9fd3-886014fd59f0.png)

**What happens to the home page**
We revive the original structure for the design, but need to plan for content & design work to finalize & approve. Where we last left off, the design & structure was hovering around these ideas:

![screen shot 2017-01-11 at 1 59 52 pm](https://cloud.githubusercontent.com/assets/11636908/21862254/6b186212-d806-11e6-9759-08f639cb1a21.png)
![screen shot 2017-01-11 at 2 00 42 pm](https://cloud.githubusercontent.com/assets/11636908/21862255/6b18ca2c-d806-11e6-810f-43c9e4d4ead0.png)

**What happens to the main navigation**

I don't remember that we specifically talked about this, but based on the two above, I'm assuming the top-level category changes to "Candidate and committee services" ?

**Comment by noahmanger** [comment]
Sounds great. And yeah, I'd agree the top nav item just changes.

**Comment by noahmanger** [comment]
We now have a strategy and the work for this page is in #736 so I'm closing this.
