### ISSUE TITLE
Implement "About: Leadership and structure" page 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#701]
So that users can learn about the leadership and organizational structure of the FEC, implement a page that contains this information.

---

🖌  Designs (pending) | 📜  [Content](https://docs.google.com/document/d/1EeFut2fBDoRStCeZP5x8rdkEXYWMfX9Y_WY4_R0R9xw/edit) | 🗣  [Discussion](https://github.com/18F/fec-cms/issues/675)

This page should be just another instance of the `ResourcePage` model but with a few additional pieces (once designs are posted). 

**Completion criteria:**
- [x] Implement any new modules
- [x] Make page and add content once on production

**Comment by noahmanger** [comment]
For this one, we need to include a grid of commissioners:
![image](https://cloud.githubusercontent.com/assets/1696495/21664343/9c9e9336-d29a-11e6-8a84-221e9fb4da69.png)

At first I was thinking this would just be another block type, but then I thought that if we're making new page models for commissioners, we could instead make this a picker that lets you select commissioner pages to reference, and then automatically pull in their headshot, title, party and position. What do you think @xtine ?

**Comment by xtine** [comment]
@noahmanger: yeah, if the commissioners are going to be stored in the cms for each profile page, then it makes sense to just pull that data instead of generating it again for this template.

**Comment by noahmanger** [comment]
We'll handle making the page in production as a separate task. This template has been coded and so the work is all done.
