### ISSUE TITLE
Implement "About: All Commissioners" page template

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#702]
So that users can see the complete list of all commissioners ever, create a page that lists all commissioners past and present.

---

🖌  Designs (pending) 

[The complete list of commissioners](http://www.fec.gov/members/formermembers.shtml)

**Completion criteria:**
- [x] Create a new page template that matches the designs

**Comment by jenniferthibault** [comment]
Here's the link to the [All Commissioner page](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085049_About-Organization-Structure-FormerCommissioners_V1) design on InVision.

@patphongs could we enlist your help in getting all the commissioner bio images from the old site? I can crop & re-export them as circles.

@xtine one thought: on the [Commissioner bio template page](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211085029_About-Organization-Structure-Commissioner_V1) the image will be almost double the size, is it best to export the image at that larger size, and scale down for the smaller instance? Or should I export two sizes?

**Comment by xtine** [comment]
@jenniferthibault: export the larger size.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/723
