### ISSUE TITLE
Add "Tips for Treasurers" to Latest Updates

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#705]
So that committees can get the latest info, add all Tips for Treasurers to the Latest Updates feed.

---

Tips for Treasurers are short, specific blurbs that are regularly published by the FEC. They all live at http://www.fec.gov/info/TipsforTreasurers.shtml#Tips

The purpose of this task it to scrape them all, create a new page model and template, and then import all the data. 

When scraping, we should just grab the date, title and content.

**Completion criteria:**
- [x] Scrape entire archive
- [x] Report broken link issues in existing content to someone at FEC (see comment below)
- [x] Create new page model
- [x] Create new template (@jenniferthibault has the design)
- [x] Import all data
- [x] Update Latest Updates feed to show

**Comment by tadhg-ohiggins** [comment]
I've started work on the first (“Scrape entire archive”) item.

**Comment by ccostino** [comment]
@tadhg-ohiggins, awesome!  I had taken your previous scraper for the record pages and incorporated it as a Django management command; if you'd like to see how I accomplished that or pair on it at all, let @dogweather and I know!

In the mean time, @dogweather you and I could start with the next two items (creating the new page model and template)

The import should be straightforward and mirror what we have for the others barring a few things specific to this model, but we can tackle that once the other pieces are in place and we can at least get some sample records.

**Comment by dogweather** [comment]
@ccostino , want to pair-program on this? The CMS is a lot to take in all at once.

**Comment by ccostino** [comment]
@dogweather yup!  Sorry I wasn't clear in the above message, that's what I meant by us starting.  I planned to use this an opportunity to go over the CMS with you. :-)

**Comment by jenniferthibault** [comment]
Here's the design for the template. It should really be the same as a Press Release template, but with two structure/style differences:
- No Contacts section at the bottom
- No `t-lead` class style on the first paragraph

![tipstreasurers-v2](https://cloud.githubusercontent.com/assets/11636908/21648411/e2813388-d26b-11e6-8c28-8067b9ffadf2.png)

**Comment by tadhg-ohiggins** [comment]
While going through the current content, I found the following broken links:

- http://a257.g.akamaitech.net/7/257/2422/01jan20061800/edocket.access.gpo.gov/2006/pdf/06-7297.pdf (Correct link: https://www.gpo.gov/fdsys/pkg/FR-2006-08-31/pdf/06-7297.pdf )
- http://a257.g.akamaitech.net/7/257/2422/01jan20061800/edocket.access.gpo.gov/2006/pdf/E6-14183.pdf (Correct link: https://www.gpo.gov/fdsys/pkg/FR-2006-08-28/pdf/E6-14183.pdf )
- http://www.fec.gov/aos/2006/ao2006-24final.pdf (Correct link: http://saos.fec.gov/saos/aonum.jsp?AONUM=2006-24 )
- http://www.fec.gov/aos/2006/ao2006-26final.pdf (Correct link: http://saos.fec.gov/saos/aonum.jsp?AONUM=2006-26 )
- https://webforms.fec.gov/form24/ (Correct link: https://webforms.fec.gov/onlinefiling/form24/login.htm )
- https://webforms.fec.gov/form6/ (Correct link: https://webforms.fec.gov/onlinefiling/form6/login.htm )
- https://webforms.fec.gov/wfja/form6 (Correct link: https://webforms.fec.gov/onlinefiling/form6/login.htm )

The scraper substitutes the correct link for the broken one in its output.

The service that redirects anything under http://www.fec.gov/aos/ is broken, going to http://saos.nictusa.com/ , a domain which doesn't exist.

I *think* https://webforms.fec.gov/formXX and https://webforms.fec.gov/wfja/formXX should redirect according to the following values of XX (but note that the FEC index page at https://webforms.fec.gov/ forces the acknowledgement of a legal agreement before letting you continue, so it's possible these pages should check for that upon arrival, something they currently don't do) :

1: https://webforms.fec.gov/webforms/form1/index.htm
2: https://webforms.fec.gov/webforms/form2/index.htm
24: https://webforms.fec.gov/onlinefiling/form24/login.htm
5: A page that lets the user choose between https://webforms.fec.gov/wfja/form5?USER_TYPE=CMT and https://webforms.fec.gov/wfja/form5
6: https://webforms.fec.gov/onlinefiling/form6/login.htm
9: A page that lets the user choose between https://webforms.fec.gov/wfja/form9?USER_TYPE=CMT and https://webforms.fec.gov/wfja/form9
99: https://webforms.fec.gov/wfja/form99

It's not certain that there are broken links out there pointing at any of the forms other than 6 and 24 (broken links for both of which are found on the Tips for Treasurers pages).

**Comment by ccostino** [comment]
Thanks, @tadhg-ohiggins!  Whenever you want to get together to go over how to integrate the scraping into the CMS like I did with the record pages just let me know.

**Comment by tadhg-ohiggins** [comment]
The scraper for these pages returns an object with these properties for each tip:

body: The HTML for the tip content.
previous_url: The URL that the tip is on in the current system.
posted_date: The date for the tip.
title_text: The HTML for the title of the tip.

For the early tips without titles, I used “Timely Tip for [month] [day], [year]” as the title, for example “Timely Tip for May 18, 2006”

Here's what the JSON output for a random tip looks like:

```
{
"body": "Starting with the July 2009 issue, the FEC will no longer print and mail copies of its monthly newsletter, the <em>Record</em>, and will instead distribute it electronically. The <em>Record</em> will continue to be made available each month on the FEC web site at <a href=\"http://www.fec.gov/pages/record.shtml\">http://www.fec.gov/pages/record.shtml</a>, and the FEC will notify all registered committees via e-mail each time a new issue is posted. Individuals and organizations who are not registered with the Commission, but who would like to continue to receive the <em>Record</em>, can subscribe through FECMail to receive e-mail notification when a new issue is posted to the web site. Subscribing is easy. Simply visit our web site at <a href=\"http://www.fec.gov/pages/record.shtml\">http://www.fec.gov/pages/record.shtml</a> and click on the link &#8220;Sign-up to<br>\r\nreceive an e-mail notification when a new issue of the <em>Record</em> is posted.&#8221; Upon request, the Commission will print and mail copies to individuals who do not have computer access.",
"previous_url": "http://www.fec.gov/info/tips/timelytipsarchive2009.shtml",
"posted_date": "2009-05-04",
"title_text": "Electronic Distribution of <em>Record</em> Begins in July 2009."
}
```

**Comment by noahmanger** [comment]
These are looking good. We'll still do an actual visual QA and there might be changes from that, but this story has been completed.
