### ISSUE TITLE
Remove About & Contact from CMS utility nav

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#709]
https://beta.fec.gov/updates/fec-elects-steven-walther-chairman-2017-caroline-hunter-serve-vice-chair/

<img width="1280" alt="screen shot 2017-01-04 at 10 19 33 am" src="https://cloud.githubusercontent.com/assets/11636908/21647249/79ea3166-d267-11e6-979c-5eb1ba56da33.png">

**Comment by noahmanger** [comment]
Did this with the last release.
