### ISSUE TITLE
Press releases not retaining filters applied in feed when selecting breadcrumb nav

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#710]
**Steps to recreate:**

1. Go to any press release in the latest updates feed: 
[FEC Approves Audit Division Recommendation Memorandum....](https://beta.fec.gov/updates/fec-approves-audit-division-recommendation-memorandum-legislative-recommendations-and-amendments-agency-circulation-vote-procedures/)
[FEC Elects Steven Walther as Chairman for 2017...](https://beta.fec.gov/updates/fec-elects-steven-walther-chairman-2017-caroline-hunter-serve-vice-chair/)
2. Click "Press Release" category from breadcrumbs bar
<img width="541" alt="screen shot 2017-01-04 at 10 25 28 am" src="https://cloud.githubusercontent.com/assets/11636908/21647426/3518e2b6-d268-11e6-9c60-26a6d145c8ef.png">

**Expected result**
Return to Latest Updates page where URL indicates filter is applied, and feed is filtered down by publication type and category.

**Actual behavior**
Latest updates feed remains unfiltered. 

<img width="1277" alt="screen shot 2017-01-04 at 10 26 24 am" src="https://cloud.githubusercontent.com/assets/11636908/21647495/84fc77f2-d268-11e6-976f-b7d00dc72e0b.png">

**Comment by noahmanger** [comment]
Resolved by #742
