### ISSUE TITLE
AO Process page is down

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#719]
Link https://beta.fec.gov/legal/advisory-opinions/process/ is down. From https://beta.fec.gov/data/legal/advisory-opinions/

![screencapture-beta-fec-gov-legal-advisory-opinions-process-1483740257275](https://cloud.githubusercontent.com/assets/24054/21734595/6fc4a3a4-d421-11e6-81f4-4032c310993d.png)

404 error page also interestingly has the development banner on top.

**Comment by jenniferthibault** [comment]
Fixed by https://github.com/18F/fec-cms/pull/720 🎉
