### ISSUE TITLE
Provide a way for users to find/navigate to the API

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#729]
Users looking for documentation of the FEC's data and ways to repurpose it for their own uses need to be able to find the API from the main site.

https://api.open.fec.gov/developers/

**Steps to completion**
- Determine strategy for building bridges across these two sites
- Design content/microcopy as needed
- Design mockups 

cc @PaulClark2

**Comment by noahmanger** [comment]
Tagging in @onezerojeremy on this as you're looking at various IA and nav things.

**Comment by noahmanger** [comment]
We're addressing this in https://github.com/18F/fec-cms/issues/833 , so I'm closing this.
