### ISSUE TITLE
Side nav on About FEC page is not sticky

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#737]
https://beta.fec.gov/about

The menu should scroll with the user down the page, like it does on https://beta.fec.gov/registration-and-reporting/ but instead it stays in place at the top

<img width="1279" alt="screen shot 2017-01-13 at 9 51 20 am" src="https://cloud.githubusercontent.com/assets/11636908/21934047/f0624f12-d975-11e6-9a35-05b399299db3.png">

cc @xtine

**Comment by noahmanger** [comment]
This is fixed in this release ([staging](https://fec-stage-proxy.18f.gov/about/
)) so I'm going to close.
