### ISSUE TITLE
Complete site map

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#740]
We need to build a complete site map that will show how the new site will allow users to get to all of the information that they can currently access on the legacy site. 

The site map should capture what pages/sections will live on the new site and which will stay on the old site. For the pages that stay on the old site, we should also include a rough plan for when those will move to the new site. 

In order to do this, we need to:
- [x] Finish going through the [content inventory](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit#gid=1663724919) to address the following tabs: 
  - Compliance
  - BRCA
  - Registration and Reporting
  - Forms
  - Reporting Dates and Deadlines
- [x] Review the sheet with FEC
- [x] Translate the sheet into a graphic site map
- [x] Resolve remaining questions in the inventory

**Comment by noahmanger** [comment]
@emileighoutlaw and I have been really heads down on this this sprint, but we finally have something to share. It's not 100% complete, but I'd say we're 95% of the way there. There's still a few notable gaps, namely:
- Making sure that everything in the compliance and registration and reporting tabs is all accounted for (which is currently in progress as we build the content for the new section)
- Account for all pages currently in the campaign finance data tab of the spreadsheet
- And there's scattered random issues that @AmyKort and others are working on chasing down answers to 

But I think we have a really strong structure that identifies several gaps that we need to fill in in order to ensure that all content is reachable via the new structure when we flip the sites. 

Here's the full map in PDF (note that you can click through to any page that includes a 🔗  icon ): 
[FEC Sitemap.pdf](https://github.com/18F/fec-cms/files/736660/FEC.Sitemap.pdf)

As you'll se, we need to make several additional pages to link to the additional tools that will continue to live on the legacy site. We'll be discussing how to tackle these in the days ahead.

**Comment by patphongs** [comment]
@noahmanger @emileighoutlaw @AmyKort this is great! Thank you for providing something that is concise. This will help me a lot when trying to figure out how to build out the legacy site. Looking forward to our future discussions about this topic.

**Comment by AmyKort** [comment]
Thanks everyone!

**Comment by nickykrause** [comment]
This is so cool and so helpful, @noahmanger and @emileighoutlaw!  :clap: :tada: ❤️

**Comment by emileighoutlaw** [comment]
One more note: Amy and Pat are meeting with OGC next week to talk about NPRMs. Everything related to a rulemaking file should be in SERS, so many of the files in our inventory's NPRM tab may be redundant.

**Comment by emileighoutlaw** [comment]
Another note: We talked about taking down old prior notices. FEC smartly believes that the benefits of keeping past year prior notices around **do not** outweigh the risk of people accidentally looking at the wrong one or the burden of having thousands of prior notices cluttering the site. 

That said, FEC staff will need a way to find the notices (when people need them). (This doesn't have to be on the website. 

Also FEC will need a way to establish that a prior notice was on the website at a particular point in time, since this could become an issue with questions of timely filing.

**Comment by noahmanger** [comment]
Update on this. We went through the campaign finance data portion of the inventory today, and while there's some questions around some old pages, I think we very nearly have a plan. Here's my suggestion for what we need to do:

![fec sitemap](https://cloud.githubusercontent.com/assets/1696495/22533933/d4fc14d0-e8a5-11e6-8e3f-b60cfad0de7d.png)

The map includes the addition of two new pages:
- "Additional data": This will act as a landing page, providing links to the bulk data sets, the data catalogue, and the entire collection of press summary statistics, all still hosted on the old site at the time of flipping. Eventually these will be ported over to pages on the new site. 
- "About the data": This can house the content from the [Disclosure FAQ](http://www.fec.gov/ans/answers_disclosure.shtml), provide links to the Pacronyms files, and link to the brochure about the permisable use of the data. 

This is my suggestion for how we could get maximal coverage for now. cc @PaulClark2 @AmyKort @emileighoutlaw @jwchumley

**Comment by emileighoutlaw** [comment]
I think this looks great. I'm curious about the decision to include "Additional data" as a top-level item in the campaign finance section.

 Based on what's inside of it, this seems possibly better suited to be a child of the "Advanced data" section? The data catalogue seems like something only advanced users would be looking for. I think the statistical releases (the value of which is a historical snapshot in time) are also a pretty advanced data need. As are the FTP download pages. 

What do you think?

**Comment by noahmanger** [comment]
@emileighoutlaw I don't have strong feelings one way or the other. It kind of depends for me on a) what we call it and b) how it would be to integrate it as a page under "Advanced". Maybe we can bracket the question until we look more closely at the implementation?

**Comment by emileighoutlaw** [comment]
Sounds good to me!

**Comment by noahmanger** [comment]
Alright, we have a working site map (also in Drive), so I'm closing. [PDF](https://github.com/18F/fec-cms/files/756224/FEC.Sitemap.pdf).
