### ISSUE TITLE
Build C&C Services second- and third-level pages in CMS

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#741]
This issue is for building out the various pages for the Candidate and Committee Services section with the content that we have. This includes:

- Building out the landing page as [designed here](https://github.com/18F/fec-cms/issues/671)
- Building the third-level pages for the candidates section and linking to the sub-pages that are being built out in https://github.com/18F/fec-cms/issues/630
- For the other committee types, moving the pages from the Reg. and Reporting section to here

**Dependency:** Depends on [this PR](https://github.com/18F/fec-cms/pull/736) being merged and deployed to production. Once that's in, we shouldn't need to actually make any additional code changes to get these built out.

**Completion criteria:**
- [ ] Candidate committee services page exists and links to content for each committee type
- [ ] Build third-level pages with information for each committee type
- [ ] Replace "Registration and reporting" nav items with "Candidate and committee services" (on CMS, web app and eregs)

@emileighoutlaw does this sound right? I realized we didn't really have an issue for this work.

**Comment by noahmanger** [comment]
Production now has the template for the C&C Services landing page and I got @emileighoutlaw set up to fill it out with content.

**Comment by emileighoutlaw** [comment]
Done. So so happy to finally close this.
