### ISSUE TITLE
Adjust POV of existing registration and reporting pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#744]
The point of view in existing registration and reporting pages has the user as "you." 

When we launch a full suite of content for `Candidate and committee services`, the new content will be in third-person. We'll need to adjust all existing Wagtail pages to move from second-person to third-person.

**Comment by emileighoutlaw** [comment]
This only needs to happen when we are about to launch the first section of content.

**Comment by emileighoutlaw** [comment]
We still want this to be the last thing that happens before launching `Help for candidates and committees`, so moving to the next sprint.

**Comment by emileighoutlaw** [comment]
- [ ]  Candidates
- [ ] Nonconnected PACs
- [ ] Political parties
- [ ] SSFs

**Comment by emileighoutlaw** [comment]
Checking in with @amykort — since these pages used to be live, and all we are changing is "you" into "a committee," I'd love to relaunch these on the site when we're done. 

This would be the "Registering as a xxxxx" and "Filing reports" section for our remaining three groups: nonconnected PACs, SSFs, and political parties. 

What do you think?

**Comment by AmyKort** [comment]
Sounds good.

**Comment by emileighoutlaw** [comment]
Three cheers to @llienfec for taking this over the finish line. This is finally done.
