### ISSUE TITLE
Review second- and third-level candidate services pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#745]
Before launch, we need to do a systematic review (both Emileigh and content managers) of

1. **Second-level landing pages**
    - Registering as a candidate
    - Taking in receipts
    - Making disbursements
    - Handling loans, debts and advances
    - Keeping records
    - Filing reports
    - Winding down a campaign

1. **Third-level Wagtail pages (for each of the above sections)**

**Comment by emileighoutlaw** [comment]
Shipped to content managers this morning for review.

**Comment by emileighoutlaw** [comment]
- [ ] Remove screenreader unfriendly words like "above" "below" and "see"
- [ ] Remove references to "chapters," which won't exist  in online structure
- Unify legal citations
    - [ ] Headers
    - [ ] Links
    - [ ] Italics
    - [ ] Order of legal types (even if only one per page)
- [ ] Bullet punctuations
- [ ] Page titles
- [ ] In-line links to the law (i.e., references _not_ in citations sidebar)
- [ ] References to FECA

**Comment by emileighoutlaw** [comment]
@AmyKort ! I am _done_ ( 🎉 🎉 🎉 🎉 🎉 🎉 🎉 ) reviewing these pages for style and consistency. So all we need is any last edits from our content managers.

I'd love to get anything we need to OGC as soon as possible, so we can launch as soon as possible :) Should we get together to discuss steps between now and taking this content live?

**Comment by AmyKort** [comment]
Thank you!! Do you want to try to meet middle of next week?
