### ISSUE TITLE
Make sidenav sticky on AO Process page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#749]
https://beta.fec.gov/legal/advisory-opinions/process/#overview

On desktop, the nav should scroll with the user down the page, like it does on https://beta.fec.gov/registration-and-reporting/ but instead it stays in place at the top

<img width="1278" alt="screen shot 2017-01-19 at 9 51 15 am" src="https://cloud.githubusercontent.com/assets/11636908/22111294/d6a4910a-de2c-11e6-806a-f08ba6d1e3ae.png">

**Comment by noahmanger** [comment]
Resolved https://beta.fec.gov/legal-resources/advisory-opinions-process/
