### ISSUE TITLE
Add missing legal citations section to AO Process page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#750]
https://beta.fec.gov/legal/advisory-opinions/process/#legal-citations

The section exist on the side nav, but is missing from the page.

<img width="1275" alt="screen shot 2017-01-19 at 9 56 05 am" src="https://cloud.githubusercontent.com/assets/11636908/22111520/9146df40-de2d-11e6-985f-bde98433386e.png">

It should look like this, which is a new pattern:

![screen shot 2017-01-19 at 9 52 58 am](https://cloud.githubusercontent.com/assets/11636908/22111369/1a9415f2-de2d-11e6-9f61-ece34806f50b.png)

Most recent text: [Google Doc](https://docs.google.com/document/d/1XElM0QI3lP_9zrUi_TBqCnk8UcogoAkTLWbhBzPzgJs/edit) 🔒

**Comment by noahmanger** [comment]
Resolved https://beta.fec.gov/legal-resources/advisory-opinions-process/

**Comment by emileighoutlaw** [comment]
The legal citations were also linking out to the GPO (not beta site) and missing titles. I went in and made those fixes just now.
