### ISSUE TITLE
Broken Image Candidate Guide Icon

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#753]
Seems to be a broken image for the Candidate Guide icon at the bottom of the page below. It's using an inline image rather than a CSS background image like all the other icons. Would be happy to help fix if we can track down what icon is supposed to be there. cc @jenniferthibault 

https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/

<img width="236" alt="screen shot 2017-01-20 at 7 32 21 pm" src="https://cloud.githubusercontent.com/assets/12799132/22170064/8b5d7600-df47-11e6-8064-6b9abe509ea1.png">

**Comment by jenniferthibault** [comment]
@noahmanger is this a casualty of what's going wrong in the CMS image loader? Or something else?

**Comment by noahmanger** [comment]
Nope, just mis-named img srcs. Fixed in https://github.com/18F/fec-cms/pull/771

**Comment by noahmanger** [comment]
Resolved in the last release:
![image](https://cloud.githubusercontent.com/assets/1696495/22672354/2e6d6506-ec88-11e6-9bd6-db6d68c58d94.png)
