### ISSUE TITLE
Build out "About" pages in the CMS

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#754]
Once we have the ability to upload images to Wagtail (https://github.com/18F/fec-cms/pull/747) we can start building out the  new "About" pages we recently added templates for in the CMS. There's a few parts to this:

## Commissioner pages
- [x] Build out individual commissioner pages (past and present). This will automatically populate the main commissioners index page.

@xtine is familiar with the templates and @emileighoutlaw knows what needs to happen with the content. This would be a good thing to get someone at the FEC set up with doing.

## Mission and history
I've got a draft of this page started. We need to:
- [x] Add the thumbnail for the video 
- [x] Publish 

## Leadership and structure
I've got a draft of this page. We need to:
- [x] Merge [this change to Wagtail](https://github.com/18F/fec-cms/pull/735) to introduce the ability to add a static block of commissioners
- [x] Add the commissioner block
- [x] Add the link to the commissioners page
- [x] Add the commission directives as Wagtail documents
- [x] Publish

## About page
Once all that's done, we can activate the links on the "[About the FEC](https://beta.fec.gov/about/)" page to the various sections.

**Comment by patphongs** [comment]
### Building Commissioner pages:
John and I will be working to build out the Commissioner pages. We're putting the current commissioners as priority and we will also try and get to the other commissioner pages too if we have time.

**Page Assignments:**

@johnnyporkchops 
Priority pages to finish first:
Caroline C. Hunter
Matthew S. Petersen
Ellen L. Weintraub 
_**Finish if you have time:**_
Thomas J. Josefiak
Trevor Potter
Darryl R. Wold
Cynthia L. Bauerly
Donald F. McGahn
Hans A. von Spakovsky
Robert D. Lenhard


**Pat**
Ann M. Ravel
Lee E. Goodman
Steven T. Walther
**Finish if you have time:**
John Warren McGarry
Lee Ann Elliott
Danny L. McDonald
Scott E. Thomas 
David M. Mason
Bradley A. Smith
Michael E. Toner

**Comment by noahmanger** [comment]
The remaining piece on the Leadership and Structure page is this piece:

![image](https://cloud.githubusercontent.com/assets/1696495/23490639/87a1e6f0-feae-11e6-86db-ce6ca9e413af.png)

I originally implemented this as the `DocumentList` block, which made use of Wagtail's native document assets:
![image](https://cloud.githubusercontent.com/assets/1696495/23490656/9bc83972-feae-11e6-9fdc-dbcf58e37001.png)

But if we want to use our own custom S3 bucket structure, this will need to be changed.

@patphongs what do you think?

**Comment by patphongs** [comment]
@noahmanger I think I would be fine with this if there was a better way to organize so that users are able to find the stuff they uploaded easily without having to search through a giant list of documents or images. Documents and images can be tagged in wagtail, however, if there is no way to sort or filter by tags in wagtail, we can't depend on this for organizing these assets. We'll have to do some investigation on how to organize assets better.

![screen shot 2017-03-01 at 9 55 52 pm](https://cloud.githubusercontent.com/assets/12799132/23491048/e1149a78-fec9-11e6-9513-5d59ead291b5.png)

**Comment by noahmanger** [comment]
Yep, I definitely hear that. Ok, so there's a new task here to make a component to handle documents. I'll make a new issue for that.

**Comment by patphongs** [comment]
@noahmanger Actually there is a concept of collections in wagtail. So we can create a bunch of collections and then train users to upload to specific collections for organizational purposes. For example, a "fec record" collection could be created and all of the images/documents associated with fec record could be uploaded to that collection.

![screen shot 2017-03-01 at 10 18 01 pm](https://cloud.githubusercontent.com/assets/12799132/23491555/f8b94554-fecc-11e6-8506-7767b78ea53a.png)

**Comment by noahmanger** [comment]
That looks promising! Should we give that a shot for this one, making a new collection for "Directives"?

**Comment by johnnyporkchops** [comment]
I don't know if this is relevant but there is a filepath field in Django:
"A CharField whose choices are limited to the filenames in a certain directory on the filesystem. Has three special arguments, of which the first is required: ..."
This might be useful for certain specific page types, but likely too complex for this issue. A CharField https://docs.djangoproject.com/en/1.10/ref/models/fields/#filepathfield

**Comment by patphongs** [comment]
@noahmanger Yes I think that's a good idea. We'll have to work on the taxonomy with @emileighoutlaw for other collections that should be created too. 

@johnnyporkchops Thanks for the suggestion. I think we might just go with the wagtail collections implementation, just because that's already baked into it.

**Comment by emileighoutlaw** [comment]
After chatting with Pat, Amy K., and John this morning, we decided that @amypike and I are ready to do a fine-tooth-comb review all the current Commissioner pages. (We can closely review historical pages later.) We're going to look for any typos, stray formatting, and make sure the pages follow [this outline](https://docs.google.com/document/d/15wQlTtuf8J2BxfAr5_N-w1jzrNHtQF4iFxSCjcpdAEY/edit) :lock:  

@patphongs and @johnnyporkchops are going to keep jamming on building out the historical Commissioner pages while Amy and I review the current ones. Thanks for all the hard work so far, Pat and John!

**Comment by patphongs** [comment]
@noahmanger @emileighoutlaw I created a separate issue concerning the collections solution. #851 Ideally it would be nice to get this done pre-flip so that the organization of assets does not get out of control.

**Comment by noahmanger** [comment]
These have all been published.
