### ISSUE TITLE
Config error when cloning fec-cms from github repository

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/fec-cms#76]
I get this error when doing:
pip install -U -r requirements.txt

I got this error when installing requirements.txt:

Error: pg_config executable not found.
Please add the directory containing pg_config to the PATH
   or specify the full executable path with the option:
python setup.py build_ext --pg-config /path/to/pg_config build ...
    or with the pg_config option in 'setup.cfg'.

**Comment by johnnyporkchops** [comment]
installing postgres seemed to got me past that point and the CMS is loading on port 8000
(thanks to Lindsay!)

**Comment by noahmanger** [comment]
@jmcarp can we update the docs with the appropriate instructions? I would, not sure what exactly needs to be said.
