### ISSUE TITLE
Simplify workflow / process for press office using CMS

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#762]
This issue a mix of training/transition/content.

Improve process for press office folks entering content into Wagtail. Things that are taking valuable time away from their team include:

1. Adding H2 headings by hand
1. Changing to sentence case 
1. Tables on statistical releases

**Comment by jenniferthibault** [comment]
We have an existing issue for point `3) Tables on statistical press releases` filed, and I've labeled it for Sprint 6. https://github.com/18F/fec-cms/issues/550

That seems to be an action we can take separate from the other two process points, so I think good to separate it out for work.

**Comment by AmyKort** [comment]
Let's focus on #550 . I think we will be able to address concerns 1 and 2 through workflow changes.
