### ISSUE TITLE
News Feed Integration

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#764]
Currently the Press Office and the Information Division have XML newsfeeds that they generate in order to update their subscribers of current events going on at the FEC. The tool they are currently using is GovDelivery, which has an API: http://developer.govdelivery.com/api/comm_cloud_v1/Default.htm

It would be good to contact those offices to see how they interface with GovDelivery and set up triggers to facilitate sending out emails to subscribers.

**Comment by johnnyporkchops** [comment]
A solution may be to replace the use of GovDelivery by using the Django The syndication feed framework
Here's a post on doing it specifically in Wagtail, it looks fairly basic:
https://chrxr.com/adding-rss-feed-wagtail-site/

**Comment by johnnyporkchops** [comment]
On second thought, this may not replace GovDelivery at first, but could remove the manual process of editing and publishing  the XML files, GovDelivery's 'page-watch' feature would trigger alerts to subscribers, whenever a feed has been updated

**Comment by johnnyporkchops** [comment]
Gov Delivery RSS Feed Options:
https://insights.govdelivery.com/Communications/CommunicationsCloud/Topics/Page_Watch%3A_Monitoring_Content_to_Automate_Messages/Automating_RSS_Feed_Updates_by_Email

**Comment by noahmanger** [comment]
Is this something we need to figure out pre- or post-flip?

**Comment by AmyKort** [comment]
I feel like this is a pre-flip issue because it generally applies to our snapshot content, which we're looking to consolidate on the new site post flip. 

(Or, is it enough to have a plan to address this now, and we can implement it later? @patphongs -- make me smart!)

**Comment by patphongs** [comment]
@noahmanger @AmyKort I'm going to ask the information department and press office to see how they are using the feeds. I believe the information department said it's fairly simple where they can change the URL they are watching for GovDelivery from our legacy site to the new site. If that's true for Press also, then this might be simple we don't have to do anything. Will get back to you. cc @johnnyporkchops

**Comment by johnnyporkchops** [comment]
I agree, this is definitely something we can consider addressing  post-flip

**Comment by patphongs** [comment]
Thanks @dorothyyeager. Yes, we will still be deploying that XML file to whatever our legacy site URL will be. For example, www.oldsite.fec.gov/info/tipsfortreasurers.xml would be the location once the domains are switched between the new and old site. We'll have to work out those logistics in greater detail in the coming weeks. It's good we have this documented in this ticket so we don't lose track of this. We'll be in touch.

**Comment by johnnyporkchops** [comment]
Dorothy, Can you include /pages/jobs.shtml to be changed to http://www.fec.gov/about/careers.

I have gotten an account on govdelivery, but have yet to go in and manage this page.


Thanks,


John

________________________________

**Comment by dorothyyeager** [comment]
Hi @johnnyporkchops am happy to include it on our list so it won't get lost - but just to be clear, I'm not a topic administrator for that topic - so our list will mainly be the Information division feeds (in other words, the ones that I can see and know about). Other divisions such as Press may have their own feeds and subscriber lists.

**Comment by johnnyporkchops** [comment]
Thanks Dorothy, I thought that you were talking about GovDelivery as a whole, not just your Dept. That makes sense, I am working to make sure myself or another admin for this topic keeps this from falling through the cracks.
