### ISSUE TITLE
Add glossary terms to Wagtail pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#767]
There's currently not a way to add glossary terms to Wagtail pages from the WYSIWYG view. This is going to be important functionality as we start to build out the new candidate and committee services sections. 

I'm not sure how hard adding this to the CMS will be, though.

**Comment by jenniferthibault** [comment]
Bumping this, we're now smack in the middle of rapidly building out new _Help for candidates and committees_ sections, and this would be really useful.

Currently it's possible by editing the html of a paragraph block in wagtail and inserting `<span class="term" data-term="candidate id">candidate ID</span>`, but it's not easy for folks who aren't comfortable with HTML, and could be easily bungled.

**Comment by dorothyyeager** [comment]
Just looking through old issues and found this. I've been doing it :) Will update here when done but we're getting there!
