### ISSUE TITLE
So that users can build and run our CMS, we will fix this Bug: Error when trying to create new page in Wagtail admin dashboard

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/fec-cms#77]
I get this error when trying to add child page:
UncompressableFileError at /admin/pages/new/home/checklistpage/1/
'ace-builds/src-noconflict/ace.js' could not be found in the COMPRESS_ROOT '/Users/jcarroll1-pr/fec_beta1/fec-cms/fec/static' or with staticfiles.

![django_error_when_create_child_page](https://cloud.githubusercontent.com/assets/5572856/10123429/45e770be-6507-11e5-8762-1336272457b6.jpg)

**Comment by johnnyporkchops** [comment]
I dowloaded ace-builds-master from github and put it as fec-cms/fec/static/ace-builds and now I am able to create a child page.
https://github.com/ajaxorg/ace-builds

**Comment by noahmanger** [comment]
To do from this issue: update documentation.
