### ISSUE TITLE
Implement new home panel for candidate and committee services

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#776]
So that users can get directly from the home page to information about running a committee, build out a new panel on the home page for the candidate and committee services section.

---

[Design issue](https://github.com/18F/fec-cms/issues/684) | [Content](https://docs.google.com/document/d/1Hz12HWNSxWGrA-5N0u2FVCZtaumLoXDysdGURQbdE-Q/edit#)

![image](https://cloud.githubusercontent.com/assets/11636908/22449795/4da530c8-e730-11e6-9353-e21ae1a1bb71.png)

This idea is that we will replace the existing "Registration and reporting" panel (because that section is being replaced by C&C Services). Not all pages will be active, so this should implement it with enabled links for anything that's active and disabled for all else. 

It also probably makes sense to do this on a feature flag, where if the flag is True, it replaces the current Reg & Reporting panel, and if False, it displays the current one (because it will depend on when the new content is approved and ready to launch).

**Completion criteria:**
- [x] Implement panel as designed
- [x] Add feature flag
- [x] If the feature flag is true, show the new panel
- [x] If the feature flag is false, show the old one
- [x] All links go to correct pages
- [x] Amy and Emileigh do a fresh content review
- [x] Update the deadlines to exclude monthlies for candidates
- [x] Re-style the cards

**Comment by xtine** [comment]
Looked at the content doc and copied over as much as I could, but is there a list of where the list of links should go to?

**Comment by xtine** [comment]
For Upcoming deadlines card for each tab, what category should I use for each one? I'm assuming `/calendar-dates/`: https://api.open.fec.gov/developers/#!/dates

**Comment by noahmanger** [comment]
I _think_ they montyly, quarterly and pre-/post-election dates apply to all types, so you want `category=report-M&category=report-Q&category=report-E`.

**Comment by emileighoutlaw** [comment]
Yep! I think we should include both for all types. There are some edge cases, but that makes the most sense to me.

**Comment by xtine** [comment]
I'm filtering for `report-M`, `report-Q`, and `report-E` and showing that latest upcoming deadline for all tab panels.

**Comment by noahmanger** [comment]
This has been approved so closing.
