### ISSUE TITLE
Build out additional CMS pages for legal resources

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#781]
This is a purposefully broad issue that we can break down later. As part of our [sitemap work](https://github.com/18F/fec-cms/issues/740), the FEC asked us to prioritize a set of pages for implementation. Those pages are:

- Dates and deadlines (compliance map stuff/reporting periods/etc)
- E&Js
- Court cases
- Audits
- Legislation landing

These are all pretty basic content pages that just need to link to the necessary old pages on the old site. I think it should be pretty trivial to make these as new instances of the ResourcePage template, repurposing content from their counterparts on fec.gov . My proposal is we take a first stab by just using pre-built templates in Wagtail and see what we can get and how well it works and if we need to put additional design or development work in later, we can.

**Comment by emileighoutlaw** [comment]
Hi @jenniferthibault ! For our new Audit page, we'll need an icon for the Audit brochure: http://www.fec.gov/pages/brochures/auditprocess.shtml 💟

**Comment by jenniferthibault** [comment]
If you 👍 / list edits on this preview, I can send it to you on Slack @emileighoutlaw 
![thumbnail--audit-process](https://cloud.githubusercontent.com/assets/11636908/22953278/7e727cba-f2de-11e6-8474-9c96f3a50c91.png)

**Comment by emileighoutlaw** [comment]
Looks perfect, Jen! Thanks.

**Comment by emileighoutlaw** [comment]
This is done, and we've moved to a new issue for design review, so I'm going to close.
