### ISSUE TITLE
Review/improve visual styling of "Candidate and committee services" section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#782]
Some of the default styles in the _Candidate and committee services_ section could use improving, now that we have real candidate content on these pages. 

These pages use Wagtail's `Custom` template, which was designed for the soon-to-be-deprecated _Registration and reporting_ section

In particular, very long pages and pages with lots of legal citations could use some of Jen's brilliant finesse. :woman_cartwheeling: 

1. It's hard to orient yourself to the content on **long pages** that have lots of sections (and subsections) (and sub-sub sections). We talked before about possibly adding a [table of contents](https://beta.fec.gov/legal-resources/advisory-opinions-process/) type thing. I think that's still worth thinking about. I also think the H3 to H4 switch is a little hard to process. 

_What it looks like now (screenshot from the [Who can and can't contribute](https://beta.fec.gov/candidate-and-committee-services/candidate-taking-receipts/who-can-and-cannot-contribute/) page):_

<img width="723" alt="screen shot 2017-01-31 at 9 34 54 am" src="https://cloud.githubusercontent.com/assets/10552702/22471666/a41c505e-e798-11e6-9943-535f4404263d.png">

2. Many pages have lots of **Legal citations.** I had the thought that the design we have for our [advisory opinion process page](https://beta.fec.gov/legal-resources/advisory-opinions-process/) might be more appropriate for this content.

_What it looks like now (screenshot from the [Handling a questionable contribution](https://beta.fec.gov/candidate-and-committee-services/candidate-taking-receipts/questionable-contributions/) page):_

![screen shot 2017-01-31 at 9 36 46 am](https://cloud.githubusercontent.com/assets/10552702/22471782/fc08234c-e798-11e6-8172-b6960c1f1f98.png)

3. **Nested bullets** in lists aren't an option right now. This may end up being more of a front-end task than visual design, but the WYSIWYG interface doesn't give us the option to nest bullets more than one layer (so I think(?) we'd want to design what it should look like before we ask our developers to add it).

_What it looks like now (screenshot from the [Coordinated communications](https://beta.fec.gov/candidate-and-committee-services/making-disbursements/coordinated-communications/) page):_

![screen shot 2017-01-31 at 9 43 10 am](https://cloud.githubusercontent.com/assets/10552702/22471964/c12241e4-e799-11e6-82e2-cfd7836d66ee.png)

**Comment by noahmanger** [comment]
Would it make sense for these to instead be instances of the Resource Page template, which includes the side nav and the citations at the bottom? I understand hierarchically it's a little asymetric, but maybe it's ok?

**Comment by jenniferthibault** [comment]
**Quick update:** 
We've made changes that make changes for the H3/H4 styling in @emileighoutlaw's point 1, and have moved Legal citations to the bottom of the page template in a horizontal format to improve point 2.
I'll start can working on sub-bullet styling for ~ 3 levels, but changing page templates feels like an extra large issue. What's your sense of that @emileighoutlaw ?

**Comment by jenniferthibault** [comment]
This issue has been broken into bullet styles: https://github.com/18F/fec-style/issues/693 and long page designs: https://github.com/18F/fec-cms/issues/1036#issuecomment-298973493

Closing in favor of specific work happening in those issues

**Comment by emileighoutlaw** [comment]
Apologies for missing being tagged in this, but I think breaking into long page designs and bullet styles feels like the right next move.
