### ISSUE TITLE
Create careers page content and implement USAJobs query

### ISSUE THREAD

**Issue by johnnyporkchops** [18F/fec-cms#785]
Create careers page based on designs here :
https://github.com/18F/fec-cms/issues/678

Open jobs are populated via a query to the USAJobs API, in this issue:
https://github.com/18F/fec-cms/issues/769

**Comment by emileighoutlaw** [comment]
Just so you have the right content easily at hand, here's the [Google Doc](https://docs.google.com/document/d/18ssePA2mtIjQwmATXJuPStz08CfzaMWcZ6aSywXiGVU/edit) 🔒 

Let me know if you have trouble accessing! :)

**Comment by johnnyporkchops** [comment]
A wagtail-produced mockup of the about/careers page can be seen as a screenshot at:
https://github.com/18F/fec-cms/pull/799

**Comment by noahmanger** [comment]
All done! Just waiting to be launched.
