### ISSUE TITLE
Advisory opinion process page not displaying document thumbnail images

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#786]
On https://beta.fec.gov/legal-resources/advisory-opinions-process

Document thumbnail images that should be above the PDF title in two places are missing:

<img width="1023" alt="screen shot 2017-01-31 at 6 22 36 pm" src="https://cloud.githubusercontent.com/assets/11636908/22488953/e789ea0a-e7e2-11e6-816b-9320a7c061e7.png">
<img width="1032" alt="screen shot 2017-01-31 at 6 22 52 pm" src="https://cloud.githubusercontent.com/assets/11636908/22488952/e78883ae-e7e2-11e6-96cc-c15a8f419cc7.png">

When I went to add them back in Wagtail, they displayed as broken image links:

<img width="981" alt="screen shot 2017-01-31 at 6 25 29 pm" src="https://cloud.githubusercontent.com/assets/11636908/22488983/0f023556-e7e3-11e6-8525-ee722b2ab968.png">

@noahmanger do you know what's up?

**Comment by noahmanger** [comment]
@jenniferthibault this all goes back to not being able to upload images to Wagtail yet. I'll keep it open as a reminder to add it, but we won't have it until the change to allow uploads to S3 is in production.

**Comment by jenniferthibault** [comment]
Thanks Noah—I know you told me about this before, but I hadn't yet figured out the pattern for where & how it caused problems. 

+1 to keeping this open so we remember where to go back and add the images in!

**Comment by noahmanger** [comment]
This was pushed to production and now works.
