### ISSUE TITLE
Remove "t--lead" class from latest update article page templates

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#788]
This styling works well on some articles that have many sections, but doesn't work well on short articles or press releases, where the entire text may be the first paragraph.

Example: https://beta.fec.gov/updates/district-court-issues-opinion-republican-party-louisiana-et-al-v-fec/

Addresses feedback from https://github.com/18F/fec-style/issues/614

**Completion criteria**
- [x] Remove from press release template
- [x] Remove from meeting agenda template (if present)
- [x] Remove from tips for treasurers template (if present)

**Comment by noahmanger** [comment]
This change is included here https://github.com/18F/fec-cms/pull/752

**Comment by jenniferthibault** [comment]
Even better! 🎉
