### ISSUE TITLE
To avoid confusing previews in the Latest Updates feed, cut off FEC Record text preview text after first sentence

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#789]
These scenarios show how when the preview text goes beyond the first sentence, the page structure and additional headline levels begin appearing fully-formatted in the document feed, which is disorienting. If possible, I think it's safer to cut off the preview text after the first sentence.

<img width="993" alt="screen shot 2017-02-01 at 10 20 18 am" src="https://cloud.githubusercontent.com/assets/11636908/22512820/3d8aa0ae-e868-11e6-84f2-d5c14b01fae2.png">
<img width="994" alt="screen shot 2017-02-01 at 10 20 31 am" src="https://cloud.githubusercontent.com/assets/11636908/22512821/3d8ab594-e868-11e6-8170-81ae23ad1bd5.png">

Is this possible?

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/628
