### ISSUE TITLE
Create more clarity in contact information for FEC Record articles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#791]
From feedback in https://github.com/18F/fec-style/issues/614

> 12. The email option next to the name of the author gives the appearance of suggesting readers contact that particular individual. Can we make it clear instead that there is a general email address for questions about campaign finance law and reporting requirements.

Current format for Record articles
<img width="375" alt="screen shot 2017-02-01 at 11 02 44 am" src="https://cloud.githubusercontent.com/assets/11636908/22514653/07cf3da2-e86e-11e6-9ef8-f7874f38a731.png">

Current format for weekly digests and press releases
<img width="761" alt="screen shot 2017-02-01 at 11 03 43 am" src="https://cloud.githubusercontent.com/assets/11636908/22514705/33020572-e86e-11e6-80c1-24b16c2707ce.png">

**Completion criteria:**

- [x] New format and logic designed 
- [ ] New format and logic implemented

**Comment by jenniferthibault** [comment]
We can create any combination of Label, position title, and email address, but we aren't sure what it should say. @AmyKort / @dorothyyeager would you prefer it to display "Information Division" with the email address for the Division? Or is it important to keep the individual authors name visible?

**Comment by dorothyyeager** [comment]
Have passed this on to Greg and George since it would be their call... If we do keep author names, might be best to use the email address for the division.

**Comment by FECHoosier** [comment]
I would prefer to keep the author's name and add his/her title, but remove the email option. We really don't want folks emailing questions to Record article authors.

**Comment by gsmaragdis** [comment]
Agree with Greg regarding emailing Record article authors.

**Comment by jenniferthibault** [comment]
We can do that! We'd need a list of all the possible authors and their titles.

On a quick scan, I'm seeing:
- Dorothy Yeager
- Jonella Culmer
- Myles Martin
- Isaac Baker
- Christopher Berg
- Katherine Carothers

Are there other folks who are publishing Record articles that aren't on the list? 

And lastly, could I ask for some help with titles for each person?

Thanks!

**Comment by gsmaragdis** [comment]
Zainab Smith

**Comment by FECHoosier** [comment]
Thanks, Jen.  Here's the complete list.

Dorothy Yeager, Sr. Communications Specialist
Katherine Carothers, Sr. Communications Specialist
Jonella Culmer, Communications Specialist
Myles Martin, Communications Specialist
Isaac Baker, Communications Specialist
Christopher Berg, Communications Specialist
Zainab Smith, Communications Specialist

**Comment by noahmanger** [comment]
Just an FYI @jenniferthibault / @emileighoutlaw / @dorothyyeager : these titles can all be added inside Wagtail on the "Authors" tab, so no need to wait for a coder.

**Comment by jenniferthibault** [comment]
I got _real_ excited to knock this out, but it turns out that once you edit information in any field, the email field requires a valid email address, otherwise it won't let you save your changes. This was avoided before by setting the "N/A" field when importing the info programmatically. 

We can remove the validation on the email field, but that required some code changes. @noahmanger kindly made the fix in https://github.com/18F/fec-cms/pull/793 but it may be too close to this week's release (scheduled for tomorrow) to get it in beforehand. If that change makes it in, I can update these fields ASAP. If not, they'll be updated in two weeks in our next release.

**Comment by jenniferthibault** [comment]
The validation patch made it into the release, and I updated everyone's info.

Authors are now displaying like this for record articles:
![screen shot 2017-02-02 at 3 22 42 pm](https://cloud.githubusercontent.com/assets/11636908/22566853/979556a4-e95b-11e6-811a-46a39baadc66.png)


Thanks for your help everyone, closing this issue.
