### ISSUE TITLE
Python version mismatch

### ISSUE THREAD

**Issue by dogweather** [18F/fec-cms#794]
`README.md` says **Python 3.5**. `runtime.txt` contains the text, **python-3.4.5**, `travis.yml` says **3.5**.

We should,

1. Remove `runtime.txt` if it's purely for documentation purposes.
2. Commit `.python-version` containing "3.5.2", which is created and used by `pyenv`
3. Update `README.md` and `travis.yml` to specify 3.5.2.

**Comment by ccostino** [comment]
We should definitely get these things on the same page.  A few things come to mind about this, though:

* `runtime.txt` [is used by CloudFoundry](http://docs.cloudfoundry.org/buildpacks/python/index.html#runtime) and we ought to keep that to ensure stability
* The latest 3.5 release of Python is now `3.5.3`, and [is supported by the Python buildpack](https://github.com/cloudfoundry/python-buildpack/releases)
* There was recently a security notice sent out regarding cloud.gov updates, which is encourage folks to use the latest versions of the languages they're using (which would actually be `3.6` for Python)

This needs to be done for more than just the CMS, as well.  I think @anthonygarvan and I can probably roll this into the migration efforts we work on this sprint as a part of getting the apps running in the new environments, but probably after we have things migrated over first to ensure everything is still working.

**Comment by dogweather** [comment]
Great - I'd like to use to Python 3.6 if possible.

**Comment by dogweather** [comment]
Completed for fec-cms.
