### ISSUE TITLE
Make data table block in Wagtail

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#813]
So that the content managers can present stats in posts cleanly, implement a new data table component.

---
Carrying over from https://github.com/18F/fec-cms/issues/550, the task here is to implement a custom table component that can be used to show tables of data like:

![image](https://cloud.githubusercontent.com/assets/1696495/22849046/3924d992-efae-11e6-8d6c-7cbc751bab64.png)

**Completion criteria:**
- [x] New custom table block in `blocks.py`. This should be an instance of the Wagtail `StructBlock` that supports two sub-blocks: a title and a table. 
- [x] Table block can be added to the `stream_factory` in `models.py` so it can be available to all page types that use that
- [x] The block should render with a custom template that contains special classes so it can be styled uniquely
- [x] The header row and header column should be bold
- [x] Every non-header cell should be right-aligned for easy comparison of numbers

**Comment by jenniferthibault** [comment]
Pulling from https://github.com/18F/fec-cms/issues/550#issuecomment-277839357 , the image below shows how the current alternating `paragraph block` + `table block` + `paragraph block` + `table block` (left) compares to the changes we're proposing on the right, which would be a `table block` with some built in surrounding text fields (right)

![screen shot 2017-02-06 at 5 39 02 pm](https://cloud.githubusercontent.com/assets/11636908/22669601/6148369e-ec93-11e6-9614-83656c2b5351.png)

Here's a few things that I'd add to @noahmanger's criteria above  (pulled from the pink in-line notes). 

- [ ] Need ability to have complex Paragraph style headers close to table—optional ability to give the table a title within that block

- [ ] Set minimum top/bottom margin between text and row edge

- [ ] A field in the table block for footnotes about the table (using the `t-note` class)

**Comment by AmyKort** [comment]
Just checking in on this. Because this allows us to have the complete set of our press releases up, it's a pre-flip task.

**Comment by noahmanger** [comment]
@AmyKort in progress and due to be released next week. We're just sussing out some details.

**Comment by AmyKort** [comment]
thank you!!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/issues/901
