### ISSUE TITLE
Unaccounted for Administrative Function Docs

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#815]
Below are administrative function documents that we are still waiting for documents for. But they will be added to this list of administrative functions on the website: http://www.fec.gov/open/index.shtml

- [ ] Memoranda from OGC related to debt settlement plans and proposed adminstrative terminations [PDF]
- [ ] Certifications of Commission votes in which the Commission approves a debt settlement plan or adminstrative termination [PDF]
- [ ] Reports of official travel paid for by the non-government sources made to the U.S. Office of Government Ethics pursuant to 31 U.S.C. 1353 [PDF]
- [ ] Annual reports made by the Commission pursuant to Equal Employment Opportunity Commission Management Directive 715
- [ ] Annual reports on the agency's privacy management program submitted by the Commission o the Office of Management and Budget [PDF]

**Comment by noahmanger** [comment]
@patphongs do these go under the "Agency operations" page or somewhere else?

**Comment by noahmanger** [comment]
@patphongs is this still relevant or have we captured these already?

**Comment by patphongs** [comment]
@noahmanger sorry, I don't know the answer to the status of these documents. @AmyKort do you happen to know? I know we've discussed the open government page before, I just don't remember where we landed on it. I could make it a transition page also if you like.

**Comment by AmyKort** [comment]
I can shorten the list: This one is on the current website and will be moved to the EEO page--the hybrid page. http://www.fec.gov/open/documents/2016-MD-715%20-OGOV.pdf

I've found locations for all of the Administrative Functions documents on the site currently.

**Comment by AmyKort** [comment]
The new website covers the reports included on classic. Closing this.
