### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#817]
We will need to update the fec.gov [privacy policy](http://www.fec.gov/privacy.shtml) to reflect the new apps. 

@patphongs is running point and I'll help, but might need others to weigh in.

**Comment by jenniferthibault** [comment]
I see this is already flagged for sprint 2.4, but want to reiterate that we need the site to have a policy page before it becomes the primary agency site during the flip. 

The link should be available where it's placed in https://github.com/18F/fec-cms/pull/910 and https://github.com/18F/openFEC-web-app/pull/1897

**Comment by emileighoutlaw** [comment]
@patphongs — if you'd like to pair on this, I can help with the content!

**Comment by patphongs** [comment]
@emileighoutlaw Privacy policy is currently here in our fecgov github:  https://github.com/fecgov/policy/blob/master/privacy_policy_README.md

**Comment by noahmanger** [comment]
I copied this over to a [Google Doc](https://docs.google.com/document/d/1O24hzMxSMEViA2OWReCxTS_iVKGmheziJ0jse5odUVs/edit) 🔒 for ease of editing and commenting. I just thought of a few random things and had some questions I wanted to capture. 

@LindsayYoung if you have time, I think it'd be helpful to have your eyes as well, given your background with the ATO.

**Comment by jenniferthibault** [comment]
Sorry I'm out of the loop, but is the idea that the privacy policy linked from the site will live on GitHub, instead of a Wagtail page? 

If so, we could add the GH link into the footer with this release since the URL won't change even if the content does.

**Comment by jenniferthibault** [comment]
Bump on the question above, is the intended format GitHub or Wagtail?

**Comment by noahmanger** [comment]
Ok, just took another pass and added lines referencing DigitalGov Search, ServiceNow and the feedback tool. @patphongs / @PaulClark2 / @LindsayYoung can you take another look and then send to The Lawyers. 

And sorry I missed your question, @jenniferthibault . My vote is for it to just be a regular Wagtail page.

**Comment by noahmanger** [comment]
Update: we have approved language. I'll make a Wagtail page for this and then we can add the link in the next release.

**Comment by noahmanger** [comment]
Resolved https://github.com/18F/openFEC-web-app/pull/2059#event-1092537832
