### ISSUE TITLE
Visual design review of new Wagtail pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#819]
This is a continuation of: https://github.com/18F/fec-cms/issues/781, creating Wagtail pages for higher-level content pages that we don't have time to rewrite before the site flip but that we need created. Basically, intermediary pages that will connect the new site to unmigrated content on the legacy site.

These pages use the "resource" template and are ready for Jen's visual design review.

@jenniferthibault, I haven't published these pages yet; if you're willing to look at them in preview mode from Wagtail, that's most convenient for me. If you'd rather have a password-protected, live version of each page, let me know, and I can set that up for you, too!

**Pages for review:**

*Candidates and committee services*
- [Dates and deadlines](https://beta.fec.gov/admin/pages/6668/edit/)

*Legal resources*
- [Legislation](https://beta.fec.gov/admin/pages/6673/edit/)
- [Regulations](https://beta.fec.gov/admin/pages/6682/edit/)
- [Explanations and Justifications](https://beta.fec.gov/admin/pages/6658/edit/)
- [Court cases](https://beta.fec.gov/admin/pages/6667/edit/)
- [Administrative fines](https://beta.fec.gov/admin/pages/6678/edit/)
- [Calculating administrative fines](https://beta.fec.gov/admin/pages/6680/edit/)
- [Alternative Dispute Resolution](https://beta.fec.gov/admin/pages/6681/edit/)
- [Audit reports](https://beta.fec.gov/admin/pages/6660/edit/)

*Footer*
- [Plain language](https://beta.fec.gov/admin/pages/6685/edit/)

**Comment by jenniferthibault** [comment]
*Candidates and committee services*
- ✅ [Dates and deadlines](https://beta.fec.gov/admin/pages/6668/edit/)

*Legal resources*
- ❓ [Legislation](https://beta.fec.gov/admin/pages/6673/edit/)
  - I feel like elsewhere I've seen us link the Document Title or the PDF/size only, rarely the whole thing, but at this point I'm getting confused. Do you want to make changes here?
  - <img width="493" alt="screen shot 2017-02-15 at 12 10 13 pm" src="https://cloud.githubusercontent.com/assets/11636908/22988015/b91aac2a-f37e-11e6-9204-c775f4928816.png">
  - <img width="333" alt="screen shot 2017-02-15 at 12 10 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/22988024/c33dd902-f37e-11e6-8677-9a27d64f22f4.png">
- ✅ [Regulations](https://beta.fec.gov/admin/pages/6682/edit/)
  - 📐 Made a small change to space between paragraph link and button
- ⚠️ [Explanations and Justifications](https://beta.fec.gov/admin/pages/6658/edit/)
  - There's a typo here, but I'm not 100% certain which is correct, so I left it for your edit:
  - <img width="225" alt="screen shot 2017-02-15 at 12 16 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/22986166/ae8f809c-f378-11e6-9f76-081402a32661.png">

- ❓ [Court cases](https://beta.fec.gov/admin/pages/6667/edit/)
  - The index pages linked to for [Ongoing litigation](http://www.fec.gov/law/litigationrecent.shtml) and [Selected court cases](http://www.fec.gov/law/litigationmajor.shtml) contain short lists of links to cases. Do we want to just move those links to this page and eliminate an click? Could be a bulleted lists in each section. Glad to make the change if you agree with it.
- ✅ [Administrative fines](https://beta.fec.gov/admin/pages/6678/edit/)
  - 📐 Changed mailing options format to use labels & icons
- ✅ [Calculating administrative fines](https://beta.fec.gov/admin/pages/6680/edit/)
  - Creative use of tables here for the examples!
- ✅ [Alternative Dispute Resolution](https://beta.fec.gov/admin/pages/6681/edit/)
  - 📐 Made a small change to space between paragraph and documents; 
  - 📐 Made new thumbnail image for brochure and replaced brochure thumbnail image
- ✅ [Audit reports](https://beta.fec.gov/admin/pages/6660/edit/)
  - 📐 Replaced brochure thumbnail image

*Footer*
- ✅ [Plain language](https://beta.fec.gov/admin/pages/6685/edit/)
  - Made a small change to space between paragraph and table

**Comment by jenniferthibault** [comment]
One last thing I forgot, and it's a larger ask:

On the [Legislation](https://beta.fec.gov/admin/pages/6673/edit/) page, the number of 1st level sections makes the side nav unusable for items further down (which is its main purpose). This screenshot is cut off at the fold on my regular laptop monitor.

<img width="246" alt="screen shot 2017-02-15 at 1 02 39 pm" src="https://cloud.githubusercontent.com/assets/11636908/22988166/3ded2356-f37f-11e6-9a6c-742920e1f239.png">





Would you consider consolidating the HR sections into one with multiple subsections?

**Comment by emileighoutlaw** [comment]
Jen! Thank you for such thoughtful, fast feedback. This is awesome!

- ❓ Legislation
    - Funny you should mention it! I had this exact question, and the answer is we've been inconsistent. Now that I've spent some time today sussing out how screen readers read links, I think, for comprehension, it's more important to link the document title than the PDF/size. How do you feel about recommending that approach across the site, and I can do a consistency audit later? 

- ⚠️ Explanations and Justifications
    - Good catch. Thanks! Fixed!


- ❓  [Court cases](https://beta.fec.gov/admin/pages/6667/edit/)
    - Brilliant! Done! Do you want to take another peek and see how the long-ish bulleted lists look to you? 

- 😖  Legislation 
    - This is a tricky one, for reasons I don't need to bore you with right now in a comment. But your point is well taken. I'm going to ask Amy about what we can do with this and get back to it tomorr-y :)

**Comment by emileighoutlaw** [comment]
Actually, I had an idea on my own for the Legislation page. I think [this version](https://beta.fec.gov/admin/pages/6673/edit/) gets us closer. What do you think?

**Comment by jenniferthibault** [comment]
**Legislation:** Yes! Exactly what I was thinking. Still a long nav because of the long section titles, but collapsing the HRs into one works well for now!

**Court cases:** also YES! Nice elimination of a page.

**Links:** Doc titles sounds good! Can you add this to your content guidance for future remembering?

Ok to close this issue in favor of you publishing the pages on whatever schedule makes sense? I think the design issues are all resolved.

**Comment by emileighoutlaw** [comment]
Circling back around on this for @jenniferthibault and @noahmanger— think we're ready to pass this off to FEC for review?

**Comment by noahmanger** [comment]
This is awesome. Just talked to @AmyKort  and she's going to review.

**Comment by emileighoutlaw** [comment]
Fantastic!

**Comment by AmyKort** [comment]
Generally, these are looking great to us. I think we'll only have a few small wording changes. One issue that jumped out is calling the House of Representatives Bills House of Representatives Bills. The bills listed are HR _____. But we think it might be better to call them "Campaign finance legislation" or something more general. Ideas?

**Comment by AmyKort** [comment]
For court cases – The names of the cases should be italicized (GPO Style Manual). (I know they aren’t in italics on the current site but I think they should be there too.) 

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
Fixed the italics, @AmyKort .

And I hear you about the HR section name. I didn't feel great about House of Representatives Bills, and I'm glad to hear that reinforced by your comment. The thing that feels werid about "campaign finance legislation," to me is—  isn't everything on the page a kind of campaign finance legislation? Is there any defining feature about the HR _____s that we can use for their section name? 😖

**Comment by AmyKort** [comment]
Ack.

I hear you about the campaign finance legislation label, @emileighoutlaw 

They are all Acts of Congress. Could we do something with that?

@amypike  Help!

**Comment by emileighoutlaw** [comment]
Yes! Please help @amypike !

**Comment by amypike** [comment]
Hmmm.  The links are to public laws that amend FECA in some way but some were done through appropriations bills so it is tricky to categorize.  The header above is " FECA and Amendment Legislative Histories"   "Recent FECA Amendments" is about the best I can come up with.  Can we try that, as a placeholder?

**Comment by amypike** [comment]
@emileighoutlaw @AmyKort  My nice husband suggested  "Recent Statutory Updates" or "Developments" or "Changes," if you like those better.  They seem more plain language.

**Comment by emileighoutlaw** [comment]
Nice husbands are the absolute best 💟 ! I'm going to mull these ideas for a bit, if y'all don't mind!

**Comment by jenniferthibault** [comment]
@emileighoutlaw since it's feeding into the sitemap issues, wondering what the status of this is? Are they ready to publish?

**Comment by emileighoutlaw** [comment]
Ah yes— I believe we can close this issue as review and publication are being tracked here: https://github.com/18F/fec-cms/issues/845
