### ISSUE TITLE
Design contact page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#82]
As a viewer, I want to be able to quickly understand what the best way for me to get in touch with the FEC is.

The recently implemented contact page would be  aided by better designing how the information is presented, and adding visual aids where possible.

**Comment by emileighoutlaw** [comment]
Ah! I see what you were asking. I'd love to be involved in this. :)

**Comment by jenniferthibault** [comment]
@emileighoutlaw based on our chat & your doc, here's what one option, which is built to a mental model of "I want to call" vs "I want to email" and has clear phone/email tracks:

![contact copy 2](https://cloud.githubusercontent.com/assets/11636908/10293634/9fd6a0c2-6b83-11e5-8a99-b27acaac87b9.png)


Here's another, that's guided more by a mental model of inquiries by department and general vs specific inquiries. The extra room in the right-hand column could be used if there are additional FEC offices/departments that are public-facing. I think this fits more with both users who do know what they're looking for, and users who don't.

![contact copy 3](https://cloud.githubusercontent.com/assets/11636908/10293649/b77044ea-6b83-11e5-9619-12a792f376a6.png)

cc @noahmanger @onezerojeremy

**Comment by noahmanger** [comment]
Oooh! I think I like the second one more. I like the division between general and specific, and feels less redundant by not listing offices with email addresses and then offices with phone numbers.

It would be helpful to make the office phone numbers more prominent. Even just bolding, or perhaps moving above the descriptive text. My eye had a tough time finding them in the paragraph.

Can you also give some thought to how the photo and map work on smaller screens?

And are both of those meant to be full-bleed?

**Comment by emileighoutlaw** [comment]
I also definitely like the second one more. Love the look and feel!

I'll add "fleshing out a comprehensive contact list" to the agenda when I meet with Amys about OGC review tomorrow.

@noahmanger @onezerojeremy How are you feeling about the copy that appears below each office, the `Including x, y, z` part? I want to make sure it's helpful and doesn't look like an FAQ page.

**Comment by noahmanger** [comment]
I love the concept. "Including" feels like kind of a weird word here, but I find it really helpful to give context around what I might want to call each office for.

**Comment by emileighoutlaw** [comment]
Yeah, the reason for the word "including" is that I fear if I suggest in
any way that it's comprehensive, the blurbs will become 1,000 words each.
Totally open to other ideas as I keep thinking about this.

**Comment by noahmanger** [comment]
What about "such as"?

**Comment by jenniferthibault** [comment]
@emileighoutlaw I'm 99% sure we're on the same page, but sure to be positive, I'd go easy on the "comprehensive" contat details. I think we want to make sure that we keep this page for offices that users and members of the public might need contact info for, and not have it be a rolodex for every FEC office.

@noahmanger thanks for the feedback on visuals! I was feeling much of the same. On finding the #'s, I'm thinking a little more space, and some clear lines. On mobile, thinking we drop the hero image and possibly make the map an image (more for aesthetics and quick cross-street viewing than interaction) with option to open in Google maps. No sense in tiny tiny maplings, unless you think that build in functionality would be helpful here?

Desktop 
![contact copy 3](https://cloud.githubusercontent.com/assets/11636908/10294468/83ff8fd0-6b88-11e5-9d58-aed554dd455a.png)


Mobile/tablet
![contact_mobile copy 2](https://cloud.githubusercontent.com/assets/11636908/10294469/840040f6-6b88-11e5-828f-41577338b5fb.png)

**Comment by noahmanger** [comment]
Great. Yeah that should work well. Not sure the exact best way to do the mapping, but I'll look into it once it's time to implement.

**Comment by emileighoutlaw** [comment]
Oh yes, completely agreed @jenniferthibault! I'll be careful how I phrase it in our meeting.

**Comment by jenniferthibault** [comment]
Minor adjustments to styling the text and icons based on feedback: the text now relies on spacing for separation, instead of cluttering the design with lines, and the icons are smaller and more simplified:

#### Desktop
![contact copy 5](https://cloud.githubusercontent.com/assets/11636908/10369826/47ed0666-6daa-11e5-84c4-964189d44ea7.png)

#### Mobile
![contact_mobile copy 3](https://cloud.githubusercontent.com/assets/11636908/10369835/52bcc568-6daa-11e5-9f44-057fba3ed841.png)

Since most of the changes are styling and content at this point, I think we can move it to implementation. Starting a new thread in #88 for building it out

**Comment by emileighoutlaw** [comment]
:+1: We may have a few departments to add, once Amys have time to finish their list, but that shouldn't be an issue to implement later.

**Comment by noahmanger** [comment]
This is moved to implementation on  #88
