### ISSUE TITLE
Place links to Court cases, Legislation and Policy on the Legal resources landing

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#824]
In moving from the updates to the IA, we need to find a home for some of the new links, including -court cases, legislation, and policy on the Legal resources landing page. Here's are two looks at a crack at that. As will be immediately evident, this does not include content. 

Rather than giving each their own section, given the relative infrequency of access (based on analytics, see below), it seemed the balance to strike was to include them in a way that kept the focus on the AOs/Regs/Statutes and Enforcement as the main use cases.  pull attention away from where we might want to focus it (each added option introduces user confusion)

![legal resources home card version](https://cloud.githubusercontent.com/assets/474916/23086390/aa53bfd4-f53a-11e6-81de-73d1c58f2f8b.png)

![legal resources home card version](https://cloud.githubusercontent.com/assets/474916/23086393/aee2fa92-f53a-11e6-9ebe-702ca76fb45a.png)

One final note: on the card version, I'm playing with a card style (i think this probably should be replicated as a link style as well) for linking to content that will exist on fec's legacy site after the switchover. It's very much a work in progress. 

Rationale from Analytics:
Analytics indicated that from the [law landing page](http://www.fec.gov/law/law.shtml), policy receives about 1% of the traffic, policy gets around 3%, and litigation (court cases) get about 0.3%.

**Comment by onezerojeremy** [comment]
Update: here's a version where the links to a number of areas are included in one section:
![legal resources home section version](https://cloud.githubusercontent.com/assets/474916/23409717/8aefe920-fd9a-11e6-9bad-183a47d17737.png)

**Comment by onezerojeremy** [comment]
After this morning's design pairing, we came to consensus that the option where the links to more material are in their own section most fits with our current pattern. 
(as seen in the last comment)

**Comment by noahmanger** [comment]
One possible tweek, because those three things feel a little weird to group together: what if we combined "Statutes" and "Legislation", as they're actually related?

**Comment by jenniferthibault** [comment]
That makes sense on the page (assuming I'm interpreting correctly) but in the nav they feel like separate items. Does it make sense this way to you as well?

![mega-menu_live legal](https://cloud.githubusercontent.com/assets/11636908/23510546/0e008e62-ff28-11e6-9a60-2a7b2e75544d.png)

![legal resources home copy](https://cloud.githubusercontent.com/assets/11636908/23510559/15f8e89e-ff28-11e6-9f6d-99faf39a7340.png)

**Comment by jenniferthibault** [comment]
@emileighoutlaw this is ready for content 👀 . Visual and info architecture design is complete ☑️ ☑️

**Comment by emileighoutlaw** [comment]
How about something along the lines of: 


**Legislation**
> Browse selected amendments to the _Federal Election Campaign Act_ and Commission recommendations to Congress.

**Court cases**
> Learn more about active and past cases involving the FEC.

**Policy statements**
> Access statements, interpretive rules and other guidance issued by the FEC.

**Comment by AmyKort** [comment]
@amypike?

**Comment by noahmanger** [comment]
I've got this all coded up in https://github.com/18F/fec-cms/pull/866 whenever language is finished.

**Comment by emileighoutlaw** [comment]
Pinging our friend @amypike! If the above^^ content's okay, we're good to launch these :)

**Comment by amypike** [comment]
@emileighoutlaw Love it, looks great!  Thanks, everybody!
