### ISSUE TITLE
include information about the data, links to additional data sets and API within the campaign finance data section

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#833]
The [sitemap/IA](https://github.com/18F/fec-cms/issues/740) has us adding a few new data sources and information about them to the campaign finance data section. 
![screen shot 2017-02-24 at 5 06 49 pm](https://cloud.githubusercontent.com/assets/474916/23322797/a77b12b6-fab3-11e6-99cd-78d7bc00923f.png)

We also are looking for a way to [re-incorporate the API](https://github.com/18F/fec-cms/issues/729) back into the site architecture. 

Here's a first take at those. 
1. About the data and API links. 
So the about the data page has good explanatory content about where to find certain aspects of the data, and importantly, the terms-of-use-esque language forbidding the use of this data for commercial ends. I think both of these bits of data feel like they belong as part of the data footer, as it provides a way to surface the warning anywhere someone might wonder about how it can be used, which is to say, while browsing the data sections in places where the underlying data is exposed (on the candidate and committee pages, on the data tables, on the advanced data landing page). Here are two looks at that:
1.1: data footer where about the data and api are added to footer menu, terms of use are directly exposed
![data footer](https://cloud.githubusercontent.com/assets/474916/23323490/d043f12e-fab6-11e6-86db-4aedeeedaf8e.png)

1.2: data footer where about the data and api are added to footer menu, terms of use  are included via a sentence which links directly to the sale and use section of the about the data page. 
![data footer less terms](https://cloud.githubusercontent.com/assets/474916/23323502/d8463152-fab6-11e6-8c66-a1e15a92f140.png)

2. Bulk data and other sources. (and also the API again)
To me, this feels like another section of Advanced data. Still not sure how we want to call out the difference in the links to the legacy content, but leaving that alone for now, each of the links to the data download and other sources are included as links in a new section _very_ tentatively titled "Bulk data downloads and other sources". This is also felt like another place to call out the API, which can be viewed as another data source. 
![advanced-data-v3 b](https://cloud.githubusercontent.com/assets/474916/23323563/1596c3be-fab7-11e6-8b66-bb5e7544bfef.png)

2.2 Here's basically the same layout, but instead of adding the API to the other sources, it shows up as a "more ways to explore the data" card. 
![advanced-data-v3 a-more api love](https://cloud.githubusercontent.com/assets/474916/23323507/e4be69c2-fab6-11e6-8f92-34a6db131953.png)

for more on the nav, see [827](https://github.com/18F/fec-cms/issues/827)

Obviously all this is very drafty, but should give us something to talk about on Monday! :)

**Comment by onezerojeremy** [comment]
actually i'm already seeing that i missed some of the data sets! I'll see if they break the pattern on Monday.

**Comment by onezerojeremy** [comment]
Updates on this, from this morning's pairing with @jenniferthibault, @emileighoutlaw and @nickykrause :
1. I was mistaken about the amount of room in the footer, and as such the "don't use this data for bad things" warning won't work there. (though the API link works fine there). @jenniferthibault pulled another 🐇 out of her 🎩 , with the data disclaimer used in other sections of the site, so that's what you're seeing here. 

2. added in the missing links, including: 

- PACronyms : included as an aside in the Committee section
- "candidates financial disclosure forms":  I'm interpreting this as "forms index", and also including it as an aside, this time within the candidate section. 
- First pass at the rest of the links to particular data sets, now re-organized to mimic the categorization in the sitemap. 
- of these, probably the one I'm least confident about is the "data catalog", which I've very tentatively named "legacy data catalog", which links to [a page](http://www.fec.gov/data/DataCatalog.do) with links to lots of different data sets. It might be fine as is, but it's a lot of different stuff that doesn't fit easily in any particular category that I can think of.


will upload an image when s3 comes back on line!

**Comment by jenniferthibault** [comment]
Had a really productive review session with @PaulClark2 on Friday that led to a few more changes to the Advanced Data section. The 🖌  [InVision prototype](https://gsa.invisionapp.com/share/HQAOQLDF9#/221534844_Advanced-Data_Raising) has been updated with those changes.

**Changes:**
- Re-ordered page sections to place raising and spending first to better reflect the interests of advanced data users
- Removed inactive “coming soon” data links: better to keep adding to the site than to create the perception that information is missing or unfinished.
- Moved candidate financial disclosure forms to External Sources, link to Office of Government Ethics
- Provided links to the legacy data maps from the "Other FEC data" category as a holdover to when the work to replace them happens in Sprint 8 & 9

**Remaining to-do's**
- @PaulClark2  is going to look into whether we can remove post-election summaries from the Bulk data page
- @AmyKort we'd like to make sure this feels good to you as well, so please help us know what the best way to do that is. Would you like to review the prototype on your own, have us give you a walkthrough, or??? Interpretive dance perhaps? Let us know 💃 

@nickykrause / @onezerojeremy this should be in good shape for testing this week!

**Comment by AmyKort** [comment]
@jenniferthibault I'm usually never one to say no to an interpretive dance, but I looked through the prototype on my own. Looks great! I really like what we've got going here. It's very easy to find what's there and understand what you're looking at. We have a lot of data and I think it's often very hard to get oriented, or even know what questions to ask about the information you want to search. This is a great solution for that. I am also a huge fan of the terms of use at the bottom of each page, given what comes above it.

It looks like there are going to be a lot of little language issues to iron out. Will you let me know when it's time to focus on that?

**Comment by jenniferthibault** [comment]
Oh that's great, @AmyKort! You are fast ⚡️ and I'll save the interpretive movement for our next  workshop. You're absolutely right there's a lot of small copy areas we're going to need your help + @emileighoutlaw 's for nailing down.

Emileigh, how would you like to break that work down?

**Comment by PaulClark2** [comment]
We do not need to find a home for http://www.fec.gov/finance/disclosure/PostCycleSummaryDataFiles.shtml on the new website.

**Comment by jenniferthibault** [comment]
Thanks! Mockups updated.

**Comment by PaulClark2** [comment]
@jenniferthibault we can also remove the links to House independent expenditure map and to Senate independent expenditure map

**Comment by jenniferthibault** [comment]
Great! That helps cut down on some clutter under that item too. Updated!

**Comment by noahmanger** [comment]
Tracking the implementation of this over in https://gsa.invisionapp.com/share/HQAOQLDF9#/221534844_Advanced-Data_Raising
