### ISSUE TITLE
Design compliance section disclaimer / link-back

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#836]
So that users from committees can find all compliance content, whether in the new or old experiences, provide a disclaimer and a link back to the content on the old site.

---

The "Candidate and committee services" section needs to provide a way for users to understand that the content is currently incomplete and provide routes to the old site for them to find further information.

**Completion criteria:**
- [x] Draft language and determine what to link to ( @emileighoutlaw / Cassiopeia team)
- [ ] Design component ( @jenniferthibault )

**Comment by emileighoutlaw** [comment]
This messaging is now a little in flux, depending on how we approach the site flip. But working through the content with @onezerojeremy and @nickykrause tonight, we came up with something along the lines of:

> We’re actively reorganizing our content about candidates and committees. If you can’t find what you’re looking for, we have also preserved this content [in its previous form](http://fec.gov/info/compliance.shtml).

And the link would go to the Help with reporting and compliance page.

**Comment by emileighoutlaw** [comment]
This one seems to be in a bit of a holding pattern, but I'm not sure why. 

Is it because we're waiting on our two-site work to take shape? Waiting for FEC or me to weigh in on the content? Waiting for me to pass this off to design?

**Comment by jenniferthibault** [comment]
Yes! I was waiting for the site flip work to settle out into its plan, and since that was in flux right up through Friday, here we are.

I'm working on a sketch that shows where we have these types of notifications, and if they need to say different things at different times of the flip (before/during/after type language), and what you jotted out in your previous comment is perfect for figuring out where we point folks & what we say at at least one of those points in time. Just need a little more working time & will update back!

**Comment by emileighoutlaw** [comment]
Thanks so much for catching me up, Jen! 💟

**Comment by jenniferthibault** [comment]
So as to be consistent with the system of messaging built for the legal tools in https://github.com/18F/fec-cms/issues/840 , the component I'd recommend is the message pattern with the info icon:

![screen shot 2017-03-16 at 10 21 50 am](https://cloud.githubusercontent.com/assets/11636908/24000772/973a1df0-0a32-11e7-99eb-c864e13aea1c.png)

**Comment by emileighoutlaw** [comment]
I love the look of this. The use of the `i` rather than the the `!`, and the use of the gray both feel like smart choices— clear and prominent without being too scary.

**Comment by noahmanger** [comment]
Implemented in #885 :

![image](https://cloud.githubusercontent.com/assets/1696495/24023314/b715c68e-0a68-11e7-972b-9a68f748b769.png)

Closing.
