### ISSUE TITLE
Add new outside spending features to candidate page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#839]
So that users can get a better understanding of the outside spending made for or against a candidate, add new visuals and totals to the candidate page.

---

![image](https://cloud.githubusercontent.com/assets/1696495/23386336/b18da03a-fd0a-11e6-9929-80e679d2a2ef.png)

**Completion criteria:**
- [ ] IEs, ECs, and CCs are broken out into different tabs and the user can toggle between them
- [ ] For IEs and CCs, show the total amount spent for and against
- [ ] The totals should link to itemized records on `/independent-expenditures/` and `/communication-costs/` filtered down
- [ ] For IEs and ECs, show a bar chart and caption 
- [ ] For ECs, just show the total amount and link to `/electioneering-communications/`

Update on this: for the first pass, let's do this with just the total numbers for and against, but not the chart.

**Comment by noahmanger** [comment]
It's been a while since we looked at these designs and the candidate pages have changed slightly with the menu re-org. I have a suggestion for a simpler way to do this:

![image](https://user-images.githubusercontent.com/1696495/26907184-7f7eebae-4ba6-11e7-8a32-bb0e9175ebcd.png)

Basically instead of doing the toggle, keep them each as separate items, with their own subnav item, and include the summary numbers above each table.

cc @jenniferthibault

**Comment by jenniferthibault** [comment]
Sorry for the delay—love this concept, and how it makes use of the new module.

I might want to do a small visual customization to the two side-by-side numbers though, at first I didn't notice that they were different (one was support and one was oppose). I'm wondering if we could use the class from the data [breakdown pages](https://www.fec.gov/data/raising/)?
<img width="818" alt="screen shot 2017-06-09 at 9 26 35 am" src="https://user-images.githubusercontent.com/11636908/26977454-f40c518c-4cf5-11e7-8305-74dae588e119.png">

**Comment by noahmanger** [comment]
Resolved by #2119
