### ISSUE TITLE
Audit "information for the public" content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#844]
So that members of the public can more easily learn more about the FEC and participate in the campaign finance process, we want to build a section of the website that collects all that content in one place. But first, we need to get a good understanding of what content exists, and what content we want to keep on the new site.

**Completion criteria**:
- [x] Audit existing resources and synthesize findings
- [x] Meet with Jason and @AmyKort to discuss findings

**Comment by AmyKort** [comment]
pinging @amypike and @rhoughfec ! They're going to take the lead on this.

**Comment by AmyKort** [comment]
Shifting things around, @gsmaragdis will take the lead on this.

**Comment by gsmaragdis** [comment]
Happy to work on this project!  I am reporting for duty.

**Comment by emileighoutlaw** [comment]
Had a fantastic meeting with @gsmaragdis, @jenniferthibault, and Jason today! We're all feeling aligned that there are three main sections of content for this section and on what all the sub-pieces of those sections should be:

![screen shot 2017-03-13 at 2 49 58 pm](https://cloud.githubusercontent.com/assets/10552702/23872584/d6967cc4-07fc-11e7-9e79-01cda343e59a.png)

So we're ready to move to design next sprint :)

**Comment by emileighoutlaw** [comment]
p.s. none of the words in that picture are intended to be the final words

**Comment by amypike** [comment]
FWIW, I love it!

**Comment by noahmanger** [comment]
What's the next step with this? Do we need to write new content? Or just jump straight to building out pages?

**Comment by emileighoutlaw** [comment]
I think we should start working on design and content together as a next step! There will be some content to write, but I'd love to at least start this work collaboratively with visual design.

**Comment by noahmanger** [comment]
Great. We have #880 for that work, so closing this.
