### ISSUE TITLE
Review new legal (and other) content pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#845]
Continuation of: https://github.com/18F/fec-cms/issues/819#issuecomment-280779198, reviewing Wagtail pages for higher-level content pages that we don't have time to rewrite before the site flip but that we need created. Basically, intermediary pages that will connect the new site to unmigrated content on the legacy site.

## Pages for review

*Candidate and committee services*
- [Dates and deadlines](https://beta.fec.gov/admin/pages/6668/edit/)

*Legal resources*
- [Legislation](https://beta.fec.gov/admin/pages/6673/edit/)
- [Regulations](https://beta.fec.gov/admin/pages/6682/edit/)
- [Explanations and Justifications](https://beta.fec.gov/admin/pages/6658/edit/)
- [Court cases](https://beta.fec.gov/admin/pages/6667/edit/)
- [Administrative fines](https://beta.fec.gov/admin/pages/6678/edit/)
- [Calculating administrative fines](https://beta.fec.gov/admin/pages/6680/edit/)
- [Alternative Dispute Resolution](https://beta.fec.gov/admin/pages/6681/edit/)
- [Audit reports](https://beta.fec.gov/admin/pages/6660/edit/)

*Footer*
- [Plain language](https://beta.fec.gov/admin/pages/6685/edit/)

## Outstanding work

We are still deciding how to handle the headers on the **legislation page**. @amypike kindly suggested:
- Recent FECA Amendments
- Recent Statutory Updates
- Something with "Developments"
- Something with "Changes"

We still need to make a decision and change about that header. What else do we need to do before these can get these pages launched, @AmyKort ?

**Comment by AmyKort** [comment]
I think that's it.

**Comment by emileighoutlaw** [comment]
Thanks, Amy!

I went in and moved a few things around— what do we think about the headers on [this Legislation page](https://beta.fec.gov/admin/pages/6673/edit/) 🔒 now? Closer to what we want? Farther away?

I think maybe the most important thing we could do here is add an intro that explains to readers what the heck all the stuff is. We don't have anything existing, but I pieced together some things from around the site. As a total shot in the dark: 

> This page provides access to campaign finance legislation. 

> _The Federal Election Campaign Act_ (FECA) instituted more strict disclosure requirements for federal candidates, political parties and political action committees (PACs). FECA was amended several times in the 1970s. 

> In addition to FECA, campaign finance legislation includes recent statutory updates and Acts of Congress. 

> Generally, the FEC offers recommendations for legislative changes every year to Congress.  

It doesn't even have to be this at all. I was just thinking _something_ is better than nothing.

**Comment by AmyKort** [comment]
The page looks good to me, but I'll leave it to @amypike to confirm the difference between recent legislative actions and acts of congress. Also, I am a fan of "This page provides access to campaign finance legislation." It is short, and I don't like to read.

**Comment by amypike** [comment]
This looks great, @emileighoutlaw !  My only suggestion is to use one heading, though.  "Recent Statutory Updates" covers all of the documents that are listed (each piece of legislation amends the FECA in some way).  Though maybe someone would argue that BCRA in 2002 isn't "recent?"  I came to the agency shortly after BCRA was enacted so personally, my old lady self likes to characterize 2002 as "recent." Makes me feel young! @AmyKort

**Comment by AmyKort** [comment]
We are actually young, @amypike  . . . by definition and despite our respective ages. We're going to put that in as a glossary definition and make it official.

Thank you for your good advice on this page. I totally agree. I think we can live with "recent," because it is simpler than any of the other options we seem to have.

**Comment by noahmanger** [comment]
Sounds like we've got some reviewed pages! Closing.

**Comment by emileighoutlaw** [comment]
Whoops! Reopening because I haven't actually implemented @amypike's change to make the "Recent" header include the Acts as well. Hang tight, and I'll update today!

**Comment by amypike** [comment]
@emileighoutlaw I just had a pow-wow with my boss and our suggestion is to make one heading for the whole page - "FECA and Selected Amendments" - and put everything under that heading (including the first four links, which are currently titled "Historical Versions of FECA.") This is the most inclusive, accurate way to describe all of these documents.  The "selected" gives us cover in case there's some small bill (piece of legislation that passed and amended FECA in some way) that we missed.  Let me know what you think.  Pinging @AmyKort so she sees all.

**Comment by emileighoutlaw** [comment]
I actually like that option the best because it makes clearer what the relationship is _between_ FECA and the amendments.  I'll get those edits in as soon as our admin side is back up again :)

**Comment by emileighoutlaw** [comment]
Okay — we've got everything under one umbrella [on the Wagtail page](https://beta.fec.gov/admin/pages/6673/edit/) 🔒, if @AmyKort and @amypike want to look at it in preview mode and see what you think.

**Comment by amypike** [comment]
@emileighoutlaw  It thrills me that you like that option best!  This page looks wonderful.  I have one last edit and then I will shut up, I swear:  Looking at the contents of the page, I think the heading should be "Selected amendments to FECA" (rather than my original suggestion,  which was "FECA and selected amendments," I'm sorry!). Technically, we don't post a copy of FECA anywhere on that page, just the amendments to the law.   The legislative histories don't contain the law, just the history of the amendments to the FECA (committee reports, floor speeches, etc.) so "Selected amendments to FECA" more accurately reflects what's on this new page.  On the legacy site, this page also includes a "Statutes" section, with the full statute (orange/grey book) and links to GPO and House Leg Counsel stuff, so the "FECA and amendments" heading would work there.  I'm pinging @AmyKort only so she can make fun of me for arguing with myself.

**Comment by emileighoutlaw** [comment]
I do think you're right that "Selected amendments to FECA" is more clear, as there aren't actually any links _to FECA_ on that page

**Comment by emileighoutlaw** [comment]
Are we ready to publish these pages, @AmyKort and @amypike? If so, I say let's go for it!

cc @noahmanger

**Comment by AmyKort** [comment]
Looks good to me if Amy gives it the thumbs up (which it looks like she already did?). @amypike ?

**Comment by amypike** [comment]
@emileighoutlaw @AmyKort  Looks great, let's do it!

**Comment by noahmanger** [comment]
Great! I'm going to go ahead and publish, though note that they won't actually be available to anyone until we've updated the legal landing page to add links to them, which will happen in an upcoming release.

**Comment by noahmanger** [comment]
Pages published. We also need to update the enforcement matters page, which I made an issue for here: https://github.com/18F/fec-cms/issues/860
