### ISSUE TITLE
Prettify Carey V. FEC release

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#846]
The [2011 Carey v. FEC ](https://beta.fec.gov/updates/fec-statement-on-carey-fec/  
)press release didn't make our chronological cut for visual cleanup, but it's going to be an important linked resource for our initial release of PAC content (toward the end of summer). This issue is to remind us to clean up the styles of this press release in the future.

**Comment by llienfec** [comment]
Carey v. FEC press release has been cleaned up as a part of the work of #1388.
