### ISSUE TITLE
Find home for eFiling report

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#847]
@AmyKort and Emileigh need to sit down this sprint and figure out where we want the eFiling report to live on the new site.

**Comment by emileighoutlaw** [comment]
Just a thought for @AmyKort — do you think this could live in our "Reports about the FEC" section? I could see a case for including it in  "Strategy and budget" or in "Agency operations" perhaps?

**Comment by AmyKort** [comment]
I could go either way. I was wondering though if there was any way to help folks get from here (https://beta.fec.gov/registration-and-reporting/get-filing-software/) to there? Would that make sense?

**Comment by emileighoutlaw** [comment]
Ooo, definitely. I can see this report being a great candidate for our "Continue learning about this topic" section on that page.

**Comment by AmyKort** [comment]
Sounds good. Let's look into putting the report into agency operations then. What do you think? 

If you'd prefer strategy and budget, let me know. Would we create a new report type?

**Comment by emileighoutlaw** [comment]
I was just going to say that I think "Agency operations" is a better fit :) 

@noahmanger — it's not too late/too hard to add another category to our "Agency operations" section of the "Reports about the FEC," right?

**Comment by noahmanger** [comment]
Nope not too late, though we'd need to push code to production for it to work.

**Comment by emileighoutlaw** [comment]
What do you think about "study" for the report type @AmyKort

**Comment by AmyKort** [comment]
Love it

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/888
