### ISSUE TITLE
Update "Enforcement matters" page to link to children pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#860]
Now that we've published pages for audits, admin fines and ADR program, we need to update the [Enforcement Matters page](https://beta.fec.gov/legal-resources/enforcement/) to link to those.

Do we already have content for this @emileighoutlaw or @jenniferthibault ?

**Completion criteria:**
- [x] Draft blurbs for these sections
- [x] Update markup on page to include all new links and content

**Comment by noahmanger** [comment]
I'd like to squeeze this into this upcoming mini release so we can basically release all these pages. I have two proposals for how we can do it with essentially no content editing: 

First, is to just use the existing page like we have it, but removing the coming soon status on the text, using the same copy and adding links. [View option 1](https://cloud.githubusercontent.com/assets/1696495/24224802/7bae5a6e-0f1a-11e7-82ba-b7d3712d157f.png)

Option 2 is to do all of the above, but to use the layout we use on other pages like this, which I think works better given how this page has evolved. 
[View option 2.](https://cloud.githubusercontent.com/assets/1696495/24224838/9aa256aa-0f1a-11e7-84ca-2419eecc9e0b.png)

**Comment by jenniferthibault** [comment]
I like 2 better, but we lost the structure, and the order got shuffled. Order seems important because it reflects the intro paragraph.

If we returned to the original structure and order but use this layout, only the h2s would be in the side nav. (That works for me.) @emileighoutlaw what's your take on the ideal structure?

(h1) Enforcement:
- (h2) Overview
  - (h3) Audit reports
  - (h3) Complaints
- (h2) Enforcement programs
  - (h3) Matters Under Review
  - (h3) Alternative Dispute Resolution
  - (h3) Administrative Fines
- (h2) Legal citations

**Comment by emileighoutlaw** [comment]
The hierarchy of this page is really tricky. I have some thoughts, but I'm going to take it to content workshop today to get some feedback. Will post an update this afternoon.

**Comment by emileighoutlaw** [comment]
Scratch waiting on critique group. I think Jen is 100% right about her outline, and so I've taken a stab at reworking the content to (hopefully) clarify this really tricky arm of FEC.

The only thing I added to Jen's outline is our enforcement statistics homeless content (which we can discuss). 


_A small note:_ None of this is a radical departure from the content FEC currently has scattered around its enforcement pages. But if we go with this direction, it will need eyes from Amy. (Probably it would be easier to review in a mock-up than in this GH drafty draft)


> # Enforcement  (h1)
> The FEC has exclusive jurisdiction over the civil enforcement of the federal campaign finance law. 

> By law, all enforcement cases must remain confidential until they’re closed. 

> ## Enforcement overview (h2)
> Enforcement cases come from audits, complaints, referrals or self-submissions.

> ### Audits (h3)
> Campaign finance law permits the Commission to conduct an audit of any political committee. Learn more about audits and search closed cases.

> ### Complaints (h3)
> Anyone can submit a complaint if they believe a violation of the law has occurred or is about to occur. Learn more about the complaint process.

> ## Enforcement programs (h2)
> Enforcement cases are primarily handled by the Office of General Counsel and are known as Matters Under Review (MURs).

> Other programs designed to augment the Office of General Counsel's enforcement role include the Alternative Dispute Resolution Program and the Administrative Fine Program.

> ### Matters Under Review (MURs) (h3)

> Because the public has the right to know the outcome of any enforcement proceeding, redacted files for closed enforcement matters are made available to the public within 30 days after the parties involved have been notified that the entire matter has been closed.

> **Search closed MURs**
> [__________________]
> ! Results don't include most of the cases closed between 1975 and 1998. Search those cases on the [MUR archive](http://www.fec.gov/MUR/).

 > ### Alternative Dispute Resolution Program (h3)
> Alternative Dispute Resolution is a series of procedures for resolving enforcement matters through mutual consent of the parties involved. Learn more about the program and search closed cases. 

> ### Administrative Fine Program (h3)
> The Administrative Fine Program, which assesses civil money penalties for late or non-filed reports. Learn more about the program, calculate a fine and search closed cases. 


> ## Enforcement statistics and process documents (h2)
> [Enforcement statistics](http://www.fec.gov/em/enfpro/EnforcementProfile.shtml) track the number of FEC enforcement matters resolved and associated penalties. 

> [Enforcement process documents](http://www.fec.gov/law/procedural_materials.shtml). The Commission  has released a number of documents relating to enforcement and compliance processes in an effort to increase transparency and make internal documents available to the public. 


> ## Legal citations
> _hurrah hurrah for the law the law_

**Comment by emileighoutlaw** [comment]
My previous post was too much content to look at in a GitHub issues— I got swept up in the site-flip frenzy and started writing microcopy before we were ready. So I'm pulling that out for later. 

Right now, I think the content structure is the important thing to get agreement on (and then the fine print will come next). 

Jen's structure outlines what I think we need to clarify for readers (and in the order we need to clarify it):

> _1. What is FEC enforcement?_
> _2. How do enforcement cases come about?_
> _3. After they come about, how are enforcement cases are handled?_

For newbies, that hierarchical and chronological clarity seems important, because this is a complicated, tricky thing. 

For experience users, easy access to enforcement research is important, and this content structure should help with that too. (Headers + content chunking = fast scanning)

So here's what I think the outline should look like:

> ## (h1) Enforcing federal campaign finance law

> - ### (h2) Uncovering possible election law violations
>    - #### (h3) Audits of political committees
>    - #### (h3) Complaints

> - ### (h2) Programs for handling enforcement cases
>    - #### (h3) Matters Under Review
>    - #### (h3) Alternative Dispute Resolution Program
>    - #### (h3) Administrative Fine Program

> - ### (h2) Enforcement statistics and internal process documents

> - ### (h2) Legal citations


 @jenniferthibault @noahmanger @AmyKort, what do y'all think?

**Comment by AmyKort** [comment]
@emileighoutlaw Generally, this looks great to me! 

Uncovering possible violations might be broader than a two step process (I'm the reason you feel like you always need the microcopy) depending on how that's worded. From the current site:

The FEC has exclusive jurisdiction over the civil enforcement of the federal campaign finance law. In exercising that authority, the Commission uses a variety of methods to uncover possible election law violations:

The agency’s monitoring process may detect potential violations through a review of a committee’s reports or through a Commission audit.  
Potential violations may be brought to the Commission’s attention through the complaint process. This process enables anyone to file a sworn complaint alleging violations and explaining the basis for the allegations.  
The referral process enables other government agencies to refer possible violations to the FEC. 
Any person or entity who believes it has committed a violation may bring the matter sua sponte to the Commission’s attention. 

cc @amypike

**Comment by jenniferthibault** [comment]
👍 to your outline @emileighoutlaw. The plain language changes in the section titles are really helpful too!

**Comment by emileighoutlaw** [comment]
Chatted with Amy, and we're both enthusiastic about making clear that possible violations come from referrals and sua sponte submissions _as well as_ audits and complaints. :)

So we're both feeling good about that outline.

**Comment by noahmanger** [comment]
Excellent. Is there fresh copy to come, or just re-arrange existing copy into this outline with these headings?

**Comment by emileighoutlaw** [comment]
I think we need some fresh copy.

@AmyKort, ready to start collaborating on this with me? Here's a [draft Google Doc](https://docs.google.com/a/gsa.gov/document/d/1Ek9kadjOKQABuvW13PPVEVbTyKmV4w3Yxk-6HRIqwe8/edit?usp=sharing) 🔒

**Comment by AmyKort** [comment]
I'll take a look!

**Comment by emileighoutlaw** [comment]
Made a couple notes in the doc for you @AmyKort :)

**Comment by noahmanger** [comment]
FYI we just merged in a [change](https://github.com/18F/fec-cms/pull/950) that will now allow this page to be edited in Wagtail.

**Comment by rhoughfec** [comment]
Updated audit section language in google doc. 
![audit lang](https://cloud.githubusercontent.com/assets/26230199/24661450/6796f26a-1920-11e7-8deb-cf2ea71b31fe.png)

**Comment by emileighoutlaw** [comment]
I believe the only things left to close out this issue are:

- [ ] Build new Wagtail page for enforcement landing (Emileigh)
- [ ] Implement MURs search box (and an alert that also links to the old search) on Wagtail enforcement landing page (Noah)
- [ ] Publish


If I'm missing anything, please feel free to jump in. But linking to all the other legacy legal searches is happening on other pages and being tracked in https://github.com/18F/fec-cms/issues/840

**Comment by noahmanger** [comment]
@emileighoutlaw a couple more things to do:
- [ ] Move the pages that are currently children of "Enforcement" to be children of the new one
- [ ] Make sure the slug is correct (should be "enforcement")

**Comment by noahmanger** [comment]
All done!
