### ISSUE TITLE
Decide on buckets for political party committees

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#869]
@amypike is helping lead the charge here. Our content team is looking at our content buckets for political party committees and deciding where things will be the same as candidates and where they will diverge. 

Steps to completion
- [x] Create draft of political party content buckets
- [x] Share for FEC and content team review
- [ ] Finalize

**Comment by emileighoutlaw** [comment]
@amypike— How'd things go in the content managers' bucket meeting? 😺  💟

**Comment by amypike** [comment]
@emileighoutlaw  It went really well!  We are actually meeting again in a few minutes to finish up.  "Disbursements" is a real bear and we wanted to noodle on some things overnight.   Stay tuned!
