### ISSUE TITLE
Implement new C&C Services landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#873]
So that users can navigate to all the content within the C&C Services section, implement the new landing page.

---

[Design](https://gsa.invisionapp.com/share/HQAOQLDF9#/screens/221667097_CC-Services-V2_Copy)

This should implement this landing page as an editable CMS landing page model, similar to what we did with `AboutLandingPage`. There's still a few details getting sketched out for the design, but the basics are ready for implementation.

**Completion criteria:**
- [x] Finish copy for the cards (cc @emileighoutlaw )
- [x] Create a new page model for this type of page that allows users to add new `section` blocks
- [x] Each section block should be a `StructBlock` that can have a title, body copy and lists of links to subpage
- [x] The cards at the top and bottom can be hard-coded into the template

**Comment by emileighoutlaw** [comment]
Amy and the content managers have been looking at all the [existing content](https://beta.fec.gov/candidate-and-committee-services/):lock: ad nauseam. 

At this point, I think the only two outstanding pieces are:
- Buckets for PACs, corporations, and parties
- Content for the `Reporting forms` card and the `Dates and deadlines` card

Since I need to hammer out those pieces with Amy still, I'm going to assign myself to this issue and move it back to "in progress for the moment"

**Comment by emileighoutlaw** [comment]
For the cards at the top of the page:
<img width="829" alt="screen shot 2017-03-16 at 11 01 01 am" src="https://cloud.githubusercontent.com/assets/10552702/24005758/e559168a-0a37-11e7-8f98-c67b94f18aff.png">

How would something like this work,  @AmyKort:


> **Dates and deadlines**
> Upcoming and past reporting deadlines and election dates

> **Forms**
> All FEC registration and reporting forms

**Comment by AmyKort** [comment]
For Dates and deadlines:  I can't think of a good sentence off the top of my head, but I feel like this should capture the same categories we included in the calendar filter. We've got the reporting deadlines, and then we've got reporting and compliance periods like IE periods, EC periods, FEA periods, and this http://www.fec.gov/info/charts_cc_dates_2017.shtml type of period.

I wonder if we could not worry about the upcoming / past nature of the information and use that space to better address the types of information available there.

**Comment by emileighoutlaw** [comment]
All that makes sense. My understanding for this page is that a majority of folks will be coming here to find current/upcoming periods and that the folks we're trying to help out tend to be more experienced committee-type users. So it seems like something along the lines of:

> **Dates and deadlines** 
> All FEC reporting deadlines, reporting periods and compliance periods

Would be specific enough for these folks. Or do you think they need more info about the specific periods written out (FEA, IE, EC, etc.)?

**Comment by AmyKort** [comment]
I love it.

**Comment by emileighoutlaw** [comment]
Fantastic! Added that content to this PR: https://github.com/18F/fec-cms/pull/885

We can keep working on the buckets for other groups but can easily add those in the CMS later.

**Comment by noahmanger** [comment]
One last question on this: Do we for-sure want to include grayed-out links to sections that aren't available yet? If so, that's a change we'd need to make to allow for links to pages that aren't yet implemented.

**Comment by emileighoutlaw** [comment]
Yes we do!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/885
