### ISSUE TITLE
Create page for form index

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#875]
So that filers and researchers can easily find a form, implement the form index page on the CMS. 

---

This issue is for implementing a new version of [this page](http://www.fec.gov/info/forms.shtml).

**Comment by emileighoutlaw** [comment]
@AmyKort: We have a [Wagtail page](https://beta.fec.gov/candidate-and-committee-services/filing-reports/registration-and-reporting-forms/) 🔒 of all reports ready for you to review! The password is the same as the password for all Candidate and Committee Services pages. Let me know if you need me to get that to you again. :)

**Comment by AmyKort** [comment]
This looks great to me. I'm tagging in @llienfec because she's super-smart.

**Comment by emileighoutlaw** [comment]
Lauren is the smartest! :nerd_face:

**Comment by emileighoutlaw** [comment]
@llienfec! Just dropping a not that we would love to have you take a look at [this new page](https://beta.fec.gov/candidate-and-committee-services/filing-reports/registration-and-reporting-forms/) 🔒  of reporting forms.  How does it look to you?
