### ISSUE TITLE
Build HTML About pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#882]
PDFs only account for a portion of the "About" content. For the section to be complete, we still need to create the following HTML Wagtail pages:

- 39 IG report pages
- ~35 Commissioner pages
- 28 budget and other reports

**Comment by emileighoutlaw** [comment]
We're getting really close on the report feeds pages!

- [ ] Inspector General HTML pages are complete
- Budget pages are almost complete with some outstanding questions:
    - How can we pull over the HTML tables into the [new 2003 HTML budget page](https://beta.fec.gov/admin/pages/7567/edit/) :lock: without devoting many of work building these tables by hand in the CMS? 
    - How can we pull over the HTML tables into the [new HTML voter registration report page](https://beta.fec.gov/admin/pages/7567/edit/) :lock: without devoting many of work building these tables by hand in the CMS? 
- The [legacy fec.gov 2001 budget page](http://www.fec.gov/pages/fc2001just.html) has broken images, and we can't finish that document until those are tracked down.

**Comment by noahmanger** [comment]
@emileighoutlaw can we just add them directly as HTML? The "Edit HTML" button now works.

**Comment by emileighoutlaw** [comment]
Okay! We are almost done with the reports feeds HTML pages. The only thing that's left are some broken images on this HTML 2001 budget page: http://www.fec.gov/pages/fc2001just.html

So, I think we'll either need to find the image files or say it's okay to publish without them. Pinging @amykort and @patphongs to help us decide?

**Comment by emileighoutlaw** [comment]
Oh! And one more note— the Performance Report says it's coming soon (in 2002). Do we know where this is? I can update.

https://beta.fec.gov/about/reports-about-fec/strategy-budget-and-performance/appendix-b-fy-2001-02-performance-report-fy-2003-budget-request-congressional-justification/

**Comment by emileighoutlaw** [comment]
Update:
- @amykort is checking to see if we need to bring over the 2001 budget page
- Otherwise, I think this issue is just waiting on @johnnyporkchops to create the Commissioner HTML pages

**Comment by emileighoutlaw** [comment]
Since my work on this issue is completed, I'm going to un-assign myself to this issue and let @johnnyporkchops take it over the finish line! 🏁 

Happy to review Commissioner HTML pages as needed, too. :)

**Comment by AmyKort** [comment]
@johnnyporkchops  Is this complete?

**Comment by johnnyporkchops** [comment]
I think this can be closed, it has been around for a while and included finishing careers and commissioners for my part

**Comment by johnnyporkchops** [comment]
I think this can be closed, it has been around for a while and included finishing careers and commissioners for my part
