### ISSUE TITLE
Add reporting examples, videos, and articles to candidate pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#884]
To provide users with a full picture of the resources available to them, we need to link to additional content on our candidate pages. 

Tasks to completion:
- [x] Add reporting examples (cc @llienfec)
- [x] Add FECTube videos (cc @llienfec @dorothyyeager)
- [x] Add FEC Record articles and brochures (cc @dorothyyeager)

**Comment by noahmanger** [comment]
Just updating on this: you should be able to start doing this either Thursday or Friday, once we've deployed a small set of changes to Wagtail.

**Comment by llienfec** [comment]
That's awesome.  Thanks!!!

**Comment by emileighoutlaw** [comment]
We're ready to get started on this, but it won't be today, so I'm moving into the next sprint. @noahmanger — are these changes up in Wagtail and ready for us?

**Comment by noahmanger** [comment]
Yes and no. It's implemented on the `CustomPage` templates, but not `ResourcePage`, which I just realized you use in several places. Do those need examples?

**Comment by emileighoutlaw** [comment]
Actually, I think `CustomPage` is the right place to have it for this work. :)

**Comment by noahmanger** [comment]
Great! Then yeah, go to town.

**Comment by emileighoutlaw** [comment]
@dorothyyeager— how are things going on getting brochures/videos added to candidate pages? Just checking in because you're so fast I suspect this might already be done!

**Comment by dorothyyeager** [comment]
@emileighoutlaw Brochures and articles are done. Not sure on videos so I'll ask Greg to comment...

**Comment by emileighoutlaw** [comment]
Some videos need updating before adding, but that's a separate task, so I'm closing this as finished! 🎉
