### ISSUE TITLE
Reports feeds headlines

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#896]
h/t to @amykort for catching this

In the reports feeds, often things are titled something along the lines of `Budget report, appendix A`. The tricky thing is: the document **isn't** the appendix of a one budget report. Instead, the whole budget report is an appendix of something else. 

We could clarify this by retitling these special cases something like "Budget report, appendix A of strategic plan blah blah". But I don't know how complex that would be to do. 

cc @noahmanger

**Comment by noahmanger** [comment]
Great. Whatever you go with, these can all be managed in Wagtail.

**Comment by emileighoutlaw** [comment]
This should be fixed now. We'll confirm when we review our work in: https://github.com/18F/fec-cms/issues/919
