### ISSUE TITLE
Use S3 credentials directly from S3 service

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#904]
I was looking into an unrelated issue with @jontours earlier today and noticed that a user-provided service includes credentials that appear to be used to access an S3 service instance. There's nothing wrong with that, but it's generally simpler to access service credentials by binding services to applications, rather than copying and pasting credentials into a user-provided service. Do you all have a requirement to pass credentials in a user-provided service rather than binding to the S3 instance?

cc @LindsayYoung @ccostino

**Comment by LindsayYoung** [comment]
We knew we were moving to govcloud and we did not want to remake or move the bucket. So the content bucket (I think that is the bucket you are referring to) was made on govcloud and we store the credentials on East west. Once we move to govcloud, we can just bind it.

**Comment by LindsayYoung** [comment]
I thought we already had done this, but this is something we will want to do in the near future.

**Comment by ccostino** [comment]
@LindsayYoung what would still be left with this?  Making sure the content buckets associated with the CMS is a cloud.gov service in all instances, not a separate S3 bucket outside of cloud.gov?

**Comment by LindsayYoung** [comment]
Sorry confused by your question. The s3 buckets are all in clould.gov.

**Comment by ccostino** [comment]
This should get fully addressed in #1700, thanks all!
