### ISSUE TITLE
Implement new footer links

### ISSUE THREAD

**Issue by xtine** [18F/fec-cms#909]
Implement new changes to footer links for both `fec-cms` and `openFEC-web-app` templates.

---

[Design Issue](https://github.com/18F/fec-cms/issues/484)

![](https://cloud.githubusercontent.com/assets/11636908/23953416/deac20ac-096a-11e7-835e-0564bee237cb.png)

**Comment by jenniferthibault** [comment]
Implemented in #910 and https://github.com/18F/openFEC-web-app/issues/1897
