### ISSUE TITLE
Update category drop-downs for `Reports about FEC` section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#916]
We'd need to adjust the category/subject drop downs in our `Reports about FEC` feeds to accommodate the last PDF and HTML page stragglers. I believe this requires a developer to change the template, but I defer to @noahmanger or @xtine:

To do:
- Remove “Operation plan” filter in `Agency operations`
- Remove “Annual report” in `Procurement and contracting`
- Remove "Annual report" filter in `Agency operations`

- Add “Fair Act” filter to `Procurement and contracting`
- Add “Buy America report” to `Procurement and contracting`
- Add “Public procurement report” to `Procurement and contracting`

**Completion criteria:**
- [ ] Finalize lists
- [ ] Make changes

cc @amykort for visibility

**Comment by AmyKort** [comment]
For the performance and budget section, what if we keep the current organization, which is by report type. The filters would be:

Strategic plans
Agency Financial Reports
Summary of Performance and Financial Information
Performance and Accountability Report
Budget requests

In cases where a Congressional budget submission is currently displayed as a series of separate pdfs (including a separate cover letter and separate documents for each appendix) we'll combine those into separate pdfs.

tagging @amypike

**Comment by emileighoutlaw** [comment]
Circling back on this! Here's what I have:

**Remove**
- Remove “Operation plan” filter in Agency operations
- Remove “Annual report” in Procurement and contracting
- Remove "Annual report" filter in Agency operations

**Add**
- Add “Fair Act” filter to Procurement and contracting
- Add “Buy America report” to Procurement and contracting
- Add “Public procurement report” to Procurement and contracting
- Add "Strategic plan" to Budgets and strategy
- Add "Agency financial report to Budgets and strategy
    - Right now we have a category called `Annual financial report`; do we want to eliminate this in favor of `Agency financial report`?
- Add "Summary of performance and financial information" to Budgets and strategy
    - Right now we have a category called `Summary report`; do we want to eliminate this in favor of `Summary of performance and financial information`?


If we're sure these are the changes we want, we can kindly ask Noah to implement :)

cc @AmyKort @amypike

**Comment by AmyKort** [comment]
Yes--it should be Agency Financial Report (should we make that caps since it is the name of the report?) and Summary of Performance and Financial Information (instead of summary report). Thanks!

**Comment by emileighoutlaw** [comment]
Sounds like we're ready to implement? 

**Remove**
- Remove `Operation plan` filter in Agency operations
- Remove `Annual report` in Procurement and contracting
- Remove `Annual report` filter in Agency operations
- Remove `Annual financial report` in Strategy and budget
- Remove `Summary report` in Strategy and budget

**Add**
- Add `Fair Act` filter to Procurement and contracting
- Add `Buy America report` to Procurement and contracting
- Add `Public procurement report` to Procurement and contracting
- Add `Strategic plan` to Budgets and strategy
- Add `Agency Financial Report` to Budgets and strategy
- Add `Summary of performance and financial information` to Budgets and strategy



I don't know how the logistics work around removing one tag and adding another, but we currently have two documents tagged as `Annual financial report`. When that filter is deleted, we want to make these `Agency financial report`:
https://beta.fec.gov/about/reports-about-fec/strategy-budget-and-performance/?category=annual+financial+report

https://beta.fec.gov/about/reports-about-fec/strategy-budget-and-performance/?category=annual+financial+report
