### ISSUE TITLE
Add missing PDFs to `Reports about FEC`

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#919]
@AmyKort and @amypike identified some PDFs that got left behind in the initial building of the Reports feeds.

Tracking that content in [our existing report feed spreadsheet](https://docs.google.com/spreadsheets/d/1ZIismo1y8mih7O4XoCTuyq13uKwtCp_Dz_RzMstOFQ4/edit#gid=168616009) :lock:

Steps to completion
- [x] Add dates to documents
- [x] Confirm new URL (for new S3 bucket)
- [x] Add to feeds

This work is also dependent on: https://github.com/18F/fec-cms/issues/916

**Comment by patphongs** [comment]
[spreadsheet](https://docs.google.com/spreadsheets/d/1ZIismo1y8mih7O4XoCTuyq13uKwtCp_Dz_RzMstOFQ4/edit#gid=168616009) has been updated with new URLs and missing PDFs have been added to the content bucket.

**Comment by amypike** [comment]
Thanks, @patphongs .  We also added dates for the documents.  The procurement docs only have a year and the OIG docs have a month and year. @AmyKort

**Comment by emileighoutlaw** [comment]
That's amazing! I'll get these uploaded to the reports feed asap!

**Comment by noahmanger** [comment]
One more that @AmyKort raised that needs to be added to annual FOIA reports, under 2017: http://www.fec.gov/foia/chieffoiareport2017.pdf

**Comment by noahmanger** [comment]
@patphongs can you move that new FOIA report and add it?

**Comment by emileighoutlaw** [comment]
Additionally, Privacy Act Notices need to be added: http://www.fec.gov/law/privacy_act_notices.shtml

**Comment by emileighoutlaw** [comment]
There are a couple that still need to be added, so I'm moving this back to in-progress. Should be resolved today, though!

**Comment by emileighoutlaw** [comment]
We're only outstanding 3 document dates and then this work can be reviewed and closed! cc @AmyKort

**Comment by emileighoutlaw** [comment]
This work is done! @AmyKort can confirm, but I believe we are good to release everything except the IG section. So, on the reports page (https://beta.fec.gov/about/reports-about-fec/) that's the cards for:

> Procurement and contracting
> Strategy, budget and performance

**Comment by emileighoutlaw** [comment]
cc @noahmanger for release readiness

**Comment by noahmanger** [comment]
@emileighoutlaw that can all be configured in the CMS on the reports landing page. No need to push code.

**Comment by emileighoutlaw** [comment]
Excellent! @AmyKort, what kind of QA do we need to do to feel comfortable making these sections live?
