### ISSUE TITLE
Figure out where efiling help pages live

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#923]
There are a couple efiling pages that we need to figure out how best to link to them. In the sitemap, they live under the "Filing reports" [page](https://cloud.githubusercontent.com/assets/1696495/24376280/334901d2-12f0-11e7-93b3-54a972f61201.png).

But as we discussed in grooming, this may be too buried. So the purpose of this issue is to identify where the pages should actually be linked from.

The pages are:
- http://www.fec.gov/support/index.shtml
- http://www.fec.gov/elecfil/electron.shtml

**Completion criteria:**
- [x] Identify where the pages live within sitemap
- [ ] Draft any microcopy or anything to link to them

**Comment by emileighoutlaw** [comment]
@llienfec and I have been pairing on this. We do think there's a way to include this content in the existing content framework, and we're working on that now :)
