### ISSUE TITLE
Update Administrative Fines citations content

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#924]
We need to content from [this page](http://www.fec.gov/af/AFPRegulations.shtml) to the citations box on [this page](https://beta.fec.gov/legal-resources/enforcement/administrative-fines/).

**Completion criteria:**
- [x] All content in the citations box

**Comment by emileighoutlaw** [comment]
These are all in, but something super wonky is happening with the spacing:
https://beta.fec.gov/legal-resources/enforcement/administrative-fines/

cc @noahmanger

**Comment by noahmanger** [comment]
Nothing broken; it's just that that's how the elements flow. If you re-ordered the sections they could line up a little nicer.
