### ISSUE TITLE
Update SERS content 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#925]
As identified in [this comment](https://github.com/18F/fec-cms/issues/840#issuecomment-287894272), we should update the SERS blurb on [this page](https://beta.fec.gov/legal-resources/regulations/) so that it speaks to the content that users will find, rather than the _system_ it lives in. Everywhere else we refer to the tools by what kind of information you can get, rather than the name of the tool.

**Completion criteria:**
- [x] Update content on SERS section of Regulations page
- [x] @amypike review

**Comment by AmyKort** [comment]
@amypike

**Comment by amypike** [comment]
@emileighoutlaw .  What do you think of this? The Commission uses a rulemaking process to write regulations that implement the law.  SERS allows users to search for proposed and final rules, public comments and hearing testimony in completed and ongoing Commission rulemakings. It also allows the public to submit comments on proposed regulations and other rulemaking documents.

**Comment by emileighoutlaw** [comment]
I love it, @amypike. @amykort, what do you think?

**Comment by AmyKort** [comment]
Let's run past OGC and we're done.

**Comment by AmyKort** [comment]
How about:

The Commission promulgates regulations in accordance with the Administrative Procedure Act. SERS allows users to search for proposed and final rules, public comments and hearing testimony in completed and ongoing Commission rulemakings. It also allows the public to submit comments on proposed regulations and other rulemaking documents.

**Comment by emileighoutlaw** [comment]
I love everything about that except the first sentence, which is pretty tough to parse. Perhaps we can get away with writing around it, saying something like: 

Use SERs to search completed and ongoing Commission rulemakings. Search for proposed rules, final rules, public comments and hearing testimony. Additionally, submit comments on proposed regulations and other rulemaking documents.

**Comment by AmyKort** [comment]
Let's try it.

**Comment by emileighoutlaw** [comment]
Change is live here: https://beta.fec.gov/legal-resources/regulations/
