### ISSUE TITLE
Link to Testing the Waters brochure from Registration page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#926]
This issue is to add a link to the Testing the Waters brochure from the [Registration](https://beta.fec.gov/candidate-and-committee-services/registering-candidate/) page. 

**Completion criteria:**
- [x] Add link on the page

**Comment by emileighoutlaw** [comment]
The link is on the page. 

We do need an cover image for the "[Testing the waters](http://www.fec.gov/pages/brochures/TestingtheWaters.shtml)" brochure from @jenniferthibault, when she has time to make and upload it :)

**Comment by jenniferthibault** [comment]
It's ready, let me know where to send it:
![thumbnail--testing-waters-brochure](https://cloud.githubusercontent.com/assets/11636908/24467378/35bbd14a-1482-11e7-90f3-65cf78358504.png)

**Comment by emileighoutlaw** [comment]
Uploaded and added to page! https://beta.fec.gov/registration-and-reporting/house-and-senate-candidate-registration/

**Comment by noahmanger** [comment]
Beautiful. Closing and updating site map.
