### ISSUE TITLE
Implement pre-flip banner

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#928]
So that users know that the beta site will soon become the main site, implement the pre-flip banner across all apps.

---

[Design](https://cloud.githubusercontent.com/assets/11636908/24270359/34e938de-0feb-11e7-8691-d90b4641a1a6.png).

**Completion criteria**:
- [x] The countdown timer should draw from some env variable that can be configured
- [x] The banner should be collapsible, with the collapsed state stored as a cookie (or `localStorage`?) and it should persist beyond sessions.
- [x] The entire banner should be turned on or off with an env feature flag
- [x] Implement in CMS, web app, eregs

Note: The actual tour will be handled in a different issue.

**Comment by xtine** [comment]
Should the countdown timer env be an env to turn on/off the countdown timer, or the actual date it counts down to?

**Comment by noahmanger** [comment]
My $.02: have an env var for the date, but if it's empty then the countdown doesn't display?

**Comment by xtine** [comment]
@noahmanger: Neat that was what I was thinking too. Just wanted to make sure.

**Comment by noahmanger** [comment]
Implemented.
