### ISSUE TITLE
Complete content for new site orientation

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#929]
This is a follow-up task to https://github.com/18F/fec-cms/issues/877 to complete the copy writing for the site orientation. 

[Google Doc](https://docs.google.com/document/d/1ZPDNQ4gNDCuWiUj3Fwkn6DwGD5rfwEZtb5e-8VUWJpc/edit#heading=h.h472d87qz6hn) 🔒
 
**Completion criteria:**
- [x] All content written and approved

**Comment by jenniferthibault** [comment]
Noah and I completed the first draft of this promotional content in the [Google Doc](https://docs.google.com/document/d/1ZPDNQ4gNDCuWiUj3Fwkn6DwGD5rfwEZtb5e-8VUWJpc/edit#heading=h.h472d87qz6hn) 🔒. 

We focused our points on two things:
- Managing change: If something moved, tell people where it is now
- Communicating new value: What's new and more useful to people about each point?


In a few places, we left other options we were considering visible in case it helped review & edits.

**Next steps**

- [ ] Review by @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Woohoo! Can't wait to dive in 🐬

**Comment by emileighoutlaw** [comment]
This is looking so great, y'all! Now that I've made some edits, I'd love to have y'all take a second look and make sure I didn't finagle anything in a way that stands out to you as not right  👀

**Comment by emileighoutlaw** [comment]
But I'm all 😍  :+1: 😍  to this draft

**Comment by jenniferthibault** [comment]
All 👏 of 👏 @emileighoutlaw's  👏 edits 👏 made 👏 this 👏 so 👏 much 👏 better!

My favorite is how Emileigh helped us use other words and phrases for "find" "search for" etc, and focused on what it means to "have a better search experience" by instead saying what that experience is made of.  👏 💪 

I know there's one outstanding point being edited about regulations, but what's next after that?

**Comment by noahmanger** [comment]
Final step: I'd love @AmyKort to work a review of this in to her busy schedule.

**Comment by emileighoutlaw** [comment]
This content is approved by Amy and me. 🚀
