### ISSUE TITLE
Implement site orientation 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#930]
So that users can be introduced to all of the new site's organization and high-level features, implement an orientation experience. 

---

This is to implement the orientation as designed in [this InVision](https://gsa.invisionapp.com/share/WYAYLDV59#/224785997_New_-_Near_Before_Copy_5) , using the copy from [this issue](https://github.com/18F/fec-cms/issues/929).

I know there's existing libraries out there that do certain things like this, so we should see if we can find something that will make this an easier lift. If there's a good library but it requires slight tweaks to the experience, that's ok. Also, it's ok to start working on the technical aspects of this while working out the content details.

Expected behavior:

- User clicks "Start tour" to begin the orientation
- Banner disappears and the top level tour flow appears, highlighting the page you're on
- Orange tour points appear throughout
- Clicking a tour point opens a tooltip. X-ing out removes the tooltip
- Clicking "next" opens the next tooltip
- Clicking "next" on the last tooltip of a page takes you to the next page
- Clicking the page title in the top bar takes you to that page
- Clicking "exit tour" ends the tour and restores the original banner

**Completion criteria**
- [x] Tour implemented as designed

**Comment by jenniferthibault** [comment]
Heads up! Content for this is nearly ready from https://github.com/18F/fec-cms/issues/929 
🔒 [Google doc](https://docs.google.com/document/d/1ZPDNQ4gNDCuWiUj3Fwkn6DwGD5rfwEZtb5e-8VUWJpc/edit#heading=h.h472d87qz6hn). There's one edit being finalized, but that should wrap shortly, or we could edit it in the code as it evolves.

**Comment by xtine** [comment]
@jenniferthibault: I just want to make sure I got the interaction correct when a user starts a tour on a page that isn't in the page header (Intro / Campaign finance data / Candidate and committee services / Legal resources). Only the dots for header/footer should light up. But for the page header, none of the links are selected (blue background), but if they click on one it takes them to that page accordingly?

**Comment by jenniferthibault** [comment]
Oh interesting! I was thinking that the tour points in the header/footer were actually attached to the "Introduction" page section.

My hypothesis is that the "start tour" language indicates a change enough that a user wouldn't be startled if clicking that link brought them back to the landing page and started the tour from the "Introduction" section there. That means that if you start the tour from any page other than the home page, it would bring you to point 1 of the "Introduction" section.

What do you think?

cc @nickykrause for a second brain

**Comment by xtine** [comment]
So I interpreted it that "Start tour" would begin the tour at the page they were at, and clicking "Introduction" goes to home page. I guess I'm thinking of the case in which someone lands on a candidate or datatable page and not necessarily the home page first, it would feel weird to me to then have it jet back to home page if they interpreted as "what's changed from old to new site on current page."

**Comment by jenniferthibault** [comment]
We don't yet have any user data for which way users expect, but one principle of the design is that when you hit "start" the tour, a tooltip opens to begin the experience, which gives users an obvious starting point on the present screen.

If it were to start on a page that isn't a data, help for cand & cmtee, or legal landing pages, like tie data tables you were describing above, even though the top nav would be available, there would be no tooltip or tour point on that page to pop open, so they'd have to self-navigate to find where it starts.

So on that principle, if you start the tour from any other page, we could have it bring you back to the landing page for that section to start with tooltip open, or back to the introduction on the home page.

**Comment by noahmanger** [comment]
Implemented.
