### ISSUE TITLE
Visual review and cleanup of meeting agenda pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#940]
So that users can find all information and documents related to an open meeting, clean up the meeting agenda templates.

---

Now that we have the scraper complete and fully understand the data that we're importing into these agenda pages, we need to do a visual review and front-end cleanup of the agenda templates. We had previously paused this work temporarily.

Note: there's a slight difference in the way that imported agendas are structured vs. the way that agendas that are entered by hand in the future are. Old agendas have all their content in a single block of HTML, which means fewer controls over how they're styled (and probably not worth a ton of energy to clean up). 

New agendas are created using custom Wagtail fields, so there's a lot more control.

Tagging in @jenniferthibault and @johnnyporkchops to connect on this.

**Comment by jenniferthibault** [comment]
@noahmanger where should I go to start seeing examples of the imported agendas?

**Comment by noahmanger** [comment]
Noting two changes we identified today that you can go ahead and make @johnnyporkchops 👍 

- Template: Remove themeeting media  `.slab` at the bottom if `imported_html == True`
- Import script: change page title to: "{{ the date }} Open meeting agenda"

**Comment by jenniferthibault** [comment]
^ Those are the only changes I'd make to what we have now. The rest would be small manual things that I'll look into making for years 2016-17, as we've been doing with other latest updates items.

**Comment by jenniferthibault** [comment]
Feeling like I've finally found the light on these! 

## For the imports
- We also need to import `Executive sessions` as a form of Commission meeting, which we don't yet have.

## For the template
There's more significant changes that probably look like a near clean start at this point—it was helpful to find out we could control the import and the new items separately, which changed my thinking on a bit of this.

[**Design**](https://cloud.githubusercontent.com/assets/11636908/24822263/c819a350-1bc1-11e7-8072-43dda706804f.png) (repeated below)  |   [**Design with annotations**](https://cloud.githubusercontent.com/assets/11636908/24822269/d21e2894-1bc1-11e7-997d-8850e16fc4dc.png) for CMS template-building

- Let's start by adding a conditional to the template for if it's an Open meeting or an Executive session. Both has a little introduction that comes from the existing page, but it's different for wach:
 **Open meetings:**
  - > Open meetings are public meetings in which the Commissioners adopt new regulations, issue advisory opinions and approve audit reports concerning political committees. Open meetings typically are held twice a month, at 10:00 a.m. on Thursdays.
  Members of the public can attend an open meeting or hearing at the FEC. Please bring a photo ID and be prepared to go through a security check. You will then be escorted to the Commission's hearing room.

  **Executive sessions:**
  - >The Commission meets regularly in executive session to discuss pending enforcement actions, litigation and other matters that, by law, must be kept confidential.

- Let's split the main body of the page into four main sections: `Minutes`, `Agenda`, `Notices` followed by `Recordings for this meeting`
This makes the page the main file for all things related to that meeting.

## Next steps
- @johnnyporkchops & @noahmanger let's sync up early next week to make sure I've understood things correctly, and hammer our everyone's existing questions on the page and how to build the template. I'll coordinate on slack 

![meetingagenda-desktop-v1](https://cloud.githubusercontent.com/assets/11636908/24822263/c819a350-1bc1-11e7-8072-43dda706804f.png)

**Comment by johnnyporkchops** [comment]
Thanks Jen! This finally pulls things together in a way that gives me a way forward with the new-page template.

**Comment by jenniferthibault** [comment]
New version ready to go, with feedback incorporated from Greg, Rebecca, and Dayna, the Commission Secretary. 

A few things we learned from this feedback:
- When a meeting  is in progress, there is a livestream available, which should be prominent on the page where people find the event. This module should be toggled off (manually or automatically?) and disappear when the meeting is no longer in progress.
- Draft minutes do not have a posting date
- Sunshine Act notices and amendments should not have a posting date
- Public hearings don't have minutes
- The calendar publishes scheduled open meetings before those meetings' Sunshine Notices will be posted on their pages, so the page will need to exist for a period with "more info coming" content. During this time, even if the posting is available in the latest updates feed, the primary way users will access this information is likely to be through the calendar.
- When a page is updated, the publish date should not be later than the date of the actual meeting.
   - > When I look for documents I look for the meeting date and then the agenda or minutes. The publish date doesn't help me in that regard.

## Mockups:
All in one InVision, so arrow ◀️ ▶️ to scroll through, or get to phases directly through the links below
- [Latest updates feed](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731089_Latest-Updates_Meeting)
- Open meeting page [before sunshine notice ](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731091_Meeting-Open-1) 
- Open meeting page [with sunshine notice](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731092_Meeting-Open-2)
- Open meeting page [at time of meeting](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731093_Meeting-Open-3)
- Open meeting page [after meeting](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731094_Meeting-Open-4)
- [Executive session with sunshine notice](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731090_Meeting-Executive)

### Next steps:
@noahmanger do you feel like this gives you enough to start implementing? Or are there other bits I can help prepare?

**Comment by noahmanger** [comment]
This is great. I just made a new issue for implementing the template changes https://github.com/18F/fec-cms/issues/985 and added to the issue for updating the page model https://github.com/18F/fec-cms/issues/977 , so I'm going to close this.
