### ISSUE TITLE
Linking to old Record articles on "Help for candidates and committees" pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#956]
Our [misappropriated funds page](https://beta.fec.gov/help-candidates-and-committees/keeping-records/misappropriated-funds/) 🔒 links to two FEC Record articles that are from 2007 and 2009. 

Those PDF articles eventually lead users to fec.gov and not beta.fec.gov.

@jenniferthibault and I chatted about this today. We think it might be best (when we occasionally encounter older Record articles that are still relevant to new content) to add them by hand as HTML pages in our Wagtail "Latest updates" section. 

As a result, these old pages would look and feel like the [other Record HTML pages](https://beta.fec.gov/updates/district-court-allows-challenge-admin-complaint-outcome-crew-v-fec-crossroadsgps-16-259/) that we link to, which makes for a more consistent user experience. Additionally, all our links in "Help for candidates and committees" pages would lead to beta.fec.gov (none would go to the legacy site).

So those are our thoughts! Paging @noahmanger @dyeager for their take on this. :) 

(cc @patphongs for visibility)

**Comment by dorothyyeager** [comment]
That makes sense to me. Let me know if it's something I can help with. It's possible I will have the original word documents for those.

**Comment by noahmanger** [comment]
I support this idea!

**Comment by emileighoutlaw** [comment]
This is done and up on our [misappropriated funds page](https://beta.fec.gov/help-candidates-and-committees/keeping-records/misappropriated-funds/)! 

If we identify other old PDFs that we want to link to, Dorothy, I can make them HTML pages (or easily show you how to do this!) for other Record articles :)

**Comment by dorothyyeager** [comment]
Sounds good Emileigh! (I'm up to do it when you get a chance to show me how.) Thanks!

**Comment by noahmanger** [comment]
I love it!
