### ISSUE TITLE
Implement new error pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#966]
So that users can understand why they can't find a certain page, implement new 404 and 500 error pages that give them context and escape paths.

---

[Design issue](https://github.com/18F/fec-cms/issues/881)

![design](https://cloud.githubusercontent.com/assets/11636908/24682441/c4f0172e-1967-11e7-8619-8ba7cf1976e6.png)

**Completion criteria:**
- [x] New 404 error page for web-app
- [x] New 500 error page for web-app
- [x] New 404 error page for cms
- [x] New 500 error page for cms
- [x] The email link should use an email address that is configured as a global constant
- [x] The Github link should go to github.com/18f/fec
- [x] The "previous FEC.gov design" link should go to a URL that is configured as a global constant. Right now it would be fec.gov but eventually it will change to classic.fec.gov

**Comment by emileighoutlaw** [comment]
Last content note: We've got so many balls in the air right now, I forgot that we're using "the old FEC.gov design" in other places. Should we update this to read the same (as opposed to "previous")?

**Comment by johnnyporkchops** [comment]
Here is a screenshot of the 404 page:
![404_error_scrnsht](https://cloud.githubusercontent.com/assets/5572856/25107746/47a4dc04-239f-11e7-9b7c-8819f9b111da.jpg)

**Comment by johnnyporkchops** [comment]
# Just double checking, this is a screenshot of the **current webapp 404 page** are we definitely removing the search box?
![webapp_404_error_scrnsht](https://cloud.githubusercontent.com/assets/5572856/25107867/0014d708-23a0-11e7-81ef-0fbe404f0a93.jpg)

**Comment by johnnyporkchops** [comment]
Changes made, plz review:
![cms_404_error](https://cloud.githubusercontent.com/assets/5572856/25207305/909ba184-253b-11e7-8ad3-252fccf76b9f.jpg)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1967 . Nice work!
