### ISSUE TITLE
Wagtail image upload broken

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#971]
Uploading file via wagtail now results in a 403. We have to figure out if the CDN is accepting POST requests and if that needs to be allowed. It is able to perform GET requests to existing files.

**Comment by ccostino** [comment]
I adjusted the CORS on the content bucket to hopefully address this issue.  @johnnyporkchops and @patphongs, whenever either of you gets a moment to test, can you let me know if this has fixed the issue or not?  Thanks!

**Comment by patphongs** [comment]
@ccostino It works again, thank you for fixing the CORS.

**Comment by ccostino** [comment]
You're welcome, I'm sorry about the hiccup!
