### ISSUE TITLE
Site Flip - Content on classic that will stay current

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#974]
@johnnyporkchops This is a list of the content on classic.fec.gov that should remain current. Site banner should reflect this on the classic site on flip.

cc @noahmanger @AmyKort @PaulClark2 @jwchumley (please check if this list is correct):

- [ ] http://www.fec.gov/pindex.shtml
- [ ] http://www.fec.gov/portal/graphic_presentation.shtml
- [ ] http://www.fec.gov/disclosurep/pnational.do
- [ ] http://www.fec.gov/disclosurehs/hsnational.do
- [ ] http://www.fec.gov/disclosure/partySummary.do
- [ ] http://www.fec.gov/disclosureie/ienational.do
- [ ] http://www.fec.gov/disclosureie/ienational.do?candOffice=S
- [ ] http://www.fec.gov/disclosure/pacSummary.do
- [ ] http://www.fec.gov/portal/searchable.shtml
- [ ] http://www.fec.gov/finance/disclosure/candcmte_info.shtml
- [ ] http://www.fec.gov/data/DataCatalog.do
- [ ] http://www.fec.gov/finance/disclosure/ie_reports.shtml
- [ ] http://www.fec.gov/finance/disclosure/norindsea.shtml
- [ ] http://www.fec.gov/portal/download.shtml
- [ ] http://www.fec.gov/data/DataCatalog.do
- [ ] http://www.fec.gov/finance/disclosure/ftp_download.shtml
- [ ] http://www.fec.gov/finance/disclosure/electioneering.shtml
- [ ] http://www.fec.gov/finance/disclosure/ftpdet.shtml
- [ ] http://www.fec.gov/finance/disclosure/ftpsum.shtml
- [ ] http://www.fec.gov/finance/disclosure/ftpefile.shtml
- [ ] http://www.fec.gov/finance/disclosure/other_disclosure.shtml
- [ ] http://www.fec.gov/calendar/calendar.shtml
- [ ] http://www.fec.gov/MUR/
- [ ] http://www.fec.gov/auditsearch/auditsearch.do

**Comment by PaulClark2** [comment]
Are we putting banners on these pages?

http://saos.fec.gov/saos/searchao
http://eqs.fec.gov/eqs/searcheqs
http://sers.fec.gov/fosers/

**Comment by patphongs** [comment]
@PaulClark2 Good question. In order to do that we would need to reach out to the application devs who work on the legal apps. @johnnyporkchops has coded out the banners that will go on our main classic site already. Might have to tweak it for those specifically. @jenniferthibault @emileighoutlaw Should banners go on those separate legal apps too?

**Comment by AmyKort** [comment]
Let's add this page as well:

http://www.fec.gov/fecig/fecig.shtml
 
@amypike

**Comment by jenniferthibault** [comment]
@patphongs i checked in with our team real quick, and we think the apps should get the same maintained content banner that will be present on classic.fec pages that are still being updated, in order to provide reassurance that people are in the right place:

![screen shot 2017-04-12 at 12 19 17 pm](https://cloud.githubusercontent.com/assets/11636908/24968163/61a77b9e-1f7a-11e7-89c6-ea8e753a03c5.png)

[GH issue](https://github.com/18F/fec-cms/issues/878) with designs for all banners | [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1I-fCJB3Cl5qXjN7o268JKfOUvjwauZW9HMU3TdR_sTU/edit?usp=sharing) 🔒 with content for all banners

**Comment by AmyKort** [comment]
One change: We're creating a transition page for http://www.fec.gov/fecig/fecig.shtml so it shouldn't be on the list. Thanks!

**Comment by johnnyporkchops** [comment]
http://classic.fec.gov/portal/download.shtml
All the links links on this page are listed as current above except the below link:
**Link Text: Presidential Matching Funds Submissions
URL: http://classic.fec.gov/finance/2012matching/2012matching.shtml**
Should this link be redirected to somewhere on beta or removed, or left as is?

**Comment by AmyKort** [comment]
That's not a page that will have an equivalent on the new site. Can we leave it as is?

**Comment by johnnyporkchops** [comment]
All the pages listed above have had the "Current Content" language added with the exception of http://classic.fec.gov/auditsearch/auditsearch.do
For which Jun and Gashaw are deploying with a new header shortly.

Also House and Senate data for 2017-2018 data has been linked so the following two URLs can show the proper banner and a map:
Can be tested here until deployed shortly:
http://webtest.fec.gov/disclosureie/ienational.do
http://webtest.fec.gov/disclosureie/ienational.do?candOffice=S
