### ISSUE TITLE
Home page: Update citizen info slab with public info links

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#976]
Designs pulled out from https://github.com/18F/fec-cms/issues/880 with new additions highlighted in pink:

![screen shot 2017-04-11 at 9 27 56 am](https://cloud.githubusercontent.com/assets/11636908/24911531/3e4d8f62-1e99-11e7-80de-a492ceb2d2c9.png)

At the moment, I can't log in to the CMS to get links to the wagtail pages that have been started. Once that bug is resolved, I'll edit this to add where these links should connect to.

**Comment by xtine** [comment]
@jenniferthibault: I have the copy ready to go on PR https://github.com/18F/fec-cms/pull/1001 so just let me know when you have the links and I can update accordingly.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1001
