### ISSUE TITLE
Import Executive Session Sunshine Notices

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#980]
The initial meeting scraping only got the Open Meetings, but we also need to scrap the Executive Sessions. These are much simpler, and only have:

- `date`: The date the meeting happened
- `meeting_type`: `executive` for all
- `sunshine_act_links`: a list of URLs to Sunshine Notice PDFs

These are all available from these pages: http://www.fec.gov/agenda/agendas.shtml

**Completion criteria:**
- [ ] Update scraper to get all of these
- [ ] Run importer on production

Additional template work is happening in other issues, so no need to worry about that here. 

---

Update: this data has all been compiled in a spreadsheet for easier importing.

**Comment by ccostino** [comment]
This has proven to be a bit trickier than anticipated and we're still working out some bugs and issues with the scraping process.  However, we are getting closer.  @xtine and I have committed the latest code for this issue and #977 in PR #1009, so you can see progress in there.  Tests aren't currently passing and we'll also need to factor in adding the notices to the updates feed after.

**Comment by johnnyporkchops** [comment]
@ccostino and @xtine, I owe you an answer in wether it's ok to not have the Sunshine Notices before a certain date, ( i believe 2003) Judging on how things are going so far its likely the stakeholder will concur with that.

**Comment by ccostino** [comment]
Thanks, @johnnyporkchops!  That part of the processing I'm a bit less worried about as I think we've found a work around if we do end up needing them, but it'd still be good to know for sure. :-)

**Comment by noahmanger** [comment]
I had a thought about how to get the historic archive of executive session notices into Wagtail: the main hangup has been in scraping the content from the current site, but it's probably not too much effort to manually create a spreadsheet of all the old executive sessions with links to their sunshine notices. 

@dorothyyeager or @johnnyporkchops is this something you (or someone else at FEC) might be able to help out with in your spare time? I could also chip in and we could divide and conquer.

**Comment by dorothyyeager** [comment]
I could help with this.

**Comment by noahmanger** [comment]
I started a Google doc for this and shared with @dorothyyeager .

**Comment by dorothyyeager** [comment]
Have finished inputting exec sessions back to 2001 on that Google doc.
