### ISSUE TITLE
Link to IG page in footer

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#981]
One FEC requirement that wasn't included in our memo on required links is a link to the Inspector General page. So for compliance, we need to add an IG link to the footer before the site flip.

Since we haven't started on the "Agency Structure" part of "About" yet, we'll have to decide if we want to link to the old FEC IG page or if we want to make an intermediary new one in Wagtail. (I'm not sure if we have a template that would be ideal for this purpose though)

**Comment by emileighoutlaw** [comment]
Chatted with Noah and Jen about the IG page question today, @AmyKort! Thanks for your notes with us!

We'd feel happy linking to the old IG page from the footer for the time being and then working on a longer-term design solution after the site flip. 

If we add the "Inspector General" link to the footer, it seems most appropriate under the _Open government_ series of links. (I'd put it third on the list so that Press and FOIA are in the same row, for scanning journalists). 

@AmyKort I know you also mentioned that we needed to add performance and strategy to the footer. Can you remind me which memo/law/original document that requirement comes from?

Here's what a proposed new footer might look like in terms of links:

<img width="1014" alt="screen shot 2017-04-13 at 3 08 04 pm" src="https://cloud.githubusercontent.com/assets/10552702/25022297/eb931d32-205a-11e7-9048-93fd2c1421d3.png">

**Comment by AmyKort** [comment]
OMB Circular A-11 Part 6, 210.5

**Comment by emileighoutlaw** [comment]
Well! The guidance couldn't be clearer than it is in that memo 😁 

> Agencies will also create a prominent link directly to this page from the
agency homepage. 

@jenniferthibault: the last comment has a proposed placement for the IG link and the performance/strategy link. What do you think?

**Comment by noahmanger** [comment]
Looks good to me.

**Comment by jenniferthibault** [comment]
Sounds good! Thanks for finding the memo Amy!

**Comment by emileighoutlaw** [comment]
Sounds like we're ready to move to implementation!

**Comment by noahmanger** [comment]
Do we still need a transition page for this? @patphongs
