### ISSUE TITLE
Implement changes to AgendaPage template

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#985]
This task is to implement the changes to the AgendaPage template now that we have new designs.

[Design issue](https://github.com/18F/fec-cms/issues/940) | [InVision](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731091_Meeting-Open-1)

This relies on changes to the page model as noted in [this issue](https://github.com/18F/fec-cms/issues/977). Once those are complete, all the front-end styling can happen.

**Implementation details**
- [x] All Open Meetings should should boilerplate content at the top; Executive Sessions have different boilerplate. This should be hardcoded into the template. 
- [x] When the page is first created, there will be no media or agenda content, and it should just show the message from [this screen](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731091_Meeting-Open-1)
- [x] Add a "Notices" section that includes the Sunshine Act notices
![image](https://cloud.githubusercontent.com/assets/1696495/24971511/449ab406-1f86-11e7-924c-fd3d94486a8e.png)
- [x] Add the live video blurb from [this screen](https://gsa.invisionapp.com/share/3QB9ZDSH6#/228731093_Meeting-Open-3) which is activated by populating a `live_video_url` field. If that field has a value, it should show the box.
![image](https://cloud.githubusercontent.com/assets/1696495/24971520/4f0c5764-1f86-11e7-9d6c-16a227b2717d.png)
- [x] Add a block for draft and approved minutes:
![image](https://cloud.githubusercontent.com/assets/1696495/24971550/65f8a81a-1f86-11e7-9869-750eb472e482.png)
- [x] Show all recordings with icons:
![image](https://cloud.githubusercontent.com/assets/1696495/24971565/6f93ffa0-1f86-11e7-96e7-769e5d91527b.png)
- [x] Each agenda item should have a title, audio file link, and then a rich text area for including everything else below the audio link:
![image](https://cloud.githubusercontent.com/assets/1696495/24971635/a4815ca8-1f86-11e7-820f-bdcbf56f6762.png)
- [x] Within each item, links to PDFs can be styled to use the sans-serif and document icon style from the design by targeting `a[href$=".pdf"]`

**Comment by johnnyporkchops** [comment]
We want to make sure that this is as user friendly as possible to build the meeting agenda each month. So that was my focus on some of the way I built the original template and want to advocate for this if I am not going to be able to complete the template based on the new model. I can see a design mockup of a finished page, but its not as easy to see from  the conversation how the UX for building the page has evolved. Can we please syn up on this before completing the template. 
@xtine , @noahmanger

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1051
