### ISSUE TITLE
Create generic update feature for What's Happening section on home page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#989]
So that short-term announcements can be made just-in-time, create the ability to make a generic (uncategorized) update pinned to "What's happening" on the home page. 

- This item should not have a page of its own, but could feasibly contain a link
- The item should have an expiration date 
- The item should appear first in the list styled as a "pinned" item

This funcitonality will replace the "Crawler" that sometimes appears on the current fec.gov

cc @noahmanger to help fill in any missing requirements, & @AmyKort for a heads up that this issue now exists 😸

**Comment by AmyKort** [comment]
Thank you!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1035
